menloresearch/jan

web-client/app/_helpers/ThemeWrapper.tsx

As #43 , default theme should be `light`.
fixes #43

chore: set default theme to light

---

electron/core/plugin-manager/execution/Plugin.js
electron/core/plugin-manager/execution/facade.js
electron/core/plugin-manager/pluginMgr/Plugin.js
electron/core/plugins/data-plugin/package.json
electron/core/plugins/inference-plugin/package.json
electron/core/plugins/model-management-plugin/package.json
electron/core/plugins/monitoring-plugin/package.json
web/app/_components/Preferences.tsx

- Activation points and abstracted plugin URLs are not meant for quick previews; they should expose the description, version, author and icon instead

chore: enhance plugin manifest

---

electron/core/plugins/data-plugin/module.ts

- getFinishedDownloadModels is assumed that the selected rows would never return undefined
fixes #271

fix: #271 Cannot read properties of undefined (reading 'map')

---

.github/workflows/linter-and-test.yml
electron/package.json

This PR aims at:
- Fixing test pipeline run failed on ubuntu
- Change release file name from `jan-electron` to `jan`

Fix CI Test run failed on ubuntu and change release file app name

---

docs/src/components/Elements/dropdown.js

Docusaurus parser string from githubapi to get latest release

Docusaurus parser string from githubapi to get latest release

---

electron/core/plugins/data-plugin/index.ts
electron/core/plugins/inference-plugin/index.ts
electron/core/plugins/model-management-plugin/index.ts
electron/core/plugins/openai-plugin/index.ts
electron/core/plugins/openai-plugin/package.json
plugin-core/README.md
plugin-core/index.ts
plugin-core/preferences.ts
web/app/_components/Preferences.tsx
web/app/page.tsx

- User can't configure Plugin settings
- The Core module supports preferences APIs, and plugins can register available preferences along with their value types
- Plugin registers available preferences (with preference value type)
```ts
import { preferences } from "@janhq/plugin-core";
export function init({ register }: { register: RegisterExtensionPoint }) {
preferences.registerPreferences<string>(register, PluginName, PreferenceName, DefaultValue);
}
```
- Plugin retrieve preference value in it entry codes
```ts
import { preferences } from "@janhq/plugin-core";
const setup = async () => {
const preferenceValue: string = (await preferences.get(PluginName, PreferenceName)) ?? DefaultValue;
}
```
- Preferences page execute to retrieve all available preferences then list out (and allow user …

#360 plugin preferences

---

plugins/inference-plugin/index.ts
plugins/inference-plugin/package.json
web/app/_hooks/useSendChatMessage.ts
web/package.json

The conversation summary has been removed due to plugin-scoped inference refactoring. This reworked PR function operates on a new extension point & to avoid duplicated SSE fetch codes.

chore: update convo summary

---

web/app/_helpers/atoms/SystemBar.atom.ts
web/app/_hooks/useGetMostSuitableModelVersion.ts
web/app/_hooks/useGetPerformanceTag.ts
web/app/_hooks/useGetSystemResources.ts

- Fixed a high CPU usage after visited Explore Model page
- App retrieve system information for every model in the explore page, should reuse cached information

fix: high cpu usage

---

electron/main.ts
electron/package.json
electron/preload.ts
web/app/_components/Preferences.tsx
web/next.config.js
web/types/index.d.ts

Explore plugins: use exported module from CDN for published plugins retrieval
Install a plugin: use `pacote` to retrieve npm manifest and install tarball package (thanks to @hiento09 ) 
( No app update required )
Action items:

feat: explore plugins from the npm repository and install them remotely

---

core/index.ts

chore: update core service enums

---

LICENSE

Folks, I've created a PR to move from GPL to AGPLv3 for Jan, as per our retreat discussion. 
* [Nitro is AGPLv3](https://github.com/janhq/nitro/pull/92), and Jan should inherit (vs. create a GPL inheriting from an AGPL)
* Jan will release a cloud-native version soon, which AGPLv3 covers
* We would like strong copyleft culture in the Jan and Nitro community, where improvements are shared with the community
* Note: most of community's involvement in Jan will be through plugins, which are not subject to GPL. 
* We will likely see a variety of approaches there, from commercially-licensed plugins, to GPL and MIT licensed ones. 
cc @0xSage

chore: Change license to AGPL

---

web/app/_components/ModelActionButton/index.tsx
web/app/_components/ModelRow/index.tsx
web/app/_components/ModelStatusComponent/index.tsx
web/containers/BottomBar/index.tsx
web/helpers/atoms/Model.atom.ts
web/hooks/useStartStopModel.ts
web/uikit/button/index.tsx

Fixing Issue: #380 
Adding indicator loader on button, make button opacity/50 and pointer event none so user cannot multiple click
Adding the status on bottom bar 
`Default state only showing active model label without value`
`State starting model `
`State active model`
`State stopping model`
Handle error message when user failed click start model, we can show an alert need component UI first

chore: added loader starting and stopping model

---

.github/workflows/jan-electron-build.yml
.github/workflows/jan-plugins.yml
plugins/data-plugin/package.json

upgrade leveldown to newest version

upgrade leveldown to newest version

---

web/app/_components/ModelTable/index.tsx
web/app/_components/SimpleTextMessage/index.tsx
web/containers/BottomBar/index.tsx
web/styles/main.scss
web/styles/message.scss

Fix #415
The LLM does respond
```sh
{"conversationId":"def9d2d4-dae5-4024-bd3d-568c504b58bf","message":"Certainly! Here are some of the main characters in the Naruto series, along with their affiliation:\n\n* Naruto Uzumaki - The protagonist and son of the Seventh Hokage, Naruto is determined to become the ultimate ninja and protect his village from threats.\n* Sasuke Uchiha - Naruto's best friend and rival, Sasuke is a skilled and cunning ninja who seeks revenge on those who wronged him and his family.\n* Sakura Haruno - A kind and intelligent girl who becomes Naruto's love interest and eventual wife. She is also a talented healer and medical ninja.\n* Kakashi Hatake - The current headmaster of the Ninja Academy and mentor to Naruto, Kakashi is wise and experienced, but struggles with …
```

bug: Chat view drops enumeration

---

plugins/openai-plugin/index.ts
plugins/openai-plugin/package.json

Its to mark experimental openai plugin as edge release plugin

chore: add required app version to edge release plugin

---

web/app/_components/InputToolbar/index.tsx
web/screens/Settings/CorePlugins/PluginsCatalog.tsx

chore: missing create conversation button when there is no conversation is selected

---

electron/main.ts
plugins/inference-plugin/index.ts

- App will just attempt to kill Nitro subprocess on window-close event fires.
- Somehow nitro subprocess is still alive (after update / force quit)
- Attempt to kill Nitro process (if any) when inference plugin is booted up
- Attempt to kill Nitro process when the app "quit" event fires

chore: attempt to kill Nitro subprocesses

---

web/app/_components/HistoryList/index.tsx
web/app/_components/InputToolbar/index.tsx
web/app/_components/LeftHeaderAction/index.tsx
web/app/_components/SecondaryButton/index.tsx
web/screens/Chat/index.tsx

Fixing #485 
Case scenario
- When user have history list and want to create new conversation, will create new conversation with current active model
- When user create new conversation but model not active, will showing popup and let user go to my model page to active the model
NB: @0xSage we move button new conv to top to avoid case when user have a lot of list, and the button will be sticky when user scroll the list

feat: add New Conversation button on the conversation sidebar

---

web/app/_components/ProgressBar/index.tsx
web/containers/BottomBar/index.tsx

bug: download new version should show in status bar

---

electron/main.ts
plugins/inference-plugin/module.ts
plugins/inference-plugin/package.json
plugins/inference-plugin/webpack.config.js
plugins/monitoring-plugin/webpack.config.js

- `kill-port-process` raises this error when attempting to kill a non-existing process
- use `kill-port` instead
fixes: #405

fix: dest.end is not a function

---

electron/main.ts

There is no toolbar which include close / minimize / maximize buttons on windows (frameless), user has no option to close / maximize without right clicking on taskbar app icon
Disable frameless (same behavior on macOS)
fixes #494

fix: app toolbar is gone on windows

---

web/app/_components/InputToolbar/index.tsx
web/app/_components/SimpleTextMessage/index.tsx

Fixing #506 
Issue
- No border bottom on first chat 
- No space last message and box message
Solution 
- Add border bottom on first convo to make consistent
- Increase padding box message since we remove button `new conversation` above a box message

bug: chat UI is not consistent 

---

web/screens/Settings/CorePlugins/PluginsCatalog.tsx

- User should not toggle off core plugins, only for development purpose.
- Mark Plugin Toggle on/off as an experimental feature
fixes #479

fix: #479 - Toggle plugin is now experimental feature

---

core/src/fs.ts
electron/handlers/fs.ts
electron/preload.ts
plugins/conversational-json/package.json
plugins/conversational-json/src/index.ts
plugins/conversational-json/tsconfig.json
plugins/conversational-json/webpack.config.js
plugins/conversational-plugin/src/index.ts
plugins/inference-plugin/src/helpers/message.ts
plugins/inference-plugin/src/index.ts
web/containers/Providers/index.tsx
web/hooks/useCreateConversation.ts
web/hooks/useSendChatMessage.ts
web/utils/conversation.ts
web/utils/message.ts

Following: https://hackmd.io/@jan-ai/platform-sdk#Example-Making-a-character-with-a-knowledge-base-pdf-docs

add conversational plugin

---

web/screens/Chat/index.tsx
web/screens/Welcome/index.tsx

- State user first download Jan and doesn't have download model yet
- State user have a downloaded model but doesn't have active model yet
- State user have a downloaded model and have active model

ui: improve state of welcome screen

---

plugins/conversational-json/.prettierrc
plugins/conversational-json/package.json
plugins/conversational-json/src/index.ts

Fix #566 . The issue is an exception between change from `conversation-md` and `conversation-json`.

fix(#566): jan cannot retrieve the conversations

---

uikit/src/button/styles.scss
uikit/src/command/styles.scss
uikit/src/main.scss
web/containers/Layout/TopBar/CommandListDownloadedModel/index.tsx
web/hooks/useGetConfiguredModels.ts
web/screens/Chat/HistoryList/index.tsx
web/screens/Chat/index.tsx
web/screens/ExploreModels/ExploreModelList/index.tsx
web/screens/MyModels/index.tsx

Issue: #564 
Solution
Disabled input when active model and current convo id is different
New Improvement 
Handle convo if model is deleted 
- still show history of convo on chat body, disabled input and show button re download again the model

bug: update convo state when user change model

---

web/styles/components/code-block.scss

This is a fix of @urmauur about code block indentation issue
Known issue: Vertical padding is very huge, @urmauur will fix

fix: preformatted text indents the first line strangely

---

web/containers/Layout/BottomBar/DownloadingState/index.tsx

bug: download modal should truncate model name

---

docs/src/components/Elements/dropdown.js

Base on this https://stackoverflow.com/questions/65146751/detecting-apple-silicon-mac-in-javascript and https://developer.mozilla.org/en-US/docs/Web/API/NavigatorUAData/getHighEntropyValues we can detect currently only chrome / browser with engine chromium eg : brave then will push default to apple-silicon
Result:
Brave:
Chrome:
Firefox:
Safari:
cc @louis-jan @0xSage @dan-jan

bug: Fix button download detect intel or apple silicon

---

web/styles/components/code-block.scss

bug: fix weird padding vertical snippet code

---

electron/main.ts

Fix #605 
Test scenario:
1. Download a model -> go to user data `models` you should see the file name current download
2. Cancel download --> go to user data `models` you should not see the file name anymore

bug: cancelling a model download should be delete the model file on user data

---

plugins/inference-plugin/package.json
plugins/inference-plugin/src/helpers/message.ts
plugins/inference-plugin/src/index.ts
plugins/model-plugin/package.json
web/containers/Providers/EventHandler.tsx
web/helpers/atoms/ChatMessage.atom.ts
web/helpers/atoms/Conversation.atom.ts
web/hooks/useCreateConversation.ts
web/hooks/useGetInputState.ts
web/hooks/useGetUserConversations.ts
web/hooks/useSendChatMessage.ts
web/package.json
web/screens/Chat/ChatItem/index.tsx
web/types/chatMessage.d.ts
web/utils/message.ts

Fix for #591 . This issue happen when assistant about to reply to user's inference request. Currently, we immediately create an empty message for assistant to response. We can add a small delay before create that empty message response.

fix(#591): prevent duplicate message id issue

---

web/screens/ExploreModels/ExploreModelItem/index.tsx
web/screens/ExploreModels/ModelVersionItem/index.tsx

Fix #644 
Result 
Another case 
When user try to resize window to small we still not showing fully content, but when user hover the content with `xxx...` we show full title using attribute title html

bug: fix compatibility content not fully display

---

docs/src/styles/base.scss

Fix same issue with Nitro https://github.com/janhq/nitro/issues/152
Result:
When clicking on any sidebar, it should move to the section.

bug: fix anchor link sidebar openapi

---

.github/workflows/jan-electron-build.yml
.github/workflows/jan-electron-linter-and-test.yml
Makefile
README.md

Chore: refactor to makefile

---

docs/src/styles/tweaks.scss

[bug] fix markdown todo items shifted to the left and remove the dots

---

docs/src/styles/tweaks.scss

Fixed #665 
Cleanup padding quotations
Result
Cleanup padding numbering
Before:
After:

bug: fix padding quotations and numbering list

---

web/containers/ModalCancelDownload/index.tsx
web/hooks/useGetPerformanceTag.ts
web/screens/ExploreModels/ExploreModelItemHeader/index.tsx

- As #624 described, Windows users see all models marked as "not enough ram"
- It seems like `PerformanceTag` hook would just persist once, it is not updated as soon as app can retrieve the total RAM value.
Address the 1st issue of #624

fix: app shows wrong performance tag, all say not enough ram on windows

---

docs/package.json
docs/yarn.lock

When we upgrade the @docusaurus/core": "3.0.0, it need to automatically upgrade the @mdx-js/react": "^3.0.0. However, this package didn't upgrade. Thus, the mermaid didn't render well. 
After upgrading @mdx-js/react": "^3.0.0, the issue is fixed. 
Testing Image:

docs: upgrade mdx-js package

---

web/containers/Layout/BottomBar/index.tsx

The app fails to display the update progress again due to an incorrect conditional check for visibility
Fixed #710

fix: incorrect update progress bar visibility check

---

uikit/src/command/index.tsx
web/containers/Layout/BottomBar/index.tsx
web/containers/Layout/TopBar/CommandListDownloadedModel/index.tsx
web/containers/Layout/TopBar/CommandSearch/index.tsx
web/containers/Shortcut/index.tsx
web/hooks/useOs.ts
web/screens/Chat/index.tsx
web/screens/Welcome/index.tsx

bug: fix filter list menu from command base on search type and make a symbol base on OS

---

web/hooks/useActiveModel.ts

- App raises error when attempting to start a model that is already starting. Should skip that action

chore: app raises error when attempting to start a model that is already starting

---

core/src/core.ts
core/src/fs.ts
core/src/index.ts
plugins/inference-plugin/src/index.ts

- `getUserSpace` is part of both the app / core logic, so it shouldn't reside in the `fs` module.
- `deleteFile` is deprecated, it should be in 'fs' module instead of `core` module.

chore: fs module should not cover app logic

---

web/context/FeatureToggle.tsx
web/helpers/atoms/ChatMessage.atom.ts
web/hooks/useSendChatMessage.ts
web/screens/Chat/MessageToolbar/index.tsx
web/screens/Chat/SimpleTextMessage/index.tsx

As a user I would like to have these features:
- Stop current streaming message (#385)
- Re-prompt the latest response
- Copy message
- Delete message
- See token speed
Stop requesting inference
Stop streaming inference
Request a new response
Copy to clipboard 
Token speed
Fixes #385

experimental: message actions tooltip

---

web/context/FeatureToggle.tsx
web/helpers/atoms/ChatMessage.atom.ts
web/hooks/useDeleteConversation.ts
web/hooks/useSendChatMessage.ts
web/screens/Chat/ChatBody/index.tsx
web/screens/Chat/ChatInstruction/index.tsx
web/screens/Chat/MessageToolbar/index.tsx
web/screens/Chat/SimpleTextMessage/index.tsx
web/screens/Chat/index.tsx

- Chat body seems boring after created, blank state is not decorated well 
- As a user I want to give the conversation context (set system prompt)
- Before the Assistant settings feature is designed, this could be an experimental feature so users can get how it is working (also to test against models / endpoints)
TODO: 
- Its better to have a toggle for every single dark feature

experimental: allow user to give instruction for the conversation

---

plugins/inference-plugin/src/module.ts
web/hooks/useActiveModel.ts
web/hooks/useSendChatMessage.ts
web/screens/Chat/ChatInstruction/index.tsx
web/screens/Chat/HistoryList/index.tsx
web/screens/Chat/index.tsx

- Load model on thread selection seems buggy. Queueing the model load on message send should be for now. Will be enhanced later by @urmauur

fix: error when switching between threads

---

electron/handlers/app.ts

- The button still lead user to system app data directory instead of jan root dir

chore: open app data should lead user to jan root

---

Makefile

This PR addresses an issue in the Makefile where 4 spaces were used instead of a tab for indentation. This caused errors when running make commands. The spaces have been replaced with tabs to adhere to Makefile syntax standards and ensure proper execution.

Fix Makefile Indentation Issue

---

electron/handlers/fs.ts
electron/package.json
web/services/coreService.ts

**Describe the bug**
Since https://github.com/janhq/jan/issues/731, Jan appends a new message as a new line onto messages.jsonl this lead to an issue where there may be many concurrent `fs` operations on messages.jsonl. 
e.g:
- multiple responses, before an fs writing operation is done, another responses may come from other assistants / extensions
- edit/delete message: this operation will delete a single line in messages.jsonl
- clean thread messages: this operation will wipe out all messages in the thread
To Reproduce
1. Start a thread and send a message
2. While message is streaming, delete another message
3. Reload the app. Thread is broken, and no messages are loaded (failed to parse)
4. Expected behavior
After reloading, the thread messages should be fully loaded.
ref …

fix: messages sync is not threadsafe

---

extensions/inference-extension/download.bat

Switch to download nitro .tar.gz file instead of .zip file on windows

Switch to download nitro .tar.gz file instead of .zip file on windows

---

web/screens/ExploreModels/index.tsx

Fix #844 
- Fix banner position 
- Temporary hide tabs element
Before
Result

bug: fix broken banner position hub screen

---

extensions/conversational-extension/src/index.ts
web/hooks/useSendChatMessage.ts
web/screens/Chat/MessageToolbar/index.tsx

- Delete a message break the entire thread data (writeMessages should append a line break at the end)
- Regenerate a message does not discard the current one and should not attach it to the messages

fix: delete message break the entire thread

---

extensions/inference-extension/src/module.ts

On windows there is a warning show up when I try to chat with new model.
This is related to nitro at IP interface `0.0.0.0`
The solution is to change to `127.0.0.1`

fix: Nitro interface update to prevent warning

---

docs/src/containers/DownloadApp/index.js

- User could not see the text of download options
Fixed

fix: download button text color is blending into the background

---

extensions/inference-nitro-extension/src/helpers/sse.ts
extensions/inference-openai-extension/src/helpers/sse.ts
models/gpt-3.5-turbo-16k-0613/model.json
models/gpt-4/model.json

fix: model parameters for inference extensions

---

core/src/types/index.ts
extensions/inference-nitro-extension/package.json
extensions/inference-nitro-extension/src/@types/global.d.ts
extensions/inference-nitro-extension/src/index.ts
extensions/inference-nitro-extension/src/module.ts
extensions/inference-openai-extension/src/index.ts

Problem statement:
- Nitro needs to know exactly the number of physical core and can combine it to run with `numactl` on linux
Solution:
- Add `systeminformation` to get cpu.physicalCores as INT an pass to `nitro`
References:
- Based on https://github.com/sebhildebrandt/systeminformation?tab=readme-ov-file#3-cpu

feat: Hotfit for Nitro loading on CPU with hyper-threading support

---

electron/package.json

Fix error Jan app linux crash
Change:
- Upgrade electron from 26.2.1 to 28.0.0
Resolve issues:
- https://github.com/janhq/jan/issues/875

Fix error Jan app linux crash

---

core/src/types/index.ts
extensions/inference-triton-trtllm-extension/README.md
extensions/inference-triton-trtllm-extension/package.json
extensions/inference-triton-trtllm-extension/src/@types/global.d.ts
extensions/inference-triton-trtllm-extension/src/helpers/sse.ts
extensions/inference-triton-trtllm-extension/src/index.ts
extensions/inference-triton-trtllm-extension/tsconfig.json
extensions/inference-triton-trtllm-extension/webpack.config.js

For #821 
**Integration diagram**
**NVIDIA triton inference server and TensorRT LLM setup**
- https://github.com/hamelsmu/llama-inference/blob/master/triton-tensorRT/README.md
- This can be extended to `triton-inference-cluster` using Helm on Kubernetes on DGX clusters

feat: Add NVIDIA triton trt-llm extension

---

.gitignore

Windows has serious problem with only CPU and also it cannot use NVIDIA GPU properly
See comments for the test result

fix: Inference engine Nitro with Windows with/ without CUDA

---

core/src/types/model/modelEntity.ts
extensions/inference-nitro-extension/src/module.ts
models/capybara-34b/model.json
models/deepseek-coder-1.3b/model.json
models/deepseek-coder-34b/model.json
models/llama2-chat-70b-q4/model.json
models/llama2-chat-7b-q4/model.json
models/llama2-chat-7b-q5/model.json
models/lzlv-70b/model.json
models/mistral-ins-7b-q4/model.json
models/mistral-ins-7b-q5/model.json
models/neural-chat-7b/model.json
models/noromaid-20b/model.json
models/openhermes-neural-7b/model.json
models/openorca-13b/model.json
models/phind-34b/model.json
models/rocket-3b/model.json
models/starling-7b/model.json
models/tiefighter-13b/model.json
models/tinyllama-1.1b/model.json
models/wizardcoder-13b/model.json
models/yi-34b/model.json
models/zephyr-beta-7b/model.json
web/hooks/useActiveModel.ts

feat: Inference Nitro with Prompt Template

---

web/containers/Loader/ModelStart.tsx
web/screens/Chat/index.tsx

feat: loader when starting model

---

electron/api/index.ts
electron/api/models/index.ts
electron/main.ts
electron/package.json

** Adding API at http://localhost:1337
Document: https://jan.ai/api-reference/#tag/Messages/operation/retrieveMessageFile

feat: adding API support at 1337

---

extensions/inference-nitro-extension/src/index.ts
extensions/inference-openai-extension/src/index.ts
web/screens/Chat/MessageToolbar/index.tsx
web/screens/Chat/index.tsx

#925 
Testing scenario:
- Retry, copy, delete button show after response is complete.
- Send button become into Stop inference when response incomplete
Result:
https://github.com/janhq/jan/assets/10354610/80e73310-391d-4313-9bfb-7743e1f62d0a

feat: move stop inference button into the send button

---

web/utils/posthog.ts

- Limit auto capture, only record the pageview and pageleave events (SPA)

fix: limit analytics events capture

---

core/src/api/index.ts
electron/handlers/app.ts
web/containers/Layout/index.tsx
web/screens/Settings/Appearance/ToggleTheme.tsx

Fixing #926 
Remove native theme electron and make theme toggle depend on `next-theme` based localstorage instead
- Open app, just make sure theme toggle works well

feat: app theme depend on local storage instead native theme electron

---

electron/api/models/index.ts
extensions/model-extension/src/index.ts

chore: read engine.json for openai chat_completion

---

web/hooks/useClipboard.ts
web/screens/Chat/MessageToolbar/index.tsx
web/screens/Chat/SimpleTextMessage/index.tsx

#908 
- Chat with any model
- Ask regarding programing
- Make sure the answer including code block, hover the code block you will see the copy button, try copy and paste anywere
- User can copy code block easily 
1. When hovering code block
2. When copied code block

feat: copy button for code block

---

web/screens/Chat/index.tsx
web/screens/Settings/Models/Row.tsx

#1045 
- Create new thread
- Type long message on `chatbox` / `textarea`
- Remove several word, make sure the box should be auto resize perfectly

bug: chatbox doesn't resize back down

---

extensions/inference-nitro-extension/package.json
extensions/inference-nitro-extension/src/module.ts

- Nitro cache hallucinations, stop inference then switch to model. Respawn nitro process on switching model would fix the issue.
- App loads model failed sometime when generating and switching models continuously. Should kill nitro instead of attempting to unload model.
- App could hang while loading model since we fetch nitro API before starting a model
fixes #1059
fixes #1069 
fixes #1046

fix: cache hallucinations and failed to load model due to race condition

---

web/screens/SystemMonitor/index.tsx

fixes #177
- Decrease padding
- Remove multiple `GB` on the title

fix: system monitor broken layout when responsive

---

uikit/src/button/styles.scss
web/screens/Chat/ThreadList/index.tsx

#1087 
- Create some of threads
- Click on the '...' to see delete option then delete
- Make sure wow we have dialog confirmation for user and action `yes` or `no`
- Yes --> delete Thread , No ---> Close dialog

fix: added dialog confirmation when delete thread

---

web/screens/Settings/Appearance/index.tsx

fixes #1082 
- Go to Setting page - Appearance
- Make sure copy already update
- Before
- After

fix: update copy setting page

---

web/hooks/useDeleteThread.ts

fix: toaster success deleted thread showing id instead of active model

---

core/src/types/message/messageEntity.ts
extensions/inference-nitro-extension/src/index.ts
extensions/inference-openai-extension/src/index.ts
extensions/inference-triton-trtllm-extension/src/index.ts
web/containers/Providers/EventHandler.tsx
web/hooks/useSetActiveThread.ts
web/screens/Chat/ChatBody/index.tsx
web/screens/Chat/MessageToolbar/index.tsx
web/screens/Chat/SimpleTextMessage/index.tsx

Based on issues #1096 and #1098, the chat completion process is currently interrupted when a user switches to another thread. This pull request aims to add a new message state called "Error" and abort ongoing chat completion requests when there is an active thread change. It will then display an appropriate error message and regenerate the options.
The update is applied to 3 following extensions: 
- Nitro extension
- OpenAI extension
- Triton LLM extension
https://github.com/janhq/jan/assets/133622055/6699e40e-bc44-420c-a7a0-bdc9b3897062
- Also fixed the issue of triton llm extension where it could yield "JSON parse error 'd token..."
fixes #1096 
fixes #1098

fix: #1096 yield error message upon thread switching

---

web/containers/Layout/BottomBar/index.tsx

fix: model active indicator only show when model activated

---

web/screens/Chat/index.tsx

As mentioned in #1112, user can press Enter to send messages continuously, despite the current chat completion state. The Send button is changed to stop when generating, but the Enter button does not handle it. It just sends a message anyway.
Check current state of the thread, if message is generating, press Enter will stop the stream, the same behavior as the send button. Otherwise send as a new message
fixes #1112

fix: handle chat completion state with enter button

---

web/screens/Settings/Models/Row.tsx

fix: remote model always active badges

---

web/screens/Chat/ChatBody/index.tsx

The previous fix of hiding empty message is not a good approach, where the thread should reflect the entire message array even it is an empty message, so user can delete it.

fix: should not hide empty message away

---

web/hooks/useSetActiveThread.ts
web/hooks/useThreads.ts
web/screens/Chat/ThreadList/index.tsx

fix(Thread): #1119 focus on the first thread to prevent blank chat screen

---

extensions/inference-nitro-extension/bin/linux-start.sh
extensions/inference-nitro-extension/bin/win-start.bat

Fix token speed slow in machine has multi gpus
Change: using nvidia-smi to query GPU has highest vram and set via env CUDA_VISIBLE_DEVICES for nitro process
This PR aims at resolving bug https://github.com/janhq/jan/issues/1002

Fix token speed slow in machine has multi gpus

---

core/package.json
core/rollup.config.ts
core/src/node/api/common/builder.ts
core/src/node/api/routes/extension.ts
core/src/node/api/routes/fs.ts
core/src/node/api/routes/v1.ts
core/src/node/extension/index.ts
core/src/node/extension/manager.ts
core/tsconfig.json
electron/handlers/app.ts
electron/handlers/download.ts
electron/handlers/extension.ts
electron/handlers/fs.ts
electron/main.ts
electron/tsconfig.json
electron/utils/menu.ts
extensions/assistant-extension/src/index.ts
extensions/conversational-extension/src/index.ts
extensions/model-extension/src/index.ts
server/main.ts

**Description**
In PR #948, we encountered an issue where we could not import node modules exported by @janhq/core but were only able to require them since modules were not exported accordingly.
In this PR, we refactored to have three exported modules:
- @janhq/core: default UMD module root, serving as its core SDK, can be imported from both browsers and Node.
- @janhq/core/sdk: ES5 core SDK module, importable from browser projects.
- @janhq/core/node: CommonJS Node module, importable from Node projects.
**Success Criteria**
Refactored modules import
```ts
// from 
const node = require('@janhq/core/dist/node/index.cjs')
// to
import  { ... } from '@janhq/core/node'
```
**Additional context**
Include any other relevant context or screenshots about the feature request here.

refactor: exported modules from core with types

---

web/app/layout.tsx
web/containers/Layout/index.tsx
web/screens/Chat/index.tsx
web/screens/ExploreModels/ExploreModelItemHeader/index.tsx
web/screens/Settings/index.tsx
web/screens/SystemMonitor/index.tsx

fixes #1170 
Broken schema color when dark mode
- Set your device to light mode by setting
- Go to app and make sure color schema dark mode works well
- Try switch to light or dark via app, user should be smoothly change color schema
https://github.com/janhq/jan/assets/10354610/84dd4697-81d7-47f2-b073-27a5814a3cc9

fix: darkmode broken color

---

extensions/inference-nitro-extension/bin/linux-start.sh
extensions/inference-nitro-extension/bin/win-start.bat
extensions/inference-nitro-extension/src/module.ts

This PR aim to fix bug #1204 
Change:
- Add tcp wait until port is released before starting nitro new process
- Update bat script and bash script to exit if nitro is killed by jan app.

Fix switch thread crash nitro windows linux

---

electron/main.ts
electron/package.json
server/index.ts
server/main.ts
server/package.json
server/tsconfig.json
web/services/restService.ts

Jan, localhost is now coupled with electron targets. The server should be exported as an ES module and used by the electron app. It could also be deployed separately. This is to remove the duplicated server settings for both electron and server target.
fixes: #1050

refactor: shared server module

---

web/containers/DropdownListSidebar/index.tsx
web/hooks/useSendChatMessage.ts

Right now users have to start a new thread to use another model which causes a lot of confusion to our users.
Threads should be persisted after switching models
fixes #1201

feat: users should be able to switch models mid-thread

---

web/hooks/useDeleteThread.ts

When a user clears the conversation in a thread, the last message displayed was still the old one. This led to confusion about whether or not the user had successfully cleared the conversation.
fixes #1200

fix: Cleared thread last message is not updated

---

web/screens/Chat/ThreadList/index.tsx

fixes #1188 
- Create thread and try delete thread, when dialog confirmation shown hit enter, thread should be deleted
https://github.com/janhq/jan/assets/10354610/cc16151f-3065-4a37-9b4e-9d5d22e70c62

fix: enable enter command on dialog confirmation delete thread

---

web/containers/DropdownListSidebar/index.tsx
web/containers/Providers/index.tsx

fixes #1190 
- Chat with local model 
- Try hovering on model setting with disabled input
- Make sure show a tooltip when hover and no delay, and when you try click the input disabled tooltip should be not disapear

fix: remove delay tooltip and click event

---

core/src/types/model/modelEntity.ts
electron/handlers/download.ts
extensions/conversational-extension/src/index.ts
extensions/inference-nitro-extension/src/index.ts
extensions/inference-nitro-extension/src/module.ts
extensions/model-extension/src/index.ts
web/containers/Layout/BottomBar/DownloadingState/index.tsx
web/containers/ModalCancelDownload/index.tsx
web/containers/Providers/EventListener.tsx
web/hooks/useDownloadModel.ts
web/hooks/useEngineSettings.ts
web/screens/Chat/ChatBody/index.tsx
web/utils/model.ts
web/utils/model_param.ts

1. GGUF model with `.download` ext while downloading
2. GGUF model with origin filename instead of model id
fixes #1231 
fixes #1039
fixes #1072

feat: Deprecate model.json ready state in favor of .download ext

---

extensions/inference-nitro-extension/src/module.ts
extensions/monitoring-extension/src/module.ts

Fix bug #1178 high ram on windows

Fix bug #1178 high ram on windows

---

web/screens/Chat/ThreadList/index.tsx

fixes: #1260 
- add auto focus on button `yes` when user hit enter on dialog confirmation clean thread

fix: enable command enter on dialog confirmation clean thread

---

docs/docs/guides/05-using-server/01-server.md
docs/openapi/jan.yaml
server/index.ts
server/package.json

As a user, I would like to see all supported APIs and test them out. Local swagger hosted at /docs would be helpful.

feat: add swagger /docs to localhost:1337

---

web/styles/components/message.scss

fixes #1253 
- Open app chat with any model
- Go to `thread` folder enter to your thread id there are a file `message.jsonl`
- Try edit the answer and add `\n` save and refresh your app
No `\n`
with `\n`

fix: support markdown break line

---

extensions/inference-nitro-extension/package.json
extensions/inference-nitro-extension/src/module.ts
extensions/monitoring-extension/package.json
extensions/monitoring-extension/src/module.ts
web/hooks/useGetSystemResources.ts

This PR introduces a significant change in our system monitoring approach. We have switched from the `systeminformation` library to `os-utils` to address two critical issues:
1. Bitdefender was incorrectly flagging our monitor extension as a virus. This false positive was causing unnecessary alarm and confusion among our users. By switching to `os-utils`, we have resolved this issue.
2. We have also addressed a memory leak issue that was affecting our Windows users. The `os-utils` library provides more efficient memory management, which has helped us eliminate this problem.
These changes will improve the overall performance and reliability of our application, providing a better user experience. We look forward to your feedback on these improvements.

Switch from systeminformation to os-utils to resolve Bitdefender false positive and memory leak issue

---

server/index.ts

- Users could not know there is a /docs endpoint (Swagger), should redirect by default when accessing localhost:1337

fix: user should be able to access Swagger docs from localhost:1337

---

core/src/node/log.ts

Issue on Windows, app failed to spawn log due to app dir is not created

fix: should check app dir before spawning log

---

electron/main.ts
web/containers/Layout/Ribbon/index.tsx

fixes #1273 
I brought back the GitHub and Twitter link back, as for discord, for some reason lucid doesn't have a dedicated discord icon, so I didn't know which Icon I should replace it with, if the team can tell me I would gladly add the icon mentioned.
as for opening the social media links, it seemed cumbersome to me to login every time the new electron window is open, so I open the link in the default browser of the user, if this is not how it should go, I can revert it back.
here is a quick demo: 
https://github.com/janhq/jan/assets/82527700/475f68ea-f673-46d4-a7ae-74064bbfefba

Bring social media links

---

docs/docs/handbook/product.md

> Please automerge for me
- Added details about how to self manage as a FOSS project
- Term definitions
- Quicklinks to important project management views
- not tracked

docs: update pm handbook

---

electron/handlers/download.ts
web/containers/Providers/EventListener.tsx
web/hooks/useDownloadState.ts

Addressed a critical issue where the application would become unresponsive at the 99% mark during model download. Seems like asynchronous predicate would return a random element: `array.find( async () =>... )`
Suppress irrelevant error log
fixes #1319
-  Updated docs (for bug fixes / features)

fix: app getting stuck at downloading 99% while downloading model

---

models/stealth-v1.2-7b/model.json
models/trinity-v1.2-7b/model.json

Correct the path for the cover image of `trinity v1.2`

fix(trinity): update cover  path for trinity v1.2

---

core/src/node/api/common/builder.ts

Check model.json exist before reading its content. There is a new default model dir created since #1314 but without model.json. This is also to fix other edge cases such as empty directory, no json file exist in /threads /assistants /messages ...
https://discord.com/channels/1107178041848909847/1110389363809976361/1192857931364978778

fix: GET /models does not work due to new default model dir

---

web/styles/components/message.scss

@namchuai already fix this as a functionality i just enhance better UX/UI for readability user
- make sure render external link correctly and open new tab
- give a blue color and hover underline for better UX
fixes #1368

fix: render external links

---

.github/workflows/jan-electron-build-nightly.yml
.github/workflows/update-release-url.yml
README.md
electron/package.json

- Add AppImage package format for linux
- https://github.com/janhq/jan/issues/1423
- https://github.com/janhq/jan/issues/1403

Feature linux support app image format

---

electron/main.ts
electron/utils/clean.ts

As per user reports, there is still a case where the app could show a 'JavaScript error occurred in the main process' on quit. This pull request is intended to handle unhandled exceptions so that we can log them to the error log accordingly in #1430
fixes #1264
Write unhandled error message into log file in #1430 for further user problem report.

fix: suppress all main node JS error message dialog

---

uikit/src/badge/index.tsx
uikit/src/badge/styles.scss
uikit/src/button/styles.scss
web/screens/ExploreModels/ExploreModelItemHeader/index.tsx

Reduce contrast color button and badge on hub page
#1515

feat: [hub] update compatibility tags colors

---

web/screens/ExploreModels/ExploreModelItemHeader/index.tsx

calculation hub labels using total RAM instead remaining RAM
#1521

fix: adjust calculation hub labels using total RAM instead remaining RAM

---

web/containers/DropdownListSidebar/index.tsx

Fixed an issue where Inference Parameters displayed on new thread with Openai GPT Model, this issue occurred since we set default of the max_tokens and ctx_len <= 4096 <= max value. It should check whether model.json does have these settings before applying the default value.
- #1559

fix: #1559 Inference Parameters displayed on new thread with Openai GPT Model

---

web/containers/DropdownListSidebar/index.tsx

- Split bug fix from #1596 - switch model caused app crash

fix: switch model caused app crash

---

web/hooks/useSetActiveThread.ts

Fixed an issue where user revisit thread after changed model without sending message could lead to wrong settings displayed.
Flow: 
- User go to thread A with model B -> change to model Y
- User go to thread X with model Y
- User go back to thread A see model B selected but Y's settings (Wrong)
- Closes #

fix: #1594 - Model settings - change thread model - go back does not see according settings

---

models/dolphin-2.6-phi-2/model.json

- This PR adds support for Dolphin 2.6 Phi-2 (https://huggingface.co/cognitivecomputations/dolphin-2_6-phi-2) in Jan. This model is a finetuned version of Phi-2 with much better results for chat. It's is a great little model (2.7B) to run locally as a personal assistant.

Feat: Add Dolphin 2.6 Phi-2 🐬

---

docs/docusaurus.config.js

- Following issue https://github.com/facebook/docusaurus/issues/6693, the reason is crawler search data doesn't have a data type for the docusaurus tag. Thus, if turn on `contextualSearch` search, result will be not found and turn off `contextualSearch`, only modal search works well, full page search e.g jan.ai/search will not working. 
- Solution: 
+ Re-implement the crawler code and added the docusaurus tag. 
+ Created new indices `jan_docs` for crawling data based on this new implementation
+ Modify docusaurus.config.js with `indexName: "jan_docs",` and `contextualSearch: true,`
- Closes #1675

fix: hot-fix algolia search

---

electron/package.json
server/index.ts

- node-fetch@^3 is not cjs compatible, it should be node-fetch@2 according to the docs.
TODO:
- Is it possible to configure core/node as ES module?
- Closes #1695

fix: Jan server - v1/chat/completions is throwing ERR_REQUIRE_ESM

---

web/containers/DropdownListSidebar/index.tsx
web/containers/Layout/TopBar/index.tsx
web/screens/LocalServer/index.tsx
web/screens/Settings/Models/Row.tsx

feat: improvement ux for local api server

---

core/src/node/api/common/builder.ts

- Fixed an issue where users could not test chat/completion request from localhost:1337 Swagger page due to CORS.
- Closes #

fix: API chat/completion is blocked by CORS

---

web/screens/Settings/Advanced/index.tsx

Since move Jan Data Folder still gated by experimental feature toggle. Should keep the Open App Data Folder action.
- Closes #

fix: bring back open app directory

---

.github/workflows/jan-electron-build-pre-release.yml

Remove paths trigger for pre-release ci to let it trigger on-push to main branch

Hotfix CI pre-release not trigger 

---

web/hooks/useDeleteThread.ts

- Clean last message when user clean up the thread
- #1501

fix: clean last message when user clean thread message

---

web/containers/Providers/EventHandler.tsx
web/helpers/atoms/ChatMessage.atom.ts
web/hooks/useInference.ts
web/hooks/useSendChatMessage.ts
web/screens/Chat/ChatBody/index.tsx
web/screens/Chat/ChatInput/index.tsx
web/screens/Chat/MessageQueuedBanner/index.tsx
web/screens/Chat/index.tsx

- Reduce unnecessary rerendering ChatScreen when user typing input.
https://github.com/janhq/jan/assets/10397206/ff83423d-631c-4e6b-a33a-c2f8818da0f5
https://github.com/janhq/jan/assets/10397206/eb8c3a79-b94c-4fc4-b36f-8907eec1ef1b

perf: remove unnecessary rerender when user typing input

---

web/hooks/useSendChatMessage.ts
web/screens/Chat/ThreadList/index.tsx

feat: put timestamp under thread name in left panel

---

web/containers/Layout/index.tsx
web/screens/Settings/Advanced/DataFolder/index.tsx
web/screens/Settings/index.tsx

add loader for block user from doing anything while the folder is moving
#1618

fix: add loader when user change folder

---

extensions/assistant-extension/src/node/tools/retrieval/index.ts
extensions/inference-nitro-extension/src/index.ts
web/screens/Settings/Advanced/index.tsx

The client api key setting is deprecated, now configure on top level
- Closes #
- Closes #

fix: openAIEmbedding now requires top level API Key configuration

---

web/utils/umami.tsx

Sync main to dev after release 0.4.6
- Closes #
- Closes #

Sync main to dev after release 0.4.6

---

web/containers/Providers/EventHandler.tsx
web/hooks/useCreateNewThread.ts
web/screens/Chat/ThreadList/index.tsx

checking last message threads if there are empty last message we prevent create new thread
#1887

fix: avoid users to create so many threads at the same time

---

uikit/src/select/styles.scss
web/containers/DropdownListSidebar/index.tsx
web/screens/Chat/SimpleTextMessage/index.tsx
web/screens/LocalServer/index.tsx

feat: revamp ui dropdown list model option

---

core/src/node/api/routes/download.ts
electron/handlers/download.ts
web/hooks/useDownloadState.ts

Root cause: wrong path splitting (separator) on Windows. Also addressed model cancel issue on both platforms.
- Closes #1980

fix: model downloads broken on nightly

---

electron/main.ts
electron/utils/dev.ts
extensions/assistant-extension/package.json
extensions/assistant-extension/src/index.ts
extensions/assistant-extension/src/node/index.ts
extensions/assistant-extension/src/node/tools/retrieval/index.ts

Since retrieval is now enabled by default, if users toggle on Experimental Feature. This would lead to an issue where users chat with default remote module without a valid key.
1. Thread stuck at generating response. This is to give a valid error message response.
2. Send wrong message context, without sending a doc but assistant keeps modifying the message context (tool's message template)
3. Redundant requests to VectorDB & Embedding Model
- #1986

fix: retrieval stuck at generating response

---

electron/main.ts
electron/utils/log.ts

The system currently lacks an auto-cleaning mechanism for logs, leading to an accumulation of unnecessary log data over time.
This fix introduces an auto-cleaning mechanism for logs, addressing two key scenarios: logs older than 7 days and logs exceeding 1MB in size. With each iteration, the delay for the log cleaning task is doubled.
- Closes #2002

fix: lack of auto-cleaning mechanism for logs

---

web/containers/DropdownListSidebar/index.tsx
web/helpers/atoms/Thread.atom.ts
web/hooks/useThreads.ts
web/screens/Chat/EngineSetting/index.tsx
web/screens/Chat/ModelSetting/index.tsx
web/screens/Chat/Sidebar/index.tsx
web/screens/Chat/ThreadList/index.tsx
web/screens/LocalServer/index.tsx

- There was an issue where users go to Server page after fresh install -> model settings are blank
- Show loading progress of selected model only
- Show error message of selected model only
Before:
After:
- Closes #1911
- Closes #

fix: local server blank parameters if there is no thread selected

---

web/containers/Layout/BottomBar/index.tsx
web/containers/Providers/DataLoader.tsx
web/containers/Providers/EventHandler.tsx
web/containers/Providers/EventListener.tsx
web/helpers/atoms/SystemBar.atom.ts
web/hooks/useGetSystemResources.ts

- Fetch system resource information once on app startup
- Refactor system resource hook to add watch, stop watching and fetch once
- Hooks should not trigger DataLoader fetch again
```ts
// useGetSystemResources.ts
return {
/**
* Fetch resource informations once
*/
getSystemResources,
/**
*  Fetch & watch for resource update
*/
watch,
/**
*  Stop watching
*/
stopWatching,
}
```
- Closes #

chore: refactor watch system resource hook

---

web/containers/Providers/EventHandler.tsx
web/helpers/atoms/ChatMessage.atom.ts
web/hooks/useCreateNewThread.ts
web/hooks/useSetActiveThread.ts
web/hooks/useThreads.ts
web/screens/Chat/ChatInput/index.tsx
web/screens/Chat/ThreadList/index.tsx

- Users should be able to switch between threads to inspect messages and also see the current sending request from another thread, which they can cancel mid-request.
- Users would see that the request is cancelled after creating a new thread and go back
- Better UX with seamless threads navigation, fixed the issue where user could not see streaming message after going back from another thread (due to in-memory states & local data overwritten)
- Fixed state loop of useThreads, set active thread from component level
- #1191

fix: message should only be interrupted when i start another thread

---

core/src/node/helper/config.ts
web/screens/Settings/Advanced/index.tsx

- The state loop causes performance issues
- The selected GPU device label has low contrast 
- Crash on open settings page
Before
Fixed
- https://github.com/janhq/jan/issues/1851#issuecomment-1948251901

fix: settings page state loop and dark theme

---

web/screens/Settings/Advanced/DataFolder/index.tsx

Fixed an issue where user could not move Jan Data Folder but got stuck with a broken build.
- #2073

fix: move jan data folder - error handling for no write permission granted

---

Dockerfile
Dockerfile.gpu
Makefile
README.md
docker-compose.yml
extensions/inference-nitro-extension/src/index.ts
server/helpers/setup.ts
web/extension/ExtensionManager.ts
web/next.config.js
web/services/restService.ts

Fix bug #2005 docker blank website
- Closes #2005

Fix bug #2005 docker blank website

---

extensions/inference-nitro-extension/src/index.ts
extensions/inference-nitro-extension/src/node/index.ts
web/containers/Providers/EventHandler.tsx
web/screens/Chat/ErrorMessage/index.tsx

It's to give a clearer error message when app could not bind a port (Nitro)
- #1688

fix: failed to bind port - nitro error message copy

---

electron/utils/menu.ts

- The changes would block copy and paste action, which is un-useable
- Closes #
- Closes #

fix: revert back menu actions

---

web/containers/Layout/BottomBar/SystemMonitor/index.tsx

- fix consistent space system monitor 
Before
After
cc @Van-QA 
#2039

fix space between progress bar and title list of gpu

---

core/src/node/api/processors/download.ts

- Download error does not have the model id, so main app can't find the corresponding model to remove it from downloading model state.
- #2080

fix: download model error does not reset state in model hub

---

.gitignore
electron/package.json
package.json
turbo.json

Currently, developers are struggling with the build step where they have to remember the build steps and combine them for a faster build time.
There are so many steps to remember, such as:
build:core
build:uikit
build:web
build:server
build:electron ...
and the order...
Makefile does help, but the build time has increased dramatically.
Now with Turborepo, we have incremental build support and can easily manage build dependencies.
```shelll
npm install -g turbo
// Run dev
yarn turbo:electron
```
cc @hiento09 please help define build commands
Fixes #2224

feat: add turborepo

---

docs/docs/guides/advanced-settings/advanced-settings.mdx
docs/docs/guides/advanced-settings/http-proxy.mdx
docs/docs/guides/best-practices.mdx
docs/docs/guides/common-error/not-using-gpu.mdx
docs/src/components/HomepagePrimaryFeatures/index.js
docs/src/components/HomepageSecondaryFeatures/index.js
docs/src/components/HomepageTerinaryFeatures/index.js
docs/src/theme/NavbarExtension/index.js

- Update Hub page content
- fix the bug and rename the Changelog nav item
- Add new content best practices for the guides section
- Update content for common-error
- Update content for guides -> advanced settings
-

docs: Update content for Hub page and Guides section

---

docs/src/theme/Layout/index.js

- Change this `allowedPaths.includes(location.pathname);` into `allowedPaths.some(path => location.pathname.startsWith(path));` by using the startsWith() it will cover child paths such as /guides/integrations, /guides/extensions, /developers/architecture, etc., as long as the parent path is included in `allowedPaths`.
- Closes #2252

docs: Fix navbar issues. Keep stay when clicked other menu items from the sidebar

---

electron/handlers/update.ts
web/containers/Layout/BottomBar/UpdateFailedModal/index.tsx
web/containers/Layout/BottomBar/index.tsx
web/containers/Providers/AppUpdateListener.tsx
web/containers/Providers/Jotai.tsx

To assist users with older versions, when auto-update to a higher build fails, we need to provide a pop-up functionality prompting manual download.
- #2241

feat: prompt user to download an update manually

---

.github/scripts/auto-sign.sh

- codesign script force sign with new cert
- Closes #
- Closes #

codesign script force sign

---

electron/package.json
electron/utils/selectedText.ts

This is to fix broken Quick Ask on Windows

fix: replace robotjs by nutjs

---

electron/main.ts
electron/managers/mainWindowConfig.ts
electron/managers/tray.ts
electron/managers/window.ts
web/containers/Providers/KeyListener.tsx

- Keep Jan app to stay on the dock when running, even if the main window is closed. (Hidden before)
- Show Jan's app's main window when users click it in the dock or open it from a quick action.
- Click on app tray icon, quick ask window should be shown
- Should not hide main window when pressing `esc`
- #2305

fix: quick app windows, tray and dock behaviors

---

web/containers/Providers/index.tsx

- Fixed an issue where the Quick Ask window performs extension migration in the background, which breaks the application
- #2305

fix: do not migrate extensions from quick ask window

---

extensions/monitoring-extension/package.json
extensions/monitoring-extension/src/node/index.ts
extensions/tensorrt-llm-extension/models.json
extensions/tensorrt-llm-extension/package.json
extensions/tensorrt-llm-extension/rollup.config.ts
web/screens/ExploreModels/ExploreModelItem/index.tsx
web/screens/Settings/CoreExtensions/TensorRtExtensionItem.tsx
web/screens/Settings/CoreExtensions/index.tsx

fix: add compatible check

---

uikit/src/badge/styles.scss
web/containers/DropdownListSidebar/index.tsx
web/screens/ExploreModels/ExploreModelItemHeader/index.tsx

- Fix some cosmetic issues: corner for badges and recommended tag
- https://github.com/janhq/jan/issues/2323#issuecomment-1996799119

fix: some costmetic issues: badges corner, recommended for tensorrt models

---

extensions/model-extension/src/index.ts
extensions/tensorrt-llm-extension/package.json
web/screens/Settings/Advanced/index.tsx
web/screens/Settings/CoreExtensions/TensorRtExtensionItem.tsx

- fix: some regressions for tensorrt nightly build
- #2359 
- #2355

fix: some regressions for tensorrt nightly build

---

.github/workflows/jan-electron-linter-and-test.yml

- CI might fail due to long file path on Windows.
- Closes #
- Closes #

fix: clean working dir with long space support on Windows

---

.github/workflows/jan-electron-linter-and-test.yml

- Fail-fast would cancel matrix jobs as soon as one job fails.
- Closes #
- Closes #

fix: fail-fast would cancel matrix jobs as soon as one job fails

---

core/src/api/index.ts
core/src/core.ts
core/src/extensions/ai-engines/LocalOAIEngine.ts
core/src/extensions/monitoring.ts
core/src/fs.ts
core/src/node/api/processors/fsExt.ts
core/src/node/extension/store.ts
core/src/types/miscellaneous/systemResourceInfo.ts
extensions/monitoring-extension/src/index.ts
extensions/monitoring-extension/src/node/index.ts
extensions/tensorrt-llm-extension/package.json
extensions/tensorrt-llm-extension/rollup.config.ts
extensions/tensorrt-llm-extension/src/@types/global.d.ts
extensions/tensorrt-llm-extension/src/index.ts
extensions/tensorrt-llm-extension/src/node/index.ts
web/screens/Settings/CoreExtensions/TensorRtExtensionItem.tsx
web/services/appService.ts

- Move tensorrt to engine to prevent user from downloading the executable again when migration extension happened.

fix: move tensorrt executable to engine

---

docs/blog/01-january-10-2024-bitdefender-false-positive-flag.mdx
docs/docs/developer/01-overview/01-architecture.md
docs/docs/developer/01-overview/02-file-based.md
docs/docs/developer/01-overview/03-user-interface.md
docs/docs/developer/01-overview/04-install-and-prerequisites.md
docs/docs/developer/01-overview/README.md
docs/docs/developer/04-build-extension/01-your-first-extension.md
docs/docs/guides/error-codes/permission-denied.mdx
docs/docs/guides/extensions/setup-ext.mdx
docs/docs/hardware/concepts/gpu-and-vram.md
docs/docs/hardware/recommendations/by-budget.md
docs/docusaurus.config.js

- Discord cannot show thumbnail in .svg.
- Closes #
- Closes #

docs: fix website thumbnail

---

electron/main.ts
electron/utils/system.ts
extensions/monitoring-extension/src/node/index.ts
web/containers/ModalTroubleShoot/AppLogs.tsx
web/containers/ModalTroubleShoot/DeviceSpecs.tsx
web/containers/ServerLogs/index.tsx
web/hooks/useLogs.tsx

- Log system information to facilitate easier support.
MacOS:
```
2024-03-22T04:03:14.479Z [APP]::Version: 0.1.3
2024-03-22T04:03:14.479Z [APP]::Parallelism: 10
2024-03-22T04:03:14.480Z [APP]::Free Mem: 398245888
2024-03-22T04:03:14.480Z [APP]::Total Mem: 34359738368
2024-03-22T04:03:14.480Z [APP]::OS Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:31:00 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6020
2024-03-22T04:03:14.480Z [APP]::OS Platform: darwin
2024-03-22T04:03:14.479Z [APP]::Machine: arm64
2024-03-22T04:03:14.479Z [APP]::CPUs: [{"model":"Apple M2 Pro","speed":24,"times":{"user":93590430,"nice":0,"sys":44968270,"idle":388674930,"irq":0}},{"model":"Apple M2 Pro","speed":24,"times":{"user":90624060,"nice":0,"sys":41163170,"idle":399774200,"irq":0}},{"model":"Apple M2 …
```

chore: log system information for debugging

---

core/src/node/api/restful/helper/builder.ts

- Trim the stop words to maximum 4 words.
- #2207

fix: only allow 4 stop words for openai

---

web/hooks/useSendChatMessage.ts
web/screens/Chat/ThreadList/index.tsx

Fixed an issue where a newly created thread could not get model linked correctly. This lead to a couple of critical issues where: 
- Blank model settings
- Upload documents but not ingested
Newly created thread with blank model settings:
Old, broken threads will have files ingested successfully afterward.
- #2175

fix: deleting threads manually breaks model settings and document upload

---

extensions/tensorrt-llm-extension/src/index.ts

- Fixed an issue where app raises wrong message toast while stopping infernece
- Closes #

fix: app shows wrong toast on stopping inference

---

core/src/api/index.ts
core/src/extensions/ai-engines/AIEngine.ts
core/src/fs.ts
core/src/node/api/processors/fs.ts
core/src/node/api/processors/fsExt.ts
core/src/node/extension/extension.ts
extensions/assistant-extension/src/index.ts
extensions/conversational-extension/src/index.ts
extensions/huggingface-extension/src/index.ts
extensions/inference-groq-extension/src/index.ts
extensions/inference-openai-extension/src/index.ts
extensions/inference-triton-trtllm-extension/src/index.ts
extensions/model-extension/src/index.ts
extensions/tensorrt-llm-extension/src/index.ts
web/screens/Settings/Advanced/index.tsx

- Remove rmdirsync from core API since it's deprecated: 
```
DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
```

chore: remove rmdirsync from core api since it is deprecated

---

web/hooks/useSendChatMessage.ts
web/utils/messageRequestBuilder.ts
web/utils/threadMessageBuilder.ts

- There is a lot of logic added to the `sendChatMessage` and `resendMessage` hooks, making it difficult to maintain and add new message types (currently limited to text, PDF, and image). It would be better to refactor them using Builders.
- #2470

refactor: introduce message request builder

---

core/src/browser/extensions/engines/AIEngine.ts
core/src/browser/extensions/engines/EngineManager.ts
core/src/browser/extensions/engines/OAIEngine.ts
core/src/browser/extensions/engines/helpers/sse.ts
core/src/browser/index.ts
core/src/browser/tools/index.ts
core/src/browser/tools/manager.ts
core/src/browser/tools/tool.ts
core/src/types/model/modelEntity.ts
extensions/assistant-extension/src/index.ts
extensions/assistant-extension/src/tools/retrieval.ts
web/containers/Providers/EventHandler.tsx
web/hooks/useActiveModel.ts
web/hooks/useSendChatMessage.ts
web/services/coreService.ts

- Extensions/assistants can now register the Inference Tool to be used across extensions/apps, which was not available previously. This eliminates the need for a hacky retrieval tool implementation (modifying & proxying requests), which added a lot of messy logic and code.
```mermaid
graph TD;
AssistantExtension --> |registers Tools| CoreSDK;
App --> |imports| CoreSDK;
Extension --> |imports| CoreSDK;
CoreSDK --> |uses| Tools;
Tools --> |inference|Engines
```
- #2451

refactor: introduce inference tools

---

web/containers/ModelLabel/NotEnoughMemoryLabel.tsx
web/containers/ModelLabel/index.tsx
web/helpers/atoms/SystemBar.atom.ts
web/hooks/useGetSystemResources.ts
web/hooks/useSettings.ts
web/screens/ExploreModels/ExploreModelItemHeader/index.tsx

The model recommendation feature under thread settings in Jan is not accounting for VRAM when GPU acceleration is enabled.
- #2339

fix: model recommendation label is not based on VRAM

---

core/src/browser/fs.ts
core/src/node/api/processors/fsExt.ts
core/src/types/api/index.ts
extensions/tensorrt-llm-extension/src/node/index.ts

fix: duplicate api definition

---

extensions/assistant-extension/src/tools/retrieval.ts
web/containers/AutoLink/index.tsx
web/screens/Chat/ErrorMessage/index.tsx

Fixed an issue: The image model did not work as expected.
Fixed an issue where the style of error messages was not consistent
- #2537

fix: image model does not work when retrieval tool is enabled

---

web/screens/Chat/SimpleTextMessage/index.tsx

- The name of the assistant is taken from the settings of the thread
Before:
Now:
- Partially #2510

Patch name assistant

---

electron/handlers/update.ts
electron/main.ts
electron/managers/window.ts
web/screens/Chat/ErrorMessage/index.tsx

- Fixed an issue where turning on Quick Ask breaks app update.
- #2480

fix: quick ask blocks app update

---

web/containers/ModalCancelDownload/index.tsx

- add the `tabular-nums` class name to where download percentages render to have the same width so all the components' widths stay the same  
https://tailwindcss.com/docs/font-variant-numeric#tabular-figures
Before:
After:
- Closes N/A

use `tabular-nums` for percentages in ModelCancelDownload

---

web/hooks/useActiveModel.ts
web/screens/Chat/ChatBody/index.tsx
web/screens/Chat/ErrorMessage/index.tsx
web/screens/Chat/LoadModelError/index.tsx

Since the app will not attempt to send a message when the model fails to start, there is no error message sent back to the app. I have decoupled the error message into two smaller components to handle both cases. It's also to address the wrong toast icon.
- #2574

fix: missing load model error message

---

web/containers/ModalCancelDownload/index.tsx

with this patch numbers in percentages have the same width so all the component widths stay the same
https://tailwindcss.com/docs/font-variant-numeric#tabular-figures
-
- Closes #
- Closes #

use `tabular-nums` for percentages in ModelCancelDownload (#2553)

---

electron/main.ts

- Fixed an issue: The app registers a global shortcut even when it's not enabled.
- #2589

fix: does not register global shortcut when quick ask is disabled

---

server/index.ts
web/hooks/useActiveModel.ts

This is to reduce the duplication of nitro-killing requests. One at a time
> Noticed the same while using the context length slider.
Each numerical change during a single slide triggers a nitro kill.
This spam can lead to a limbo state where nitro is not stopped and time-out messages flood the logs.
- #2486

fix: app does not gracefully stop a model

---

core/src/node/api/restful/helper/builder.ts

```curl
{
"messages": [
{
"content": "Hello!",
"role": "user"
}
],
"model": "tinyllama-1.1b",
"stream": false,
"max_tokens": 2048
}
```
- #2560 
- #2429

fix: wrong response header for non streamed responses

---

web/screens/Chat/ChatBody/index.tsx

- The error should only display one.
- #2599

fix: duplicated error message

---

web/containers/ModalTroubleShoot/AppLogs.tsx
web/containers/ServerLogs/index.tsx
web/hooks/usePath.ts

chore: add open log dir to troubleshooting modal

---

.github/workflows/jan-electron-linter-and-test.yml

Enable trigger for pull_request_target ci linter, this aim to automatically trigger CI linter for PR from a forked repository.
- Closes #
- Closes #

Enable trigger for pull_request_target ci linter

---

extensions/inference-nitro-extension/package.json
extensions/inference-nitro-extension/src/node/index.ts
web/containers/Loader/ModelReload.tsx
web/containers/Loader/ModelStart.tsx
web/containers/Providers/EventHandler.tsx
web/hooks/useActiveModel.ts
web/hooks/useCreateNewThread.ts
web/screens/Chat/ChatInput/index.tsx
web/screens/Chat/EditChatInput/index.tsx
web/screens/Chat/LoadModelError/index.tsx
web/screens/Settings/Models/Row.tsx

- There was no way to cancel a model load before; now, users can click the 'Stop' button to cancel model loading.
- Added `terminate` to kill spawned processes more efficiently.
- #2527

fix: cancel loading model with stop action

---

core/src/node/api/processors/app.ts
server/index.ts
web/helpers/atoms/ApiServer.atom.ts
web/screens/LocalServer/index.tsx

- I added a new field to the server API settings
You can change prefix for another clients.

Add API prefix settings

---

extensions/monitoring-extension/src/node/index.ts

Correct condition checking cuda dependencies windows
- Closes #
- Closes #

Correct condition checking cuda dependencies windows

---

.gitignore
web/screens/ExploreModels/ExploreModelList/index.tsx

-Rearrange using following condition:
1. Featured models -> remote models -> local models -> remaining models
2. Each of categories are sorted by name ascendingly
- Closes #2532

Rearrange model position in Hub page

---

electron/main.ts
electron/utils/shortcut.ts

- Fixed an issue: The RegisterShortcut function could not retrieve app configurations.
- Closes #
- Closes #

fix: quick ask could not register global shortcuts

---

core/src/browser/extensions/engines/helpers/sse.ts
core/src/types/message/messageEntity.ts
web/screens/Chat/ErrorMessage/index.tsx

Fix issue where app fails to handle missing API key input
Updated error handling to address the scenario where the application fails to prompt users for an API key input. Instead of displaying a vague "something's amiss" message, the application now accurately notifies users of the missing API key and redirects them to the settings for key configuration.
Changes Made:
- Improved error handling to detect missing API key input
- Updated error message for clarity and user guidance
- #2644

fix: missing api key error handling

---

core/src/browser/extensions/engines/helpers/sse.ts

-When mistral return 401 response with message:  'Unauthorized'||  'No API key found in request'. Return API key error

fix error handling of core for mistral integration

---

core/src/browser/extensions/engines/OAIEngine.ts
extensions/inference-groq-extension/src/index.ts
extensions/inference-mistral-extension/src/index.ts
extensions/inference-openai-extension/src/index.ts
extensions/inference-triton-trtllm-extension/src/index.ts

- When init, model can't read from the settings folder so we need to provide it with default setting values.

fix: can't read the setting at first time

---

core/src/browser/extensions/monitoring.ts
core/src/types/miscellaneous/systemResourceInfo.ts
core/src/types/monitoring/monitoringInterface.ts
extensions/inference-nitro-extension/src/index.ts
extensions/monitoring-extension/src/index.ts
extensions/tensorrt-llm-extension/src/index.ts
extensions/tensorrt-llm-extension/src/node/index.ts
web/screens/Settings/CoreExtensions/ExtensionItem.tsx
web/screens/Settings/CoreExtensions/index.tsx

- Fixed the issue where the monitoring extension's interface defines GPU Settings as mandatory, but the actual implementation returns a null value due to an incorrect type definition. Now, the interface accurately reflects the optional nature of GPU Settings, and the type definition aligns with the implemented functionality.
- Also fixed the issue where user could not see the `Incompatible` button from Extension Setting's Install Additional Dependencies

fix: wrong monitoring system information type

---

extensions/tensorrt-llm-extension/package.json
extensions/tensorrt-llm-extension/src/node/index.ts

- Sending a kill signal to the nitro instance will be queued and not processed until all inference requests are completed, which is inefficient. Attempting to kill the subprocesses directly could be a more efficient approach.
- Closes #
- Closes #

fix: better kill process tensorrt-llm

---

extensions/inference-nitro-extension/package.json
web/screens/Settings/CoreExtensions/ExtensionItem.tsx
web/screens/Settings/CoreExtensions/index.tsx

- Add markdown support for extension description

fix: add markdown support for extension description

---

core/src/browser/extensions/engines/LocalOAIEngine.ts
extensions/inference-nitro-extension/src/index.ts
extensions/inference-nitro-extension/src/node/index.ts

- The model unload promise is not waited on until it's fully unloaded.
- Closes #
- Closes #

fix: switch between models get stuck

---

uikit/src/modal/styles.scss

- fix modal component scrollable content
1. Go to Hub page 
2. Download model more than 10 example 
3. Make sure the layout modal not broken and content scrollable
`Before`
`After`
- #2567

fix: scrollable modal component

---

core/src/node/api/processors/download.ts
core/src/node/helper/download.ts

- Adding neccessary information for download so that FE can remove it from download state.
- #2568

fix: cannot cancel model which is progress at 0 percent

---

.github/workflows/jan-electron-linter-and-test.yml

Chore: temporary disable cache for server migration
- Closes #
- Closes #

Chore: temporary disable cache for server migration

---

web/containers/DropdownListSidebar/index.tsx

- SelectItem swallow the click event.

fix: user cannot click on copy icon of model id

---

web/screens/Settings/Advanced/DataFolder/ModalChangeDirectory.tsx

- correct copy for Jan data folder to highlight original Jan data folder intact upon relocation
- MacOS
- Windows
- https://github.com/janhq/jan/issues/2377#issuecomment-2060747141

chore: correct copy for Jan data folder to highlight original Jan data folder intact upon relocation

---

web/containers/Providers/EventHandler.tsx

- Thread title not persisted
- #2694

fix: thread title not persisted

---

web/containers/ListContainer/index.tsx
web/screens/Chat/ChatBody/index.tsx

- Paritally remove react scroll to bottom.
- Remove below error.
https://github.com/janhq/jan/assets/10397206/c8e1174e-8924-4d26-95d6-49a0dcf22708

refactor: good bye react-scroll-to-bottom

---

extensions/inference-groq-extension/resources/models.json

- Adds new Llama 3 models 8B and 80B for the Groq inference extension
- Adds Gemma 7B It model for Groq inference extension

Feat: Add new Llama 3 and models to Groq Extension

---

core/src/node/api/restful/helper/startStopModel.ts
extensions/assistant-extension/src/node/engine.ts
extensions/inference-nitro-extension/src/node/index.ts
extensions/monitoring-extension/src/node/logger.ts
web/containers/ServerLogs/index.tsx
web/screens/Chat/ModelSetting/predefinedComponent.ts

-  Users should be able to override the cpu_threads settings from model.json, so that they can adjust the expected CPU inference threads to match their system specs. There would be global extension-scoped settings that would avoid manipulating every single model.json file.
- The default behavior of the inference engine is to try to use the number of physical cores as the parameter for CPU inference threads.
Loading model with params {"cpu_threads":10,"ctx_len":4096,"prompt_template"...}
1. Model scoped
- Users edit model.json and add `cpu_threads` into `settings` section
- Thread settings GUI should display the CPU Threads setting under Engine Parameters
- Users can adjust the number of cpu inference threads according to their system specs
2. Extension scoped (TBD)
- #2692 
- #2749 
- …

fix: override cpu_threads setting from model.json

---

web/hooks/useActiveModel.ts
web/screens/LocalServer/index.tsx

- Stop server if we failed to load model.
- [#2791](https://github.com/janhq/jan/issues/2791)

fix: stop server if failed to load model

---

web/screens/Chat/EditChatInput/index.tsx

- Remove hidden overflow property to allow scrolling
- Update layout -> submit and cancel buttons are now below the textarea instead of being next to it.
- Closes #2855

Fix scrolling issue on edit chat input

---

extensions/inference-cohere-extension/resources/models.json

- Current remote model only has command-r+. Thus, this PR adds the command-r to the remote model list, so user can use another price option.
- Price: https://cohere.com/pricing
- Closes #
- Closes #

feat: add remote model command-r

---

extensions/inference-openai-extension/resources/models.json

- This pull requests add the gpt-4 turbo to the model list. As a user, I prefer use GPT-4 Turbo rather than GPT-4 normal because it's recently cut off knowledge from April 2023, and cheaper price and better than the normal GPT 4 model.
- Thus, I think it should be added to the default list. For the non-technical user, seems a little bit inconvenient as requires additional steps. This PR adds the GPT-4-Turbo model, so when users download it, they can use it without additional steps.
- Closes #
- Closes #

feat: add model gpt-4 turbo

---

web/hooks/useCreateNewThread.ts
web/screens/Chat/ModelSetting/SettingComponent.tsx
web/screens/Chat/Sidebar/index.tsx

- Validate max `max_token`  from `content_length`
https://github.com/janhq/jan/assets/10354610/4923fa64-b9be-4167-a5b4-d25978ca9bd5
- Closes #
- Closes #

fix: validate max_token from context_length value

---

extensions/inference-martian-extension/README.md
extensions/inference-martian-extension/package.json
extensions/inference-martian-extension/resources/models.json
extensions/inference-martian-extension/resources/settings.json
extensions/inference-martian-extension/src/index.ts
extensions/inference-martian-extension/tsconfig.json
extensions/inference-martian-extension/webpack.config.js

- Implement `inference-martian-extension`
- From Martian website (https://withmartian.com/), Martian invented the first LLM router. By dynamically routing between multiple models, Martian can beat GPT-4 on performance, reduce costs by 20%-97%, and simplify the process of using AI.
- Closes #
- Closes #

feat: implement-inference-martian-extension

---

extensions/inference-nitro-extension/package.json
extensions/inference-nitro-extension/resources/models/codeninja-1.0-7b/model.json
extensions/inference-nitro-extension/resources/models/command-r-34b/model.json
extensions/inference-nitro-extension/resources/models/deepseek-coder-1.3b/model.json
extensions/inference-nitro-extension/resources/models/deepseek-coder-34b/model.json
extensions/inference-nitro-extension/resources/models/gemma-2b/model.json
extensions/inference-nitro-extension/resources/models/gemma-7b/model.json
extensions/inference-nitro-extension/resources/models/mistral-ins-7b-q4/model.json
extensions/inference-nitro-extension/resources/models/mixtral-8x7b-instruct/model.json
extensions/inference-nitro-extension/resources/models/noromaid-7b/model.json
extensions/inference-nitro-extension/resources/models/openchat-3.5-7b/model.json
extensions/inference-nitro-extension/resources/models/phind-34b/model.json
extensions/inference-nitro-extension/resources/models/qwen-7b/model.json
extensions/inference-nitro-extension/resources/models/stealth-v1.2-7b/model.json
extensions/inference-nitro-extension/resources/models/trinity-v1.2-7b/model.json
extensions/inference-nitro-extension/resources/models/vistral-7b/model.json
extensions/inference-nitro-extension/resources/models/wizardcoder-13b/model.json

- Correct upper bound for models on the Catalog
- Closes #
- Closes #

Feat: Correct context length for models

---

web/containers/ListContainer/index.tsx
web/screens/Chat/ChatBody/index.tsx

- Stop auto scroll if user is scrolling up.
- Fix issue press copy on message and the chat body scrolled down all to the bottom.
https://github.com/janhq/jan/assets/10397206/4cb136fa-bc22-4cb3-88b0-acc3ebb8b4b0
- #2873

fix: stop auto scroll if user manually scrolling up

---

extensions/inference-anthropic-extension/README.md
extensions/inference-anthropic-extension/package.json
extensions/inference-anthropic-extension/resources/models.json
extensions/inference-anthropic-extension/resources/settings.json
extensions/inference-anthropic-extension/src/index.ts
extensions/inference-anthropic-extension/tsconfig.json
extensions/inference-anthropic-extension/webpack.config.js
extensions/inference-cohere-extension/src/index.ts
extensions/inference-groq-extension/resources/models.json
extensions/inference-openai-extension/resources/models.json

- Implement `inference-anthropic-extension`
- Model list includes 3 most updated models including Claude 3 Opus, Claude 3 Sonnet, Claude 3 Haiku
- Overwrite header, payLoad, and response based on anthropic API structure
- Closes #
- Closes #

feat: inference anthropic extension

---

.github/workflows/jan-electron-linter-and-test.yml
electron/package.json
electron/utils/selectedText.ts
web/screens/Settings/Advanced/index.tsx

- Reverts janhq/jan#2860
- In the nutjs section of the package.json file, replace the version with this URL: `github:nut-tree/nut.js#4.2.0`. This will install it from Git directly
- Fix https://github.com/janhq/jan/issues/2850

Revert "chore: remove nutjs" and replace nutjs version

---

web/screens/Settings/HuggingFaceRepoDetailModal/ModelSegmentInfo/index.tsx

- Fix crash when Hugging Face does not return model name. Tested with: `crusoeai/Llama-3-8B-Instruct-262k-GGUF`

fix: fix crash when model name not ready

---

web/helpers/atoms/ChatMessage.atom.ts
web/hooks/useDeleteThread.ts
web/screens/Chat/MessageToolbar/index.tsx

https://github.com/janhq/jan/assets/10354610/eb34c634-bb95-4bbd-8898-864a0c5d3240
- #2613

fix: unchange title and last message when clean or delete message

---

electron/utils/setup.ts
joi/src/core/Modal/styles.scss
joi/src/core/ScrollArea/index.tsx
web/app/layout.tsx
web/containers/CenterPanelContainer/index.tsx
web/containers/Layout/BottomPanel/index.tsx
web/containers/Layout/TopPanel/index.tsx
web/containers/ModalTroubleShoot/AppLogs.tsx
web/containers/ModalTroubleShoot/DeviceSpecs.tsx
web/containers/ModalTroubleShoot/index.tsx
web/containers/ModelDropdown/index.tsx
web/containers/ServerLogs/index.tsx
web/screens/LocalServer/LocalServerRightPanel/index.tsx
web/screens/Settings/Appearance/index.tsx

fix: wrong direction icon collapse right panel

---

web/utils/predefinedComponent.ts

feat: update setting tooltip explainer

---

extensions/model-extension/src/index.ts

- Some user registered models are not found because of `\`. This PR will help scanning the `models` folder recursively to find the metadata.

fix: scan the models folder recursive to find model metadata file

---

Makefile

- Specific version for turbo at 1.13.2 when using `make dev`

fix: specific version for turbo

---

web/containers/Layout/TopPanel/index.tsx

since we make the transparent window and frameless, the native topbar will gone, so we need to enable the window control button on Linux and windows
- Closes #
- Closes #

fix: enable window control button on linux

---

web/screens/Thread/ThreadCenterPanel/SimpleTextMessage/index.tsx

add class `break-all` only for text without space
- Closes #
- Closes #

fix: handle words without space

---

web/containers/ModelDropdown/index.tsx
web/screens/Thread/ThreadLeftPanel/ModalCleanThread/index.tsx
web/screens/Thread/ThreadLeftPanel/ModalDeleteThread/index.tsx
web/screens/Thread/ThreadLeftPanel/ModalEditTitleThread/index.tsx
web/screens/Thread/ThreadLeftPanel/index.tsx
web/screens/Thread/ThreadRightPanel/Tools/index.tsx

1. Handle long thread titles without space
Testing -> Try changing edit title with this `aaaaabbbbccccddddeeeeffffgggg` make sure `...` ellipsis does not disappear and the setting menu is still  accessible
2. Added auto focus on the search bar inside the model dropdown
- #3104

fix: handle long thread title without space

---

web/screens/Thread/ThreadCenterPanel/MessageToolbar/index.tsx

fix: add tooltip messages toolbar

---

core/src/browser/fs.ts
core/src/node/api/processors/download.ts
core/src/node/api/processors/fs.ts
core/src/node/api/processors/fsExt.ts
core/src/node/helper/config.ts
core/src/node/helper/path.ts
core/src/types/api/index.ts
core/tests/node/path.test.ts

-  validate path in fs, only allow access to the file in the Jan folder
before the fix
- invalid path:
after the fix:
- valid path:
- invalid path:
- Closes #
- Closes #

fix: validate path in fs

---

web/containers/ModelDropdown/index.tsx

- Search result always showing model downloaded first 
- #3043 
- Closes #

fix: model dropdown search result always show downloaded models first

---

web/screens/HubScreen2/components/DetailModelGroup.tsx

Added UI for no result component for model groups search & adjust right padding 
Before
After
- Closes #
- Closes #

chore: models group search blank state

---

web/screens/HubScreen2/index.tsx
web/screens/Thread/ThreadCenterPanel/SimpleTextMessage/index.tsx

NB: this max width work when window app of Jan is large
- #3184 
- Closes #

chore: set container max width for chat message and new hub screen

---

electron/handlers/native.ts

Fixed migration issues where: 
- Remote models are not being migrated
- Symlink models are not being migrated
- Migration fail due to: 
- Missing /models
- Models folder contains weird files
- Model folder contains weird file
- Messages folder does not contains messages.jsonl
- Closes #
- Closes #

fix: migration should not skip symlink models

---

electron/main.ts
web/containers/Providers/DownloadEventListener.tsx
web/hooks/useCortex.ts
web/hooks/useDropModelBinaries.ts
web/screens/Settings/ChooseWhatToImportModal/index.tsx
web/screens/Settings/ImportSuccessIcon/index.tsx
web/screens/Settings/SelectingModelModal/index.tsx

fix import on windows

---

joi/src/core/ScrollArea/index.tsx
joi/src/core/ScrollArea/styles.scss

- Make default visible scrollbar when element need scroll and increase the size to 10px
- #3177 
- Closes #

feat: make scroll area type auto for make default visible scrollbar

---

web/screens/Thread/index.tsx

The case when cortex still loading we not display screen, bc thread screen now depend with cortex, in thread screen we have conditional to check downloaded models and any remote model setup, so thread screen will depends on cortex already load ot not.
- Closes #
- Closes #

chore: update conditional starter screen after cortex load

---

web/screens/HubScreen2/components/HubScreenFilter/index.tsx
web/screens/HubScreen2/components/RemoteModelGroup.tsx

- Group search result 
- Closes #
- Closes #

chore: update hub search result

---

web/screens/Settings/EngineSetting/index.tsx

As a user, I want to be able to reinitialize the engine to get the latest version or repair a broken installation.
- #3250

fix: allow user to reinit engine from settings page

---

core/src/types/model/modelEntity.ts
web/helpers/atoms/HuggingFace.atom.ts
web/hooks/useEngineInit.ts
web/hooks/useHfModelFetchAndDownload.ts
web/hooks/useSendMessage.ts
web/screens/HubScreen2/components/GroupInfo.tsx
web/screens/HubScreen2/components/HubModelCard.tsx
web/screens/HubScreen2/components/RemoteModelCard.tsx
web/screens/HubScreen2/components/RemoteModelGroup.tsx
web/screens/HubScreen2/components/SetUpApiKeyModal.tsx
web/screens/Settings/EngineSetting/index.tsx

- FIxed an issue where users can reinit remote engines
- Added EngineStatus enum
- Closes #
- Closes #

fix: remote engine should not allow reinit

---

web/containers/ModelDropdown/ModelSection.tsx

Fix render logo engine on model dropdown
Before
After
Updated with disabled item when engine isn't setup
- Closes #
- Closes #

fix: engine logo on model dropdown

---

core/src/types/api/index.ts
core/src/types/config/appConfigEntity.ts
electron/handlers/native.ts
electron/main.ts
electron/managers/tray.ts
electron/managers/window.ts
electron/preload.ts
electron/utils/path.ts
electron/utils/shortcut.ts
web/app/search/layout.tsx
web/screens/Settings/Advanced/DataFolder/index.tsx
web/screens/Settings/Advanced/index.tsx

- Support changing the app data folder
Happy cases:
1. Confirmation Prompt
2. In-progress
3. Succeed
Edge cases:
1. Nested dir
2. Destination dir is not empty
- Data Migration
- Model Path
- #3282
- There is a problem where users switch back to an older version, it will change data folder to the default path.

feat: change data folder

---

web/constants/Threads.ts
web/hooks/useCortex.ts
web/hooks/useMigratingData.ts
web/hooks/useSendMessage.ts
web/screens/Thread/ThreadLeftPanel/ModalCleanThread/index.tsx
web/screens/Thread/ThreadLeftPanel/ThreadItem/index.tsx
web/screens/Thread/ThreadLeftPanel/TypingAnimated/index.tsx

https://github.com/user-attachments/assets/879d0629-a7b1-47fd-9d87-cd3b59c94953
- #3116 
- Closes #

fix: avoid lose title threads

---

electron/utils/path.ts

fix: update legacy path

---

web/containers/Layout/TopPanel/index.tsx
web/screens/Thread/ThreadLeftPanel/index.tsx

feat: move icon create new thread into top panel

---

.github/ISSUE_TEMPLATE/bug_report.md
core/src/types/events/resource.event.ts
electron/package.json
web/containers/Layout/BottomPanel/SystemMonitor/index.tsx
web/helpers/atoms/SystemBar.atom.ts

This PR is to add back GPU information to system monitoring bar where:
- GPU information is added to /system/events/resources body since cortex 0.5.0-43
- It supports different GPU vendors
- I'm not quite sure why FE shows MB instead of GB unit so I leave it as is
Windows:
Before loading models
After loaded a model
MacOS: 
- Closes #

chore: add back GPU information to system monitoring bar

---

.gitignore
core/src/node/api/processors/app.ts
core/src/node/api/processors/extension.ts
core/src/node/helper/config.ts
core/src/node/helper/path.ts
electron/utils/migration.ts
web/app/layout.tsx
web/styles/main.scss

The latest patch raises errors in some cases where the app could not access its resources, e.g. Application Support and App Resources, which is critical.
There are a couple of small code refactoring where:
- css import should be in main.scss files
- application resources should not do async (consistent with others)
- isolated test config. E.g., while running a test with the same package, it should generate data under rootDir/test-data; running the same package without a test environment generates data under a 'jan data' folder.

fix: Jan should have access to it resource folders

---

core/src/browser/extension.ts
web/containers/ListContainer/index.tsx
web/hooks/useRecommendedModel.ts

There are issues where the app tries to read files or folders without checking their availability, emitting a bunch of errors that confuse users.
| Ugly Errors |
|:--:|
| <img width="928" alt="Screenshot 2024-08-16 at 22 56 26" src="https://github.com/user-attachments/assets/bc6eb90b-865b-4ad6-b256-4390a6f07da9"> |
| *Fixed by checking file exist* |

fix: app emits ugly errors when retrieving settings

---

web/containers/ModelDropdown/index.tsx
web/helpers/atoms/Thread.atom.ts
web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
web/screens/Thread/ThreadRightPanel/index.tsx

Save toggle setting on chat input box, once user turn on will show advance chat input instead of simple one to all thread and new thread, also update ux of button tools, when right panel active on tools tab the button highlight instead of outline.
- #3384 
- Closes #

fix: save state toggle input box setting

---

core/src/browser/extension.ts
extensions/inference-openrouter-extension/resources/settings.json
extensions/inference-openrouter-extension/src/index.ts

- Per #3110 - OpenRouter extension should route requests to the default model (by omitting it from the request) instead of "auto" (which is costly).
- This PR also registers new settings from the OpenRouter extension, allowing users to input the model they want to use. Adding a full list of OpenRouter supported models would bring hundreds of remote models that would clutter the UI and are not the primary feature.
| Openrouter uses default model |
|:-:|
|<img width="1362" alt="Screenshot 2024-08-20 at 21 21 43" src="https://github.com/user-attachments/assets/dc65e156-21ae-47e4-b4a5-9e45cee5cf83">|
| Openrouter extension registers model input setting |
|<img width="1273" alt="Screenshot 2024-08-20 at 21 31 14" src="https://github.com/user-attachments/assets/5097ba04-7b88-44cf-a97d-e4c58bab24 …

feat: openrouter model settings

---

core/src/types/model/modelEntity.ts
extensions/model-extension/src/index.ts
web/containers/ModelDropdown/index.tsx
web/helpers/atoms/AppConfig.atom.ts
web/helpers/atoms/Model.atom.ts
web/hooks/useCreateNewThread.ts
web/hooks/useUpdateModelParameters.ts
web/screens/Settings/Advanced/index.tsx

This PR aims to enhance the UX of thread creation by using the previous model settings for new threads, which will be introduced to users as an experimental feature.
NOTES: This will add 2 new fields into model.json > metadata
```json
"metadata": {
"default_ctx_len": 4096,
"default_max_tokens": 4096
}
```
| Preserve Model Settings Feature Toggle|
|:-:|
|<img width="1273" alt="Screenshot 2024-08-21 at 16 27 32" src="https://github.com/user-attachments/assets/eb5ca848-d729-4fcf-9e81-f4678e3f4fb5">|
|New thread with previous model settings|
|<img width="1273" alt="Screenshot 2024-08-21 at 16 30 47" src="https://github.com/user-attachments/assets/43677698-5523-4e79-89d7-fdf04a6b3268">|
- #3377

feat: preserve model settings

---

core/src/node/api/restful/v1.ts

API Server should only expose OpenAI compatible endpoints. All of the internal endpoints that support Jan Web Docker should be disabled.
The latest release actually gated access to the APIs from outside of Jan Resources, but this is to ensure that no such cases are left.
- ##3379

chore: disable internal REST endpoints due to a vulnerability issue

---

web/hooks/useCreateNewThread.ts

@Van-QA have good feedback here, instead return `null` we just return `toast` instead when user blocked create new thread bc there empty last message
- Closes #
- Closes #

fix: add toaster warning when blocked create new thread

---

web/containers/Layout/TopPanel/index.tsx
web/helpers/atoms/ThreadRightPanel.atom.ts
web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
web/screens/Thread/ThreadRightPanel/index.tsx

https://discord.com/channels/1107178041848909847/1275647742906994699/1275651719925075988
Make setting button inside chatbox input like a toggle, when inactive will close right panel 
- Closes #
- Closes #

fix: setting chatbox input

---

extensions/model-extension/src/index.ts
web/containers/ModelDropdown/index.tsx
web/hooks/useCreateNewThread.ts
web/hooks/useRecommendedModel.ts
web/hooks/useUpdateModelParameters.ts

- Fixed an issue where `useUpdateModelParameters` does not maintain all settings, causing the model.json to lose unchanged values.
- Fixed a legacy issue where users remove a stop word, resulting in an empty stop string being sent instead of an empty array.
To reproduce: 
1. Toggle on the feature flag
2. Change inference params
3. Switch between local and remote models
- #3427

fix: preserve model settings should maintain all settings

---

core/src/node/api/processors/fsExt.ts
core/src/node/helper/config.ts
web/app/search/layout.tsx
web/containers/Providers/DataLoader.tsx
web/hooks/useFactoryReset.ts

Currently, we are setting the Jan default data folder path to the user's home directory. It would be better to change it back to the app's `appData` folder, which is defined by the OS and used by the Electron app.
```
appData Per-user application data directory, which by default points to:
%APPDATA% on Windows
$XDG_CONFIG_HOME or ~/.config on Linux
~/Library/Application Support on macOS
userData The directory for storing your app's configuration files, which by default is the appData directory appended with your app's name. By convention files storing user data should be written to this directory, and it is not recommended to write large files here because some environments may backup this directory to cloud storage.
```
> https://www.electronjs.org/docs/latest/api/app
So when a user does …

chore: change jan default data folder path to app's userData

---

electron/managers/mainWindowConfig.ts

Fixed an issue where double-clicking the app toolbar to maximize or minimize would shrink it to a super-minimized size that was un-interactable.
| Minimized issue |
|:-:|
|<img width="512" alt="Screenshot 2024-08-26 at 13 49 18" src="https://github.com/user-attachments/assets/f880544b-11e1-482c-9cce-eff1e6c9c70a">|
| Fixed | 
|<img width="512" alt="Screenshot 2024-08-26 at 13 54 07" src="https://github.com/user-attachments/assets/e3e3d0a3-0940-4157-ad6f-eb65593711e0">|
- #3459

fix: add a minimum height for the main window otherwise it shrinks

---

web/app/search/layout.tsx
web/containers/Providers/DataLoader.tsx
web/screens/Thread/ThreadRightPanel/Tools/index.tsx

- It is placed in the wrong position before (Vector Database section)
| Correct Time-Weighted Retrieval Toggle Position |
|:-:|
|<img width="1292" alt="Screenshot 2024-08-26 at 14 51 32" src="https://github.com/user-attachments/assets/c0999b9e-d0ab-4cb0-9e71-645711d86318">|
- #3460

fix: correct time-weighted retrieval toggle

---

joi/src/core/Input/index.tsx
joi/src/core/Input/styles.scss
web/containers/ModelSearch/index.tsx
web/screens/Settings/CoreExtensions/index.tsx

- Search input have clearable menu
- #3455 
- Closes #

fix: search input clearable component

---

web/screens/Hub/ModelList/index.tsx

| Remote models should not be prioritized over other local models in the Model Hub screen |
|:-:|
|<img width="1289" alt="Screenshot 2024-08-27 at 13 05 28" src="https://github.com/user-attachments/assets/85a4ff55-b26d-4d08-9bab-60afdd1706ad">|

chore: move remote models to bottom of the models hub

---

web/containers/LeftPanelContainer/index.tsx
web/containers/RightPanelContainer/index.tsx

it's great find from @Van-QA 
- make resize left and right panel on top scroll area
since we make force default show scroll area will overlap the resize element, so i reverse resize element z index on top of scroll area
you can tested on setting left panel 
- Closes #
- Closes #

fix: resize left and panel when scroll area show

---

electron/managers/mainWindowConfig.ts
web/screens/Settings/HuggingFaceRepoDetailModal/ModelDownloadList/index.tsx
web/screens/Settings/HuggingFaceRepoDetailModal/ModelSegmentInfo/index.tsx

- Need increased minimum height, and make a scroll when size small on tag model section
- #3181
- Closes #

fix: modal responsive import model

---

web/containers/ModelDropdown/index.tsx
web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
web/screens/Thread/ThreadLeftPanel/index.tsx

Before
After
- Closes #
- Closes #

fix: wrong classname icon

---

web/containers/Providers/Responsive.tsx

Track last state left and right panel, and apply it when responsive
https://github.com/user-attachments/assets/2d99b7ea-6d77-46fc-8bc0-42fed048a8f3
- #3178 
- Closes #

feat: track last state left and right panel

---

web/containers/Layout/RibbonPanel/index.tsx
web/hooks/useImportModel.ts
web/screens/Thread/ThreadCenterPanel/ChatBody/EmptyModel/index.tsx
web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx
web/screens/Thread/index.tsx

- Starter screen will show if user doesn't have downloaded a local model, not yet setup api key remote model, and doesn't have thread 
- See all will direct to hub
- See more will extend more list remote model 
- Click remote model will direct to setting and setup apikey
- Search by configured model and can download by download icon
- No search result 
- Download on the list page will show actual indicator download
- Showing only 2 local model based on feature model
- #3170 
- Closes #

feat: starter screen

---

web/containers/SliderRightPanel/index.tsx

Now the value input allow `0.5` instead `0,5`
- Closes #3481 
- Closes #

fix: using type text instead number for avoid region issue

---

web/containers/SliderRightPanel/index.tsx

Sorry my bad, the value should be Number instead string
Context:
There was an issue with a feature build that was behind the update, where the application loaded a model with some string parameters that should have been numbers.
To reproduce:
Build from any commits prior to this fix and behind the update.
Input a number into any number input box
Chat with model
See the error
- Closes #
- Closes #

fix: missing type number for slider input right panel

---

joi/package.json
joi/src/core/Button/Button.test.tsx
joi/src/core/Checkbox/Checkbox.test.tsx
joi/src/core/Input/Input.test.tsx
joi/src/core/Input/index.tsx
joi/src/core/Modal/Modal.test.tsx
joi/src/core/Progress/Progress.test.tsx
joi/src/core/Progress/index.tsx
joi/src/core/ScrollArea/ScrollArea.test.tsx
joi/src/core/Select/Select.test.tsx
joi/src/core/Slider/Slider.test.tsx
joi/src/core/Switch/Switch.test.tsx
joi/src/core/Tabs/Tabs.test.tsx
joi/src/core/TextArea/TextArea.test.tsx
joi/src/core/Tooltip/Tooltip.test.tsx

Write Unit Tests Components
Finished All UI components test case
- Closes #3507 
- Closes #

test: finished all ui components test

---

.gitignore
electron/.eslintrc.js
web/.eslintrc.js
web/containers/SliderRightPanel/index.test.tsx
web/containers/SliderRightPanel/index.tsx
web/hooks/useCreateNewThread.ts
web/jest.config.js
web/package.json
web/tsconfig.json

This PR is a follow-up fix for #3609, where users could get stuck when inputting a value to the model settings input component.
In this PR, it covers the case where users could get stuck in a broken state after inputting an invalid settings value and then force quitting the app immediately. This behavior is hard to reproduce but possible.
Rework web test configurations to resolve the collision between Jest Babel and Next Babel.
Tests have been added to cover such cases.
We've received a broken app report while testing a feature build; after investigating, we found the root cause and fixed it. However, tests have not been added in this PR due to the incomplete setup.
This PR is to add tests but it turned out that there are missing cases to handle.
- #3609

test: add tests to model settings's Slider Input

---

.github/workflows/nightly-integrate-cortex-cpp.yml
core/src/node/api/restful/helper/startStopModel.ts
extensions/inference-nitro-extension/download.bat
extensions/inference-nitro-extension/download.sh
extensions/inference-nitro-extension/package.json
extensions/inference-nitro-extension/rollup.config.ts
extensions/inference-nitro-extension/src/index.ts
extensions/inference-nitro-extension/src/node/execute.test.ts
extensions/inference-nitro-extension/src/node/execute.ts
extensions/inference-nitro-extension/src/node/index.test.ts
extensions/inference-nitro-extension/src/node/index.ts
extensions/inference-nitro-extension/tsconfig.json

In version 0.5.3, the app ships with non-AVX binaries only (previously AVX2), which causes significant performance degradation, especially in CPU mode.
**1. Fixed the app's inference performance degradation when running in CPU mode.  App bundles 7 binaries in total, including:**
Windows & Linux
- NO-AVX
- AVX
- AVX2
- AVX512
- VULKAN
- AVX2-CUDA-12-0
- AVX2-CUDA-11-7
MacOS
- ARM64
- X64
This would address the degradation issues with different CPU instructions where the app would pick the correct binary to run on optimized CPU instructions.
When GPU Acceleration settings is ON, the app will use AVX2-Cuda binaries by default (12.0 or 11.7, depending on the Cuda version installed by the user). This structure is the same as that of the llama.cpp releases and previous app releases.
**2. CPU …

fix: #3549, #3552 - Inference on CPU is slower on Jan 0.5.3

---

.github/workflows/jan-electron-linter-and-test.yml
web/containers/SliderRightPanel/index.test.tsx
web/containers/SliderRightPanel/index.tsx

since we allow 0.5 instead 0,5 to avoid issue regarding region number format, we change input on slider right panel using input string, we need prevent empty string when on change and on blur value.
we just need check length value when onBlur and onChange and apply to minimum value and update test case including test  when value empty string 
https://github.com/user-attachments/assets/3e842e51-b0a5-4d76-8da5-a47100bc1c36
- Closes #3634 
- Closes #

fix: prevent value empty string on slider right panel

---

.github/workflows/jan-electron-build-nightly.yml
.github/workflows/jan-electron-build.yml
.github/workflows/jan-electron-linter-and-test.yml
.github/workflows/template-build-linux-x64.yml
.github/workflows/template-build-macos-arm64.yml
.github/workflows/template-build-macos-x64.yml
.github/workflows/template-build-windows-x64.yml

Fix issue github action failed due to a deprecated github action step: 
- Upgrade actions/upload-artifact@v2 to actions/upload-artifact@v4
- Closes #
- Closes #

Fix issue github action failed due to a deprecated github action step

---

electron/.eslintrc.js
web/.eslintrc.js
web/screens/Settings/Advanced/index.tsx

This is a separate PR from #3476, to deprecate the Preserve Thread settings, which are poorly aligned and can be replaced by the future Preset feature.
https://discord.com/channels/1107178041848909847/1283644162838892564/1283749880937971774
1. **Removed a feature**: A feature that allowed the user to preserve model settings was removed from the code.
2. **Import removed**: The `preserveModelSettingsAtom` was removed from the code.
3. **Variable and function calls removed**: The `preserveModelSettingsAtom` variable and the `setPreserveModelSettings` function call were removed.
4. **Switch component removed**: The `Switch` component related to the removed feature was removed.
5. **Conditional rendering removed**: The conditionally rendered code block related to the removed feature was …

chore: deprecate preserve thread settings

---

extensions/inference-nitro-extension/package.json
extensions/inference-nitro-extension/resources/models/phi3-medium/model.json

- There was an issue with the Phi-3 Medium prompt template (0.5.3), which lead to a wrong output like this:
| <Assistant> |
|:-:|
|![Sept 16 Screenshot from Discord](https://github.com/user-attachments/assets/d787f733-28b3-41ba-b7c4-ac1ed426f18c)|
- This is the second attempt at correcting the model prompt template, and the result should be like this:
| <Assistant> |
|:-:|
|![Sept 16 Screenshot from Discord (1)](https://github.com/user-attachments/assets/50188778-998d-4496-a2d3-3ce2f1dafdc5)|
1. The model version has been updated from "1.3" to "1.4".
2. The prompt template has been modified:
- Old: "<|user|> {prompt}<|end|><|assistant|><|end|>"
- New: "<|user|> {prompt}<|end|><|assistant|>"
The main difference is the removal of "<|end|>" after "<|assistant|>".
- #3608

fix: correct prompt template for Phi3 Medium model

---

extensions/inference-nitro-extension/src/node/index.ts
extensions/tensorrt-llm-extension/src/node/index.ts
web/containers/Providers/EventHandler.tsx
web/containers/SliderRightPanel/index.tsx
web/hooks/useSendChatMessage.ts
web/hooks/useUpdateModelParameters.test.ts
web/hooks/useUpdateModelParameters.ts
web/jest.config.js
web/screens/LocalServer/LocalServerRightPanel/index.tsx
web/screens/Thread/ThreadRightPanel/index.tsx
web/utils/modelParam.test.ts
web/utils/modelParam.ts

This PR is a follow-up to the changes in #3615, where none of the model parameters (including inference and model load parameters) of pre-persistence layer were covered by tests.
1. Added validation rules for parameters so they can be verified before being persisted (sent to the endpoint later when cortex.cpp manages the models).
2. Added tests for both validation rules (parameters extraction utility) and the `updateModelParameter` hook.
3. Fixed an issue where Jest Babel failed to compile modules. See jest.config.js [22].
4. Removed `Debug:` prefix, which confused users.
5. Outputs an error to the FE console if a model parameters UI component is broken.
6. Fixed an issue where model settings inputs allowed invalid values.
7. Normalize values before sending out (e.g. float vs int)
- #3615 …

test: add model parameter validation rules and persistence tests

---

extensions/inference-openai-extension/resources/models.json

Add support for 'o1-preview' and 'o1-mini' model names in the OpenAI API.
* **Update `models.json`**:
- Add 'o1-preview' model details with appropriate parameters and metadata.
- Add 'o1-mini' model details with appropriate parameters and metadata.
Closes #3652 
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/janhq/jan?shareId=ebcc39a6-99ad-46f5-a233-e0f75289c885).

Add support for 'o1-preview' and 'o1-mini' models

---

web/containers/ModelLabel/ModelLabel.test.tsx
web/containers/ModelLabel/index.tsx

It can be confusing when a recommended tag is applied to all models using the `model size < available RAM/VRAM` formula, because in reality, these models can still perform slowly on users' machines due to lack of GPU acceleration and the need to handle large contexts.
Hide the "Recommended" tag in the Hub and only display compatibility tags for models that are marked as "Slow on your device" or "Not enough RAM".
- #3667
**Changes in `ModelLabel.test.tsx`:**
Three test cases are defined to cover different scenarios:
*   The first test case checks if the `ModelLabel` component renders the `NotEnoughMemoryLabel` when the minimum RAM model is greater than the total RAM.
*   The second test case checks if the `ModelLabel` component renders the `SlowOnYourDeviceLabel` when the minimum RAM model …

fix: #3667 - The recommended label should be hidden

---

web/screens/Settings/Advanced/DataFolder/index.tsx
web/screens/Settings/Advanced/FactoryReset/index.tsx
web/screens/Settings/Advanced/index.test.tsx
web/screens/Settings/Advanced/index.tsx

This is an app bug where it does not reset other settings when the experimental feature is toggled off.
Two of the major changes: 
- Fixed the wrong HTMLInputElement (Experimental Toggle) target value (`e.target.checked` instead of `e`)
- Added tests to Advanced Settings component
1. Users toggle ON the Experimental Settings & Vulkan Support
2. Users toggle OFF the Experimental Settings. The app should toggle off others automatically.
It should toggle off features gated by Experimental Settings when toggling off.
Regarding the issue where app could not get Vulkan device VRAM which is not scoped by the issue, it should be a part of https://github.com/janhq/cortex.cpp/issues/1165
> all local models will still appear as "Slow on your device"
- Closes #1142
**Added components and …

Fix: #1142 setting groups toggle does not turn off it's nested settings

---

electron/tests/e2e/thread.e2e.spec.ts
web/containers/Layout/RibbonPanel/index.tsx
web/containers/Layout/TopPanel/index.tsx
web/helpers/atoms/Thread.atom.ts
web/hooks/useStarterScreen.ts
web/screens/Thread/ThreadCenterPanel/ChatBody/OnDeviceStarterScreen/index.tsx
web/screens/Thread/index.test.tsx

1. Disable the "New Threads" icon on the top
2. Duplicate render progress bar when more than one download from feat/suggestion model.
3. @louis-jan temporary with hard-coded recommend model
4. Overlap progress bar when dropdown search open
5. Cloud model should be left aligned
6. Update UI regarding miss font weight and spacing
1. Update conditional render `New threads` icon when user downloads a local model or configured any cloud model and thread length 
2. The new code filters the `downloadStates` object values using the condition `x.modelId === featModel.id`. This means that only items with a `modelId` matching `featModel.id` will be rendered.
3. temporary with hard-coded recommend model 
4. Update `z-index` to avoid overlap, since the element dropdown options is absolute 
5. Removed …

fix: small leftover issues with new starter screen

---

joi/src/core/TextArea/TextArea.test.tsx
joi/src/core/TextArea/index.tsx
web/containers/ModelConfigInput/index.tsx
web/containers/ModelSetting/SettingComponent.tsx
web/screens/Thread/ThreadRightPanel/index.tsx

`TextArea` component enhances user experience by automatically adjusting its height based on content, while also allowing customization through props. This makes it suitable for dynamic input scenarios where the amount of text can vary significantly.
```tsx
autoResize?: boolean
minResize?: number
maxResize?: number
```
`Auto-Resizing Logic`
The `useEffect` hook adjusts the height of the textarea based on its scroll height whenever the value changes.
It sets the height to the minimum value initially, then adjusts it based on the content, ensuring it does not exceed the maximum height.
https://github.com/user-attachments/assets/1c8cedb1-3b14-4d95-9e81-f34531f423e1
- Closes #3649 
- Closes #

feat: textarea auto resize

---

web/containers/Providers/EventHandler.tsx

Preventing title generation. This ensures that the title generation logic runs only for local models
Added new condition on `generateThreadTitle`
https://github.com/user-attachments/assets/707b0026-ca60-475d-8499-9f03654ddad2
- Closes #3121 
- Closes #

fix: update the condition for generating the title

---

core/src/browser/extensions/assistant.test.ts
core/src/browser/extensions/inference.test.ts
core/src/browser/extensions/monitoring.test.ts
core/src/browser/tools/index.test.ts
core/src/browser/tools/tool.test.ts
core/src/index.test.ts
core/src/node/api/index.test.ts
core/src/node/api/processors/Processor.test.ts
core/src/node/api/processors/extension.test.ts
core/src/node/api/restful/helper/consts.test.ts
core/src/node/helper/config.test.ts
core/src/types/message/messageEntity.test.ts
core/src/types/miscellaneous/systemResourceInfo.test.ts
core/src/types/monitoring/index.test.ts
core/src/types/setting/index.test.ts
core/src/types/setting/settingComponent.test.ts
core/src/types/thread/threadEvent.test.ts
electron/jest.config.js
electron/testRunner.js
web/jest.config.js
web/utils/base64.test.ts
web/utils/converter.test.ts
web/utils/modelParam.test.ts
web/utils/threadMessageBuilder.test.ts

This PR adds missing tests for the core module and its types, specifically for browser and extension cases.
There is also a minor configuration update that could help tests be generated more efficiently.
These tests are auto-generated.
1. In `core/src/browser/tools/tool.test.ts`:
- Test to check if an error is thrown when `process` is called without implementation.
2. In `core/src/node/api/processors/extension.test.ts`:
- Test to handle empty extension list for install.
- Test to handle empty extension list for update.
- Test to handle empty extension list for uninstall.
3. In `core/src/node/helper/config.test.ts`:
- Test to check if extensions path is returned when retrieved successfully.
- Test to check if data folder path is returned when retrieved successfully.
4. In …

test: add missing tests to Jan core modules

---

web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx

- Fix toolbar chat input overlap
We are using `bg-textarea` for our toolbar because the `textarea` is on the right panel and needs a blur effect. 
That’s why we don’t set a background for the textarea, instead, the toolbar background should match the center panel. 
The code changes only update the background class for the toolbar element and reposition the toolbar to fit with the chat input, as the toolbar is positioned absolutely
- Closes #3647 
- Closes #

fix: toolbar overlap chat input

---

jest.config.js

- Extensions should be ignored while running jest, since it should be covered during packaging.
- Closes #
- Closes #

chore: The monorepo jest configs should not cover extensions - they would be moved to mini repositories soon

---

extensions/model-extension/src/index.test.ts
extensions/model-extension/src/index.ts
extensions/model-extension/src/node/index.ts
extensions/model-extension/src/node/node.test.ts

When downloading the HF GGUF model via URL import from the model hub, the model is using default settings instead of the correct settings. The fixed context length is set to 2048, the prompt template is incorrect, and there is an issue with the stop word. However, importing GGUF directly seems to resolve these issues.
Download the HF GGUF model from the model hub using URL import.
Check the settings for context length, prompt template, and stop word.
Compare the settings with the correct settings for the GGUF model.
The HF GGUF model downloaded via URL import should have the correct settings for context length, prompt template, and stop word, matching the settings when GGUF is imported directly.
The issue seems to be specific to downloading the HF GGUF model via URL import from the model …

fix: #3558 wrong model metadata import or download from HuggingFace

---

extensions/inference-anthropic-extension/jest.config.js
extensions/inference-anthropic-extension/package.json
extensions/inference-anthropic-extension/src/anthropic.test.ts
extensions/inference-anthropic-extension/src/index.ts
extensions/inference-anthropic-extension/tsconfig.json

Instructions are not sent when using the Claude 3.5 model. They work with other models (tested Open AI).
1. Select Claude 3.5 model.
2. Enter instructions e.g. "You will play the role of Hal, a highly knowledgeable AI assistant with a humorous and often sarcastic personality. Engage in conversation with the user, providing informative and helpful responses while injecting wit, irony, and playful jabs. Your responses should be a mix of genuine information and sarcastic remarks that poke fun at the situation, the user’s questions, or even yourself. Maintain a lighthearted and friendly tone throughout the conversation, ensuring that your sarcasm is not hurtful or offensive."
3. Send a chat "What's your name"
4. Model will respond: "My name is Claude."
5. Switch to GPT4o model and ask the …

fix: #3513 - Anthropic extension does not forward the system prompt

---

web/hooks/useCreateNewThread.test.ts
web/hooks/useCreateNewThread.ts

Fixed the issue #3515 
> Default instructions are no longer read from the configuration file when launching a new thread on linux.
I tried to remove the ~/jan file, remove my .AppImage file and install it from deb source (with today latest version) then fill again the "instructions" field in ~/jan/assistant/jan/assistant.json . Nothing work. I have to copy / paste my instructions from one thread to another instead of just spawning a new thread and go with my "all purpose for my needs" dev instructions.
- Closes #3515
1. **Creating a New Thread:**
- **Test Case**: `it('should create a new thread')`
- **Description**: This test mocks the dependencies and verifies that the `requestCreateNewThread` function properly sets up and saves a new thread. Expectations include checking that specific …

fix: #3515 - The default assistant instructions are ignored

---

extensions/inference-openai-extension/jest.config.js
extensions/inference-openai-extension/src/OpenAIExtension.test.ts
extensions/inference-openai-extension/src/index.ts
extensions/inference-openai-extension/tsconfig.json

This PR addresses the issue where OpenAI preview models don't work with the `max_tokens` parameter. We'll likely deprecate `model.json` for remote models at least, so we're not introducing new model parameter support. Instead, we're using the standard payload transform that's been applied to other providers.
The changes are mostly about adding tests.
> When making a request using o1-preview or o1-mini, getting:
> Unsupported parameter: 'max_tokens' is not supported with this model. Use 'max_completion_tokens' instead.
Jan’s in beta. Access troubleshooting assistance now.
> Cannot change these model parameters settings.
| o1-preview |
|:-:|
|![64707](https://github.com/user-attachments/assets/09d7e0ce-0200-43b5-9428-2998620ee8a3)|
| gpt-3.5-turbo|
|:-:| …

fix: #3698 - o1 preview models do not work with max_tokens

---

core/src/node/api/restful/helper/builder.test.ts
core/src/node/api/restful/helper/builder.ts
server/index.ts

This addresses the issue where the Jan API server gates requests based on body size, rejecting any larger than 1MB. This PR increases the accepted request body size and also handles errors gracefully.
> I'm trying to integrate OpenAI LLMs like, gpt-4-turbo, gpt-4o...etc to integrate with LaVague-QA framework for Test Automation. While LaVague is sending request to the LLM running in Jan.AI is responding with "Request body is too large" error.
1.Download the LLM gpt-4-turbo OR gpt-4o using Jan.AI interface
2.Make an API call to LLM (gpt-4-turbo OR gpt-4o)
3.Observe the response returned "Request body is too large"
Note: Attaching the API request body.
| Error handling |
|:-:|
|![28536](https://github.com/user-attachments/assets/453cd282-2267-45d8-8ea4-305da6dc8a2c)|
| Succeed |
|:-:| …

fix: #3673 - API responds with Request body is too large

---

core/src/node/api/processors/download.test.ts
core/src/node/api/processors/download.ts

- This PR addresses an issue where a model download failure still allows usage.
Root cause: The `request-progress` event fires `end` after the `error` event is emitted, toggling the download status back to succeed.
Models occasionally do not download correctly, but still report a "use" button, indicating that it was downloaded successfully, but the models can not be ran.
1. Open Jan
2. Attempt to download a model from the Hub
3. Use an app blocking software like glasswire to block the access to jan, simulating a loss of internet connection
4. Model will report as a failed or cancelled download in the top right
5. Model will show as downloaded and have a "use" button
6. Attempt to run the model, it will fail, sometimes with no error message
- Fixes #3727
- **New Test Added**:
- `should …

fix: #3727 LLM model download fail can still be used

---

extensions/inference-nitro-extension/package.json
extensions/inference-nitro-extension/resources/models/deepseek-coder-1.3b/model.json
extensions/inference-nitro-extension/resources/models/deepseek-coder-34b/model.json

This PR updates the DeepSeek Coder 33B Instruct download URL to a working quantized version. Stop tokens have also been added, allowing the model to outputs properly.
1. Download Deepseek Coder 33B Instruct
2. Try to use it in threads
| Deepseek Coder 33B |
|:-:|
|![38183](https://github.com/user-attachments/assets/d770b360-d238-4c8a-8d3a-2c935d642bc7)|
- Fixes #3703 
1. **`package.json` Updates:**
- The version number of the package has been incremented from `1.0.17` to `1.0.18`.
2. **`model.json` Updates for `deepseek-coder-1.3b`:**
- Version number incremented from `1.3` to `1.4`.
- The array for `stop` is now explicitly set to `["<|EOT|>"]`, which defines the end-of-text token.
- Tags have been modified to remove `"Foundational Model"`, leaving only `"Tiny"`.
3. **`model.json` Updates …

fix: #3703 - Deepseek-Coder-33B-Instruct is incompatible

---

core/src/node/api/processors/download.ts
core/src/types/file/index.ts
core/src/types/model/modelInterface.ts
extensions/model-extension/src/index.test.ts
extensions/model-extension/src/index.ts

There was an edge case where the model folder didn't match the model_id, leading to an issue where the app would download the local model to a cloned folder using the folder as its ID. This could result in an unwanted outcome, different from what the user had intended. 
We previously knew about an issue with the remote model, and now we've discovered an edge case for the local model folder.
This is a follow-up PR of #3476 
| Correct download progress |
|:-:|
|![88332](https://github.com/user-attachments/assets/e105ce4a-a799-4ebf-aac6-61693b44e91f)| 
| GUGU is a copied model of Gemma - It handles the download accordingly instead of duplicated or stuck at 0% |
1. **download.ts** in **core/src/node/api/processors/**
- The `modelId` variable now uses the `downloadRequest.modelId` if …

fix: wrong model download location when there is a mismatch model_id

---

extensions/tensorrt-llm-extension/jest.config.js
extensions/tensorrt-llm-extension/package.json
extensions/tensorrt-llm-extension/rollup.config.ts
extensions/tensorrt-llm-extension/src/index.test.ts
extensions/tensorrt-llm-extension/src/index.ts
extensions/tensorrt-llm-extension/tsconfig.json
web/hooks/useDownloadModel.ts

This PR fixes the Tensor-LLM engine download URL, making it accessible to Windows users with supported Nvidia GPUs, who can now install and use Tensort-LLM models. 
This also fixes the incorrect supported platforms from the extension, which currently only support Windows.
There's an edge case with model downloading on Windows that's been fixed, and it also resolved an issue where the renderer process would send a wrong aborting ID.
| Install Tensorrt-llm engine on Windows|
|:-:|
|![Screenshot 2024-09-29 153511](https://github.com/user-attachments/assets/58bdebe5-b66a-4b17-8a0b-7884f8b0c5a9)|
|![Screenshot 2024-09-29 153727](https://github.com/user-attachments/assets/ca8d6cc7-33a9-4f64-9962-1439264ae57f)|
- #3491 
1. In `package.json`:
- Added Jest testing setup and dependencies
- Updated …

fix: #3491 - Unable to use tensorrt-llm

---

web/containers/Layout/BottomPanel/SystemMonitor/TableActiveModel/index.tsx
web/containers/ModelDropdown/index.test.tsx
web/containers/ModelDropdown/index.tsx
web/containers/Providers/EventHandler.tsx
web/containers/SetupRemoteModel/index.tsx
web/helpers/atoms/Model.atom.test.ts
web/helpers/atoms/Model.atom.ts
web/hooks/useStarterScreen.ts
web/screens/Settings/MyModels/MyModelList/index.tsx
web/screens/Settings/MyModels/index.tsx
web/screens/Thread/ThreadCenterPanel/ChatBody/OnDeviceStarterScreen/index.tsx
web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
web/screens/Thread/ThreadRightPanel/index.tsx
web/utils/modelEngine.test.ts
web/utils/modelEngine.ts

- There was an issue where App hard-coded a static list of supported engines, making it difficult to enable community engine extensions support. Model UI's hacky part is being replaced by an Extension Class comparison, and this PR aims to unlock further engine installations.
| Installed MLX extension should be displayed |
|:-:|
|![image](https://github.com/user-attachments/assets/b35d87b6-a892-4f76-b737-e0288eaed19d)|
| The models should be able to run, as it's a local model |
|![56294](https://github.com/user-attachments/assets/c73b6c71-199f-45f4-8dfa-e3af50d9a550)|
1. The `localEngines` array is removed and replaced with an `isLocalEngine` function.
2. `isLocalEngine` function is introduced to check if an engine conforms to `LocalOAIEngine`:
- It uses …

fix: correct model dropdown for local models

---

web/helpers/atoms/Model.atom.test.ts
web/helpers/atoms/Model.atom.ts

There was an issue where recommended models weren't expanding to download, and this PR is just to fix that. This will be changed to cortex after 0.5.5
| Local models section is expanded by default |
|:-:|
|![21636](https://github.com/user-attachments/assets/df6782cf-6511-43c1-a99f-88afb70777d5)|
1. Model.atom.test.ts:
- In the test for 'showEngineListModelAtom', the expected initial value has been changed from an empty array ([]) to an array containing 'nitro' (['nitro']).
2. Model.atom.ts:
- The import statement has been updated to include 'InferenceEngine' from '@janhq/core'.
- The 'showEngineListModelAtom' has been modified to initialize with [InferenceEngine.nitro] instead of an empty array.
These changes suggest that the 'showEngineListModelAtom' is now being initialized with a …

fix: model dropdown should show recommended models to download

---

web/containers/Layout/RibbonPanel/index.tsx
web/containers/ModelDropdown/index.tsx
web/helpers/atoms/Extension.atom.test.ts
web/helpers/atoms/Model.atom.test.ts
web/helpers/atoms/Model.atom.ts
web/helpers/atoms/SystemBar.atom.test.ts
web/helpers/atoms/Thread.atom.test.ts
web/helpers/atoms/Thread.atom.ts
web/hooks/useAssistant.test.ts
web/hooks/useClipboard.test.ts
web/hooks/useDeleteModel.test.ts
web/hooks/useDeleteThread.test.ts
web/hooks/useDownloadModel.test.ts
web/hooks/useDropModelBinaries.test.ts
web/hooks/useFactoryReset.test.ts
web/hooks/useGetHFRepoData.test.ts
web/hooks/useGetSystemResources.test.ts
web/hooks/useGpuSetting.test.ts
web/hooks/useImportModel.test.ts
web/hooks/useLoadTheme.test.ts
web/hooks/useLogs.test.ts
web/hooks/useModels.test.ts
web/hooks/useModels.ts
web/hooks/useSetActiveThread.ts
web/hooks/useThread.test.ts
web/hooks/useThreads.ts
web/hooks/useUpdateModelParameters.ts
web/types/model.d.ts
web/utils/modelParam.ts

This PR introduces caching mechanisms for Models and Threads to enhance application performance and reduce potential risks when communicating with extensions. This would improve the app load experience a bit since it doesn't wait for the extensions function to complete its operation.
This is a very small step of Jan path to Cortex epic. Aim to apply minimal changes and add missing tests to app's state management and hook queries.
This PR also provides additional comments and clarification on using Atom for clearer state management stores.
**Notes**
Most of the code changes involve adding missing tests.
Next action item is to asynchronously import models from cortex.cpp.
```mermaid
flowchart LR
subgraph "Chat Shell"
direction LR
ChatShell[Chat Shell]
end
subgraph "Models Cache"
direction …
```

chore: improve models and threads caching

---

extensions/inference-nitro-extension/package.json
extensions/inference-nitro-extension/resources/models/command-r-34b/model.json
extensions/inference-nitro-extension/resources/models/gemma-2-27b/model.json
extensions/inference-nitro-extension/resources/models/gemma-2-2b/model.json
extensions/inference-nitro-extension/resources/models/gemma-2-9b/model.json
extensions/inference-nitro-extension/resources/models/llama3.1-70b-instruct/model.json
extensions/inference-nitro-extension/resources/models/llama3.1-8b-instruct/model.json
extensions/inference-nitro-extension/resources/models/llama3.2-1b-instruct/model.json
extensions/inference-nitro-extension/resources/models/llama3.2-3b-instruct/model.json
extensions/inference-nitro-extension/resources/models/qwen2.5-14b-instruct/model.json
extensions/inference-nitro-extension/resources/models/qwen2.5-32b-instruct/model.json
extensions/inference-nitro-extension/resources/models/qwen2.5-72b-instruct/model.json
extensions/inference-nitro-extension/resources/models/qwen2.5-7b-instruct/model.json
extensions/inference-nitro-extension/resources/models/qwen2.5-coder-7b-instruct/model.json
extensions/inference-nitro-extension/rollup.config.ts
web/screens/Thread/ThreadCenterPanel/ChatBody/OnDeviceStarterScreen/index.tsx

This PR is to add new models to the Model Hub and Starter screens.
New added models: 
- Llama3.2 1B Instruct Q8
- Llama3.2 3B Instruct Q8
- Qwen2.5 7B Instruct Q4_K_M
- Qwen2.5 Coder 7B Instruct Q4_K_M
- Qwen2.5 14B Instruct Q4_K_M
- Qwen2.5 32B Instruct Q4_K_M
- Qwen2.5 72B Instruct Q4_K_M
1. Version updates:
- The inference-cortex-extension package version is bumped from 1.0.18 to 1.0.19.
- Several model versions are incremented (e.g., Command-R, Gemma, Llama).
2. Model tag changes:
- The "Featured" tag is removed from several models (Command-R, Gemma, Llama).
3. New models added:
- Llama 3.2 1B and 3B Instruct models
- Qwen 2.5 series models (7B, 14B, 32B, 72B, and Coder 7B)
4. Configuration updates:
- New model JSON configurations are added to the rollup config.
5. UI changes:
- In …

chore: add llama3.2 and qwen2.5 models

---

web/containers/Layout/BottomPanel/SystemMonitor/SystemMonitor.test.tsx
web/containers/Layout/BottomPanel/SystemMonitor/index.tsx

Currently, the System Monitoring component continuously requests information from the hardware's endpoints to retrieve resource details. However, it could be improved by sending requests only when the system monitoring bar is shown. When it's closed, it should stop requesting.
Also added tests to the component.
1. A new test file `SystemMonitor.test.tsx` has been added:
- It includes unit tests for the SystemMonitor component
- Mocks dependencies and hooks used by the component
- Tests basic rendering and expanded view scenarios
2. Changes to the existing `index.tsx` file:
- Imports have been updated, removing `useEffect` and adding `useCallback`
- A new `toggleShowSystemMonitorPanel` function has been introduced using `useCallback`
- The `useEffect` hook for watching resources has been …

fix: Optimize resource watching

---

web/containers/Loader/ModelStart.tsx
web/containers/ModelDropdown/index.tsx

fix: overlap text on model selector and loader

---

extensions/model-extension/src/index.test.ts
extensions/model-extension/src/index.ts
extensions/model-extension/src/node/index.ts

This PR is the hotfix branch for issue #3763 merged into main.
There was an issue where the fix for #3708 attempted to retrieve metadata and the chat template from GGUF models, but models without a `chat_template` could throw an error. To address this, we added error handling to catch exceptions and fall back to the default chat template.
| Imported GGUF models without chat_template metadata |
|:-:|
|![57210](https://github.com/user-attachments/assets/1209fd6b-cb1e-47d5-8fd0-15e190b7b083)|
- #3558 
1. In `index.test.ts`:
- Two new test cases were added:
a. Testing the handling of a model with a valid chat_template
b. Testing the handling of a model without a chat_template
2. In `index.ts`:
- The `retrieveGGUFMetadata` method was modified:
- Added error handling for the `executeOnMain` …

hotfix: graceful error handling model import

---

extensions/model-extension/src/index.test.ts
extensions/model-extension/src/index.ts
extensions/model-extension/src/node/index.ts

There was an issue where the fix for #3708 attempted to retrieve metadata and the chat template from GGUF models, but models without a `chat_template` could throw an error. To address this, we added error handling to catch exceptions and fall back to the default chat template.
|Import and HF Download Models|
|:-:|
| Mathstral |
|<img width="1206" alt="image" src="https://github.com/user-attachments/assets/c53196ef-74a4-4b72-811b-67b964295e06">|
| A random missing metadata model |
|<img width="1206" alt="image" src="https://github.com/user-attachments/assets/07b4b3a8-fd59-45ab-9e6c-d961237823dd">|
|With the correct model metadata imported|
|<img width="1206" alt="image" src="https://github.com/user-attachments/assets/bd51e942-2f2a-470e-ae79-a0123d070999">|
- #3558 
1. In `index.test.ts`:
- …

fix: error handling for model imports should be handled gracefully

---

web/hooks/useLoadTheme.ts
web/package.json
web/screens/Thread/ThreadRightPanel/index.tsx

`ThreadRightPanel/index.tsx`
The condition checking for `experimentalFeature` before rendering <CopyOverInstruction /> has been removed. This means the component will always be rendered, regardless of whether the feature is experimental or not.
`eslint-plugin-react-hooks` has been removed for fix the `eslint` issue 
- Closes #3704 
- Closes #

feat: save instruction for new threads as a stable feature

---

joi/src/core/Tabs/styles.scss
web/screens/Hub/index.tsx
web/screens/LocalServer/LocalServerLeftPanel/index.tsx
web/screens/Settings/Advanced/index.tsx

- From https://github.com/janhq/jan/issues/3818 
- Fix search model on Hub 
- Fix text overlapping button
- Closes #
- Closes #

fix: api playground text overlap button and search hub model

---

web/containers/ModelSetting/SettingComponent.tsx
web/containers/SliderRightPanel/index.tsx

To make val always stay in sync with `value.toString()` in React, you need to update val whenever value changes. we need using the `useEffect` hook, which will listen for changes in value and update val accordingly.
- Closes #3842 
- Closes #

fix: context length input value isn't update 

---

.github/workflows/template-build-windows-x64.yml

- chore: replace windows codesign cert
- Related issue #3801 
- Closes #
- Step 1: Download the Jan Windows version with the old codesign of the beta version (this is a test version, and we haven't notified users about it yet; I will remove it later). You can download it here: https://github.com/janhq/jan/releases/download/v0.5.7-rc1-beta/jan-beta-win-x64-0.5.7-rc1-beta.exe. After downloading, you can verify that this version is signed with Jan's certificate.
- Step 2: Install the app. After installation, you will see a notification that a new version (v0.5.7-rc2-beta) is available for update. Click to update it, and then restart the app => you update app successfully
- Step 3: You can download the Windows file for v0.5.7-rc2-beta here: …

chore: replace windows codesign cert

---

extensions/inference-martian-extension/resources/settings.json

- Updated the incorrect hyperlink for the **Martian** section under **Settings > Model Providers > Martian** to point to the correct documentation.
- Replaced the old link [https://docs.withmartian.com/martian-model-router/api-reference/get-chat-completions](https://docs.withmartian.com/martian-model-router/api-reference/get-chat-completions) with [https://docs.withmartian.com/martian-model-router/getting-started/quickstart-integrating-martian-into-your-codebase](https://docs.withmartian.com/martian-model-router/getting-started/quickstart-integrating-martian-into-your-codebase), which provides more accurate and up-to-date integration instructions for Martian.
---
- Closes #3856 
---

Update broken/outdated hyperlink

---

web/screens/Settings/Advanced/index.tsx

- Wrong logic, hidden dropdown only 
- Closes #
- Closes #

fix: hardware section

---

web/screens/Thread/ThreadCenterPanel/ChatInput/RichTextEditor.tsx

fix: reset prompt when send click button

---

web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx

https://discord.com/channels/1107178041848909847/1149558035971321886/1299591685667553290
- Issue edge case show tiny chat input box
- copy and paste text below to input chat box
```
Hi mew,
asdf awef 
afsdfawef
asdf awe f 
```
- Hides elements from visual users but makes them available to screen readers
- Closes #
- Closes #

fix: edge case tiny chat input box show randomly

---

joi/rollup.config.mjs

Update `rollup` config to use option sass `silenceDeprecations`
- Closes #
- Closes #

chore: remove deprecated warning from build project joi

---

web/containers/Layout/RibbonPanel/index.tsx

Adding `onClick` to the outer `div`:
A new `onClick` attribute was added to the outer div, which calls the `onMenuClick(menu.state)` function when clicked. This change ensures that clicking on the entire menu item triggers the `onMenuClick` function, rather than just the icon.
- Closes #3885 
- Closes #

feat: expand the clickable areas ribbon panel

---

web/containers/ModelSearch/index.tsx
web/screens/Thread/ThreadCenterPanel/ChatInput/RichTextEditor.tsx

Auto-focus the chat input box and search box when switching between pages and thread lists
https://github.com/user-attachments/assets/9d9454d2-6f2a-4e33-8215-db30656e0705
- Closes #3932 
- Closes #

ux: auto-focus the chat input box 

---

web/containers/Layout/RibbonPanel/index.tsx
web/screens/Settings/SettingLeftPanel/SettingItem/index.tsx
web/screens/Thread/ThreadLeftPanel/index.tsx

Remove redundant animation when switch menu on ribbon and left panel
- Closes #3815 
- Closes #

ui: remove redundant animation

---

web/containers/Layout/BottomPanel/SystemMonitor/index.tsx
web/screens/Thread/ThreadCenterPanel/index.tsx

Calculate the height of the thread center panel based on the system monitor height to avoid overlapping with the input chat box
- Closes #3812 
- Closes #

ui: system monitor should not cover input box

---

core/src/node/api/processors/download.ts
core/src/types/file/index.ts
web/containers/Layout/BottomPanel/DownloadingState/index.tsx
web/containers/ModalCancelDownload/index.tsx
web/hooks/useDownloadModel.ts
web/hooks/useDownloadState.ts
web/screens/Settings/MyModels/MyModelList/index.tsx

- There was an issue where cortex.cpp does not support simultaneous downloads. Therefore, Jan should show the model download at 0 percent as a download bar.
1. **`download.ts`:**  
- Removed `time` and `speed` from the initial download state definition, reflecting these as optional in the `DownloadState` type.
2. **`file/index.ts`:**  
- Modified the `DownloadState` type to make `time` and `speed` optional.
3. **`DownloadingState/index.tsx`:**  
- Added the `removeDownloadStateAtom` to handle the removal of download states.
- Enhanced the abort logic to also remove the download state when an abort is initiated.
4. **`ModalCancelDownload/index.tsx`:**  
- Similar updates as in `DownloadingState`, using `removeDownloadStateAtom` to remove download states upon abort.
5. …

fix: Inconsistent model hub and download bar

---

extensions/model-extension/src/legacy/model-json.ts
web/hooks/useModels.ts

This PR allows users to customize model.json to point to a compatible OpenAI endpoint. It applies the legacy model scanning for these cases.
The `git diff` highlights the following changes in the `model-json.ts` file:
1. **Added Local Engines Array:**
- A new constant array `LocalEngines` has been added. It contains specific inference engines from the `InferenceEngine` enum: `cortex`, `cortex_llamacpp`, `cortex_tensorrtllm`, `cortex_onnx`, `nitro_tensorrt_llm`, and `nitro`.
2. **Modified Conditional Logic:**
- The conditional check within the `scanModelsFolder` function was altered.
- Previously, the code returned the `model` if all `existFiles` evaluated to true.
- Now, the code checks if the model's engine is *not* in the `LocalEngines` list or if all `existFiles` are true before …

chore: support customized OpenAI model.json

---

web/screens/Thread/ThreadCenterPanel/ChatBody/OnDeviceStarterScreen/index.tsx

https://github.com/janhq/jan/issues/3911#issuecomment-2459146523
fix text alignment off and missing model size when downloading state
- Closes #
- Closes #

fix: starter screen text alignment and missing model size

---

extensions/inference-cortex-extension/download.bat
extensions/inference-cortex-extension/src/index.ts
extensions/inference-cortex-extension/src/node/index.ts
extensions/model-extension/src/index.ts

This is to add engine destination into PATH so that the OS can scope the additional dlls in.
The given `git diff` shows changes made to the `index.ts` file in the `extensions/inference-cortex-extension/src/node/` directory. Here's a summary of the modifications:
- **Addition**: A new block of code has been added between existing lines (after line 33). This newly added block is responsible for adding the `cortex.llamacpp` path to both the `PATH` and `LD_LIBRARY_PATH` environment variables.
- **Context**: This addition is necessary for ensuring that the `cortex` engine executable and its dependencies (DLLs) can be found and executed correctly, as the required DLLs are not yet moved to a more accessible location within the system's root directories.
- **Impact**: By calling `addEnvPaths` …

fix: export PATH env to engine destination folder to have additional dlls scoped

---

web/screens/Settings/SettingDetail/SettingDetailItem/SettingDetailTextInputItem/index.tsx
web/screens/Thread/ThreadCenterPanel/EditChatInput/index.tsx

1. Edit Message will always make cursor input on latest length
2. Issue unable copy api_key, update icon also, when copied will show checklist
3. Update Toggle icon EyeOnIcon / EyeOffIcon
https://github.com/janhq/jan/issues/3911#issuecomment-2462273485
https://github.com/janhq/jan/issues/3911#issuecomment-2462296163
- Closes #
- Closes #

fix: ux edit message and copy api_key

---

.github/workflows/jan-electron-build-nightly.yml
.github/workflows/template-build-linux-x64.yml
.github/workflows/template-build-macos-arm64.yml
.github/workflows/template-build-macos-x64.yml
.github/workflows/template-build-windows-x64.yml

- chore: enable notification nightly
- Closes #
- Closes #

chore: enable notification nightly

---

web/screens/Thread/ThreadCenterPanel/ChatInput/RichTextEditor.tsx

https://github.com/janhq/jan/issues/3911#issuecomment-2463806672
https://github.com/user-attachments/assets/1cd067ad-db95-418c-af04-cd9654f822ba
- Closes #
- Closes #

fix: correct chat input cursor behavior when content is scrollable

---

core/src/browser/extensions/model.ts
extensions/model-extension/src/cortex.ts
extensions/model-extension/src/index.ts
web/containers/Providers/EventHandler.tsx
web/hooks/useModels.ts

- In previous versions, the model was marked as stopped as soon as a message error occurred. However, it could be an issue with the inference parameters, meaning the model was still running, leading to an incorrect status. This PR aims to improve this by checking the model status before marking it as not started.
- This also updates legacy model.json settings & inferences to overwrite cortex.cpp prompt extraction from the model's metadata, which could cause issues.
The changes in the provided diff focus on adding a feature to check the loading status of a model and ensuring better code readability. Here’s a summary of the changes:
1. **`ModelExtension` Class in `model.ts`:**
- Added a new abstract method `isModelLoaded(model: string): Promise<boolean>` to check if a model is loaded.
2. …

chore: retrieves the exact model running status upon message error

---

core/src/node/api/restful/common.ts
core/src/node/api/restful/helper/builder.test.ts
core/src/node/api/restful/helper/builder.ts
core/src/node/api/restful/helper/consts.ts

This PR makes Jan /models and /chat_completions proxies to cortex.cpp.
NOTES: This removed the OpenAI proxy due to poor implementation and missing features. It would be better for cortex.cpp to support this more soon.
1. **Proxying /models Route:**
- The `getModels` function was introduced in `helper/builder.ts`. It is designed to proxy requests to the `/models` endpoint of the Cortex API.
- In `common.ts`, the `/models` route handling in the `commonRouter` was modified to use the new `getModels` function.
2. **Refactoring chatCompletions:**
- Removed retrieval of model details and configuration for the chatCompletions logic.
- The `chatCompletions` function no longer fetches model configurations or dynamically constructs the API URL based on a model ID. Instead, it directly calls the …

chore: proxies Jan APIs to cortex.cpp

---

extensions/model-extension/src/cortex.ts
extensions/model-extension/src/index.ts
web/containers/Providers/EventListener.tsx
web/hooks/useModels.ts

- This PR addresses the major issue of migrating the Jan model.json to cortex.cpp model.yaml. Legacy model settings and parameters are not maintained during the transition because cortex.cpp attempts to extract metadata from the GGUF model file.
- As described in #3690, Jan will import all existing models to cortex.cpp, and new model download requests will be proxied to cortex.cpp. An idea came up to force the app to use model.json settings, but this created an issue where users could only change model settings through the GUI and not update model.yml.
- This PR updates model settings and parameters when transferring models to cortex.cpp, keeping all settings intact and allowing users to edit via model.yml.
| Gemma 2B uses a pre-defined prompt template not from gguf metadata |
|:-:| …

fix: migrate model settings and parameters but still allow model.yml editing

---

web/screens/Thread/ThreadCenterPanel/ChatInput/RichTextEditor.tsx

Enforce strict code block rules, 
- The code block should start with triple backticks followed by a file extension `(```css)`, and end with triple backticks `(```)`.
This ensures that the code block is correctly defined with both the opening and closing triple backticks, with an optional file extension immediately after the opening backticks.
- Multiple code blocks may impact each other. For example, if one of the code blocks is missing a formatting rule (e.g., missing the closing backticks), none of the code blocks will be highlighted
- Closes #3884 
- Closes #

fix: edge cases highlight codeblock

---

electron/utils/migration.ts
web/hooks/useImportModel.ts
web/package.json
web/screens/Settings/Advanced/index.tsx

- This PR addresses the issue of app importing models as full paths on model ID windows.
- #3911 
1. **Imports:**
- The import for `ModelEvent` was removed.
- A new import `baseName` was added from `@janhq/core`.
2. **Function Changes:**
- Inside the `importModels` function:
- The `.map()` method on `models` was changed to be `async`.
- The `modelId` assignment now uses `await baseName(model.path)` instead of `model.path.split('/').pop()` to extract the base name of the path.

fix: Model import name and ID are incorrect on Windows

---

core/src/node/api/processors/download.ts
core/src/node/api/processors/fs.ts
core/src/node/api/processors/fsExt.ts
core/src/node/helper/path.ts
extensions/model-extension/src/index.ts
web/containers/ModelDropdown/index.tsx
web/screens/Settings/SelectingModelModal/index.tsx

- Fixed inconsistent model list across components.
- Fixed import of gguf files on Linux (file picker).
- Fixed importing symlinked models to files outside the app folder.
Notes: 
Path validation is no longer needed since now
1. App does not expose FS APIs to external sources
2. Shifting those to cortex.cpp
- Removed usage of `validatePath` imported from `../../helper/path`.
- The function is no longer called to validate the path before processing file operations.
- Instances of `validatePath` were removed when resolving paths for various file operations, such as directory removal and creation.
- The `validatePath` function call was removed before writing a file and copying a file.
- The `validatePath` function was removed entirely. It was responsible for ensuring paths were whitelisted, …

fix: inconsistent model dropdown list and my models

---

extensions/inference-openai-extension/src/index.ts

- A follow-up PR of #3728 to update transform payload to support o1 preview models
- #3771 
The code changes in the Git diff involve a modification to the `transformPayload` function within a TypeScript file, specifically `src/index.ts`.
1. **Comment Formatting**: There were minor formatting changes to remove extra spaces in the comments.
2. **Function Logic**:
- The `transformPayload` function originally extracted the `max_tokens` from the `payload` and passed the rest of the parameters through.
- Now, it also extracts `temperature`, `top_p`, and `stop` parameters along with `max_tokens`, and the remaining parameters (`params`) are spread into the new object.
- The key `max_completion_tokens` is set with the value of `max_tokens`.
- A new property `stream` is added to the returned …

fix: update the payload transform for OpenAI preview models

---

web/hooks/useDropModelBinaries.ts
web/hooks/useImportModel.ts
web/screens/Thread/ThreadCenterPanel/LoadModelError/index.tsx

This PR removes the irrelevant error message about missing CUDA toolkit dependencies since it’s now shipped by default. Bring back the legacy incremental model import naming convention.
**1. `useDropModelBinaries.ts`:**
- The name processing for file names was modified. Any spaces in the file name are now removed before the '.gguf' extension is stripped.
**2. `useImportModel.ts`:**
- Jotai's `useAtomValue` was imported to access the atom state.
- `downloadedModelsAtom` was added to the imports, which enables tracking of already downloaded models.
- A new utility function, `incrementalModelName`, was introduced to handle naming conflicts. This function ensures that any model name duplicates are resolved by appending a number to the model's name.
- The naming logic for models during import …

fix: remove cuda toolkit error message and bring back incremental model import

---

web/containers/Layout/BottomPanel/SystemMonitor/index.tsx
web/screens/Thread/ThreadCenterPanel/index.tsx

Since content System monitor panel element will be dynamic from list of GPU, we change base layout will detect and calculate height base on height of system monitor panel.
- Closes #
- Closes #

fix: calculate base layout with system monitor panel

---

extensions/inference-openrouter-extension/resources/models.json
web/screens/Settings/SettingDetail/SettingDetailItem/SettingDetailTextInputItem/index.tsx

fix: max tokens params OpenRouter

---

web/screens/LocalServer/LocalServerRightPanel/index.tsx

Issue when on local API server page Jan App, switch model not update max `ctx-len`
- Closes #
- Closes #

fix: api local server max ctx len not update when switch model

---

web/screens/Thread/ThreadCenterPanel/SimpleTextMessage/index.tsx

Before
After
- Closes #4039 
- Closes #

fix: improper line break on response message

---

extensions/inference-cortex-extension/src/index.ts
extensions/model-extension/src/index.ts
extensions/model-extension/src/legacy/delete.ts
extensions/model-extension/src/legacy/model-json.ts
web/hooks/useModels.ts

This PR added a few changes that handle edge cases of models import, such as:
1. The model import and run fail due to a mismatch between the folder name and the model ID.
2. Model deletion failed due to a mismatch between folder name and model ID.
3. The model wouldn’t be automatically reimported if the user deleted the same model before.
4. The model display name is incorrect, it’s displaying the model’s ID instead.
5. A broken import process could block the model listing process
| This screenshot shows a case where users have a self-crafted model.json folder named "test" with a model ID of "this-is-test-model".` |
|:-:|
|![Screenshot 2024-11-19 at 11 47 16](https://github.com/user-attachments/assets/85119219-4a47-4163-9306-aa6eaf8eb5a2)|
|![Screenshot 2024-11-19 at 11 57 …

fix: model import edge cases

---

extensions/inference-cortex-extension/src/index.ts

This PR addresses a specific edge case where users could create a symlink to a model file located outside the data folder. This is done to fall back to legacy model run behavior in case model import fail due to potential issues like server API corruption, metadata extraction errors, or YAML parse errors.
To ensure a fallback to the legacy model run behavior, where it can be forced to run with llama_model_path.
In the screenshot, there are no models imported to cortex.cpp. Instead, there was a Test ID model that was symlinked by the model.json file (version 0.5.7 or lower). This model can still run as before the update.
The provided `git diff` output shows changes made across three files. Here's a summary of the modifications:
1. **`extensions/inference-cortex-extension/src/index.ts`:**
- …

fix: handle symlink model import failure - fallback to legacy model run

---

web/hooks/useActiveModel.ts
web/hooks/useSendChatMessage.ts
web/screens/Thread/ThreadCenterPanel/LoadModelError/index.tsx

There’s an issue where the app displays two different user interfaces for error handling between Model Inference and Load. Additionally, this is being done to add the error information returned from cortex.cpp for improved error handling in the future.
| Model Load | Model Inference |
|:-:|:-:|
|![Screenshot 2024-11-19 at 23 17 57](https://github.com/user-attachments/assets/c64c22c5-0799-4957-b8bd-645b2a841aa8)|![image](https://github.com/user-attachments/assets/403d08b8-fa58-459a-9eff-0fcfbb5ff064)|
| Model Load with the fix - First error message is returned from cortex.cpp server |
|:-:|
|![Screenshot 2024-11-19 at 23 17 37](https://github.com/user-attachments/assets/72299dfc-9d61-4f51-a580-e824b39bf21b)|
This PR also eliminates the deprecated error handling scenario where the port …

fix: inconsistent error handling

---

core/src/browser/extensions/engines/helpers/sse.ts
extensions/inference-cortex-extension/src/index.ts
extensions/inference-openai-extension/resources/models.json
extensions/inference-openai-extension/src/index.ts
extensions/model-extension/package.json
extensions/model-extension/src/index.ts

- As discussed in https://github.com/janhq/jan/issues/3745, there are fixed parameters from the endpoints of the o1 models. Therefore, the current model.json files should be updated accordingly.
- This PR aims to correct the transform payload to the models and also to return graceful error messages as soon as inference errors occur.
- A few unsupported parameters have been removed to prevent confusion.
- #3745
- #3771
This git diff summarizes a set of code changes across multiple files. Here's a concise breakdown:
1. **`sse.ts` (Helper for SSE requests):**
- Added a check for an overridden `stream` parameter in the request body. If `stream` is false either in the request body or model parameters, it adjusts accordingly.
2. **`models.json` (Model Configuration File):**
- Removed the …

fix: correct OpenAI o1 model parameters

---

core/src/browser/extensions/engines/helpers/sse.ts
extensions/inference-cohere-extension/src/index.ts
extensions/inference-openai-extension/package.json
extensions/inference-openai-extension/resources/models.json
extensions/inference-openai-extension/src/index.ts
web/containers/ErrorMessage/index.test.tsx
web/containers/ErrorMessage/index.tsx
web/containers/Providers/EventHandler.tsx

This press release aims to enhance the error handling of remote models, which previously returned a generic error message indicating something was wrong. Now, it displays a more detailed error message from the provider.
It was also an additional request that caused the confusion, so I removed it.
This also fixed Cohere & O1 models stream mode issue
- #4054 
- #3475
1. **sse.ts**: 
- The error handling logic was modified to check for an additional `data.message` field when constructing error messages. This change ensures the error message falls back to `data.message` if `data.error?.message` is not available.
2. **ErrorMessage/index.tsx**: 
- The `ErrorCode.Unknown` case was removed from the error title handling, meaning no specific title is provided for unknown errors.
- Minor refactoring …

chore: remote models error handling

---

extensions/inference-cortex-extension/download.bat
extensions/inference-cortex-extension/download.sh

- This PR fixed the issue where app look for dll files in an incorrect location. Where it should be in bin path instead of shared path.
- Closes #
- For all of subfolders of engine variants before, we use different names, so now is to align with that.

fix: correct download script to relocate dll files properly

---

web/screens/Thread/ThreadCenterPanel/SimpleTextMessage/index.tsx
web/styles/components/code-block.scss

hide copy element when code block empty 
- Closes #3990 
- Closes #

fix: edge cases empty code block

---

extensions/model-extension/src/index.ts
extensions/monitoring-extension/src/node/index.ts
web/hooks/useSettings.ts
web/screens/Settings/Advanced/index.tsx

This press release aims to enable users to configure HuggingFace tokens to access private repositories through the cortex.cpp configuration endpoint.
This PR also resolved a legacy issue where the app incorrectly reported the GPU mode, which caused an issue when running a model with only a CPU model.
- #4067
Reproduce:
1. As a user, if I haven’t configured any Hugging Face token with access to a restricted repository, I would encounter an error when attempting to download its files.
2. After configuring a valid token that granted access to the repository, I was able to download the models.
The code changes introduce and manage a new setting for a Hugging Face access token within the `JanModelExtension` class. Here's a summary of the changes made:
1. **Enum Declaration**:
- Added a new …

feat: configure HuggingfaceToken via cortex.cpp

---

extensions/inference-cortex-extension/package.json
extensions/inference-cortex-extension/resources/models/phi3-3.8b/model.json
extensions/inference-cortex-extension/resources/models/phi3-medium/model.json
web/hooks/useModels.ts

This PR is to correct the download URL of Phi 3 Mini 4k Instruct model. 
#[4073](https://github.com/janhq/jan/issues/4073)
The model can now be downloaded with proper metadata, including its size, name, and it runs properly.
Update:
This PR included a hot fix for Tensorrt-LL models listing

fix: Phi 3 Mini Instruct model download url replacement

---

extensions/inference-cortex-extension/src/index.ts
extensions/inference-cortex-extension/src/node/cpuInfo.ts
extensions/inference-cortex-extension/src/node/execute.ts
web/hooks/useFactoryReset.test.ts
web/hooks/useFactoryReset.ts

- This resolves the issue where the app hangs during a factory reset. The root cause is that some dependencies are loaded onto the JavaScript VM and hold the process.
To resolve this issue, we can fork the dependency execution to a separate process and terminate it once its execution is complete.
- [#4001](https://github.com/janhq/jan/issues/4001)
1. **asynchronous OnUnload Method**:
- Changed the `onUnload` method in `JanInferenceCortexExtension` to be asynchronous and added an `await` before calling `executeOnMain`.
2. **New File for CPU Information**:
- Added a new file `cpuInfo.ts` that uses the `cpu-instructions` package to check CPU features (`avx512`, `avx2`, `avx`, or `noavx`) and sends this information back to the parent process using inter-process communication.
3. **CPU …

fix: factory reset hang on wiping data

---

joi/src/core/Slider/index.tsx
joi/src/core/Slider/styles.scss
web/helpers/atoms/LocalServer.atom.ts
web/screens/LocalServer/LocalServerLeftPanel/index.tsx
web/screens/LocalServer/LocalServerRightPanel/index.tsx

1. **Slider Component Enhancements**:
- Added `twMerge` from `tailwind-merge` to conditionally apply Tailwind CSS classes.
- Modified the `className` prop of the `SliderPrimitive.Root` component to use `twMerge` for dynamic class names based on whether the slider is disabled.
2. **Slider Styles**:
- Added styles for a disabled state in `styles.scss`, making the cursor unavailable and reducing opacity when the slider is disabled.
3. **Atom Updates**:
- Added a new atom `LocalAPIserverModelParamsAtom` in `LocalServer.atom.ts`.
- Updated imports and uses of `serverEnabledAtom` and `selectedModelAtom` across various components to ensure consistency and access to these atoms.
4. **Left Panel Enhancements**:
- Imported necessary types from `@janhq/core` for better type safety.
- Used …

fix: model params settings local api server

---

web/containers/Providers/KeyListener.tsx

The Git diff shows that there have been some modifications made to the `KeyListener.tsx` file located in the `web/containers/Providers` directory. Here's a detailed description of the changes:
1. **Import Statement**:
- A new import statement for `useStarterScreen` has been added from '@/hooks/useStarterScreen'.
2. **Variable Declaration**:
- A new variable `isShowStarterScreen` is declared by destructuring from the `useStarterScreen` hook.
3. **UseEffect Dependency Update**:
- The dependency array of the `useEffect` hook has been updated to include the newly added `isShowStarterScreen`.
4. **Conditional Check in useEffect**:
- Inside the `onKeyDown` event handler, there is a conditional check to ensure that the `isShowStarterScreen` is `false` before proceeding with certain actions.
- …

fix: disabled shortcut create new thread on starter screen

---

web/screens/Settings/Hotkeys/index.tsx
web/screens/Thread/ThreadCenterPanel/ChatBody/OnDeviceStarterScreen/index.tsx

<br/>
Also fix for remove deprecated shortcut
https://github.com/janhq/jan/issues/4055#issuecomment-2490320629
- Closes #4066 
- Closes #

fix: reorder alphabetical cloud model on starter screen

---

web/styles/components/message.scss

- Cannot open right panel bc value content markdown no space, center panel will push out right panel
using `word-break: break-word`
- Closes #4090 
- Closes #

fix: handle case markdown value no space

---

web/hooks/useSendChatMessage.ts
web/screens/Thread/ThreadCenterPanel/EditChatInput/index.tsx

When editing a message, for instance, "A of A _ B _C," it sends "A B C A" instead of just "A."
- #4086
1. **`useSendChatMessage.ts`:**
- The `sendChatMessage` function's signature has been updated to accept an optional `messages` parameter of type `ThreadMessage[]`.
- When calling `requestBuilder.requestThread`, if `messages` is provided, it will be used; otherwise, `currentMessages` will be used as before.
2. **`index.tsx`:**
- Within the `EditChatInput` component, the call to `sendChatMessage` has been updated to pass `newMessages` as the second argument, matching the updated function signature.
These changes likely aim to provide more flexibility when sending chat messages by allowing an optional thread message array to be passed to the `sendChatMessage` function.

fix: 4086 - editing message should not send follow-up messages

---

core/src/types/setting/settingComponent.ts
web/containers/EngineSetting/index.tsx
web/containers/ModelConfigInput/index.tsx
web/containers/ModelSetting/SettingComponent.tsx
web/containers/ModelSetting/index.tsx
web/containers/TagInput/index.test.tsx
web/containers/TagInput/index.tsx
web/screens/LocalServer/LocalServerRightPanel/index.tsx
web/screens/Settings/ExtensionSetting/index.tsx
web/screens/Settings/SettingDetail/SettingDetailItem/SettingDetailTextInputItem/index.tsx
web/screens/Settings/SettingDetail/SettingDetailItem/index.tsx
web/screens/Thread/ThreadCenterPanel/AssistantSetting/index.tsx
web/screens/Thread/ThreadRightPanel/PromptTemplateSetting/index.tsx
web/screens/Thread/ThreadRightPanel/index.tsx
web/utils/componentSettings.ts
web/utils/predefinedComponent.ts

Type Modifications:
In settingComponent.ts, the `ControllerType` type now includes 'tag' as a possible value. The `InputComponentProps` type has been adjusted to allow value to be either string or string[].
`ModelConfigInput` Component:
The code in `ModelConfigInput/index.tsx` has been refactored to use a return statement with curly brackets {} instead of an implicit return, although its logic remains largely unchanged.
`SettingComponent` Component:
In ModelSetting/SettingComponent.tsx, added support for the 'tag' controller type, including handling for the value to be string[] and modifying the `onValueUpdated` function to handle arrays of strings.
`ModelSetting` Component:
In ModelSetting/index.tsx, the onValueChanged function signature was updated to accept string[].
TagInput …

feat: stop word model setting

---

web/screens/Thread/ThreadCenterPanel/SimpleTextMessage/index.tsx
web/styles/components/code-block.scss

Missing border color and line number color when code block render on Jan light theme
Dark dimmed
Dark
Light 
Night Blue
- Closes #4103 
- Closes #

fix: Line-number and border color code block UI

---

web/package.json

Update highlight.js version
https://github.com/user-attachments/assets/6b24cc4c-4d13-42a6-a344-5feba9bf589c
issue on highlight.js 
reference:
- https://github.com/wooorm/lowlight/issues/60
- https://github.com/rehypejs/rehype-highlight/issues/31
- https://github.com/remarkjs/react-markdown/issues/791
- Closes #4102 
- Closes #4124

fix: memory leak when the code block response is too long

---

electron/tests/e2e/thread.e2e.spec.ts
web/containers/ErrorMessage/index.test.tsx
web/containers/ErrorMessage/index.tsx

The error message for an invalid request is not handled correctly. Instead of displaying a clear error message from the provider, it prompts users about an invalid API key error.
- #3986
The provided `git diff` shows a modification in the `index.tsx` file located in the `web/containers/ErrorMessage` directory. Specifically, the change involves removing a single case from a switch statement. The case that has been removed is:
```typescript
case ErrorCode.InvalidRequestError:
```
This change means that the `ErrorMessage` component will no longer handle the `InvalidRequestError` by displaying a specific error message (i.e., an invalid API key error), which was part of the switch statement before this modification.

fix: 3986 - invalid request should show clear error message

---

extensions/inference-cortex-extension/src/index.ts

This PR addresses an issue where the app frontend displays an active running model even after the user forcefully terminates the cortex-server.cpp process through the activity monitor.
Before killing the process
After killing the process
- #4012
1. **Whitespace Adjustment:**  
- A line containing only whitespace was modified. An unnecessary trailing whitespace was removed on line 71.
2. **Event Emission on WebSocket Closure:**  
- A new line was added after the `console.log('WebSocket closed:', event)` within the `this.socket.onclose` function. The new line emits an event `ModelEvent.OnModelStopped` with an empty object (`{}`) as the payload. This likely triggers logic elsewhere in the application when a WebSocket connection is closed.

fix: 4012 - active model should be gone as soon as cortex.cpp server is killed

---

extensions/inference-cortex-extension/src/index.ts
extensions/inference-cortex-extension/src/node/execute.test.ts

This PR aims to update the cortex API request regarding the default engine variant. Previously, the settings payload was included in the search parameters, but it’s now correct to include it in the body of the request.
- #4123
1. **API Request Changes**:
- Added explicit JSON payload (`version`, `variant`) while posting to the `ky.post` method to support a legacy API.
2. **Test Enhancements**:
- **Imports**: Added import for `fork` from the `child_process` module.
- **Mocks**: Implemented a mock for `child_process.fork` to simulate child process behavior.
- **Test Cases**: 
- Updated test descriptions for more clarity.
- Used `mockFork` to define behavior for `fork` mock, especially handling messages for CPU instruction sets.
- Changed test assertions to use `resolves.toEqual` or …

feat: update Jan’s client request to adapt API changes from Cortex

---

extensions/inference-cortex-extension/src/index.ts
extensions/monitoring-extension/src/index.ts

This PR addresses an issue where the app fails to configure a new GPU variant update after detecting GPU information in the background during the first launch. The app still runs in CPU mode even when the GPU toggle is enabled in the settings.
- #4094
The first attempt it sets CPU engine variant, then it switched to GPU engine variant
GPU is used without additional settings
The code changes introduce the following updates across multiple files:
1. **`inference-cortex-extension/src/index.ts`:**
- Import `AppConfigurationEventName` from `@janhq/core`.
- Added a new event listener for `AppConfigurationEventName.OnConfigurationUpdate` that updates the system's run mode when settings change.
- Added an event emission `ModelEvent.OnModelStopped` when a WebSocket connection is closed.
2. …

fix: 4094 - gpu mode toggle on by default but not affect for the first time launch

---

core/src/browser/core.test.ts
core/src/browser/core.ts
core/src/node/api/processors/download.test.ts
core/src/node/api/processors/download.ts
core/src/types/api/index.ts
web/containers/ModelSearch/index.tsx
web/utils/huggingface.test.ts
web/utils/huggingface.ts

- Fix a bad implementation that fetches the Huggingface repository N + 1 times, where N = repo file list sizes. It’s easy to reach the limit rate issue by doing that, where it should make only one request to get all the file sizes information. Also, waiting N requests would cause a bad UX where users have to wait for a long time, it hits all the model download endpoints.
Results
- Fast model repo information display, consistent from repo to repo
- Only 1 request sent to get all file sizes
- #4096
The code changes involve the removal and refactoring of the `getFileSize` function across the codebase:
1. **Tests**:
- Removed the `getFileSize` unit test from `core.test.ts` and `download.test.ts`.
2. **Core Functionality**:
- Deleted the `getFileSize` function definition from `core.ts` and its …

fix: 4096 - failed to get huggingface models

---

web/package.json
web/screens/Thread/ThreadCenterPanel/SimpleTextMessage/index.tsx

Downgrade `rehype-highlight` due to issue `lowlight` performance
- Closes #4102 
- Closes #

fix: memory leak lowlight dependencies

---

core/src/types/api/index.ts
electron/handlers/native.ts
electron/utils/migration.ts
web/hooks/useFactoryReset.test.ts
web/hooks/useFactoryReset.ts

This PR addresses an issue where the app requires a factory reset to relaunch. Now, it simply reloads the frontend to show the affected behavior.
- #4098
This diff introduces several changes across multiple files:
1. **New IPC Route:**
- A new `NativeRoute` named `factoryReset` is added to `core/src/types/api/index.ts`.
2. **Electron Handler Updates:**
- The `electron/handlers/native.ts` file has been updated:
- Added handling for the new `factoryReset` IPC, which clears imported modules, recreates user space, runs migrations, and sets up extensions.
- Added documentation comments to various IPC handlers for clarity.
3. **Utils Cleanup:**
- In `electron/utils/migration.ts`, the unused `readFileSync` import has been removed.
4. **Web Hook Modifications:**
- In …

fix: 4098 - factory reset closes the app & never opens again on Linux

---

web/package.json
web/screens/Thread/ThreadCenterPanel/SimpleTextMessage/index.tsx

Downgrade `ryhype-highlight` and added manually latex language
- Closes #4102 
- Closes #

chore: use rehype-highlight v6 update latex language

---

web/containers/Layout/index.tsx
web/containers/MainViewContainer/index.tsx
web/containers/Providers/CoreConfigurator.tsx
web/containers/Providers/index.tsx
web/helpers/atoms/AppConfig.atom.ts
web/helpers/atoms/Model.atom.ts
web/helpers/atoms/Setting.atom.ts
web/helpers/atoms/Thread.atom.ts
web/hooks/useStarterScreen.ts
web/screens/Thread/ThreadCenterPanel/ChatBody/OnDeviceStarterScreen/index.tsx
web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx
web/screens/Thread/ThreadCenterPanel/index.tsx
web/screens/Thread/index.tsx

Re-rendering across components in the app caused poor performance. This PR addresses numerous instances of poor state handling that lead to this issue.
JotaiProvider and ThemeProvider now load only once, which also the same issue before. These providers hold the main app states and themes, which could lead to unforeseen performance problems.
App appearance, theme, and show welcome screen toggle once on launch, causing screens to flash (attempt to display then disappear) due to initial storage state settings. These settings should persist on load.
Previously, the thread screen re-renders 16 times on launch
Now it renders once (plus one due to Strict React debugging).
1. **Component Refactoring**:
- `MainViewContainer`: Moved the `framer-motion` animation logic from `Layout` to …

fix: app re-render issues caused by bad state handling

---

web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx
web/screens/Thread/ThreadCenterPanel/ChatItem/index.tsx

Re-rendering the entire messages list on every token yield causes poor performance. This is to address the issue of the convo component where it should not re-render on message update, but the message component re-render itself instead.
On mount, the convo component should render the initial messages list only, then listening for new message arrival. And pending update message component will listen to new message update event and re-render itself.
In the recorded video, in case there is a re-render attempt on convo component (messages list), it would console log a message "re-render".
1. **`ChatBody` Component:**
- `ChatBody` has been renamed to `ChatConfigurator`, and the former `ChatBody` logic has been encapsulated inside a new `ChatBody` component that's utilized within …

fix: convo component re-render every single token yield

---

web/hooks/useRecommendedModel.ts
web/screens/Thread/ThreadLeftPanel/index.tsx

Remove filter engine on hooks recommend model 
- Closes #
- Closes #

fix: remove filter on recommend model

---

web/containers/Providers/ModelHandler.tsx
web/helpers/atoms/ChatMessage.atom.ts
web/hooks/useSendChatMessage.ts
web/screens/Thread/ThreadCenterPanel/SimpleTextMessage/index.tsx
web/types/token.d.ts

This PR addresses an issue where message rendering could impact token speed, which is not intended. The token speed calculation should not be affected by component rendering, but rather based on the received tokens.
Ensure that rendering of complicated message contents doesn’t reduce token speed (currently it does).
Token speed is now calculated on message receive, assuming each event yields one token. 
The formula for calculating token speed is given by:
$$
\text{Token Speed} = \frac{\text{Eval Count}}{\text{Eval Duration}}
$$
Where:
- Total Tokens is the total number of tokens processed.
- Duration is the time taken in seconds to process those tokens.
Screenshot demonstrate a case where convo is very long, but the token speed is not reduced (it's reduced to ~3 before where it should be …

fix: token speed should not be calculated based on state updates

---

web/containers/ModelSearch/index.tsx
web/utils/huggingface.test.ts
web/utils/huggingface.ts

This PR corrects the error message to display the correct error from the response.
The changes in the code are in the `ModelSearch` component, specifically in the error handling section. The `toaster` function call has been modified:
- The `title` previously had a static message: "Oops, you may be rate limited, give it a bit more time".
- Now, the `title` is set to the value of `errMessage`, which dynamically contains the error message.
- The `description` property, which used to contain `errMessage`, has been removed.
This change means that the error message displayed will now be more specific to the error encountered, as the exact error message will be shown in the title.

chore: display error message from response

---

web/helpers/atoms/Setting.atom.ts
web/hooks/useLoadTheme.test.ts
web/hooks/useLoadTheme.ts

There’s an issue with an app where when the user launches the app with the first thread is a large one, it glitches the app’s theme a bit before the conversation is loaded. This results in a very ugly display, with only a border and a translucent background.
This fix intends to store the previously set settings in the localStorage., ensuring that themes are applied effectively without the need to load JSON files from the disk.
Before:
After:
Notes: 
Ordered list offscreen issue is filed in another issue
This diff introduces several changes to the `Setting.atom.ts` and `useLoadTheme.ts` files, as follows:
1. **Atoms and Constants Updates:**
- New constants `THEME_DATA`, `THEME_OPTIONS`, and `THEME_PATH` are defined.
- The `themesOptionsAtom`, `janThemesPathAtom`, and `themeDataAtom` are …

fix: Glitch theme applies on launch

---

web/package.json
web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx
web/screens/Thread/ThreadCenterPanel/ChatItem/index.tsx
web/screens/Thread/ThreadCenterPanel/LoadModelError/index.tsx

Enhance Jan’s convo rendering by virtualizing only the visible DOM nodes.
There was a performance issue on latest release 0.5.9, where it renders only a few tokens / second for a large convo (just around ~100 messages). After investigating, we found a few issues related to app state handling and top-level components re-rendering. We attempted to address these issues to minimize the likelihood of app re-rendering.
This pull request also addressed the issue where the conversation does not follow the generated text, which significantly impacts the user experience.
0.5.9 - Very laggy while generating
0.5.9 Nightly with better state handling
However, that’s not sufficient, we constantly strive for better UX. With this fix, we apply visible DOM node virtualization for enhanced performance and …

fix: high performance large convo rendering

---

joi/src/core/ScrollArea/styles.scss
web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx

This is to fix the scrollview's thumb CSS
The code changes include:
1. **SCSS File (`styles.scss`):**
- Added a `border-radius` of `20px` to the scrollbar thumb to give it rounded edges in the scroll area.
2. **React Component (`index.tsx`):**
- Added a new class name `scroll-area` to the `div` enclosing the chat body layout. This class is likely added to apply specific styling or features to that `div`, possibly related to the modified scrollbar thumb style.

chore: correct scrollview thumb style

---

docs/src/pages/docs/error-codes.mdx
docs/src/pages/docs/troubleshooting.mdx

This pull request aims to update the documentation accordingly to the new Cortex server port update.
cortex.cpp server is no longer run on port 3928

chore: update the docs for the new Cortex server port

---

web/containers/ErrorMessage/index.tsx
web/screens/Thread/ThreadCenterPanel/ChatItem/index.tsx
web/screens/Thread/ThreadCenterPanel/LoadModelError/index.tsx
web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx

This pull request aims to enhance the current generate message by ensuring that the message options are always visible at the bottom.
Previously, these options were absolute positioned, which meant that the parent visible frame was not measured accordingly. This fix will remove the absolute class when this is a currently generated message. Instead, it will use flex orders to swap out the components’ order accordingly.
Short thread
Long thread
Error message should not be capitalized like this:
But like this
- #4178
The code changes involve adjustments to the `ChatItem` and `MessageContainer` components.
- Added an `isCurrentMessage` prop to the `MessageContainer` component, defaulting to `false` if undefined.
- Modified the type definition of `MessageContainer` to include the …

fix: 4178 - current generated message options should be visible

---

web/hooks/useSendChatMessage.ts
web/utils/messageRequestBuilder.ts

- I’ve resolved the issue where the app could include empty messages, which caused problems with a few remote providers. There was a case where message pushing could include an empty message in case of an error.
- #4165
The code changes involve refactoring the function `normalizeMessages` and its integration within the system:
1. **Removal from `useSendChatMessage.ts`:**
- The `normalizeMessages` function and the `Stack` import were removed from `useSendChatMessage.ts`. This function was previously responsible for ensuring consecutive messages from the same role (e.g., User or Assistant) were separated by an empty message. The feature was meant to meet specific requirements of some models.
- The call to `normalizeMessages` was also removed from the `resendChatMessage` function, meaning …

fix: 4165 - Refactor message builder to avoid sending empty messages

---

core/src/browser/extensions/engines/OAIEngine.ts
core/src/browser/extensions/engines/helpers/sse.ts

This PR aims to handle error messages returned by OpenRouter gracefully. Unlike others, it doesn’t return JSON but a stream message.
- #4162
The code changes remove certain debug logging statements and add error handling logic:
1. **OAIEngine.ts:**
- Removed debug statements that logged the inference URL, headers, and the inference error as a JSON string.
2. **sse.ts:**
- Added logic to handle errors received in the SSE data. If the parsed data contains an `error`, it triggers the error handling in the subscriber, marks the stream as complete, and exits early to prevent further processing.
These changes improve error handling and reduce unnecessary logging output.

fix: 4162 - Graceful Openrouter error handling

---

extensions/inference-cortex-extension/src/index.ts

- This fixes the issue where users force-kill the Cortex process in Windows Task Manager and immediately try to send a message in Jan's UI, they receive a "failed to fetch" error. This indicates that Jan is not gracefully handling cases where the Cortex process is terminated unexpectedly.
- #4155
The code modification introduces several updates within the `onclose` event handler for a WebSocket connection:
1. **Comment Addition**: A comment explaining the server segfault issue handling has been added.
2. **Event Emission**: Before attempting to reconnect, the code now emits a `ModelEvent.OnModelStopped` event to notify the application about a model's stopped state.
3. **Health Check**: After attempting to reconnect, the code queues up a health check call (`this.healthz()`) using the …

fix: 4155 - Queue up health check on server restarting

---

web/containers/ModelDropdown/index.tsx
web/hooks/useCreateNewThread.ts

This PR addresses an issue where selecting the max_tokens parameter in the thread.json file doesn’t get updated when the model is changed.
- #4209
The code change involves adjustments to how model parameters are handled in two different files: `ModelDropdown/index.tsx` and `useCreateNewThread.ts`.
1. **ModelDropdown/index.tsx Changes:**
- The `overriddenSettings` logic is replaced with `overriddenParameters`.
- A new `defaultContextLength` variable is defined, which chooses the minimum between 8192 and the model's `ctx_len` setting (defaulting to 8192 if not specified).
- The `overriddenParameters` object now includes both `ctx_len` and `max_tokens`, both set to this new `defaultContextLength`.
2. **useCreateNewThread.ts Changes:**
- Similar to the changes in `ModelDropdown`, a …

fix: 4209 - Inconsistent max tokens value persistence

---

web/containers/Providers/ModelHandler.tsx

- This PR addressed an issue where thread title generation removed special characters that should also prevent multilingual support for that. Now it will remove only non-letter Unicode characters. 
- #4208
The code change in `ModelHandler.tsx` updates the `cleanedMessageContent` processing logic and adds validation. Specifically:
1. The regular expression used in `replace()` is modified to:
- Before: `[^a-z0-9\s]`, which removes non-alphanumeric ASCII characters.
- After: `[^\p{L}\s]+`, which removes non-letter Unicode characters using the Unicode property escapes.
2. A new validation step is introduced:
- It checks if `cleanedMessageContent` is empty after trimming. If it is, the function exits early to avoid processing or persisting an empty message.

fix: 4208 - Empty title with special characters

---

extensions/inference-cortex-extension/package.json
extensions/inference-cortex-extension/resources/models/bakllava-1/model.json
extensions/inference-cortex-extension/resources/models/llava-13b/model.json
extensions/inference-cortex-extension/resources/models/llava-7b/model.json

It’s an update to add new NGL settings for the llava model.json files. It’s a minor update for predefined models, but there should be a correct update from cortex.cpp to import vision models.
[- #1763](https://github.com/janhq/cortex.cpp/issues/1763)
The changes in the code are as follows:
1. **package.json**:
- The version of the package `@janhq/inference-cortex-extension` has been updated from "1.0.23" to "1.0.24".
2. **model.json files**:
- Changes were made to three different model JSON files located in different subdirectories: `bakllava-1`, `llava-13b`, and `llava-7b`.
- For each of these models, an additional property `"ngl": 33` was added to the "model" key.
- This update is consistent across all model files, suggesting a related change or parameter update applicable to multiple …

chore: add NGL settings for vision models

---

web/package.json
web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx

This PR addresses an issue where ReactMarkdown could crash due to unsupported languages in code highlighting. This has been resolved in the newer version of the dependency.
Also fixed the issue where switching between new threads (very shorts) would not take effect
- #4205
- #4215
The changes in the `git diff` are as follows:
1. **`package.json` Update:**
- The version of the `rehype-highlight` package was updated from `^6.0.0` to `^7.0.1` in the project's dependencies.
2. **`index.tsx` Code Modifications:**
- **Import Changes:**
- Added a new import: `import { activeThreadAtom } from '@/helpers/atoms/Thread.atom'`.
- **State and Effect Hook Adjustments:**
- Introduced a new state variable `currentThread` using `useAtomValue` to get the value of `activeThreadAtom`.
- Updated the …

fix: react-markdown crash on code highlighting - threads switching do not take effect sometime

---

web/screens/Thread/ThreadCenterPanel/TextMessage/MarkdownTextMessage.tsx

The given `git diff` shows changes made to the `MarkdownTextMessage.tsx` component. Here's a summary of the modifications:
1. **Import Statements**:
- The `latex` language import from `highlight.js` has been removed.
- The CSS import for `katex` has been rearranged, but it's effectively unchanged.
- A new CSS import for `highlight.js` styles (`atom-one-dark.css`) has been added, which implies a change in the highlighted code's visual appearance.
2. **Rehype Plugins Configuration**:
- The configuration for `rehypeHighlight` has been simplified. The previous custom configuration that included the `latex` language, no subset, and plain text options has been replaced with a default setup by removing the custom configuration object.
These changes likely simplify the markdown rendering logic …

fix: syntax highlight configurations that made everything dark

---

web/styles/components/message.scss

Changes made to the SCSS file located at `web/styles/components/message.scss`. Here's a summary of the changes:
1. **Padding Adjustment:**
- The `padding-left` property for `ul` and `ol` elements has been changed from `24px` to `16px`. This reduces the left padding of list items.
2. **List Style Position Added:**
- A new property, `list-style-position: inside;`, has been added to the `ul` and `ol` elements. This positions the bullet points or numbers inside the content flow of the list items, effectively aligning the text neatly with the bullets. 
- Closes #4169 
- Closes #

fix: list style off screen

---

web/containers/Providers/Jotai.tsx
web/screens/Settings/Advanced/index.tsx
web/types/file.d.ts
web/utils/messageRequestBuilder.ts
web/utils/threadMessageBuilder.ts

This minor fix aims to hide Vulkan settings in case the system doesn’t detect a GPU.
- #4093
The code change is in the `index.tsx` file located at `web/screens/Settings/Advanced/`. Here's a summary of the modification:
- **Conditional Rendering Update**: The condition for rendering a specific `<div>` component has been modified.
- **Old Condition**: The component was rendered based on the condition `!isMac && experimentalEnabled`.
- **New Condition**: The component will now be rendered if `!isMac && gpuList.length && experimentalEnabled`, meaning it adds a check that requires `gpuList` to have a non-zero length (i.e., it is not empty).
This change introduces a dependency on `gpuList.length` as an additional condition for rendering, which implies that the display of this section is …

fix: hide Vulkan option for users who don't have GPU

---

web/containers/Providers/Responsive.tsx
web/helpers/atoms/App.atom.ts
web/helpers/atoms/Thread.atom.ts

changes made to three files in a codebase: `Responsive.tsx`, `App.atom.ts`, and `Thread.atom.ts`. Here's a summary of each change:
1. **Responsive.tsx**:
- The initial values for the refs `lastLeftPanelState` and `lastRightPanelState` have been modified. Previously, these refs were initialized as `true` for both, but now they are initialized using the current state values of `showLeftPanel` and `showRightPanel`.
- This change ensures that when switching to a state where the panels should close, their last states are known from the outset.
2. **App.atom.ts**:
- An import of `atomWithStorage` from `jotai/utils` was added, which allows creating a persistent atom.
- `showRightPanelAtom` is modified to use `atomWithStorage`, meaning it will now persist the panel's state using local storage …

enhancement: default open Jan Input Box Settings and Right panel

---

web/package.json
web/screens/Thread/ThreadCenterPanel/TextMessage/MarkdownTextMessage.tsx

case is user write codeblock without backtick 
The root cause is likely malformed Markdown content or the handling of raw HTML tags in the Markdown processor.
- **Removed Dependency**: The package `rehype-raw` with version `^7.0.0` has been removed from the list of dependencies.
- **Import Removal**: The import statement for `rehypeRaw` has been deleted.
- **Plugin Removal**:
- `rehypeRaw` has been removed from the `rehypePlugins` array.
- **Attribute Change**:
- The `skipHtml` attribute, which was set to `true`, has been removed from the `<Markdown>` component.
Overall, the changes reflect the removal of the `rehype-raw` package and associated logic from the codebase, likely to improve security or simplify functionality by disallowing the use of raw HTML content in Markdown rendering.
- …

fix: crash markdown render code block without triple backtick

---

web/containers/ErrorMessage/index.tsx

1. **Addition of `defaultDesc` Function**: 
- A new function `defaultDesc` is added to encapsulate the logic for displaying a default error description along with a troubleshooting assistance link and modal.
2. **Updates in `getErrorTitle` Function**:
- The refactoring introduced the utilization of `defaultDesc` in case of an invalid API key error, providing a consistent error description format.
3. **New Error Handling Logic**:
- Within the `default` case of the `getErrorTitle` switch statement, there's a new conditional check to display a specific message if the content is "Failed to fetch" indicating no internet connection, otherwise, it falls back to showing the message text along with `defaultDesc`.
4. **Structural Changes**:
- Removal of redundant elements by integrating them within …

enhancement: better error handing for remote models when there's no internet connection

---

web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx

1. **Imports Adjustments**: 
- `useCallback` is added to the existing imports from React. 
2. **New Refs Introduced**:
- `prevScrollTop`: Added as a `useRef` to track the previous scroll position.
- `isUserManuallyScrollingUp`: Added as a `useRef` to flag when the user manually scrolls up.
3. **Effect Logic Update**:
- An additional condition is added in the `useEffect` to return early if the user is manually scrolling up or if `parentRef.current` is not defined.
4. **Virtualizer Adjustment Function**:
- An early return is added in the `shouldAdjustScrollPositionOnItemSizeChange` function to avoid adjustments if the user manually scrolls up.
5. **New Scroll Handler**:
- A `handleScroll` function is defined using `useCallback`. It detects manual user scrolling by comparing the current …

fix: auto scrolling to bottom

---

extensions/inference-groq-extension/resources/models.json

- This PR is to remove deprecated groq model Llama 3.1 70B Versatile
- #4244
The following changes were made to the `models.json` file:
- **Removed a Model Entry**: The model entry with the id `"llama-3.1-70b-versatile"` was completely removed. This model had the name "Groq Llama 3.1 70b Versatile" and was described as having "supercharged speed." It included various configurations such as:
- Maximum tokens: 8000
- Temperature: 0.7
- Top_p: 0.95
- Streaming enabled
- Tags including "General" and "Big Context Length"
The rest of the models in the file remain unchanged.

chore: 4244 - deprecate groq llama 3.1 70B Versatile

---

.github/workflows/publish-npm-core.yml

- chore: add ci janhq/core publish npm
To publish a new version of janhq/core push a tag with format `vx.y.z-core` (start from `v0.2.1-core`)
- Related issue #4261
- Closes #

chore: add ci janhq/core publish npm

---

web/screens/Thread/ThreadCenterPanel/ChatInput/RichTextEditor.tsx

Based on the latest discussion with @imtuyethan , we observed user behavior and concluded that highlighting code inline in the chat input box is an unnecessary feature. However, we will still allow text formatting like bold and italic. Users will be able to type code blocks by using the backticks for starting and closing, and we will render those as code blocks in the user’s message.
1. Removal of the `highlight.js` import:
```diff
-import hljs from 'highlight.js'
```
2. Elimination of a large block of code responsible for syntax highlighting within the rich text editor. This block handled:
- Parsing lines for code blocks using regular expressions.
- Managing language state for highlighted code blocks.
- Applying syntax highlighting to code within the text editor using `highlight.js`.
- …

fix: markdown inline inputbox

---

extensions/inference-openai-extension/resources/models.json
web/containers/ModelDropdown/index.tsx
web/hooks/useCreateNewThread.ts
web/utils/modelEngine.ts

I've resolved the issue where it sets the default context_length as the first value for max_tokens.
- #4238
1. **`models.json`:**
- Moved the `max_tokens` parameter above the `temperature` parameter for better grouping in two sections of the file.
2. **`ModelDropdown/index.tsx`:**
- Updated `overriddenParameters`:
- Changed `ctx_len` to be `undefined` if `isLocalEngine` returns `false`, otherwise use `defaultContextLength`.
- Changed `max_tokens` to use either the model's `max_tokens` or `defaultContextLength` based on whether `isLocalEngine` returns `false`.
3. **`useCreateNewThread.ts`:**
- Updated imports to include `isLocalEngine`.
- Modified `overriddenSettings` and `overriddenParameters`:
- Changed `ctx_len` to behave similarly to the changes in `ModelDropdown/index.tsx`.
- Changed …

fix: 4238 - fix default max_tokens set on remote models

---

web/screens/Settings/MyModels/MyModelList/index.tsx

Missing disable start model from my model list when server is running 
- Closes #4182 
- Closes #

fix: disabled start model from mymodel list when server is running

---

web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx

- Move position token speed into bottom message item
- Closes #4258 
- Closes #

enhancement: move token speed to bottom

---

.github/workflows/template-build-linux-x64.yml
.github/workflows/template-build-macos.yml
.github/workflows/template-build-windows-x64.yml
electron/tests/e2e/thread.e2e.spec.ts
web/containers/Layout/BottomPanel/index.tsx
web/containers/Layout/index.tsx
web/containers/LeftPanelContainer/index.tsx
web/containers/RightPanelContainer/index.tsx
web/helpers/atoms/Setting.atom.ts
web/next.config.js
web/package.json
web/screens/Settings/Advanced/index.test.tsx
web/screens/Settings/Advanced/index.tsx
web/screens/Settings/Privacy/index.test.tsx
web/screens/Settings/Privacy/index.tsx
web/screens/Settings/SettingDetail/index.tsx
web/screens/Settings/index.tsx
web/types/index.d.ts

- Permission pop-up
- Privacy setting
- Integrate posthog
```
if (typeof window !== 'undefined') {
posthog.init(POSTHOG_KEY, {
api_host: POSTHOG_HOST,
autocapture: false,
person_profiles: 'always',
persistence: 'localStorage',
});
}
```
Initializes PostHog only on the client side (browser environment) to avoid errors during server-side rendering.
- PostHog is configured with the following options:
- api_host: Specifies the PostHog API endpoint.
- autocapture: false: Disables automatic event tracking; events need to be explicitly tracked.
- person_profiles: 'always': Enables person profiles in all cases.
- persistence: 'localStorage': Ensures data is stored in localStorage for consistency across browser sessions.
```
useEffect(() => {
const timer = setTimeout(() => {
if …
```

feat: product analytic UI

---

web/screens/Thread/ThreadCenterPanel/ChatInput/RichTextEditor.tsx

- Resolve problem where pressing Enter triggers events twice: once for the composed string and once for the composing character.
- Ensure proper handling of composition events for Chinese, Japanese, and Korean input.
- #4267

Fix: Fix issue with duplicate events on Enter key press during CJK character composition in chat input

---

web/containers/CenterPanelContainer/index.tsx
web/screens/Thread/ThreadCenterPanel/ChatBody/OnDeviceStarterScreen/index.tsx
web/screens/Thread/index.tsx

Before
After
1. **CenterPanelContainer Component**:
- A new type `Props` is introduced to include an optional property `isShowStarterScreen`, in addition to `PropsWithChildren`.
- The `CenterPanelContainer` function is updated to accept `isShowStarterScreen` as a prop.
- The inline styling for the `div` element is updated to account for `isShowStarterScreen`. The condition for `maxWidth` now additionally checks if `!isShowStarterScreen`.
2. **OnDeviceStarterScreen Component**:
- A new type `Props` is introduced with an optional property `isShowStarterScreen`.
- The `OnDeviceStarterScreen` function is updated to accept `isShowStarterScreen` as a prop.
- The `CenterPanelContainer` component within the `OnDeviceStarterScreen` component is now called with the `isShowStarterScreen` prop passed …

fix: starter screen layout

---

web/containers/ModelDropdown/index.tsx
web/hooks/useCreateNewThread.ts
web/hooks/useSendChatMessage.ts
web/screens/Thread/ThreadCenterPanel/ChatBody/OnDeviceStarterScreen/index.tsx
web/screens/Thread/ThreadCenterPanel/ChatInput/RichTextEditor.tsx
web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
web/utils/model.ts

1. **ModelDropdown Component (`index.tsx`)**
- Imported `atom` from `jotai`.
- Introduced a new atom `modelDropdownStateAtom` initialized to `false`.
- Updated the state handling of the dropdown's open/close status to use the new atom.
- Added a `useEffect` to sync the dropdown open state with the `chatInputMode`.
2. **useCreateNewThread Hook**
- Removed import and usage of the `useRecommendedModel` hook.
- Adjusted logic to set `defaultModel` without using `recommendedModel`.
3. **useSendChatMessage Hook**
- Imported `modelDropdownStateAtom` and added logic to open the model dropdown if no model is selected when sending a chat message.
4. **RichTextEditor Component**
- Added import for `selectedModelAtom` and used it to determine if the editor should reset after sending a message.
5. …

feat: handle case thread when original model deleted

---

web/screens/Hub/ModelList/ModelHeader/index.tsx
web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx

1. **In `web/screens/Hub/ModelList/ModelHeader/index.tsx`:**
- The `z-50` class was removed from the `Button` component. This class might have been related to the z-index, and its removal suggests a possible simplification or a fix for a styling issue.
2. **In `web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx`:**
- The `isModelSupportRagAndTools` constant has been refined to focus solely on the result of `isLocalEngine(selectedModel?.engine as InferenceEngine)`. Previously, it also checked if `selectedModel?.engine === InferenceEngine.openai`.
- The logic for the `disabled` property of certain elements has been updated to disable the button if `!isModelSupportRagAndTools` instead of `isModelSupportRagAndTools`.
- The text list item’s className logic was updated to disable user …

fix: empty tooltip on attachment icon, also fix z-index

---

web/hooks/useCreateNewThread.ts

- Fixed an issue where app resets context length setting while creating a new thread due to undefined model selection value. Now should use default model value.
- Closes #
- Closes #
The Git diff shows the following changes to the `useCreateNewThread.ts` file:
1. **Variable Renaming**:
- The variable `model` is renamed to `defaultModel`. This change ensures that the function uses the default model settings consistently.
2. **Consistent Use of Default Model**:
- In both `overriddenSettings` and `overriddenParameters`, the code now checks if the engine of `defaultModel` is local using `!isLocalEngine(defaultModel?.engine)`. This ensures that the settings are applied based on whether the model's engine is local or not, maintaining consistency.
3. **Token Limit Adjustment**:
- The token limit …

fix: context length is reset while creating a new thread

---

web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx

1. **TypeScript Type Annotation**: The `useRef` hook for `parentRef` is updated from `useRef(null)` to `useRef<HTMLDivElement>(null)`, providing a type annotation to specify that the ref should point to a `HTMLDivElement`.
2. **New State Addition**: A new state `currentThread` is introduced, which uses the `useAtomValue` hook to retrieve the value from `activeThreadAtom`.
3. **Refactoring useEffect Hook**: 
- The existing `useEffect` hook is refactored to:
- Remove the check for `isUserManuallyScrollingUp` and `!parentRef.current`.
- Add a `requestAnimationFrame` call to delay scrolling until the DOM updates. This ensures smoother behavior when scrolling to the last index of messages.
- Update the dependencies of the `useEffect` to include `currentThread?.id` and remove unused …

fix: scroll to bottom issue

---

core/src/browser/extensions/engines/OAIEngine.ts
extensions/assistant-extension/src/index.ts
web/containers/Providers/ModelHandler.tsx
web/helpers/atoms/Assistant.atom.ts
web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx
web/screens/Thread/ThreadLeftPanel/index.tsx
web/utils/datetime.test.ts
web/utils/datetime.ts
web/utils/messageRequestBuilder.ts
web/utils/threadMessageBuilder.ts

This PR fixes the issue where the app doesn't automatically create a new thread after downloading a model from the welcome screen.
The changes in this PR include modifications to the following files:
- `core/src/browser/extensions/engines/OAIEngine.ts`: Adjusted timestamp to use seconds.
- `extensions/assistant-extension/src/index.ts`: Adjusted timestamp to use seconds.
- `web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx`: Adjusted timestamp to use seconds.
- `web/screens/Thread/ThreadLeftPanel/index.tsx`: Changed logic for creating new thread with default assistant.
- `web/utils/datetime.ts`: Adjusted timestamp handling to use seconds.
- `web/utils/messageRequestBuilder.ts`: Removed unused import.
- `web/utils/threadMessageBuilder.ts`: Adjusted timestamp to use seconds.

fix: new thread isn't automatically created on factory reset

---

web/hooks/useCreateNewThread.ts
web/hooks/useRecommendedModel.ts
web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx

- set recommend model to undefined when model.length === 0
- Closes #3537 
- Closes #

enhancement: set recommend model to undefined if no model available

---

web/screens/Thread/ThreadRightPanel/index.tsx

The changes in the `ThreadRightPanel/index.tsx` file involve wrapping an `Accordion` component and its children with an additional conditional check to ensure that a `selectedModel` exists before rendering the `Accordion` and its `AccordionItem` children. Here's a summary of the modifications:
1. **Conditional Rendering**: Previously, the `Accordion` component and its `AccordionItem` components were rendered unconditionally. Now, they are only rendered if `selectedModel` is truthy.
2. **No Changes to Styling or Structure**: There are no changes to the styling (`className`) or the internal structure of the `Accordion` and `AccordionItem` components.
3. **Preservation of Existing Logic**: The logic inside `AccordionItem`s remains intact, including checks on the length of …

fix: conditional render model setting based on selected model

---

web/screens/Thread/ThreadCenterPanel/TextMessage/MarkdownTextMessage.tsx
web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx

The changes in the provided `git diff` involve two TypeScript files and focus on modifying how markdown text is processed and rendered. Here's a breakdown of what has been changed:
1. **MarkdownTextMessage.tsx:**
- **Function Parameter Modification:**
- The `MarkdownTextMessage` component's props have been modified to include an `isUser` boolean property alongside the existing `id` and `text` properties. This is indicated by the change to the function signature from:
```typescript
({ text }: { id: string; text: string })
```
to:
```typescript
({ text, isUser }: { id: string; text: string; isUser: boolean })
```
- **Markdown Preprocessing:**
- Introduced a new function `preprocessMarkdown` to modify the markdown text if the `isUser` flag is `true`. The function escapes markdown headings by …

fix: escape heading on user message item

---

web/containers/Providers/ModelHandler.tsx
web/hooks/useDeleteThread.ts

Fixed the issue where cleaning the thread raises an error, preventing it from being cleaned.
The changes in this pull request involve the following updates:
1. Simplified the conditions in the `generateThreadTitle` function:
- Removed unnecessary braces and reduced lines by combining conditions.
- Added a `.catch(console.error)` to handle errors in a promise chain.
1. Updated the `useDeleteThread` function:
- Added code to filter out the deleted thread and update the thread state accordingly.
- Added a `.catch(console.error)` to handle errors in a promise chain.
These changes aim to streamline the code and improve error handling.

fix: thread error handling

---

web/containers/ModelDropdown/index.tsx
web/screens/Thread/ThreadCenterPanel/ChatBody/EmptyThread/index.tsx
web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx

1. **ModelDropdown Component (`index.tsx`):**
- Text placeholders have been updated for consistency:
- Changed "Select Model" to "Select a model" in two different instances.
2. **EmptyThread Component (`EmptyThread/index.tsx`):**
- Changed the onboarding message text from "You don't have a local model yet." to "You don't have any model."
3. **ChatBody Component (`ChatBody/index.tsx`):**
- Additional imports include `isGeneratingResponseAtom` and `threadStatesAtom` from `Thread.atom`.
- Added state checks for generating or streaming responses:
- `isGeneratingResponse` is used to check if a response is currently being generated.
- `isStreamingResponse` determines if any thread state is waiting for a response.
- Updated scrolling behavior logic:
- Ensured that scrolling only happens when it …

fix: scroll bottom issue

---

web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
web/screens/Thread/ThreadCenterPanel/index.tsx

1. Remove  tooltip and make image optios disabled
2. Input box width depend on preference setting
- Closes https://github.com/janhq/jan/issues/4291#issuecomment-2556527910
- Closes https://github.com/janhq/jan/issues/4291#issuecomment-2556725858

fix: dynamic input box width and remove tooltip image option

---

extensions/conversational-extension/src/index.ts
web/helpers/atoms/Thread.atom.ts
web/hooks/useCreateNewThread.ts
web/hooks/useDeleteThread.test.ts
web/hooks/useDeleteThread.ts

- Fixed an issue where the legacy implementation of thread cleaning no longer worked. Now, cleaning a thread clears messages and resets its metadata.
- #4291
The code changes in the pull request include the following updates:
1. **`extensions/conversational-extension/src/index.ts`**:
- Reformatted the code for better readability by splitting a chained method call across multiple lines.
- Changed the `healthz` method to be `async`.
2. **`web/helpers/atoms/Thread.atom.ts`**:
- Added a new atom `createNewThreadAtom` for creating a new thread and adding it to the thread list.
3. **`web/hooks/useCreateNewThread.ts`**:
- Removed the inline definition of `createNewThreadAtom` and imported it from `Thread.atom.ts`.
4. **`web/hooks/useDeleteThread.test.ts`**:
- Updated mock functions to reflect …

fix: cleaning a thread should just clear out messages

---

web/helpers/atoms/Setting.atom.ts
web/hooks/useLoadTheme.ts
web/screens/Settings/Appearance/index.tsx

- Fixed an issue where changing the theme did not work after relocating the data folder. Theme settings were cached to avoid glitches during app launch, but the settings page used unnecessary cached states.
- #4291
This pull request includes several changes to the theme loading functionality in the project. The main changes involve the removal of the `janThemesPathAtom` and the introduction of a new `applyTheme` function to streamline the application of theme variables. Below are the most important changes grouped by theme.
* [`web/helpers/atoms/Setting.atom.ts`](diffhunk://#diff-fe970dc673b247de554e793d3e1a453f1456278107ae53a390229595621c4384L23-R23): Removed the `janThemesPathAtom` export.
* [`web/hooks/useLoadTheme.ts`](diffhunk://#diff-ebfeebc079f299318f7ca32d33c9a99115774693cde0aa06ec …

fix: change theme settings do not work after relocated data folder

---

web/helpers/atoms/Thread.atom.ts

This PR fixed an issue where threads are sorted incorrectly after updated a certain thread.
- #4291
This pull request includes various updates across multiple files to enhance the functionality and maintainability of the project. The most significant changes include modifications to API requests, updates to the model configurations, improvements to the thread handling logic, and adjustments to the theme management.
* [`extensions/conversational-extension/src/index.ts`](diffhunk://#diff-8556eacb45b5ef692a9d500744d6cacad5f2660bc457a83281b79eb9cb3751cbL43-R43): Updated API requests to include a `limit=-1` parameter for fetching threads, messages, and assistant info. [[1]](diffhunk://#diff-8556eacb45b5ef692a9d500744d6cacad5f2660bc457a83281b79eb9cb3751cbL43-R43) …

fix: threads sorting order after updated

---

web/hooks/useCreateNewThread.ts

- Fixed an issue where editing the titles of other threads might not work due to incorrect assistant accessibility for the thread.
This pull request includes a small but important change to the `useCreateNewThread` hook in the `web/hooks/useCreateNewThread.ts` file. The change ensures that the `setActiveAssistant` function is only called if the `thread.assistants` array is not empty, which prevents potential errors when the array is empty or undefined.
* [`web/hooks/useCreateNewThread.ts`](diffhunk://#diff-11adf34745ca476ecb45f143cb48d7ceb507793be060729acb9b0708ee3fd6ceL194-R198): Updated the `useCreateNewThread` hook to check if `thread.assistants` is non-empty before calling `setActiveAssistant` and `updateAssistantCallback`.

fix: update thread's title edge cases

---

web/helpers/atoms/ChatMessage.atom.ts

Fixed an issue where generating message disappear after switching to another thread then go back.
- #4291 
##Changes made
This pull request includes multiple changes across various files to enhance functionality and improve code quality. The most important changes include adding new parameters to API requests, updating thread management, and modifying theme handling.
* [`extensions/conversational-extension/src/index.ts`](diffhunk://#diff-8556eacb45b5ef692a9d500744d6cacad5f2660bc457a83281b79eb9cb3751cbL43-R43): Added `limit=-1` parameter to the `listThreads`, `listMessages`, and `getThreadAssistant` methods to fetch all items without pagination. [[1]](diffhunk://#diff-8556eacb45b5ef692a9d500744d6cacad5f2660bc457a83281b79eb9cb3751cbL43-R43) …

fix: generating message is gone after switching to another thread

---

web/containers/ModelDropdown/index.tsx
web/hooks/useDeleteThread.ts
web/screens/Thread/ThreadRightPanel/Tools/index.tsx

Fixed an issue where deleted models were not handled gracefully. However, there are still edge cases where users could change tool settings or delete a new thread, causing the app to automatically assign a new model to older threads with deleted models.
- #4291
This pull request includes several changes to improve the handling of model selection and thread management in the web application. The most important changes include refactoring the code to simplify model selection and updating the thread deletion logic to use a new hook.
Improvements to model selection:
* [`web/containers/ModelDropdown/index.tsx`](diffhunk://#diff-897fe0e9366de0fa6ec9428b1423439aaab3dee774cea4b7efd6401a42fb00fbL186-R186): Simplified the logic for finding and setting the selected model by removing unnecessary …

fix: app picks model automatically edge cases

---

web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx

The changes in this Git diff can be summarized as follows:
1. **Use of `requestAnimationFrame`:**
- Removed the `requestAnimationFrame` calls from two places where scrolling is performed. This was used to schedule the scroll operation to occur optimally in the browser's next repaint cycle.
2. **Direct Scrolling:**
- The code now directly calls `scrollTo` on `parentRef.current` without wrapping it in a `requestAnimationFrame`. This may have been done to simplify the logic or because the timing provided by `requestAnimationFrame` wasn't necessary.
3. **Dependency Array Modifications in `useEffect`:**
- Added `currentThread?.id` to the dependency array of both `useEffect` hooks. This ensures that the effects are re-executed whenever `currentThread?.id` changes, which might be to ensure that …

fix: scroll bottom when generation text

---

joi/src/core/TextArea/index.tsx
web/screens/Thread/ThreadRightPanel/index.tsx

- Disbaled resize native textarea when we use autogrowing
- Closes https://github.com/janhq/jan/issues/4291#issuecomment-2553433359
- Closes #

fix: disabled native resize textarea when textarea autogrowing

---

web/helpers/atoms/Thread.atom.ts
web/hooks/useActiveModel.ts
web/hooks/useDeleteThread.ts
web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx

This PR addresses the issue where stopping a model mid-generation can cause the stop button to remain in the generating state.
This pull request includes changes to improve the handling of thread states and model management in the application. The key changes involve adding a new atom to reset the thread waiting for response state and updating the `useActiveModel` hook to incorporate this reset functionality.
Improvements to thread state management:
* [`web/helpers/atoms/Thread.atom.ts`](diffhunk://#diff-4d7af9a9bba964e4d35729b2cdafe1ac8c4d6a7fd7eae7ed2c680f67bdc3a15cR176-R190): Added `resetThreadWaitingForResponseAtom` to reset the waiting for response state of threads.
* [`web/hooks/useActiveModel.ts`](diffhunk://#diff-3b4961cb78a2f54ecdeb49e921fd543e45ced1c8b5a12edc12e2c6f324f54d56R13-R …

fix: send message button state reset on stop

---

web/containers/Providers/ModelHandler.tsx
web/helpers/atoms/Thread.atom.ts
web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx
web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
web/screens/Thread/ThreadCenterPanel/MessageToolbar/index.tsx

• Combined isGeneratingResponseAtom & isWaitingForResponse with isBlockingSendAtom 
• Update dependencies in ChatBody, ChatInput, and MessageToolbar components 
• Remove unused code and variables
• Avoid unnecessary rerendering
This pull request includes several changes to improve the handling of thread states and reduce unnecessary re-renders in the application. The most important changes involve replacing individual state atoms with a combined state atom and updating various components to use this new combined state.
Changes to thread state handling:
* [`web/helpers/atoms/Thread.atom.ts`](diffhunk://#diff-4d7af9a9bba964e4d35729b2cdafe1ac8c4d6a7fd7eae7ed2c680f67bdc3a15cR37-R52): Added `isWaitingForResponseAtom` and `isBlockingSendAtom` to combine thread states and reduce re-renders.
* …

chore: Refactor thread state management

---

web/hooks/useCreateNewThread.ts

This is to fix the issue where stop button is disabled when creating a new thread
This pull request includes changes to the `web/hooks/useCreateNewThread.ts` file, focusing on code cleanup and removal of unused imports and variables. The most important changes include the removal of the `useActiveModel` import and associated variables and functions.
Code cleanup and simplification:
* Removed unused import `useActiveModel` from `web/hooks/useCreateNewThread.ts`.
* Removed the `setIsGeneratingResponse` variable and the `stopInference` function from the `useCreateNewThread` function in `web/hooks/useCreateNewThread.ts`.

chore:  don't stop inference and hide the stop button when creating a new thread

---

web/helpers/atoms/Thread.atom.ts
web/hooks/useActiveModel.ts
web/screens/Thread/ThreadCenterPanel/AssistantSetting/index.tsx

This PR resolved the issue where switching to a new button would cause the stop button to disappear.
This pull request includes several changes to improve state management and streamline the codebase in the `web` directory. The changes focus on the use of Jotai atoms for state management, the addition of new utility atoms, and the removal of redundant code.
* [`web/containers/Providers/ModelHandler.tsx`](diffhunk://#diff-c52744b512485151ef69f9c9e8b58535cc47dc550c4caf152cb52ec103ea898dL59-R59): Replaced the use of `useAtom` with `useAtomValue` for `subscribedGeneratingMessageAtom` to simplify state retrieval.
* [`web/helpers/atoms/Thread.atom.ts`](diffhunk://#diff-4d7af9a9bba964e4d35729b2cdafe1ac8c4d6a7fd7eae7ed2c680f67bdc3a15cR37-R52): Added `isWaitingForResponseAtom` and …

fix: button state reset on switching models

---

extensions/yarn.lock
web/screens/Settings/Engines/Settings.tsx

- Import of a new module: `import DeleteEngineVariant from './DeleteEngineVariant'`.
- Replaced a block of code that used to render a `Button` with logic for uninstalling an engine variant with the `DeleteEngineVariant` component. The `DeleteEngineVariant` component is now rendered instead when an engine variant is installed.
These changes suggest a refactor or modularization of the code related to uninstalling engine variants, possibly for better maintainability or reuse. The changes to `yarn.lock` denote an updated package or a repackaging with new checksum validations.
- Closes #
- Closes #

enhancement: update ui delete engine with modal confirmation

---

.github/workflows/jan-electron-linter-and-test.yml

This PR remove build-joi step from CI script
- Closes #
- Closes #
This pull request includes a small change to the `.github/workflows/jan-electron-linter-and-test.yml` file. The change corrects the order of the build commands to ensure proper dependency installation.
* [`.github/workflows/jan-electron-linter-and-test.yml`](diffhunk://#diff-2ddb5adaf1a0673126fe60af7cf39a5d87b4936f65bd223f28ff8cb979c57650L54-R56): Modified the `Install dependencies` step to run `yarn build:joi` before `yarn build:core` to ensure proper build order.

chore: deprecate make build-joi

---

extensions/inference-cortex-extension/download.bat
extensions/inference-cortex-extension/download.sh
extensions/inference-cortex-extension/rollup.config.ts

This PR addressed an issue where the app couldn't load the model on certain MacOS Intel devices because of missing instruction set support from cortex llama.cpp engine. This issue occurs on Jan 0.5.12, as this version was building on a self-hosted CI machine to support MacOS 12.x versions. However, GitHub's runner had already deprecated support for this version.
- #4366 
This pull request includes several updates to the `inference-cortex-extension` to address a hotfix for the engine version. The most important changes involve updating the engine version across different scripts and configuration files.
Updates to engine version:
* [`extensions/inference-cortex-extension/download.bat`](diffhunk://#diff-8a7d1c23da498167c2b1a94a2d4ce076f6f2549607a116a66528fe8e44c678a6L5-R5): Changed …

fix: bump llama.cpp engine hotfix version to address model load issue on some MacOS Intel machines

---

extensions/engine-management-extension/rolldown.config.mjs
extensions/engine-management-extension/src/index.ts
extensions/yarn.lock

There would be an issue where the app wouldn't reset the default engine if the user manually modifies it or updates from a hotfix version. This would break the default settings, and users would have to manually update the engine in the settings. This isn't a good UX, they should have it configured properly on launch.
On launch: 
Check default variant -> Get installed variants -> If installed variants are not including default variant it would not work -> Reset default variant to bundled version.
- Closes #
- Closes #
This pull request includes updates to the `extensions/engine-management-extension` to improve version handling and remove unnecessary code. The most important changes include updating the Cortex engine version, modifying the logic for checking installed engines, and removing …

fix: if the default engine isn't installed, the app should reset it

---

web/screens/Settings/Advanced/index.tsx

Users should not be restricted from enabling Vulkan mode solely based on GPU detection.
Context: 
- Some GPUs aren't detected by the app.
- We will allow users to select the Vulkan variant anyway soon.
- #4378
This pull request includes a change to the `Advanced` component in the `Settings` screen. The change simplifies the condition for displaying the Vulkan settings for AMD GPU/APU and Intel Arc GPU by removing the dependency on `gpuList.length`.
* [`web/screens/Settings/Advanced/index.tsx`](diffhunk://#diff-8d119b4ddbfcbb13597702a44730e486bc4c02dc630069686effa3333ab90411L420-R420): Simplified the condition for displaying Vulkan settings by removing the check for `gpuList.length > 0`.

fix: should not disable Vulkan support option

---

web/helpers/atoms/Setting.atom.ts

This pull request includes a small change to the `web/helpers/atoms/Setting.atom.ts` file. The change modifies the default value of `productAnalyticAtom` from `false` to `true`.
* [`web/helpers/atoms/Setting.atom.ts`](diffhunk://#diff-fe970dc673b247de554e793d3e1a453f1456278107ae53a390229595621c4384L50-R50): Changed the default value of `productAnalyticAtom` from `false` to `true` to enable product analytics by default.
- Closes #
- Closes #

fix: enable default opt in analytic

---

extensions/inference-cortex-extension/resources/default_settings.json
web/containers/Layout/index.tsx

This pull request includes a small but important change to the `web/containers/Layout/index.tsx` file. The change adds a new event capture for when a user opts out.
* [`web/containers/Layout/index.tsx`](diffhunk://#diff-14ae8afe09456109846de9e991341105e0d570a68d771860be34c3626c438f59R126): Added a `posthog.capture` call to log the 'user_opt_out' event with a timestamp when a user opts out.
- Closes #
- Closes #

fix: send event opt out

---

web/containers/Layout/index.tsx
web/helpers/atoms/Setting.atom.ts

This pull request includes two changes to the `web` directory, focusing on user analytics and settings.
Changes to user analytics:
* [`web/containers/Layout/index.tsx`](diffhunk://#diff-14ae8afe09456109846de9e991341105e0d570a68d771860be34c3626c438f59L126): Removed the `posthog.capture('user_opt_out', { timestamp: new Date() })` call when a user opts out of capturing.
Changes to settings:
* [`web/helpers/atoms/Setting.atom.ts`](diffhunk://#diff-fe970dc673b247de554e793d3e1a453f1456278107ae53a390229595621c4384L50-R50): Changed the default value of `productAnalyticAtom` from `true` to `false`.
- Closes #
- Closes #

fix: revert back product analytic with default opt-out

---

web/hooks/useCreateNewThread.ts

This PR addresses an issue where the app resets the max_tokens to 8192 whenever users create a new thread. This occurs because the parameter retrieve when creating a new thread is incorrect. It should instead use the max_tokens from the model settings instead of token_limit.
- Closes #4372 
This pull request includes a small but important change to the `useCreateNewThread` function in `web/hooks/useCreateNewThread.ts`. The change corrects the parameter name from `token_limit` to `max_tokens` to ensure the correct value is used.
* Corrected the parameter name from `token_limit` to `max_tokens` in `useCreateNewThread` function to ensure the correct value is used.

fix: max_tokens revert back to 8192 automatically when creating a new thread

---

extensions/inference-cortex-extension/download.bat
extensions/inference-cortex-extension/download.sh
web/screens/Thread/ThreadCenterPanel/ChatInput/RichTextEditor.tsx
web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
web/screens/Thread/index.test.tsx

This PR fixed the issue where app force-scroll to bottom every time user set the caret to top of the long input.
This PR also added a minor engine version bump to be the same as the engine management extension.
- Closes #4377
This pull request includes several changes across multiple files to update the engine version, fix a typo, and enhance the functionality of the `RichTextEditor` component. The most important changes include updating the engine version, correcting a typo in the `ChatInput` component, and adding new functionality to the `RichTextEditor`.
Updates and fixes:
* [`extensions/inference-cortex-extension/download.bat`](diffhunk://#diff-8a7d1c23da498167c2b1a94a2d4ce076f6f2549607a116a66528fe8e44c678a6L5-R5): Updated `ENGINE_VERSION` from `0.1.42` to `0.1.43`.
* …

fix: input scrolls to the bottom when set the caret to the top

---

ai.menlo.jan.desktop
ai.menlo.jan.metainfo.xml

This pull request includes several changes to add configuration files and setup scripts for the Jan application, a local AI assistant by Menlo. The most important changes include creating a desktop entry, adding Flatpak configuration files, and specifying build options and dependencies.
Configuration and setup:
* [`ai.menlo.jan.desktop`](diffhunk://#diff-8d4eb37c529f08fe27057db0a8d1e23d35c7e95163f7e1bdc0da09f08b13b7d7R1-R8): Added a desktop entry for the Jan application, including the name, comment, execution command, terminal usage, application type, categories, and icon.
* [`ai.menlo.jan.yml`](diffhunk://#diff-92f5e2326174f4a21cc458a5e9acc249bb78648aedc300e24b85f526f0cee4b4R1-R53): Added a Flatpak configuration file specifying the app ID, runtime, SDK, base app, command, finish …

chore: add flathub submission

---

web/screens/Thread/ThreadRightPanel/index.tsx

This pull request includes a small change to the `web/screens/Thread/ThreadRightPanel/index.tsx` file. The change re-enables the `autoResize` property for the assistant instructions input field.
* [`web/screens/Thread/ThreadRightPanel/index.tsx`](diffhunk://#diff-edaf5f3af4dcdced18bb55d7ef086e99b3025a77ac18f9797d18cbbbc51bf69fL260-R260): Re-enabled the `autoResize` property for the assistant instructions input field.
- Closes #4361 
- Closes #

enhancement: instruction textarea using autoresize

---

core/src/types/setting/settingComponent.ts
extensions/inference-cortex-extension/resources/default_settings.json
web/screens/Settings/SettingDetail/SettingDetailItem/SettingDetailDropdownItem/index.tsx
web/screens/Settings/SettingDetail/SettingDetailItem/SettingDetailTextInputItem/index.tsx
web/screens/Settings/SettingDetail/SettingDetailItem/index.tsx

This PR enhances cortex settings page with better description and UX.
Fixed CSS for setting input:
- Smaller number input
- Remove the right padding. The `completions` text is cut off at the letter "c" because of extra padding for the reveal password action. However, in the case of normal input, there should be no extra padding since there's no such action.
We've resolved the issue where users couldn't scroll to view the complete extension settings page in a narrow window.
- Closes #4414
- Closes #4406
This pull request includes changes to improve the settings configuration and UI components in the `inference-cortex-extension` and `web` directories. The most important changes include enhancements to the default settings descriptions, the addition of a new dropdown component for setting …

enhancement: Update Cortex page with better description & UX

---

core/src/types/engine/index.ts
web/containers/ModelDropdown/index.tsx
web/screens/Settings/Engines/ModalAddRemoteEngine.tsx
web/screens/Settings/Engines/RemoteEngineSettings.tsx

This PR added support for custom request headers, such as anthropic requires version header to work. Deprecated API Key template since it's a part of request headers template already.
This pull request includes changes to update the handling of API key templates to header templates, and to improve the filtering logic in the `ModelDropdown` component. The most important changes include renaming `api_key_template` to `header_template` across various files and modifying the `ModelDropdown` component to handle potential undefined values.
* [`core/src/types/engine/index.ts`](diffhunk://#diff-409789d5b5f115c05e88675475c28af9ba0aab7206e250dd5ad0b90930bf0d3dL9-R9): Renamed `api_key_template` to `header_template` in the `EngineMetadata` type.
* …

chore: support request headers template

---

docs/src/pages/index.mdx

This pull request includes a change to the `docs/src/pages/index.mdx` file to improve the fetching of release data from the GitHub API.
* Modified the `resRelease` fetch call to include a query parameter that increases the number of releases fetched to 500.
- Closes #https://discord.com/channels/1107178041848909847/1251527460021993593/1326764176194011190
- Closes #

fix: add per_page params on github releases endpoint

---

extensions/inference-cortex-extension/rolldown.config.mjs

This PR is solely intended to synchronize the engine version to 0.1.43.
This pull request includes a small but important update to the `extensions/inference-cortex-extension/rolldown.config.mjs` file. The change updates the version of the Cortex engine used in the project.
* [`extensions/inference-cortex-extension/rolldown.config.mjs`](diffhunk://#diff-9b93590cc9312a835d0c11d009d45deeb5ff72bca39e246b2e3f8fde7e3d5e8eL114-R114): Updated `CORTEX_ENGINE_VERSION` from 'v0.1.42' to 'v0.1.43'.

chore: bump engine version to 0.1.43

---

electron/package.json
joi/package.json
joi/rollup.config.mjs
yarn.lock

This pull request includes changes to the `joi` package to update dependencies and improve the build configuration. The most important changes include replacing the `rollup-plugin-sass` with the `sass` package and updating the Rollup configuration to use the modern Sass API.
Dependency updates:
* [`joi/package.json`](diffhunk://#diff-c528dc1b5dd8e454997100b4ad27d03c9499e8946dfe7c6bdab5bfca6f3e73a9L43): Removed `rollup-plugin-sass` and added `sass` as a dependency. [[1]](diffhunk://#diff-c528dc1b5dd8e454997100b4ad27d03c9499e8946dfe7c6bdab5bfca6f3e73a9L43) [[2]](diffhunk://#diff-c528dc1b5dd8e454997100b4ad27d03c9499e8946dfe7c6bdab5bfca6f3e73a9R73)
Build configuration improvements:
* [`joi/rollup.config.mjs`](diffhunk://#diff-c39d7d25ca91c984c98b2a928df5f2c32dd4a554dc7e7733c1554961d84b624eL14) …

fix: sass legacy warn

---

web/screens/Settings/Engines/Settings.tsx

This pull request includes several updates to the `web/screens/Settings/Engines/Settings.tsx` file. The changes primarily focus on improving error handling, ensuring immutability, and cleaning up the code by removing unused imports.
Error Handling and Immutability Improvements:
* Added error logging when a variant is not found during the engine installation process.
* Updated the `setInstallingEngines` function to clone the existing `Map` to ensure immutability before making modifications. 
Code Cleanup:
* Removed the unused `Trash2Icon` import from `lucide-react`.
* Removed the unused `uninstallEngine` import from `@/hooks/useEngineManagement`.
Minor Adjustments:
* Added a newline for better readability in the return statement of the `EngineSettings` component.
- Closes #
- Closes #

chore: resolve button state download engine variant

---

web/helpers/atoms/Thread.atom.ts
web/hooks/useDeleteThread.test.ts
web/hooks/useDeleteThread.ts
web/screens/Settings/Advanced/index.test.tsx
web/screens/Settings/Advanced/index.tsx
web/screens/Thread/ThreadLeftPanel/ModalDeleteAllThreads/index.tsx

- Delete all threads and data base on issue required here by @imtuyethan 
https://github.com/janhq/jan/issues/4396
Add a "Delete All Threads" button in the advanced settings
Clear warning that this action cannot be undone and will remove all conversation threads in `file_path`, Delete (red) and Cancel buttons for confirmation
Result information on top right app

feat: delete all threads

---

electron/package.json
extensions/engine-management-extension/resources/anthropic.json
extensions/engine-management-extension/resources/cohere.json
extensions/engine-management-extension/resources/groq.json
extensions/engine-management-extension/resources/martian.json
extensions/engine-management-extension/resources/mistral.json
extensions/engine-management-extension/resources/nvidia.json
extensions/engine-management-extension/resources/openai.json
extensions/engine-management-extension/resources/openrouter.json
extensions/yarn.lock
web/screens/Settings/Engines/ModalAddRemoteEngine.tsx
web/screens/Settings/Engines/RemoteEngineSettings.tsx
web/utils/modelEngine.ts

This pull request includes several changes to enhance the functionality of the `ModalAddRemoteEngine` and `RemoteEngineSettings` components, as well as updates to the utility functions related to engine management. The most important changes include adding support for a new `chatCmpletionsUrl` field, updating the UI to provide API key instructions, and adding utility functions for engine-specific URLs.
Enhancements to `ModalAddRemoteEngine`:
* Added `chatCmpletionsUrl` field to the `engineSchema` validation and form default values. [[1]](diffhunk://#diff-5e7396c224a11e90fca9f92866aa0071fd66aabfde9457e254de451c77912e60L14-R22) [[2]](diffhunk://#diff-5e7396c224a11e90fca9f92866aa0071fd66aabfde9457e254de451c77912e60L32-R39)
* Updated the form submission to include the `chatCmpletionsUrl` …

chore: add chat completion field form add remote engine

---

web/screens/Settings/Engines/LocalEngineSettings.tsx
web/screens/Settings/Engines/index.tsx
web/screens/Settings/ExtensionSetting/index.tsx
web/screens/Settings/SettingDetail/SettingDetailItem/SettingDetailTextInputItem/index.tsx
web/screens/Settings/SettingDetail/SettingDetailItem/index.tsx
web/screens/Settings/SettingDetail/index.tsx
web/screens/Settings/SettingLeftPanel/index.tsx

This PR is to update app local engine settings which extended from it's parent extension settings. From now on, there is no Cortex extensions page, but all settings moved to llama.cpp engine page.
- Closes #4441
This pull request includes several changes to the `Settings` screen in the web application, primarily focusing on the `ExtensionSetting` component and related files. The changes introduce new functionality, improve existing code, and fix minor issues.
* Updated `ExtensionSetting` to accept an optional `extensionName` prop and use `useMemo` to determine the current extension name. This allows for more flexible usage of the component. [[1]](diffhunk://#diff-758ec3f45cd922288cdf5c18ff0d9481d997b843eeb918588aa783bf4d4cc3afL17-R17) …

feat: move cortex extension settings to local engine page

---

web/utils/componentSettings.ts

This pull request addressed an issue where Jan application displayed an incorrect maximum number of NGL settings. It always displayed 100 instead of using the value specified in the model configuration.
- Closes #4035
This pull request includes a change to the `web/utils/componentSettings.ts` file to add a new case for handling 'ngl' settings in the `getConfigurationsData` function.
The most important change is:
* [`web/utils/componentSettings.ts`](diffhunk://#diff-ab2c4bdf5e5c7d108c34453a926aac4e09d984458c183ba82fd091b5d86190acR36-R40): Added a new case 'ngl' to set `componentSetting.controllerProps.max` based on `selectedModel?.settings.ngl` or a default value of 100.

fix: mismatch NGL number between UI and model settings

---

.github/scripts/rename-uninstaller.sh
electron/scripts/uninstaller.nsh
extensions/yarn.lock
yarn.lock

- fix: windows uninstall not force close app
- Closes #4411 
- Closes #

fix: windows uninstall not force close app

---

web/screens/Settings/Engines/LocalEngineSettings.tsx

- Fixed a minor display issue where hyperlinks were displayed as plain text.
This pull request includes a small but important change to the `LocalEngineSettings` component in the `web/screens/Settings/Engines/LocalEngineSettings.tsx` file. The change improves the user interface by converting a plain text link into a clickable HTML anchor tag with styling.
* [`web/screens/Settings/Engines/LocalEngineSettings.tsx`](diffhunk://#diff-fb438e50789357b1faa6cc0a4695db4ba333e3f5bb597d9f4dd05d53ea121723L220-R227): Changed the plain text link to an HTML anchor tag with classes for cursor pointer and text color, and added `target="_blank"` to open the link in a new tab.

chore: fix engine description hyperlink display

---

extensions/engine-management-extension/rolldown.config.mjs
extensions/engine-management-extension/src/node/index.ts
extensions/inference-cortex-extension/download.bat
extensions/inference-cortex-extension/download.sh
extensions/inference-cortex-extension/rolldown.config.mjs
extensions/inference-cortex-extension/src/node/index.ts
web/containers/Layout/BottomPanel/DownloadingState/index.tsx
web/screens/Settings/Engines/LocalEngineSettings.tsx

- This PR addressed an issue where cuda dependencies symlink require admin privileges. Also to bump engine version to the latest one.
This pull request includes several updates and improvements across multiple files related to the Cortex engine version and error handling. The most important changes include updating the Cortex engine version, improving error logging, and modifying download paths.
* Updated `CORTEX_ENGINE_VERSION` from `v0.1.43` to `v0.1.46` in multiple configuration files (`rolldown.config.mjs`, `download.bat`, `download.sh`). [[1]](diffhunk://#diff-30942dcc326a20cefe8cde68225a2aebaf2dab82021400521c5f63724210f558L16-R16) [[2]](diffhunk://#diff-30942dcc326a20cefe8cde68225a2aebaf2dab82021400521c5f63724210f558L29-R29) …

fix: bump engine version - update engine variant symlink and copy CUDA dependencies

---

web/screens/Settings/Engines/RemoteEngineSettings.tsx
web/screens/Thread/ThreadCenterPanel/ChatBody/OnDeviceStarterScreen/index.tsx

Fixed an issue where the app would crash if the user clicked on the cloud model during the first time of onboarding.
This pull request includes changes to improve the handling of engine settings and filtering logic in the `RemoteEngineSettings` and `OnDeviceStarterScreen` components. The most important changes include adding a null check for the `engine` variable and filtering engines by type before mapping them.
Improvements to engine settings handling:
* [`web/screens/Settings/Engines/RemoteEngineSettings.tsx`](diffhunk://#diff-d8d84f4f488f0d35b2751fee2cad04a83f6661a0f11b2b6a2355ac0e70aec575R118-R119): Added a null check for the `engine` variable to return null if the engine is not defined.
Enhancements to filtering logic:
* [`web/screens/Thread/ThreadCenterPanel/ChatBody/OnDeviceStarter …

fix: app crashes on select cloud model first time onboarding

---

web/containers/ModelDropdown/index.tsx
web/containers/Providers/ModelHandler.tsx
web/hooks/useActiveModel.ts
web/hooks/useConfigurations.ts
web/hooks/useRecommendedModel.ts
web/hooks/useStarterScreen.ts
web/screens/Hub/ModelList/index.tsx
web/screens/LocalServer/LocalServerLeftPanel/index.tsx
web/screens/Settings/Engines/RemoteEngineSettings.tsx
web/screens/Thread/ThreadCenterPanel/AssistantSetting/index.tsx
web/screens/Thread/ThreadCenterPanel/LoadModelError/index.tsx

This PR addresses numerous issues related to the remote engine revamp that were preventing the release of 0.5.14.
- #4456
This pull request includes several changes to the `web` directory, primarily focusing on improving the handling of inference engines and models. The most important changes include modifying the logic for selecting models, updating the inference engine handling, and adding new hooks and atoms for managing engine configurations.
* [`web/containers/ModelDropdown/index.tsx`](diffhunk://#diff-897fe0e9366de0fa6ec9428b1423439aaab3dee774cea4b7efd6401a42fb00fbR197-R212): Added logic to handle cases where the model is not found and updated the `setSelectedModel` function accordingly.
* [`web/containers/Providers/ModelHandler.tsx`](diffhunk://#diff-c52744b512485151ef69f9c9e8b58535 …

fix: remote engine revamp issues

---

web/containers/Layout/BottomPanel/SystemMonitor/TableActiveModel/index.tsx
web/containers/ModelDropdown/index.tsx
web/containers/Providers/SWRConfigProvider.tsx
web/containers/Providers/index.tsx
web/screens/Settings/MyModels/MyModelList/index.tsx

Currently, the app waits for the cortex.cpp server to load before displaying the current model and engines, which is not user-friendly.
This PR introduces a SWR storage cache provider to eliminate any delays users experience when opening the app, especially after engine persistence.
This pull request includes several important changes to the `web/containers` directory, focusing on improving the caching mechanism and simplifying the codebase. The most significant changes include the addition of a new `SWRConfigProvider` component, updates to the `Providers` component to use the new provider, and a minor simplification in the `TableActiveModel` component.
* [`web/containers/Providers/SWRConfigProvider.tsx`](diffhunk://#diff-97146f3e2aa54719e6134acb6376b80a3ba6dfa937d86a2ef83ea959e618f18aR1-R …

chore: add caching for engines to improve load time

---

extensions/inference-cortex-extension/download.bat
extensions/inference-cortex-extension/download.sh
extensions/inference-cortex-extension/rollup.config.ts

This PR aims to bump llama.cpp engine to the latest version. The scope of this version bump is to support new DeepSeek R1 models, incorporating the latest fix from llama.cpp upstream.
This pull request updates the `ENGINE_VERSION` for the Cortex extension across multiple files to ensure consistency and compatibility with the latest release. The most important changes include updating the version in batch and shell scripts, as well as in the rollup configuration file.
Version update:
* [`extensions/inference-cortex-extension/download.bat`](diffhunk://#diff-8a7d1c23da498167c2b1a94a2d4ce076f6f2549607a116a66528fe8e44c678a6L5-R5): Updated `ENGINE_VERSION` from `0.1.42-hotfix` to `0.1.49` to download the latest binaries.
* [`extensions/inference-cortex-extension/download.sh`](diffhunk://#diff-f6 …

chore: bump llama.cpp to the latest version

---

docs/src/components/DropdownDownload/index.tsx

This pull request includes a small change to the `DropdownDownload` component in the `docs/src/components/DropdownDownload/index.tsx` file. The change updates the default system setting for Windows users.
* [`docs/src/components/DropdownDownload/index.tsx`](diffhunk://#diff-31842c3a9c132b23b5a3900edd457747c73325b128e37bc5ab05ab477891d750L68-R68): Changed the default system for Windows users from `systems[2]` to `systems[1]`.
- Closes #
- Closes #

fix: Correct index for Windows download button

---

web/containers/Providers/ModelHandler.tsx

This PR resolved the issue where thread titles weren't being generated for threads using reasoning models.
1. Summarization title shouldn't break when encountering a line break
2. Exclude `thought` section
This pull request includes several changes to the `ModelHandler` function in the `web/containers/Providers/ModelHandler.tsx` file. The changes focus on improving the handling and cleaning of message content before updating the thread title.
Improvements to message content handling:
* Changed `messageContent` from `const` to `let` to allow for modifications.
* Replaced newline characters in `messageContent` with spaces and extracted content after `</think>` tag if present.
Simplification of code:
* Removed unnecessary checks and warnings related to the length of the message content. …

fix: thread title summarization doesn't work well on reasoning models

---

.github/workflows/auto-assign-author.yml

This pull request includes a small change to the `.github/workflows/auto-assign-author.yml` file. The change adds a conditional statement to ensure that the job only runs if the pull request's head repository matches the current repository.
* [`.github/workflows/auto-assign-author.yml`](diffhunk://#diff-241936f6a26af3f159725951c5a3302bfa839fdde96b98ed891b555e8faaab9aR9): Added a conditional statement to the `assign-author` job to check if the pull request's head repository matches the current repository.
- Closes #
- Closes #

chore: ignore external contributors

---

web/helpers/atoms/AppConfig.atom.ts
web/hooks/useConfigurations.test.ts
web/hooks/useConfigurations.ts
web/screens/Settings/Advanced/ProxySettings/index.test.tsx
web/screens/Settings/Advanced/ProxySettings/index.tsx
web/screens/Settings/Advanced/index.test.tsx
web/screens/Settings/Advanced/index.tsx
web/screens/Settings/SettingDetail/index.tsx

sub-page for Proxy Settings base on feature https://github.com/janhq/jan/issues/4047 by @louis-jan 
User can click on right arrow from Advanced Settings:
sub-page for its detailed settings:

Feat: Allow HTTP proxy authentication inputs

---

extensions/yarn.lock
web/containers/CenterPanelContainer/index.tsx
web/containers/Layout/TopPanel/index.tsx
web/containers/LeftPanelContainer/index.tsx
web/containers/Loader/ModelReload.tsx
web/containers/Providers/index.tsx
web/containers/RightPanelContainer/index.test.tsx
web/containers/RightPanelContainer/index.tsx
web/screens/Settings/Advanced/ProxySettings/index.tsx
web/screens/Settings/Engines/index.tsx

This pull request includes several changes to improve the state management and UI components in various files. The most important changes involve replacing local storage with Jotai atoms for panel widths, adding tooltips to buttons, and cleaning up unused imports.
* Replaced local storage with Jotai atoms for managing `leftPanelWidth` and `rightPanelWidth` in `LeftPanelContainer` and `RightPanelContainer` components. 
* Added tooltips to buttons in the `TopPanel` component for better user guidance. 
* Removed unused imports and code to streamline the `ModelReload`, `Providers`, `ProxySettings`, and `Engines` components. 
* Added CSS classes to manage the `select-none` class during resizing in the `LeftPanelContainer` and `RightPanelContainer` components. 
The center panel will always …

enhancement: minor ui refinements

---

docs/src/pages/docs/desktop/mac.mdx

- Fix a typo where "Apple Intel Macs" are written as "Appple Intel Macs" at https://jan.ai/docs/desktop/mac
N/A

fix: typo on apple

---

web/hooks/useCreateNewThread.ts

This pull request includes a small but significant change to the `useCreateNewThread` hook in the `web/hooks/useCreateNewThread.ts` file. The change introduces the use of a `selectedModel` state value to prioritize the model selection process when creating a new thread.
Key change:
* [`web/hooks/useCreateNewThread.ts`](diffhunk://#diff-11adf34745ca476ecb45f143cb48d7ceb507793be060729acb9b0708ee3fd6ceR54-R60): Added `selectedModel` from the `selectedModelAtom` and updated the `defaultModel` assignment to prioritize `selectedModel` over `recommendedModel` when no specific model is provided.
https://github.com/user-attachments/assets/8354b0c9-e55c-47c1-a67e-b88002a9370c
- Closes #4398 
- Closes #

enhancement: create new thread with last chosen model

---

web/containers/MainViewContainer/index.tsx
web/screens/Thread/ThreadCenterPanel/index.tsx

This pull request includes changes to the `MainViewContainer` and `ThreadCenterPanel` components to improve the handling of the system monitor panel's height. The changes involve moving the logic for adjusting the height based on the system monitor panel's visibility from `ThreadCenterPanel` to `MainViewContainer`.
* Added `useEffect` and `useState` imports to manage the height of the system monitor panel.
* Imported `showSystemMonitorPanelAtom` from `App.atom` and added state management for the system monitor panel's height.
* Updated the `MainViewContainer` component to adjust its height based on the system monitor panel's height.
* Removed the import of `showSystemMonitorPanelAtom` and the related state management logic.
* Cleaned up the `ThreadCenterPanel` component by removing the …

enhancement: Update app layout with an expanded system monitor

---

core/src/browser/extensions/enginesManagement.ts
core/src/types/model/modelEntity.ts
web/hooks/useEngineManagement.ts
web/screens/Settings/Engines/ModalAddModel.tsx
web/screens/Settings/Engines/RemoteEngineSettings.tsx

Allow users to manually add models when model list URL is unavailable/inaccessible (e.g. OpenRouter).
AC:
- User can manually add models for any remote 
- Added models appear in the model list in respective remote engine settings
- Models can be configured and used normally
- Proper error handling if:
- model ID already exists
Out of scope:
- model ID doesn't exists (/models settings don't work for all endpoints - KIV)
- Closes #4515
This pull request includes several changes to improve the management and addition of remote engine models. The key changes involve adding new functionalities for handling remote engine models, updating the UI components, and importing necessary modules.
* [`core/src/types/model/modelEntity.ts`](diffhunk://#diff-710b560c58b045d2eae48d8fc5305758af6f9a48886230395 …

feat: allow users to add remote models

---

web/screens/Settings/Advanced/index.tsx
web/screens/Settings/MyModels/index.tsx

This pull request includes changes to the `Advanced` and `MyModels` components in the `web/screens/Settings` directory to improve layout and alignment. The most important changes include adjustments to the flexbox properties to ensure consistent alignment and layout behavior across different screen sizes.
Layout and alignment improvements:
* [`web/screens/Settings/Advanced/index.tsx`](diffhunk://#diff-8d119b4ddbfcbb13597702a44730e486bc4c02dc630069686effa3333ab90411L215-R216): Changed the flex direction from `flex-col` to `flex-row` for the Experimental section to ensure consistent layout.
* [`web/screens/Settings/Advanced/index.tsx`](diffhunk://#diff-8d119b4ddbfcbb13597702a44730e486bc4c02dc630069686effa3333ab90411R225-R232): Added a `flex-shrink-0` class to the experimental switch …

enhancement: update responsive setting and my model page

---

web/containers/ErrorMessage/index.test.tsx
web/containers/ErrorMessage/index.tsx

This pull request introduces several changes to the `ErrorMessage` component and its associated tests in order to enhance functionality and improve the user interface. The most important changes include the addition of new icons, a copy-to-clipboard feature, and updates to the test cases to reflect these changes.
Enhancements to the `ErrorMessage` component:
* [`web/containers/ErrorMessage/index.tsx`](diffhunk://#diff-711ca7c6c49338a63c87e2e9eee4cae1cc0ec950daf8269051e23ca64ca0f244R1-R2): Added new imports for `useRef`, `useState`, and icons from `lucide-react`. Introduced a copy-to-clipboard feature using `useRef` and `useState` hooks, and updated the error message display to include new styling and icons for troubleshooting and copying error messages. …

feat: Standardize inline error messages

---

web/screens/Thread/ThreadRightPanel/index.tsx

This pull request includes a change to the `ThreadRightPanel` component in the `web/screens/Thread/ThreadRightPanel/index.tsx` file. The change removes a conditional block that was responsible for updating the `max_tokens` parameter in the `activeAssistant` model settings based on the `ctx_len` key.
* [`web/screens/Thread/ThreadRightPanel/index.tsx`](diffhunk://#diff-edaf5f3af4dcdced18bb55d7ef086e99b3025a77ac18f9797d18cbbbc51bf69fL205-L214): Removed the conditional block that updates the `max_tokens` parameter when the `ctx_len` key is present and its value is less than the `max_tokens` parameter in the `activeAssistant` model settings.
https://github.com/user-attachments/assets/8f9be3f0-38ff-4efe-b4fc-61d26ec62382
- Closes #4427 
- Closes #

fix: broken range slider ctx length

---

extensions/engine-management-extension/rolldown.config.mjs
extensions/inference-cortex-extension/rolldown.config.mjs

This PR aims to synchronize the Cortex engine with the latest version.
This pull request includes updates to the Cortex engine version in the configuration files for both the engine management and inference cortex extensions.
Updates to Cortex engine version:
* [`extensions/engine-management-extension/rolldown.config.mjs`](diffhunk://#diff-30942dcc326a20cefe8cde68225a2aebaf2dab82021400521c5f63724210f558L16-R16): Updated `CORTEX_ENGINE_VERSION` from `v0.1.46` to `v0.1.49` in both occurrences. [[1]](diffhunk://#diff-30942dcc326a20cefe8cde68225a2aebaf2dab82021400521c5f63724210f558L16-R16) [[2]](diffhunk://#diff-30942dcc326a20cefe8cde68225a2aebaf2dab82021400521c5f63724210f558L29-R29)
* [`extensions/inference-cortex-extension/rolldown.config.mjs`](diffhunk://#diff-9b93590cc9312a835d0c11d009d45d …

chore: sync cortex engine version

---

extensions/engine-management-extension/rolldown.config.mjs
extensions/inference-cortex-extension/rolldown.config.mjs
web/containers/ModelDropdown/index.tsx

This PR addressed an issue where users switch to a different model and then switch back to the original model. The new settings are not applied in this scenario.
Chore update:
Cortex engine version bump to 0.1.49
- Closes #4505
This pull request includes several updates and improvements across different files, primarily focusing on version updates and enhancements to the `ModelDropdown` component.
* Updated `CORTEX_ENGINE_VERSION` from `v0.1.46` to `v0.1.49` in `extensions/engine-management-extension/rolldown.config.mjs` [[1]](diffhunk://#diff-30942dcc326a20cefe8cde68225a2aebaf2dab82021400521c5f63724210f558L16-R16) [[2]](diffhunk://#diff-30942dcc326a20cefe8cde68225a2aebaf2dab82021400521c5f63724210f558L29-R29).
* Updated `CORTEX_ENGINE_VERSION` from `v0.1.46` to `v0.1.49` in …

fix: app does not reload model when prompt template is updated

---

core/src/types/config/appConfigEntity.ts
web/containers/Layout/index.tsx
web/hooks/useFactoryReset.ts
web/utils/settings.ts

This PR ensures that the app ID remains unchanged, just like other global app settings.
This pull request introduces changes to support the management of a distinct ID within the app configuration. The most important changes include adding a new optional `distinct_id` field to the `AppConfiguration` type, updating the layout to handle this distinct ID, and adding utility functions for updating and retrieving the distinct ID.
Changes to support distinct ID management:
* [`core/src/types/config/appConfigEntity.ts`](diffhunk://#diff-81d34794166bc265d38342b18eabd32a24bcb444a9d56afdc11995469b32e517R4): Added an optional `distinct_id` field to the `AppConfiguration` type.
* [`web/containers/Layout/index.tsx`](diffhunk://#diff-14ae8afe09456109846de9e991341105e0d570a68d771860be34c3626c438f59R29-R3 …

chore: ensure app Id is maintained

---

web/helpers/atoms/App.atom.ts
web/screens/Hub/index.tsx

As designed, users will see a different Model Hub banner every time they reopen the app if they haven't set any banner. This PR is for that.
1. Users have not changed the banner hub -> Set a random hub image from the default list when the app is opened using Atom Storage and a bridge ReadOnly Atom.
2. As soon as users set a banner hub image, WriteOnly Atom writes this setting into Atom Storage. From then on, it returns the latest banner hub image.
- Closes #4170
This pull request introduces changes to the `web/helpers/atoms/App.atom.ts` and `web/screens/Hub/index.tsx` files to enhance the management of the app banner hub settings. The most important changes include renaming and refactoring atoms for better clarity, adding new atoms for retrieving and setting the banner, and updating the …

chore: rotate model hub banner on app launch until set

---

core/src/types/model/modelEntity.ts
extensions/engine-management-extension/rolldown.config.mjs
extensions/engine-management-extension/src/@types/global.d.ts
extensions/engine-management-extension/src/index.ts

Previously, when setting up a new remote provider, users had to manually set up models. With this update, as soon as users set up a new provider, it will automatically attempt to pull models from the specified /models endpoint.
- Closes #4515
This pull request includes several changes to the `JSONEngineManagementExtension` class and related configuration files to enhance the handling of remote models and engines. The most important changes include modifying the `Model` type, updating the configuration, and improving the methods for adding and populating remote models.
Changes to `Model` type:
* [`core/src/types/model/modelEntity.ts`](diffhunk://#diff-710b560c58b045d2eae48d8fc5305758af6f9a48886230395b028d94bdf635f5L74-R74): Renamed the `mode` property to `model` in the `Model` type. …

feat: pull models list when setting up a new remote engine

---

extensions/yarn.lock
web/containers/ErrorMessage/index.tsx

This pull request includes a small change to the `web/containers/ErrorMessage/index.tsx` file. The change ensures that the elements within the error message container are properly aligned by adding the `items-center` class to the `div` element.
Alignment improvement:
* [`web/containers/ErrorMessage/index.tsx`](diffhunk://#diff-711ca7c6c49338a63c87e2e9eee4cae1cc0ec950daf8269051e23ca64ca0f244L107-R107): Added the `items-center` class to the `div` element to ensure proper alignment of the elements within the error message container.
- Closes #
- Closes #

chore: align item menu action error message

---

web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
web/screens/Thread/ThreadCenterPanel/FileUploadPreview/index.tsx
web/screens/Thread/ThreadCenterPanel/ImageUploadPreview/index.tsx
web/screens/Thread/ThreadCenterPanel/TextMessage/DocMessage.tsx
web/screens/Thread/ThreadCenterPanel/TextMessage/RelativeImage.tsx

This pull request includes several changes to improve the styling and functionality of various components in the `web/screens/Thread/ThreadCenterPanel` directory. The changes mainly involve updating CSS classes to enhance the user interface and user experience.
Styling improvements:
* [`web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx`](diffhunk://#diff-6939e74c6339668f085c4edb1a90987fea21a6e5679fa3ff95495629ba249b4aL141-R148): Adjusted the CSS classes for the `RichTextEditor` component to better handle the file upload preview state.
* [`web/screens/Thread/ThreadCenterPanel/FileUploadPreview/index.tsx`](diffhunk://#diff-6f0fab6a46ddc16b49a300a11df4541fa4396a032ecf1f3ac911c144af0dd1c8L25-R25): Updated the background color and border styles for the file upload preview container and …

enhancement: update UI uploading files and images

---

extensions/engine-management-extension/rolldown.config.mjs
extensions/yarn.lock
web/screens/Settings/Engines/DeleteEngineVariant.tsx
web/screens/Settings/Engines/ModalDeleteModel.tsx
web/screens/Settings/Engines/RemoteEngineSettings.tsx

This pull request includes various changes across multiple files, focusing on updates to configuration, enhancements to engine management, and improvements to the web interface.
* [`core/src/types/config/appConfigEntity.ts`](diffhunk://#diff-81d34794166bc265d38342b18eabd32a24bcb444a9d56afdc11995469b32e517R4): Added an optional `distinct_id` field to the `AppConfiguration` type.
* [`core/src/types/model/modelEntity.ts`](diffhunk://#diff-710b560c58b045d2eae48d8fc5305758af6f9a48886230395b028d94bdf635f5L74-R74): Renamed the `mode` field to `model` in the `Model` type.
* [`extensions/engine-management-extension/rolldown.config.mjs`](diffhunk://#diff-30942dcc326a20cefe8cde68225a2aebaf2dab82021400521c5f63724210f558L16-R25): Updated `CORTEX_ENGINE_VERSION` to `v0.1.49` and added default payload, …

enhancement: remote engine model

---

web/screens/Thread/ThreadCenterPanel/TextMessage/MarkdownTextMessage.tsx
web/screens/Thread/ThreadCenterPanel/TextMessage/ThinkingBlock.tsx

This pull request includes changes to the `web/screens/Thread/ThreadCenterPanel/TextMessage` components to enhance the handling of markdown text messages. The most important changes include updating the `MarkdownTextMessage` component to make some props optional and integrating this component into the `ThinkingBlock` component.
Enhancements to markdown text message handling:
* [`web/screens/Thread/ThreadCenterPanel/TextMessage/MarkdownTextMessage.tsx`](diffhunk://#diff-248577b16f0456ecc74b4c2feb89430842934aea33e2a7d3fcbec9cced25bf1bL22-R22): Updated the `MarkdownTextMessage` component to make the `id` and `isUser` props optional.
Integration of markdown text message component:
* [`web/screens/Thread/ThreadCenterPanel/TextMessage/ThinkingBlock.tsx`](diffhunk://#diff-ab6a818fc54ea9f5203a346a …

fix: think content render as markdown

---

extensions/yarn.lock
web/screens/Settings/HuggingFaceRepoDetailModal/ModelDownloadRow/index.tsx

This pull request includes a change to the `ModelDownloadRow` component in the `HuggingFaceRepoDetailModal` screen. The change modifies the logic for determining if a model is currently downloading.
* [`web/screens/Settings/HuggingFaceRepoDetailModal/ModelDownloadRow/index.tsx`](diffhunk://#diff-b5c4343baba94d9357d77fd6e643b315b466f367e4b3ee7c87d96f5576a6e51fL54-R56): Updated the `isDownloading` variable to check if the `fileName` includes any of the `downloadingModels` elements, in addition to checking for equality.
- Closes # https://discord.com/channels/1107178041848909847/1324287882722021407/1336221159712358430
- Closes #

fix: download progress import from hgf

---

docs/src/utils/format.ts
docs/yarn.lock

This pull request includes a change to the `totalDownload` function in `docs/src/utils/format.ts` to improve the accuracy of download counts for versions starting from `0.5.15`. Additionally, a minor comment correction was made to clarify the purpose of the dummy return value.
Changes to improve download count accuracy:
* [`docs/src/utils/format.ts`](diffhunk://#diff-29ca9662b787658f96a8616026b10f474b42a37a7fca0f8087d7a9d7c684c7f5L9-R22): Modified the `totalDownload` function to filter out assets ending with `.yml` for versions starting from `0.5.15`.
Minor comment correction:
* [`docs/src/utils/format.ts`](diffhunk://#diff-29ca9662b787658f96a8616026b10f474b42a37a7fca0f8087d7a9d7c684c7f5L9-R22): Corrected the comment to clarify that the dummy return value is used to avoid rate limit API …

fix: exclude yml into totaldownload start next version

---

extensions/yarn.lock
joi/src/core/Dropdown/styles.scss
web/screens/Hub/ModelList/ModelHeader/index.tsx
web/screens/Hub/ModelPage/index.tsx
web/screens/Hub/index.tsx
web/styles/components/marked.scss

This pull request includes a series of updates to the styles and components in the project. The changes primarily focus on improving the visual consistency and theming across various components by using CSS variables.
* Updated `border-color` and `background-color` properties to use the `hsla(var(--app-border))` and `hsla(var(--app-bg))` variables for better theming in `Dropdown` styles. [[1]](diffhunk://#diff-e0c8f2ed2135869b2d3a3f255de10fadc1eac86faa64211716c46e01bd9c9586R41) [[2]](diffhunk://#diff-e0c8f2ed2135869b2d3a3f255de10fadc1eac86faa64211716c46e01bd9c9586L73-R74)
* Modified the `Dropdown` component in `ModelHeader` to include additional styling properties like `max-h`, `max-w`, and `overflow-y` for better layout control.
* Removed the hardcoded `text-black` class from table cells …

enhancement: adjust hub ui in different themes

---

web/containers/ErrorMessage/index.tsx
web/tailwind.config.js

This pull request includes changes to the `ErrorMessage` component and updates to the Tailwind CSS configuration. The most important changes are focused on improving the styling and appearance of error messages and updating the font families used in the project.
Styling improvements for `ErrorMessage` component:
* Added a visual indicator next to the error message title and updated the title's styling to be more prominent (`web/containers/ErrorMessage/index.tsx`).
* Enhanced the styling of the clickable elements within the error message to make them more noticeable (`web/containers/ErrorMessage/index.tsx`).
* Changed the font style of the error message content to use a serif font for better readability (`web/containers/ErrorMessage/index.tsx`).
Updates to Tailwind CSS configuration:
* …

enhancement: error ui in threads

---

extensions/engine-management-extension/src/index.ts

This pull request includes an enhancement to the `addRemoteModel` method in the `JSONEngineManagementExtension` class to include additional inference parameters when adding a model.
Enhancements to `addRemoteModel` method:
* [`extensions/engine-management-extension/src/index.ts`](diffhunk://#diff-d8c74089c1ad29e79d22182a9a2d8721dd5c77e8bd937363487496ba8cd8c991L198-R212): Modified the `addRemoteModel` method to include additional inference parameters (`max_tokens`, `temperature`, `top_p`, `stream`, `frequency_penalty`, `presence_penalty`) in the JSON payload when posting to the API.

chore: add default inference parameters for custom remote models

---

extensions/inference-cortex-extension/package.json
extensions/inference-cortex-extension/resources/models/deepseek-r1-distill-llama-70b/model.json
extensions/inference-cortex-extension/resources/models/deepseek-r1-distill-llama-8b/model.json
extensions/inference-cortex-extension/resources/models/deepseek-r1-distill-qwen-1.5b/model.json
extensions/inference-cortex-extension/resources/models/deepseek-r1-distill-qwen-14b/model.json
extensions/inference-cortex-extension/resources/models/deepseek-r1-distill-qwen-32b/model.json
extensions/inference-cortex-extension/resources/models/deepseek-r1-distill-qwen-7b/model.json
extensions/inference-cortex-extension/resources/models/llama3.1-8b-instruct/model.json
extensions/inference-cortex-extension/rolldown.config.mjs

This pull request includes several updates to the `inference-cortex-extension` package, focusing on adding new model configurations and updating the package version. The most significant changes involve the addition of multiple new models and necessary configuration adjustments.
* Added new model configuration for `DeepSeek R1 Distill Llama 70B Q4` in `resources/models/deepseek-r1-distill-llama-70b/model.json`.
* Added new model configuration for `DeepSeek R1 Distill Llama 8B Q5` in `resources/models/deepseek-r1-distill-llama-8b/model.json`.
* Added new model configuration for `DeepSeek R1 Distill Qwen 1.5B Q5` in `resources/models/deepseek-r1-distill-qwen-1.5b/model.json`.
* Added new model configuration for `DeepSeek R1 Distill Qwen 14B Q4` in …

chore:add deepseek r1 distill models to hub

---

web/containers/ErrorMessage/index.tsx
web/screens/Thread/ThreadCenterPanel/LoadModelError/index.tsx

This pull request includes changes to improve error handling and component reuse in the `ErrorMessage` and `LoadModelError` components. The most important changes include making the `ErrorMessage` component more flexible by adding optional props, updating references to the `message` object to handle undefined values safely, and integrating the `ErrorMessage` component into the `LoadModelError` component.
Improvements to `ErrorMessage` component:
* [`web/containers/ErrorMessage/index.tsx`](diffhunk://#diff-711ca7c6c49338a63c87e2e9eee4cae1cc0ec950daf8269051e23ca64ca0f244L26-R32): Added optional `errorComponent` prop to the `ErrorMessage` component and updated references to `message` to handle undefined values safely. [[1]](diffhunk://#diff-711ca7c6c49338a63c87e2e9eee4cae1cc0ec950daf8269051e2 …

fix: load model error component

---

extensions/engine-management-extension/models/openrouter.json
extensions/engine-management-extension/resources/deepseek.json
extensions/engine-management-extension/resources/google_gemini.json
extensions/engine-management-extension/resources/groq.json
extensions/engine-management-extension/resources/martian.json
extensions/engine-management-extension/resources/nvidia.json
extensions/engine-management-extension/resources/openai.json
extensions/engine-management-extension/resources/openrouter.json
extensions/engine-management-extension/rolldown.config.mjs

This pull request includes several changes to the `extensions/engine-management-extension` module, primarily focusing on adding new models to `openrouter.json` and simplifying the response transformation templates across various resource files.
* Added new models `qwen/qwen-vl-plus:free` and `qwen/qwen2.5-vl-72b-instruct:free` to the `openrouter.json` file.
* Simplified the response transformation template in `deepseek.json` to use `{{tojson(input_request)}}`.
* Simplified the response transformation template in `google_gemini.json` to use `{{tojson(input_request)}}`.
* Simplified the response transformation template in `groq.json` to use `{{tojson(input_request)}}`.
* Simplified the response transformation template in `martian.json` to use `{{tojson(input_request)}}`.
* Simplified the …

chore: update remote provider response transform template

---

extensions/yarn.lock
web/screens/Settings/Engines/RemoteEngineSettings.tsx

This pull request includes updates to the `RemoteEngineSettings.tsx` file to enhance functionality and improve state management by adding new atom values and setters from the `jotai` library. The most important changes include importing additional atoms, setting the selected model atom based on conditions, and using the `threadsAtom` to manage thread-related data.
Enhancements to state management:
* [`web/screens/Settings/Engines/RemoteEngineSettings.tsx`](diffhunk://#diff-d8d84f4f488f0d35b2751fee2cad04a83f6661a0f11b2b6a2355ac0e70aec575L20-R20): Added `useSetAtom` from `jotai` to manage state updates.
* [`web/screens/Settings/Engines/RemoteEngineSettings.tsx`](diffhunk://#diff-d8d84f4f488f0d35b2751fee2cad04a83f6661a0f11b2b6a2355ac0e70aec575L35-R39): Imported `selectedModelAtom` and …

fix: remote engine model auto select

---

web/screens/Hub/ModelList/ModelHeader/index.tsx
web/screens/Hub/ModelList/ModelItem/index.tsx
web/screens/Thread/ThreadCenterPanel/TextMessage/MarkdownTextMessage.tsx
web/screens/Thread/ThreadCenterPanel/TextMessage/MarkdownUtils.tsx

This pull request includes several changes aimed at enhancing the functionality and user interface of the Model List and Markdown components in the Hub and Thread screens. The most important changes include the addition of a default model indicator, the integration of custom markdown components, and the simplification of dropdown options.
- Closes #4563
* [`web/screens/Hub/ModelList/ModelHeader/index.tsx`](diffhunk://#diff-c12507244d72ba8a5e975aa7ed41cdc8d996e3030a5248237aa84dd5f9da02a4L1-R1): Added `useMemo` to compute the default model and included a `Badge` to indicate the default model in the dropdown options. [[1]](diffhunk://#diff-c12507244d72ba8a5e975aa7ed41cdc8d996e3030a5248237aa84dd5f9da02a4L1-R1) [[2]](diffhunk://#diff-c12507244d72ba8a5e975aa7ed41cdc8d996e3030a5248237aa84dd5f9da0 …

chore: open URL from model detail page should open in an external browser

---

electron/main.ts
electron/utils/logger.ts

This pull request adds back logging function to the application. It includes adding a `FileLogger` class for logging to files and integrating this logger into the application startup process. (previously implemented from monitoring extension, the extension is now removed)
* **New File Logger Implementation**:
- Added a `FileLogger` class in `electron/utils/logger.ts` to handle logging to files, including methods for logging messages and cleaning old logs.
* **Register Logger**:
- Imported the `registerLogger` function in `electron/main.ts` and added it to the application startup sequence to initialize the logger. [[1]](diffhunk://#diff-13ee644059574b054a4e5ec081666a03579b28da03a50331215908f8d0ef7cfdR31) [[2]](diffhunk://#diff-13ee644059574b054a4e5ec081666a03579b28da03a50331215908f8d0ef7cfd …

chore: add back app logging function

---

extensions/engine-management-extension/src/index.ts

This pull request includes changes to the `extensions/engine-management-extension/src/index.ts` file to rename a class and improve the handling of remote models.
In the latest beta version, users will need to delete the engine and then add it back to have the /models pulled. Instead, with this update, users will only need to update the /models endpoint to trigger the models pull.
Class renaming:
* [`extensions/engine-management-extension/src/index.ts`](diffhunk://#diff-d8c74089c1ad29e79d22182a9a2d8721dd5c77e8bd937363487496ba8cd8c991L28-R31): Renamed `JSONEngineManagementExtension` to `JanEngineManagementExtension` to better reflect its functionality.
Handling of remote models:
* [`extensions/engine-management-extension/src/index.ts`](diffhunk://#diff-d8c74089c1ad29e79d22182a9a2d8721dd5c77e …

fix: error handling - pull remote models list raise an error on fail

---

extensions/engine-management-extension/src/index.ts

This pull request includes a change to the `JanEngineManagementExtension` class in the `extensions/engine-management-extension/src/index.ts` file to improve the handling of remote models during the engine update process.
Improvements to handling remote models:
* [`extensions/engine-management-extension/src/index.ts`](diffhunk://#diff-d8c74089c1ad29e79d22182a9a2d8721dd5c77e8bd937363487496ba8cd8c991L344-R348): Modified the code to use `Promise.all` for adding remote models concurrently instead of sequentially. This change ensures that all remote models are added before emitting the `ModelEvent.OnModelsUpdate` event.

fix: inconsistent models list on first launch

---

web/services/appService.ts

This pull request includes an important change to the `appService` in the `web/services/appService.ts` file. The change ensures that only GPUs with a total VRAM greater than 0 are included in the `gpuSettingInfo`.
* [`web/services/appService.ts`](diffhunk://#diff-10ba7524a3bbc6790bdfcd1f9ecae35602c1f124d1483c8d817278325cc9730fL37-R39): Modified the `gpuSettingInfo` to filter out GPUs with zero total VRAM.
- Closes #
- Closes #

fix: filter out fake gpu

---

extensions/inference-cortex-extension/src/node/index.ts

This pull request includes a small change to the `extensions/inference-cortex-extension/src/node/index.ts` file. The change adds logging configuration to the `run` function to set the log level to `INFO`.
* [`extensions/inference-cortex-extension/src/node/index.ts`](diffhunk://#diff-f8f14f9faebbb7438e169298472574322d46c7f4e7901479defc6a24efdd0a64R49-R50): Added `--loglevel` and `INFO` parameters to the `run` function to configure logging.

chore: change cortex.cpp log level to info for easier log observation

---

extensions/engine-management-extension/src/utils.ts

This pull request includes modifications to the `extensions/engine-management-extension/src/utils.ts` file to enhance the `engineVariant` function by introducing a new constant `platform` and optimizing the logic for determining the engine variant.
This will fix the issue where running Jan on Mac, by default it appends `no-avx` extension to the engine variant, hence no model can run.
When I first time open Jan it should show configured engine instead of a blank setting.
Improvements to the `engineVariant` function:
* Introduced a new constant `platform` to store the result of the `os(gpuSetting)` function call, which simplifies the subsequent code.
* Added a conditional check to return the `platform` directly if it starts with 'mac', avoiding unnecessary processing for macOS platforms.
* …

chore: fix engine variant for mac targets

---

extensions/yarn.lock
web/containers/ModelLabel/index.tsx

This pull request includes a modification to the `ModelLabel` component to adjust the calculation of available RAM and add a debug log.
Changes to `ModelLabel` component:
* [`web/containers/ModelLabel/index.tsx`](diffhunk://#diff-bfb0a9dfbc5c4313f7542042221037f3f5ddca8a52b56683ecffa1c42460e0e7L45-R51): Adjusted the calculation of `availableRam` to account for the size of the active model's metadata more accurately by converting it to megabytes and applying a multiplier. Added a `console.log` statement to log the size of the active model's metadata for debugging purposes.
before active a model
After active a model, we calculate model size into `availableRam`
- Closes # https://github.com/janhq/jan/issues/4456#issuecomment-2650007836
- Closes #

fix: render slow on device label

---

.github/workflows/jan-electron-build-beta.yml

This pull request includes a small but important change to the `.github/workflows/jan-electron-build-beta.yml` file. The change modifies the way the version is set to an environment variable by stripping the leading 'v' character from the version string.
* [`.github/workflows/jan-electron-build-beta.yml`](diffhunk://#diff-3eda9251187aa95e51016c05c5813e16d13e53225833d5bf4ae19b196e9ad8e0L66-R68): Updated the script to strip the leading 'v' from the version string before setting it as an environment variable.

fix: beta noti discord

---

web/screens/Settings/Engines/LocalEngineSettings.tsx

This pull request includes changes to the `LocalEngineSettings` component in the `web/screens/Settings/Engines/LocalEngineSettings.tsx` file. The changes focus on filtering and formatting within the `releasedEnginesByVersion` map function and improving the readability of nested code.
Changes to filtering and formatting:
* Added a filter to exclude engines with names that include 'cuda-' in the `releasedEnginesByVersion` map function.
* Improved readability by reformatting the nested `installingEngines.get` function call within the `formatDownloadPercentage` function.
- Closes #
- Closes #

fix: filter out variant engine

---

web/utils/modelEngine.ts

This pull request includes a small change to the `web/utils/modelEngine.ts` file. The change updates the title returned for the `google_gemini` engine to 'Gemini' instead of 'Google Gemini'. 
* [`web/utils/modelEngine.ts`](diffhunk://#diff-309cd47b5075dcd8ead194871d0804128567943093ba99c5138ce1c173cf1918L68-R68): Modified the return value for the `google_gemini` engine to 'Gemini'.
- Closes #
- Closes #

fix: rename google gemini into gemini

---

web/containers/ModelDropdown/index.tsx

This pull request includes changes to the `ModelDropdown` component in the `web/containers/ModelDropdown/index.tsx` file to improve the display of model names by truncating long text.
Improvements to model name display:
* Modified the `className` of the `p` element to truncate long model names, ensuring they do not overflow and are displayed within a maximum width of 200px. [[1]](diffhunk://#diff-897fe0e9366de0fa6ec9428b1423439aaab3dee774cea4b7efd6401a42fb00fbL478-R478) [[2]](diffhunk://#diff-897fe0e9366de0fa6ec9428b1423439aaab3dee774cea4b7efd6401a42fb00fbL576-R576)
- Closes #
- Closes #

fix: model dropdown icon miss align

---

docs/src/pages/about/index.mdx

Changed "Redhat" to "Red Hat" (which is the correct company name).

Fix typo for Red Hat company name

---

web/screens/Settings/Engines/LocalEngineItem.tsx

This pull request includes a small change to the `web/screens/Settings/Engines/LocalEngineItem.tsx` file. The change ensures that the `Switch` component is only rendered if the engine is not `InferenceEngine.cortex_llamacpp`.
- Closes #
- Closes #

chore: disable turn off local engine llamacpp

---

extensions/yarn.lock
web/screens/Settings/Hardware/index.tsx

This pull request includes a small change to the `web/screens/Settings/Hardware/index.tsx` file. The change ensures that the page is reloaded after updating the active GPUs.
* [`web/screens/Settings/Hardware/index.tsx`](diffhunk://#diff-3121a4c10de81ebf1d30e16b0b45015089e9777193653a11ef4b9fd4ccaf123cR73): Added a call to `window.location.reload()` after setting the active GPUs and calling `mutate()`.
- Closes #
- Closes #

fix: reload app when gpu change

---

docs/src/utils/format.ts

This pull request includes a small change to the `docs/src/utils/format.ts` file. The change modifies the `formatCompactNumber` function to include a `maximumFractionDigits` option in the number formatter.
* [`docs/src/utils/format.ts`](diffhunk://#diff-29ca9662b787658f96a8616026b10f474b42a37a7fca0f8087d7a9d7c684c7f5L2-R2): Added `maximumFractionDigits: 1` to the `Intl.NumberFormat` options in the `formatCompactNumber` function.
- Closes #
- Closes #

fix: format compact number utils

---

web/screens/Hub/ModelList/ModelHeader/index.tsx
web/screens/Hub/ModelPage/index.tsx
web/screens/Thread/ThreadCenterPanel/TextMessage/MarkdownTextMessage.tsx

This pull request includes several changes to the `web/screens/Hub/ModelPage/index.tsx`, `web/screens/Hub/ModelList/ModelHeader/index.tsx`, and `web/screens/Thread/ThreadCenterPanel/TextMessage/MarkdownTextMessage.tsx` files. The changes mainly focus on UI enhancements, conditional rendering based on model types, and CSS class adjustments.
UI Enhancements:
* [`web/screens/Hub/ModelList/ModelHeader/index.tsx`](diffhunk://#diff-c12507244d72ba8a5e975aa7ed41cdc8d996e3030a5248237aa84dd5f9da02a4L86-R86): Updated the `Dropdown` component to include additional styles for better appearance and usability, such as `max-h`, `max-w`, `overflow-y`, and border properties.
Conditional Rendering:
* [`web/screens/Hub/ModelPage/index.tsx`](diffhunk://#diff-02e81029a62de211929358113c60a101efd0bd0f7ce9b2237fa4 …

chore: Hub UI and markdown CSS

---

web/containers/Providers/ModelHandler.tsx
web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx

This pull request includes several updates to the `ModelHandler` component and related files to improve the handling and display of token speed. The most important changes include adding the `useAtom` hook, updating references to token speed, and ensuring token speed is correctly displayed in the UI.
Token usages will be stored in the metadata of messages from now on. There'll be another update to persist token usage from cortex.cpp chat/completion.
- Closes #2750
Improvements to token speed handling:
* [`web/containers/Providers/ModelHandler.tsx`](diffhunk://#diff-c52744b512485151ef69f9c9e8b58535cc47dc550c4caf152cb52ec103ea898dL21-R21): Added `useAtom` from `jotai` to manage the token speed state and updated references to use this hook. …

feat: preserve token speed in the thread

---

extensions/engine-management-extension/models/cohere.json

This pull request includes changes to the `extensions/engine-management-extension/models/cohere.json` file to update the streaming configuration.
Configuration updates:
* [`extensions/engine-management-extension/models/cohere.json`](diffhunk://#diff-0f356207d41156712777d654492953c89a59617bac89b8266507652492e395efL12-R12): Changed the `stream` parameter from `false` to `true` to enable streaming. [[1]](diffhunk://#diff-0f356207d41156712777d654492953c89a59617bac89b8266507652492e395efL12-R12) [[2]](diffhunk://#diff-0f356207d41156712777d654492953c89a59617bac89b8266507652492e395efL26-R26)
- Closes #4682

chore: streaming should be turned on by default

---

web/screens/Settings/MyModels/MyModelList/index.tsx

This pull request includes changes to the `MyModelList` component in the `web/screens/Settings/MyModels/MyModelList/index.tsx` file to enhance the user interface behavior by considering the loading state of the model.
There are two issues with the current app regarding this action:
1. Race condition when starting model if users interact with the button too fast
2. Starting button is not gated properly, it's disabled but still clickable
- Closes #4673 
Improvements to user interface behavior:
* Updated the conditional class assignment to disable the cursor and reduce opacity when either `serverEnabled` or `stateModel.loading` is true.
* Modified the `onClick` handler to prevent action when either `serverEnabled` or `stateModel.loading` is true.
* Adjusted the `disabled` attribute to …

fix: should disable start model button when there is a model is loading

---

.github/workflows/jan-electron-build-beta.yml
.github/workflows/jan-electron-build-nightly.yml
.github/workflows/template-build-linux-x64.yml
.github/workflows/template-build-macos.yml
.github/workflows/template-build-windows-x64.yml

This pull request includes significant changes to the GitHub Actions workflows for building the Electron app. The main focus of the changes is to streamline the build process by consolidating the icon replacement steps and adding support for nightly builds.
Changes to streamline the build process:
* [`.github/workflows/jan-electron-build-beta.yml`](diffhunk://#diff-3eda9251187aa95e51016c05c5813e16d13e53225833d5bf4ae19b196e9ad8e0L12-R15): Removed the `rename-icons-beta` job and adjusted dependencies for `build-macos`, `build-windows-x64`, and `build-linux-x64` jobs to no longer depend on `rename-icons-beta`. [[1]](diffhunk://#diff-3eda9251187aa95e51016c05c5813e16d13e53225833d5bf4ae19b196e9ad8e0L12-R15) [[2]](diffhunk://#diff-3eda9251187aa95e51016c05c5813e16d13e53225833d5bf4ae19b196e9ad8e0L4 …

chore: change app logo for build nightly

---

web/screens/Hub/index.tsx
web/screens/LocalServer/LocalServerCenterPanel/index.tsx

This pull request includes changes to the layout and styling of the `HubScreen` component in the `web/screens/Hub/index.tsx` file. The most important changes involve adjustments to the filters section and the model list section.
Layout and styling adjustments:
* Modified the filters section to have a width of `200px`, added a right margin of `6px`, and made it sticky with a top offset of `10px`.
* Added a left border to the model list section with `md:border-l` and adjusted the border color using `border-[hsla(var(--app-border))]`.

chore: sticky model hub filter panel

---

web/screens/Hub/index.tsx

This pull request includes changes to the `HubScreen` component in the `web/screens/Hub/index.tsx` file to optimize the sorting and filtering logic for models. The key changes involve reordering the sorting and filtering operations to improve performance and code clarity.
Key updates:
- Fixed the issue where sorting before filtering had no effect.
Optimizations to sorting and filtering logic:
* Moved the sorting logic to occur after the filtering logic by relocating the `sortedModels` `useMemo` hook to follow the `filteredModels` `useMemo` hook. This ensures that only the filtered models are sorted, reducing the number of items that need to be sorted.
* Updated the `filteredModels` `useMemo` hook to directly filter the `sources` array, and adjusted its dependencies to reflect this change. …

chore: fix model hub sorting

---

extensions/yarn.lock
joi/src/core/ScrollArea/styles.scss
web/containers/Layout/index.tsx
web/containers/LeftPanelContainer/index.tsx
web/containers/ListContainer/index.tsx
web/containers/ModelDropdown/index.tsx
web/containers/RightPanelContainer/index.tsx
web/containers/ServerLogs/index.tsx
web/helpers/atoms/Setting.atom.ts
web/screens/Hub/ModelPage/index.tsx
web/screens/Hub/index.tsx
web/screens/Settings/Advanced/ProxySettings/index.tsx
web/screens/Settings/Advanced/index.tsx
web/screens/Settings/Appearance/index.tsx
web/screens/Settings/CoreExtensions/index.tsx
web/screens/Settings/Engines/LocalEngineSettings.tsx
web/screens/Settings/Engines/RemoteEngineSettings.tsx
web/screens/Settings/Engines/index.tsx
web/screens/Settings/Hardware/index.tsx
web/screens/Settings/Hotkeys/index.tsx
web/screens/Settings/MyModels/index.tsx
web/screens/Settings/Privacy/index.tsx
web/screens/Thread/ThreadCenterPanel/ChatBody/OnDeviceStarterScreen/index.tsx
web/styles/base/global.scss

This pull request introduces a new feature to control the visibility of scrollbars throughout the application. It includes the addition of a `showScrollBarAtom` state and updates several components to use this state to conditionally display scrollbars. The most important changes are summarized below:
* [`web/helpers/atoms/Setting.atom.ts`](diffhunk://#diff-fe970dc673b247de554e793d3e1a453f1456278107ae53a390229595621c4384R49-R54): Introduced the `showScrollBarAtom` to manage the scrollbar visibility state.
* [`web/containers/Layout/index.tsx`](diffhunk://#diff-14ae8afe09456109846de9e991341105e0d570a68d771860be34c3626c438f59R45): Added `showScrollBarAtom` and updated the layout to conditionally apply a CSS class for showing scrollbars. …

enhancement: scrollbar setting options

---

electron/handlers/update.ts
electron/utils/menu.ts

This pull request includes changes to the `electron` module, specifically focusing on handling app updates and user notifications. The most important changes include the removal of an event listener for updates not being available and the modification of the menu update check to notify the main window instead of showing a dialog box.
* Removed the event listener for `update-not-available` in `handleAppUpdates` function, which previously sent a message to the main window when no updates were available. (`electron/handlers/update.ts`)
* Modified the menu update check to send a message to the main window when no updates are available, replacing the previous behavior of showing a message box. (`electron/utils/menu.ts`)
- Closes #1471 
- Closes #

fix: flow app updater manual check from native menu

---

web/containers/ModelDownloadButton/index.tsx
web/screens/Hub/ModelList/ModelHeader/index.tsx
web/screens/Hub/ModelPage/index.tsx
web/screens/Hub/index.tsx
web/screens/Thread/ThreadCenterPanel/TextMessage/MarkdownTextMessage.tsx
web/styles/components/code-block.scss
web/styles/components/marked.scss
web/styles/components/message.scss

This pull request includes several changes to improve the styling and functionality of the `ModelDownloadButton`, `ModelHeader`, `ModelPage`, and `HubScreen` components. The most important changes include the addition of the `twMerge` utility for merging Tailwind CSS classes, the introduction of the `className` prop in `ModelDownloadButton`, and updates to the `ModelPage` component to include a new `ModelLabel` component.
Styling improvements:
* [`web/containers/ModelDownloadButton/index.tsx`](diffhunk://#diff-cb17fb15f4023177e3e5c8ade2c6f9f289a7ad0d48398b025c8a83ef41c25b58R6-R7): Added `twMerge` utility for merging Tailwind CSS classes and introduced the `className` prop in `ModelDownloadButton` to allow custom styling. [[1]](diffhunk://#diff-cb17fb15f4023177e3e5c8ade2c6f9f289a7ad0d48398b …

chore: update hub UI 

---

docs/src/pages/docs/troubleshooting.mdx

- Update Jan doc to reflect the corresponding channel to ask for help

chore: correct channel name to ask for help

---

web/screens/Hub/ModelList/index.tsx
web/screens/Hub/index.tsx

This pull request includes changes to add a "No results found" message when there are no models to display in the Hub screens. The most important changes include adding a `filterOption` prop to `ModelList` and updating the `HubScreen` to handle cases where no models are found.
Changes to handle "No results found" message:
* [`web/screens/Hub/ModelList/index.tsx`](diffhunk://#diff-e9ff40c6dc139ce515749a2557984b01897bf63c652838149612849151c1f4a3R8-R30): Added `filterOption` prop to `ModelList` and updated the component to display a "No results found" message when there are no models and the filter option is 'on-device'.
Updates to `HubScreen`:
* [`web/screens/Hub/index.tsx`](diffhunk://#diff-4acda36130f9ceb893281d73ffa88c92378b2a79c7b9a6c1b0704300cb2dd5d1L407-R417): Updated the visibility …

fix: hub ui no result search found

---

electron/main.ts

This pull request includes a small change to the `electron/main.ts` file. The change reorders the `handleAppUpdates` function call to occur after the `createMainWindow` function call.
* [`electron/main.ts`](diffhunk://#diff-13ee644059574b054a4e5ec081666a03579b28da03a50331215908f8d0ef7cfdL88-R90): Moved `handleAppUpdates` to occur after `createMainWindow` in the promise chain.
- Closes #
- Closes #

fix: app check available update

---

web/screens/Hub/index.tsx
web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx
web/styles/components/marked.scss

This pull request includes a small change to the `web/styles/components/marked.scss` file. The change adds specific styles for ordered and unordered lists within the `.markdown-content` class.
Styling changes:
* [`web/styles/components/marked.scss`](diffhunk://#diff-1b1f53e7a74b33e06c05954c28edd796aaa6576156a27e4e154d70e4c2bf2651R93-R108): Added padding and list-style specifications for `ol` and `ul` elements, and adjusted `li` line-height within the `.markdown-content` class.
- Closes #
- Closes #

chore: handle list number and disc readme hgf

---

electron/main.ts
electron/managers/quickAskWindowConfig.ts
electron/managers/window.ts
electron/preload.quickask.ts
web/app/layout.tsx
web/app/search/UserInput.tsx
web/app/search/layout.tsx
web/app/search/page.tsx
web/containers/ModelDropdown/index.tsx
web/containers/Providers/QuickAskConfigurator.tsx
web/containers/Providers/index.tsx
web/hooks/useApp.ts
web/hooks/useModelSource.ts
web/screens/Settings/Advanced/DataFolder/index.tsx
web/screens/Settings/Advanced/index.tsx
web/screens/Settings/CoreExtensions/index.tsx
web/styles/base/global.scss

This pull request includes several changes to enhance the Quick Ask feature, improve configuration handling, and clean up the codebase. The most important changes include the addition of a new preload script for Quick Ask, updates to the window configuration, and the introduction of a new hook for application relaunch.
Key  updates:
- Fixed cortex.cpp dangling process issue on app relaunch to apply some of the configurations.
- Quick App window does not responds to mouse capture (input and send button)
- Quick App window is not movable.
- Quick App window executes redundant operations on launch.
- App craches due to missing model tags in metadata
- Closes #4674 
- Closes #4206
Enhancements to Quick Ask feature:
* [`electron/main.ts`](diffhunk://#diff-13ee644059574b054a4e5ec081666a03579b28d …

fix: Jan Quick Ask window capture input issues

---

web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx
web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx

This pull request includes changes to the `web/screens/Thread/ThreadCenterPanel` directory to improve the user interface and enhance the chat experience. The most important changes include adding a new class for margin-top styling in `ChatBody` and modifying the `MessageContainer` component to handle the current message state more effectively.
User Interface Improvements:
* [`web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx`](diffhunk://#diff-3f5d1c0b7af75f2f221b9504d3f50f0cb42b683d7eb7b565caf7ced16b2c765fR170): Added a new class `first:mt-4` to provide margin-top styling for the first element in the chat body.
Enhancements to Message Handling:
* [`web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx`](diffhunk://#diff-efce7749ad34c34cc3f189aea671b9975208995580033b9de787c3c96c …

fix: first message padding is off

---

extensions/engine-management-extension/models/anthropic.json
extensions/engine-management-extension/models/openai.json

- Added new models:
- OpenAI chatGPT-4.5-preview
- Anthropic Claude-3.7-sonnet

feat: add openai 4.5 preview and anthropic claude 3.7 sonnet models

---

web/hooks/useEngineManagement.ts
web/screens/Hub/ModelPage/RemoteModelRefresh.tsx
web/screens/Hub/ModelPage/index.tsx
web/screens/Hub/index.tsx
web/screens/Settings/Engines/RemoteEngineSettings.tsx

This pull request includes changes to improve the consistency and clarity of the codebase by standardizing the naming of the `engine` parameter across multiple files. The most important changes include updating the `useRefreshModelList` hook, modifying the `RemoteModelRefresh` component, and adjusting the `RemoteEngineSettings` component.
Standardization of `engine` parameter:
* [`web/hooks/useEngineManagement.ts`](diffhunk://#diff-2be7333c9d57e11689071fc1bf5aa7eaf12b907ebc5236ed5abbdb53b031201aL480-R481): Updated the `useRefreshModelList` hook to include `engine` as a parameter in the `refreshModels` function. [[1]](diffhunk://#diff-2be7333c9d57e11689071fc1bf5aa7eaf12b907ebc5236ed5abbdb53b031201aL480-R481) [[2]](diffhunk://#diff-2be7333c9d57e11689071fc1bf5aa7eaf12b907ebc5236ed5abbdb53b031 …

fix: image upload button does not work - refresh models list persist current selected engine

---

web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx
web/styles/components/marked.scss

This pull request includes changes to the `web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx` and `web/styles/components/marked.scss` files to improve the user interface and styling of the message components. The most important changes include conditionally rendering the `MessageToolbar` component and updating the list styles in the markdown content.
Improvements to message components:
* [`web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx`](diffhunk://#diff-efce7749ad34c34cc3f189aea671b9975208995580033b9de787c3c96c878cccL136-R136): Conditionally render the `MessageToolbar` component only when the message is not being edited.
Styling updates:
* [`web/styles/components/marked.scss`](diffhunk://#diff-1b1f53e7a74b33e06c05954c28edd796aaa6576156a27e4e154d70e4c2bf2651R97-L107): …

fix: list space styled and hidden message toolbar when editmode

---

extensions/inference-cortex-extension/src/index.ts
extensions/model-extension/src/index.ts

This pull request includes several changes to the `extensions/inference-cortex-extension` and `extensions/model-extension` modules. The most important changes involve removing legacy support for certain model settings and improving the handling of model file paths.
* [`extensions/inference-cortex-extension/src/index.ts`](diffhunk://#diff-c7af858b5ac4edfb9d2aa937583d964a47e3d135c9f42dd1e858f19b0a59b86eL150-L179): Removed legacy chat model and clip vision model support by eliminating the conditional logic that handled `llama_model_path` and `mmproj` settings. These settings are now handled entirely by Cortex.
* [`extensions/inference-cortex-extension/src/index.ts`](diffhunk://#diff-c7af858b5ac4edfb9d2aa937583d964a47e3d135c9f42dd1e858f19b0a59b86eL337-L355): Deleted the `getModelFilePath` …

refactor: clean up legacy vision model settings

---

web/screens/Thread/ThreadCenterPanel/TextMessage/ImageMessage.tsx
web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx

This pull request includes changes to improve the layout and behavior of image messages in the thread center panel of the web application. The most important changes are:
Layout adjustments:
* [`web/screens/Thread/ThreadCenterPanel/TextMessage/ImageMessage.tsx`](diffhunk://#diff-ad16689fb40e6158413a43ebf918322e8b6e55f9f456d22b00a6c4f7a0ce92cdL7-R7): Added a top margin to the image message container for better spacing.
Behavior improvements:
* [`web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx`](diffhunk://#diff-efce7749ad34c34cc3f189aea671b9975208995580033b9de787c3c96c878cccL114-R117): Modified the `MessageContainer` class to adjust the positioning and z-index of the message container when hovered, ensuring it is displayed correctly over other elements. Additionally, added …

fix: image preview overlap toolbar message

---

extensions/engine-management-extension/src/node/index.ts

This pull request includes updates to the `symlinkEngines` function in the `extensions/engine-management-extension/src/node/index.ts` file to handle AppImage environments more effectively. The changes introduce the use of the `cp` function for copying files instead of creating symlinks in AppImage environments, and add checks to skip existing targets.
Key changes include:
* Added `cp` and `existsSync` imports from `fs/promises` and `fs` respectively.
* Introduced a check for the AppImage environment using `process.env.APPIMAGE`.
* Implemented logic to skip the creation of symlinks if the target already exists.
* Added functionality to copy files instead of creating symlinks when running in an AppImage environment.

fix: app image - could not load model

---

web/screens/Hub/ModelList/ModelItem/index.tsx
web/utils/modelSource.ts

This pull request introduces enhancements to the `ModelItem` component and the `extractDescription` utility function. The changes involve adding a new plugin for Markdown rendering and improving the text extraction logic by removing image tags.
Enhancements to the `ModelItem` component:
* [`web/screens/Hub/ModelList/ModelItem/index.tsx`](diffhunk://#diff-cb3e07a310eb449312da3731e3667aa9d92c0df386d0796454f4f2675b98e232R8): Added the `rehype-raw` plugin to the Markdown component to allow raw HTML rendering. [[1]](diffhunk://#diff-cb3e07a310eb449312da3731e3667aa9d92c0df386d0796454f4f2675b98e232R8) [[2]](diffhunk://#diff-cb3e07a310eb449312da3731e3667aa9d92c0df386d0796454f4f2675b98e232R40)
Improvements to the `extractDescription` utility function:
* …

fix: hub model list desc render

---

web/containers/ModelDropdown/index.tsx

This pull request includes changes to the `ModelDropdown` component in the `web/containers/ModelDropdown/index.tsx` file to enhance its functionality and user interface. The most important changes are:
* Added `CheckIcon` import to the list of icons used in the component.
* Included a conditional rendering of the `CheckIcon` next to the selected model to visually indicate the currently selected model.
- Closes #4635 
- Closes #

enhancement: add checkmark selected model

---

extensions/engine-management-extension/src/node/index.ts

This pull request includes changes to the `symlinkEngines` function in the `extensions/engine-management-extension/src/node/index.ts` file. The changes improve the handling of standalone Linux environments by updating the condition checks and related logic.
Improvements to Linux environment handling:
* Changed the `isAppImage` variable to `isStandalone` to better reflect its purpose, checking if the platform is Linux.
* Updated the condition to use `isStandalone` instead of `isAppImage` for copying files in standalone environments.

chore: do not symlink engine on linux

---

docs/src/components/FooterMenu/index.tsx
docs/src/pages/about/team.mdx
docs/src/pages/docs/index.mdx

This pull request includes updates to the URLs for the Careers page across multiple files to reflect the new BambooHR link.
Changes to URLs for the Careers page:
* [`docs/src/components/FooterMenu/index.tsx`](diffhunk://#diff-e58b1b4f7af1e40a58d249fe32e4577e3dffb8b745d83782293d336afcb90b9fL98-R98): Updated the `path` for the 'Careers' menu item to `https://menlo.bamboohr.com/careers`.
* [`docs/src/pages/about/team.mdx`](diffhunk://#diff-bd822ebdf9bd6a0eca34e493d50136e5846eedfd6f8ff143d42b79dd92c28dbdL23-R23): Updated the Careers page link in the text to `https://menlo.bamboohr.com/careers`.
* [`docs/src/pages/docs/index.mdx`](diffhunk://#diff-d257e59fb0044ee1c82adfc6eeafb2054095eaa05670d6d07b97b80fadcf9db6L161-R161): Updated the Careers page link in the FAQ section to …

fix: update career url

---

web/containers/Providers/DataLoader.tsx

This pull request includes changes to the `web/containers/Providers/DataLoader.tsx` file to incorporate hardware information loading functionality. The most important changes include importing the `useGetHardwareInfo` hook, adding a new `mutate` function for hardware information, and calling this function within a `useEffect` hook to load hardware information once the component is mounted.
Improvements to data loading:
* [`web/containers/Providers/DataLoader.tsx`](diffhunk://#diff-b3a10000ff3b8316a1062f61e4286a582ea6d78628f749d3df61204553101797R18): Imported `useGetHardwareInfo` from `useHardwareManagement` to enable hardware information retrieval.
* [`web/containers/Providers/DataLoader.tsx`](diffhunk://#diff-b3a10000ff3b8316a1062f61e4286a582ea6d78628f749d3df61204553101797R38): Added …

chore: should get hardware information on launch

---

extensions/hardware-management-extension/src/index.ts
extensions/model-extension/src/index.ts
web/containers/Providers/DataLoader.tsx
web/hooks/useHardwareManagement.ts

This pull request includes several changes to the `extensions/hardware-management-extension` and `extensions/model-extension` codebases, as well as some updates to the `web` module. The most important changes involve refactoring the API instance handling in the `JSONHardwareManagementExtension` class, adding timeout configurations to API requests in the `JanModelExtension` class, and modifying the `useGetHardwareInfo` hook to support conditional periodic updates.
Refactoring API instance handling:
* [`extensions/hardware-management-extension/src/index.ts`](diffhunk://#diff-62746e863ccfaef934a7929aa607a6ba7dd5bc8b2a8eb8d7655ad4134b0fa93bL12-L29): Refactored the `JSONHardwareManagementExtension` class to replace direct API access with an `apiInstance` method, ensuring API instances are …

chore: should have an option to not revalidate hardware information

---

extensions/conversational-extension/src/index.ts
extensions/engine-management-extension/src/index.ts
extensions/hardware-management-extension/src/index.ts
extensions/inference-cortex-extension/src/index.ts
extensions/model-extension/src/index.ts
web/screens/Settings/Hardware/index.tsx

This PR addresses a race condition issue in cortex.cpp, which occurs when the user terminates the process while activating the GPU using the /hardware API. For now, Jan will refrain from restarting the process to avoid the issue, but there will be an enhancement to cortex.cpp soon.
This pull request introduces significant changes to the API management in multiple extensions by refactoring the way API instances are handled. The changes primarily focus on improving the handling of API instances through the introduction of an `apiInstance` method, which ensures that the API instance is created only once and reused thereafter.
* [`extensions/conversational-extension/src/index.ts`](diffhunk://#diff-8556eacb45b5ef692a9d500744d6cacad5f2660bc457a83281b79eb9cb3751cbR25-R44): Introduced the …

chore: cortex.cpp gpu activation could cause a race condition

---

src-tauri/Cargo.toml
src-tauri/src/core/cmd.rs
src-tauri/src/core/fs.rs
src-tauri/src/core/mcp.rs
src-tauri/src/core/mod.rs
src-tauri/src/core/server.rs
src-tauri/src/core/setup.rs
src-tauri/src/core/state.rs
src-tauri/src/lib.rs
web/containers/Providers/CoreConfigurator.tsx
web/services/tauriService.ts

This PR introduces MCP Host functionality to Jan, enabling users to utilize any existing mcp_config.json that is compatible with other MCP Hosts, such as Claude Desktop.
There will be another PR to update the Jan Chat UI to display the steps involved in using the tool. For now, this PR is to expose all the necessary APIs to the frontend, so that it can use these as parameters for OpenAI's tool use.
- Implemented MCP Host support in Jan.
- Ensured compatibility with mcp_config.json to allow seamless integration with various MCP Servers.
- Added connection handling for multiple MCP Servers.
- Improved request routing between Jan (as an MCP Host) and configured MCP Servers.
This enhancement allows Jan to function as a flexible MCP Host, making it interoperable with existing MCP-compatible …

feat: Jan - MCP Client Host

---

src-tauri/capabilities/default.json
src-tauri/tauri.conf.json
web/containers/Layout/TopPanel/index.tsx

This pull request includes several changes to improve the functionality and appearance of the application. The most important changes include updating permissions, modifying window dimensions, and enhancing the drag region for better user interaction.
* [`src-tauri/capabilities/default.json`](diffhunk://#diff-8fe2bbfebcddedcaa718510825d2a4bd04f59d2826a6848ea55fa086c5bb4213R11): Added the permission `core:window:allow-start-dragging` to the capabilities.
* [`src-tauri/tauri.conf.json`](diffhunk://#diff-fa09f1dac39604a735cd6a53957d3c35e0c3298cca9cf4829180f167abbd69b7L17-R18): Changed the default window dimensions from 1000x700 to 1024x768.
* [`web/containers/Layout/TopPanel/index.tsx`](diffhunk://#diff-144fb1f3592881414cfc6860d959d7b0fb1ffc1a4f427f005a9da3e61523ccd7R73-R79): Added …

chore: allow draggable window app

---

src-tauri/tauri.conf.json

This pull request includes a change to the `src-tauri/tauri.conf.json` file to enhance the window effects configuration. The most important change is the addition of new window effects options.
Enhancements to window effects configuration:
* [`src-tauri/tauri.conf.json`](diffhunk://#diff-fa09f1dac39604a735cd6a53957d3c35e0c3298cca9cf4829180f167abbd69b7L23-R27): Added the `windowEffects` property with options for `fullScreenUI`, `mica`, `blur`, and `acrylic`, and set the state to `active`.
- Closes #
- Closes #

chore: enable window effect blur

---

web/containers/ModelSearch/index.tsx

This pull request includes a small change to the `ModelSearch` component in the `web/containers/ModelSearch/index.tsx` file. The change involves modifying the class name of an element to remove the `border-0` class, simplifying the styling.
* [`web/containers/ModelSearch/index.tsx`](diffhunk://#diff-246b4b85fb7409a40822b732441e9c9aa329d2f950ce0d87b882e98887bf75f2L86-R86): Removed the `border-0` class from the element's className property to simplify the styling.
- Added border for the search text field

fix: added border for search textfield

---

core/src/types/inference/inferenceEntity.ts
core/src/types/message/messageEntity.ts
web/containers/Providers/ModelHandler.tsx
web/helpers/atoms/ChatMessage.atom.ts
web/hooks/useSendChatMessage.ts
web/screens/Hub/ModelFilter/ModelSize/index.tsx
web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
web/screens/Thread/ThreadCenterPanel/TextMessage/ToolCallBlock.tsx
web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx
web/utils/messageRequestBuilder.ts

This pull request includes significant updates to the chat message handling and tool call processing within the application. The changes enhance the functionality and simplify the codebase by adding new properties, improving message handling, and introducing a new UI component for tool call results.
- Add new ToolCallMessage type.
- Message's metadata now has tool_calls persisted (pending moving threads to Jan - cortex.cpp could not save metadata with key - object type).
- Using OpenAI client sdk to parse response from cortex.cpp for now (soon move back to Jan with model proviers as extensions)
#4862
* [`core/src/types/inference/inferenceEntity.ts`](diffhunk://#diff-c3667eaa51fed6cc102a698812611ed0518c93e79623b0416cb0e9e6c84b8a59R10): Added `Tool` to `ChatCompletionRole` enum and new …

feat: jan UI with Tool use UX

---

src-tauri/src/core/threads.rs
web/containers/ModelDropdown/index.tsx
web/hooks/useCreateNewThread.ts
web/hooks/useUpdateModelParameters.ts

This pull request includes several updates to improve thread and assistant management in both backend and frontend code. The changes focus on enhancing assistant identification, updating model parameters, and refining assistant tools. Below is a summary of the most important changes:
* **Assistant Identification Update**: Modified the key used to identify assistants in the `modify_thread_assistant` function from `"id"` to `"assistant_id"` for better clarity and consistency (`src-tauri/src/core/threads.rs`).
* **Assistant Tools Management**:
- Removed outdated logic for updating assistant tools in the `ModelDropdown` component, simplifying the code (`web/containers/ModelDropdown/index.tsx`).
- Added support for updating assistant tools when model parameters are updated, ensuring proper …

fix: clean up threads persistence and fix assistant update issue

---

web/containers/Providers/ModelHandler.tsx
web/hooks/useCreateNewThread.ts
web/hooks/useDeleteThread.ts

This pull request fixed an issue where remote model threads do not have title set properly. Since this PR, there's no thread creation gate because users would want to create multiple threads (with different prompts) beforehand.
The refactoring of the `ModelHandler` component in `web/containers/Providers/ModelHandler.tsx` aims to clean up unused imports and streamline its logic.
* Removed unused imports such as `ModelExtension`, `useGetEngines`, and `isLocalEngine` from `@janhq/core` and other modules. This helps declutter the file and ensures only necessary dependencies are included.
* Removed the `deleteMessageAtom` and its associated `useSetAtom` call, as it was not being used in the component.
* Removed the `useGetEngines` hook and its destructured `engines` property, as it was not …

fix: thread title does not set on remote models

---

web/screens/Settings/MCP/configuration.tsx

This pull request introduces enhancements to the `MCPConfiguration` component in the `web/screens/Settings/MCP/configuration.tsx` file. The changes focus on improving the user experience when editing configuration files, particularly by sanitizing input and maintaining cursor position during updates.
* **Added `useRef` for TextArea reference**: Introduced a `textAreaRef` using `useRef` to manage the cursor position during updates. (`[[1]](diffhunk://#diff-32acd7247a078095f811607a2902c02bc7070611281ad58c813cb49e1813c322L1-R1)`, `[[2]](diffhunk://#diff-32acd7247a078095f811607a2902c02bc7070611281ad58c813cb49e1813c322R15-R16)`)
* **Sanitized quotes in input**: Implemented logic to replace curly quotes (`“”` and `‘’`) with straight quotes (`"` and `'`) to ensure consistent formatting of the …

fix: prevent curly quotes from MCP config

---

web/containers/ToolCallApprovalModal/index.tsx
web/helpers/atoms/Thread.atom.ts
web/hooks/useSendChatMessage.ts
web/screens/Thread/ThreadCenterPanel/ChatInput/RichTextEditor.tsx
web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
web/screens/Thread/ThreadCenterPanel/EditChatInput/index.tsx
web/screens/Thread/ThreadCenterPanel/MessageToolbar/index.tsx
web/screens/Thread/ThreadCenterPanel/index.tsx

This pull request introduces a tool call approval modal, enhancing user control over tool usage in chat threads. It includes the creation of a modal component to approve or deny tool calls, integration of this modal into various parts of the application, and the introduction of a new atom to track approved tools.
https://github.com/user-attachments/assets/af75ff39-7a33-4553-ac6b-0a6bd4f53993
* **Modal Component**: Added `useTollCallPromiseModal` in `web/containers/ToolCallApprovalModal/index.tsx` to create a reusable modal for approving or denying tool calls. The modal supports both one-time and thread-specific approvals.
* **New Atom**: Introduced `approvedThreadToolsAtom` in `web/helpers/atoms/Thread.atom.ts` to store thread-specific tool approvals.
* **Chat Message Handling**: Updated …

feat: permission dialog for tool call requests

---

.github/workflows/auto-label-conventional-commits.yaml

This pull request introduces a small but significant change to the `.github/workflows/auto-label-conventional-commits.yaml` file. The change adds a conditional statement to ensure that the workflow only runs when the pull request originates from the same repository.
* [`.github/workflows/auto-label-conventional-commits.yaml`](diffhunk://#diff-a394f880f50eb3772ae5a74c2a03140168abffbc204db8945f133da68d312784R9): Added an `if` condition to the `label_prs` job to check that `github.event.pull_request.head.repo.full_name` matches `github.repository`.

ci(workflow): add condition pr labelling job for forked repo

---

web/containers/ToolCallApprovalModal/index.tsx
web/helpers/atoms/Thread.atom.ts
web/hooks/useSendChatMessage.ts
web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx

This PR introduces the ability to enable or disable individual tools within the MCP tools list. Users can now toggle tool availability through the updated interface, allowing for more flexible and customizable workflows.
https://github.com/user-attachments/assets/c6ab577c-d38f-4328-8726-c4b2aa91a03b
- Added support for tracking tool state (enabled/disabled)
- Updated MCP tools list UI to reflect tool states
- Implemented logic to persist and respect tool states across sessions

feat: allow users to enable and disable tools

---

web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx
web/screens/Thread/ThreadCenterPanel/ChatItem/index.tsx
web/screens/Thread/ThreadCenterPanel/TextMessage/ToolCallBlock.tsx
web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx

Improved the UI by wrapping the tool call block in a collapsible container with scroll support. This keeps the interface clean and more manageable, especially when tool calls produce long or verbose outputs.
This also fixes the glitchy issue when users hover over the bottommost message.
https://github.com/user-attachments/assets/2e495823-05ab-4f68-8eb5-8f8cb078d5cd
No UI glitch issue when reaching the bottommost message
https://github.com/user-attachments/assets/a10b2d72-f4f2-4713-8619-5c53bb183ef4
Simplify assistant display name until the new UI/UX arrived.
- Cleaner UI for large tool call outputs
- Easier navigation and focus on relevant content
- Optional visibility via collapsible section

enhancement: tool call block should be wrapped in a collapsible scroll area

---

web/screens/Settings/MCP/search.tsx

This PR adds caching for MCP server search results during the initial page load to eliminate the blank state for first-time users. Previously, users visiting the page for the first time would experience a brief blank screen while search results were fetched from the server. With this update, initial data is fetched and cached early in the lifecycle, allowing the UI to render meaningful content immediately.
https://github.com/user-attachments/assets/2d6d2b30-584a-47b5-adfe-3dba109b7436
- Closes #
- Closes #

enhancement: cache MCP Server search results to enhance UX

---

docs/src/pages/about/index.mdx
docs/src/pages/about/team.mdx

This pull request makes updates to the "About" section of the documentation, focusing on improving clarity and simplifying team member information. The most important changes include updating project management and roadmap links, and replacing individual team member cards with a link to the Menlo handbook.
* **Updated project management and roadmap links**: The links to the public project management and roadmap views were updated to reflect the correct URLs for better accessibility. (`docs/src/pages/about/index.mdx`)
* **Simplified team member section**: Removed individual team member and board member cards and replaced them with a single link to the Menlo handbook, which provides comprehensive team information. (`docs/src/pages/about/team.mdx`)

chore: fix jan about doc

---

.github/workflows/jan-docs-new-release.yaml
.github/workflows/jan-docs.yml
docs/_headers

This pull request includes updates to the documentation build process and introduces a new `_headers` file to enhance security configurations for the deployed website. The key changes involve modifying the GitHub Actions workflows to include the `_headers` file during the build process and adding security-related headers.
* [`.github/workflows/jan-docs-new-release.yaml`](diffhunk://#diff-78078ebad586cc9fb54bc959e437dc3411e688a9bc8fdcc5faebac85d9b2ad62L52-R52): Updated the `Build website` step to copy the `_headers` file into the `out` directory during the build process.
* [`.github/workflows/jan-docs.yml`](diffhunk://#diff-307479c4bef1f0bb90238fcfe3f7df26d8a15312aab6233edf9e1c43fd3fa5a4L58-R58): Updated the `Build website` step to copy the `_headers` file into the `out` directory during …

chore: fix headers

---

scripts/download-bin.js
src-tauri/tauri.conf.json

MacOS code sign will be updated in another PR because the Tauri CI/CD PR is not merged yet
Still have some issue with `appimage` build that it can not bundle `bun`
This pull request introduces platform-specific improvements and error handling in the `scripts/download-bin.js` script, along with updates to the Tauri configuration file to include new binaries. The changes enhance compatibility across operating systems, improve error resilience, and ensure proper handling of platform-specific binaries.
* Updated `getPlatformArch` function to refine platform and architecture mappings for Linux and Windows, ensuring accurate binary selection (`scripts/download-bin.js`).
* Added platform-specific logic for handling `.zip` and `.tar.gz` files, ensuring compatibility with Windows …

chore: pull binaries windows, linux

---

.gitignore
package.json
scripts/download-bin.js
src-tauri/Cargo.toml
src-tauri/src/core/mcp.rs
src-tauri/tauri.conf.json

This PR aims to bundle MCP command binaries with the app, eliminating the need for users to install them locally.
While building the app, there will be a new step to download bun and uvx binaries into src-tauri/resources/bin folder, where MCP client can use to run commands in runtime.

feat: run mcp with bundled bun and uv

---

extensions/engine-management-extension/rolldown.config.mjs
extensions/inference-cortex-extension/download.bat
extensions/inference-cortex-extension/download.sh
extensions/inference-cortex-extension/rolldown.config.mjs
web/utils/messageRequestBuilder.ts

- This PR is to not include reasoning content in the chat/completions request, this will address the issue where qwen3 0.6b returns weird token outputs where it should not be.
- This also reduce the request payload size (prompt length).
- Ship llama.cpp - b5219 with the app.
https://github.com/user-attachments/assets/27878292-cc07-48e3-a3db-0e7fdb150b5c
- Closes #4955

fix: qwen3 - weird token output  - reasoning content should not be in completion request

---

web/containers/ModelSearch/index.tsx

- This PR fixes the styling issue of My Models search box. Where it should have border and no HF URL text (since model import feature moved to Mod
- Closes #4902

chore: my models search box css issue

---

extensions/engine-management-extension/models/cohere.json
extensions/engine-management-extension/models/deepseek.json
extensions/engine-management-extension/models/google_gemini.json
extensions/engine-management-extension/models/groq.json

This pull request updates the model configurations across several files in the `engine-management-extension` directory. The changes include adding new models, renaming and updating existing models, and removing outdated models. These updates ensure that the configurations reflect the latest versions and capabilities of the models.
* Added a new model, `command-a-03-2025`, to the `cohere.json` file. This model is optimized for complex workflows and multi-step tool use, with a longer context and improved task performance.
* Introduced new models, `gemini-2.5-pro-preview-05-06` and `gemini-2.5-flash-preview-04-17`, in the `google_gemini.json` file. These models offer advanced reasoning and price-performance capabilities, respectively, with experimental/preview status.
* Updated the …

fix: update remote models list

---

web/containers/ModelSearch/index.tsx

This pull request includes a small change to the `ModelSearch` component in `web/containers/ModelSearch/index.tsx`. The `className` property was updated to remove the `border-1` class, simplifying the styling.

fix: border for the search box in my models

---

core/src/browser/extensions/model.ts
extensions/model-extension/src/index.ts
web/containers/ModelSearch/index.tsx
web/hooks/useEngineManagement.ts
web/screens/Hub/index.tsx

- This PR is to distinguish between model search in hub and in my models page where:
- Model Hub should allow users to import models.
- My Models should only allow users to search for downloaded models since there are no detail page implemented in this page.
- Model Hub should be refreshed on mount.
https://github.com/user-attachments/assets/3c72783d-094c-42c8-9ba3-bc3bbbc7c2d5
- Closes #
- Closes #

fix: distinguish between hub and models search

---

web/utils/messageRequestBuilder.ts

From the PR #4983, we normalize completion request to not have reasoning_content in the request body, but somehow users could create thinking input manually which should be kept. This PR is to filter out user messages from the normalization.
https://github.com/user-attachments/assets/bd0607b7-6941-4cf3-b4c6-594377bb65cb

fix: should not normalize user input content

---

.github/workflows/jan-electron-linter-and-test.yml
Makefile
extensions/inference-cortex-extension/src/index.ts
package.json
web-app/package.json
web-app/src/containers/ChatInput.tsx
web-app/src/lib/extension.ts
web-app/src/lib/model.spec.ts

Since #4904, cortex.cpp will now spawn a llama.cpp server for every model start request. This has resulted in an issue where multiple llama.cpp servers could be spawned for the same model. This PR aims to address this issue before the new /chat function is supported by the model provider.
After llama.cpp extension completed. There should be only single function invoked which is `chat`, required model will be loaded automatically then.
So that, this fix will unblock current workstreams on new frontend revamp.

fix: should not spawn many llama.cpp servers for the same model

---

core/src/browser/extensions/engines/EngineManager.ts
core/src/browser/extensions/enginesManagement.ts
core/src/types/engine/index.ts
core/src/types/model/modelEntity.ts
extensions/engine-management-extension/src/index.ts
extensions/inference-cortex-extension/src/index.ts
extensions/model-extension/src/index.ts
extensions/model-extension/src/legacy/model-json.ts
web-app/src/services/providers.ts
web-app/src/services/threads.ts

This is a very bad practice in the past where we hardcoded several provider names for the transition from nitro to cortex.cpp. All of these should be removed to unblock dynamic model providers support. 
From now all, all of the operations should be done using provider name as raw string, registry will manage all of the registered providers using their provider name.

refactor: remove hardcoded provider names

---

web-app/src/containers/ChatInput.tsx
web-app/src/containers/DownloadManegement.tsx
web-app/src/hooks/useDownloadStore.ts
web-app/src/lib/completion.ts
web-app/src/lib/models.ts
web-app/src/providers/ExtensionProvider.tsx
web-app/src/routes/hub.tsx
web-app/src/services/eventsService.ts
web-app/src/services/mcp.ts
web-app/src/services/models.ts

This PR provides the download function for the new frontend model. It forwards requests to model handler extension (the same as current stable version). Later on this will go down to model provider (simple switch).
> The attachment shows pause and cancel functions but for now the pause button will be hidden due to lack of the functionality.

feat: new frontend with model download function

---

web-app/src/containers/ChatInput.tsx
web-app/src/containers/DownloadManegement.tsx
web-app/src/containers/ThreadContent.tsx
web-app/src/hooks/useAppState.ts
web-app/src/hooks/useChat.ts
web-app/src/hooks/useMessages.ts

This PR provides chat functions to the new FE, including the ability to regenerate an assistant's response, refactor completion handlers to a new hook to clean up the ChatInput component, and share chat functions across components.
https://github.com/user-attachments/assets/674358a3-b0d0-40ed-ab3b-4d7fafb0b66e

chore: handle chat functions

---

web-app/src/containers/DownloadManegement.tsx
web-app/src/containers/dialogs/DeleteModel.tsx
web-app/src/hooks/useLocalApiServer.ts
web-app/src/hooks/useModelProvider.ts
web-app/src/routes/settings/local-api-server.tsx
web-app/src/routes/settings/providers/$providerName.tsx
web-app/src/services/models.ts
web-app/src/services/providers.ts

This PR is to handle local model provider to have models list synced with pull and remove requests. Before this PR, when users download or remove any models would not trigger the fetch to update the list accordingly.
This also provide API server start stop functions to the new frontend.

chore: update model handlers on the new frontend

---

src-tauri/Cargo.toml
src-tauri/src/core/mcp.rs

Pin rmcp to latest commit to avoid breaking changes, as well as ensure we use the same version across the team
- `transport-sse` becomes `transport-sse-client`: https://github.com/modelcontextprotocol/rust-sdk/pull/167
- Requires explicit `reqwest` feature: https://github.com/modelcontextprotocol/rust-sdk/pull/185
- Closes #
- Closes #

chore: Pin rmcp commit

---

web-app/src/components/ui/switch.tsx

This pull request includes a minor adjustment to the `Switch` component in `web-app/src/components/ui/switch.tsx`. The change simplifies the translation calculation for the `data-[state=checked]` state of the `SwitchPrimitive.Thumb` element.
* [`web-app/src/components/ui/switch.tsx`](diffhunk://#diff-c52343474e2a1ee7fc46bda8de540434bb7904774d24c590d11357df169167ddL22-R22): Updated the `data-[state=checked]` translation value from `calc(100%-1px)` to `calc(100%)` for improved clarity and maintainability.
https://discord.com/channels/1107178041848909847/1373886186485186621/1373886186485186621
- Closes #
- Closes #

chore: improve switch component offset

---

web-app/src/containers/LeftPanel.tsx

This pull request includes a small change to the `LeftPanel` component in `web-app/src/containers/LeftPanel.tsx`. The change removes an unnecessary bottom margin (`mb-4`) from a `div` wrapping the `ThreadList` component.
https://discord.com/channels/1107178041848909847/1365253683272618025
- Closes #
- Closes #

chore: cleanup whitespace left panel on thread list

---

extensions/inference-cortex-extension/src/index.ts
web-app/src/containers/ChatInput.tsx
web-app/src/containers/StreamingContent.tsx
web-app/src/hooks/useAppState.ts
web-app/src/hooks/useChat.ts
web-app/src/lib/completion.ts
web-app/src/routes/threads/$threadId.tsx

This PR added UI handlers for many features such as
- Stop streaming message
- Scroll down to bottom will not push up at the end of streaming
- Streaming content will not jump to other threads
- Load many models as need (it blocks 2nd load attempt before)
https://github.com/user-attachments/assets/733401a4-917d-4979-9027-2b3efbb76dae

feat: handle stop streaming message, scroll to bottom and model loads

---

core/src/types/thread/threadEntity.ts
src-tauri/src/core/threads.rs
web-app/src/containers/DropdownAssistant.tsx
web-app/src/hooks/useAssistant.ts
web-app/src/hooks/useChat.ts
web-app/src/hooks/useThreads.ts
web-app/src/lib/messages.ts
web-app/src/routes/index.tsx
web-app/src/routes/threads/$threadId.tsx
web-app/src/services/threads.ts
web-app/src/types/threads.d.ts

This pull request introduces functionality to manage and utilize a "current assistant" across various parts of the application. Key changes include updates to the assistant and thread state management, integration of assistant-specific instructions in chat messages, and enhancements to the `CompletionMessagesBuilder` class. 
https://github.com/user-attachments/assets/04e09718-ba29-4270-af0f-f7fb17609a04
Closes #2845 
* Added a `currentAssistant` property and corresponding `setCurrentAssistant` method to the `useAssistant` hook for tracking and updating the currently selected assistant. (`web-app/src/hooks/useAssistant.ts`, [[1]](diffhunk://#diff-31ef10114cb17030e296e4b582d6c4d5f6c1873078a75c4af856450a32f540cdL5-R12) [[2]](diffhunk://#diff-31ef10114cb17030e296e4b582d6c4d5f6c1873078a75c4af85 …

feat: Jan supports multiple assistants

---

web-app/src/lib/model.spec.ts
web-app/src/routes/threads/$threadId.tsx

- Putting messages directly to useEffect could introduce a continuous rerender due to content update. Wrap in usesMemo to reduce the state update loop.

chore: reduce state update to prevent glitchy scroll to bottom

---

web-app/src/constants/localStorage.ts
web-app/src/constants/routes.ts
web-app/src/containers/SettingsMenu.tsx
web-app/src/hooks/useAppearance.ts
web-app/src/hooks/useAssistant.ts
web-app/src/hooks/useCodeblock.ts
web-app/src/hooks/useGeneralSetting.ts
web-app/src/hooks/useHardware.ts
web-app/src/hooks/useLeftPanel.ts
web-app/src/hooks/useLocalApiServer.ts
web-app/src/hooks/useMCPServers.ts
web-app/src/hooks/useMessages.ts
web-app/src/hooks/useModelProvider.ts
web-app/src/hooks/useProxyConfig.ts
web-app/src/hooks/useTheme.ts
web-app/src/hooks/useThreads.ts
web-app/src/i18n.ts
web-app/src/routeTree.gen.ts
web-app/src/routes/settings/hardware.tsx

This pull request introduces a new "Hardware" settings feature to the web application. It includes updates to constants, menus, routes, and the addition of a `useHardware` hook to manage hardware-related data and state. Below is a summary of the most important changes:
* Added a new key, `settingHardware`, to `localStorage` constants to persist hardware settings. (`web-app/src/constants/localStorage.ts`, [web-app/src/constants/localStorage.tsR13](diffhunk://#diff-89c995cbbcdaed6eb5f8a27f5cdb8d2b82dda97d048a7dd77b00649298908acdR13))
* Introduced a new route `/settings/hardware` for the hardware settings page. (`web-app/src/constants/routes.ts`, [web-app/src/constants/routes.tsR16](diffhunk://#diff-85174d9cc0307ab14cb1ad7801566e9347ab57c6976b3c2ad05ad5782a1a670dR16))
* Updated the settings …

chore: add setting hardware

---

web-app/src/containers/ChatInput.tsx
web-app/src/containers/DropdownAssistant.tsx
web-app/src/containers/LeftPanel.tsx
web-app/src/routes/assistant.tsx
web-app/src/routes/threads/$threadId.tsx

This pull request introduces several updates to the `ChatInput` and `DropdownAssistant` components, along with minor adjustments in the `ThreadDetail` route. The changes focus on improving user experience by refining UI behavior, temporarily hiding unused features, and enhancing the loading experience for specific models. Below is a breakdown of the most important changes:
* Removed the unused `IconMicrophone` import and temporarily commented out the microphone feature in the UI. This suggests the feature is being hidden for now but may return in the future. [[1]](diffhunk://#diff-e6927577dd0c5d682ae3ac9367b9a6b7df9f76df4cf35c5a05779e539749f417L13) [[2]](diffhunk://#diff-e6927577dd0c5d682ae3ac9367b9a6b7df9f76df4cf35c5a05779e539749f417R179-R193)
* Introduced conditional rendering for the …

chore: model loading and truncate dropdown assiatant title

---

web-app/src/containers/ChatInput.tsx

This pull request introduces enhancements to the `ChatInput` component in `web-app/src/containers/ChatInput.tsx`, focusing on improving user experience by adding automatic focus behavior and making minor code adjustments for readability.
* Added a new `useEffect` hook to automatically focus the chat input when the component mounts.
* Introduced focus behavior when the `currentThreadId` changes, ensuring the chat input remains contextually relevant.
* Implemented focus restoration with a slight delay after streaming content finishes to improve usability.
* Imported the `useThreads` hook and integrated `currentThreadId` into the `ChatInput` component for thread-specific behavior. [[1]](diffhunk://#diff-e6927577dd0c5d682ae3ac9367b9a6b7df9f76df4cf35c5a05779e539749f417R6) …

chore: fix auto focus chat input

---

src-tauri/src/core/setup.rs
src-tauri/tauri.bundle.windows.nsis.template

This pull request includes updates to the Tauri application setup and the Windows installer configuration. The most important changes involve expanding allowed origins for the sidecar setup and restructuring the installer directories to include new subdirectories for engines, pre-install resources, and themes.
* [`src-tauri/src/core/setup.rs`](diffhunk://#diff-5d6e1079ed2c01af0b0fd41ba3f1189e30abd5666c7a4a08b30957975685b252L222-R222): Expanded the `--allowed_origins` list to include `tauri://localhost` and `http://tauri.localhost`, enabling additional origins for local development and testing.
* `src-tauri/tauri.bundle.windows.nsis.template`: 
- Added a new subdirectory `$INSTDIR\binaries\engines` and updated the `SetOutPath` commands to reflect this change.
- Added new subdirectories …

fix: windows installer and allowed origins

---

web-app/src/routes/settings/providers/$providerName.tsx
web-app/src/services/models.ts

This pull request introduces functionality to import models for the `llama.cpp` provider, along with related UI updates and service enhancements. Key changes include adding an import button in the provider settings, implementing the `importModel` function, and updating the UI logic to handle the new feature.
* **Added `importModel` function**: A new function in `web-app/src/services/models.ts` allows importing models from a file path, with support for optional model IDs and defaulting to the `llama.cpp` provider. It handles file validation, model ID derivation, and integration with the `ExtensionManager`.
* **Conditional "Import" button**: Updated the `ProviderDetail` component in `web-app/src/routes/settings/providers/$providerName.tsx` to display an "Import" button for the `llama.cpp` …

chore: model import from llama.cpp provider

---

web-app/src/containers/ThreadList.tsx
web-app/src/hooks/useThreads.ts
web-app/src/services/threads.ts

Modified the `onDragEnd` handler in `ThreadList.tsx` to use the complete global thread list from the `useThreads` store. This resolves a bug where dragging and dropping threads could lead to items disappearing from "Favorites" or "Recents" sections by ensuring the reordering logic operates on the full dataset.
Additionally, the default `order: 1` initialization for new threads in `useThreads.ts` and `services/threads.ts` has been commented out this make thread sorted by newest to oldest
<div>
<a href="https://www.loom.com/share/60830d0e7e65431c8a205a645c09da1a">
<p>Fix/thread sorted and drag drop - Watch Video</p>
</a>
<a href="https://www.loom.com/share/60830d0e7e65431c8a205a645c09da1a">
</a>
</div>

fix: thread sorted and drag drop

---

web-app/src/hooks/useChat.ts
web-app/src/hooks/useThreads.ts

This PR introduces automatic thread ordering based on activity, ensuring the most recently active threads appear at the top of the thread list.
- **Thread Timestamp Updates**: Automatically update thread timestamps when new messages are added
- Added `updateThreadTimestamp(threadId: string)` function to the ThreadState interface
- Implemented smart ordering logic:
- If thread is already at order 1: only update timestamp
- If thread is not at top: move to order 1 and increment all other threads' order by 1
- Ensures both local state and backend storage are updated
- Maintains search index consistency after reordering
- Integrated `updateThreadTimestamp` calls at key interaction points:
- When user sends a message
- When assistant responds with a message
- Ensures threads stay current based …

fix: thread update after chat

---

.devcontainer/devcontainer.json
.devcontainer/postCreateCommand.sh

The current dev container is far from reproducing the linux build env. The github workflow uses Ubuntu 22.04 as a base, so I chose microsoft's jammy dev container as the base image. Tauri requires node and rust as dev dependencies, and we've opted into yarn + corepak. I've added those features to the dev container accordingly. Tauri also requires some system packages to build, + some implicit dependencies that come preinstalled in the github runner/host systems. In postCreateCommand.sh, I've added tauri's explicit dependencies + xdg-utils for xdg-open (used by linuxdeploy) + libfuse2 (used when manually packing an appimage with appimagekit). I've also added the docker run args to enable fuse in the devcontainer, it requires fuse be setup on the host.
- update devcontainer to mirror build …

chore: update .devcontainer to provide a reproducible build environment

---

autoqa/tests/new-user/1-user-start-chatting.txt
web-app/src/hooks/useModelProvider.ts
web-app/src/routes/hub/index.tsx
web-app/src/services/providers.ts

This PR fixes the issue where the app continued to show models that were manually deleted from the filesystem. Previously, the app used a cached models list, which became stale when users removed model files directly. Additionally, this PR enhances the model hub to show proper recommended models for download.
- **Before**: App used cached models list that didn't reflect filesystem changes
- **After**: App now calls `llama.cpp list()` function to get current model state
- Models that are manually deleted are now immediately removed from the UI
- Enhanced model hub to display proper recommended models for download
- Improved model discovery and recommendation logic

fix: app should not show manually deleted models

---

package.json

The local build script for Linux was failing due to a bundling error. This commit updates the `build:tauri:linux` script in `package.json` to be consistent with the CI build pipeline, which resolves the issue.
The updated script now includes:
- **`NO_STRIP=1`**: This environment variable prevents the `linuxdeploy` utility from stripping debugging symbols, which was a potential cause of the bundling failure.
- **`--verbose`**: This flag provides more detailed output during the build, which can be useful for debugging similar issues in the future.
- Closes #6010

fix: update linux build script to be consistent with CI

---

extensions/llamacpp-extension/src/backend.ts
web-app/src/containers/DownloadManegement.tsx

This PR allows users to cancel a backend download.
https://github.com/user-attachments/assets/abd951c5-8101-4958-bb0a-9dc611df20ab
This pull request introduces improvements to the download management and error handling logic for backend downloads. The main changes enhance the user experience by ensuring that download cancellations and fallback mechanisms work more reliably and intuitively.
**Download cancellation logic:**
* Updated the download cancellation handler in `DownloadManagement` so that downloads with IDs starting with `'llamacpp'` are cancelled using the `@janhq/download-extension`'s `cancelDownload` method, while other downloads continue to use the existing `serviceHub.models().abortDownload` method. This ensures the correct cancellation mechanism is used for different types …

fix: allow users cancel backend download

---

docs/_redirects

This pull request adds several new redirect rules to improve navigation and ensure users are directed to the correct documentation pages.
**New redirect rules added:**
- General documentation:
* `/docs/quickstart` now redirects to `/docs/`
- Desktop installation documentation:
* `/docs/desktop/mac` now redirects to `/docs/desktop/install/mac`
- Handbook:
* `/handbook/open-superintelligence` now redirects to `/handbook/why/open-superintelligence`

docs: update redirect links

---

src-tauri/plugins/tauri-plugin-llamacpp/src/gguf/utils.rs

The KV cache size calculation in estimate_kv_cache_internal now includes a fallback mechanism for models that do not explicitly define key_length and value_length in the GGUF metadata.
If these attention keys are missing, the head dimension (and thus key/value length) is calculated using the formula embedding_length / total_heads. This improves robustness and compatibility with GGUF models that don't have the proper keys in metadata.
Also adds logging of the full model metadata for easier debugging of the estimation process.
- Closes #6626 
- Closes #

fix: Improve KV cache estimation robustness

---

web-app/src/containers/dialogs/AddModel.tsx
web-app/src/locales/de-DE/providers.json
web-app/src/locales/en/providers.json
web-app/src/locales/id/providers.json
web-app/src/locales/pl/providers.json
web-app/src/locales/vn/providers.json
web-app/src/locales/zh-CN/providers.json
web-app/src/locales/zh-TW/providers.json

This pull request improves the user experience when adding a new model by preventing duplicate model IDs and providing localized error messages. The main changes are an added check in the add model dialog to detect existing model IDs and new translations for the error message in multiple languages.
- Closes #6631
**User experience improvements:**
* Added a check in `DialogAddModel` (`AddModel.tsx`) to prevent users from adding a model with an ID that already exists, displaying an error toast if a duplicate is detected.
* Integrated the `sonner` toast library to show error notifications in the add model dialog.
**Localization updates:**
* Added new translation keys for the duplicate model ID error (`modelExists`, `modelExistsDesc`) in English, German, Indonesian, Polish, Vietnamese, …

fix: should not allow duplicating model

---

web-app/src/hooks/useAppState.ts
web-app/src/hooks/useChat.ts

Some of remote providers stream chunked completion instead of token by token. This PR is to extract token usage at the end of the stream to display proper token speed. 
Formula: Total Completion Token / (Current Time - Time To First Token in seconds)
https://github.com/user-attachments/assets/45d85a6c-5490-439c-8f46-fea5650bc7eb
Note: 
I planned to add a tokenizer, but it's costly and incompatible with most models and providers, so I skipped it.
- Closes #6289

fix: chat completion usage - token speed

---

.github/workflows/template-tauri-build-windows-x64.yml

This pull request makes a small change to the Windows build workflow by removing a step that uploaded the MSI release asset to GitHub if the public provider was set to GitHub. This simplifies the release process and reduces unnecessary upload actions.

ci: revert upload msi to github release

---

web-app/src/containers/ChatInput.tsx
web-app/src/containers/LeftPanel.tsx
web-app/src/containers/ThreadList.tsx
web-app/src/containers/dialogs/DeleteProjectDialog.tsx
web-app/src/hooks/useChat.ts
web-app/src/hooks/useThreadManagement.ts
web-app/src/locales/en/common.json
web-app/src/providers/AuthProvider.tsx
web-app/src/providers/DataProvider.tsx
web-app/src/routes/project/$projectId.tsx
web-app/src/routes/project/index.tsx
web-app/src/services/index.ts
web-app/src/services/projects/default.ts
web-app/src/services/projects/types.ts
web-app/src/services/projects/web.ts
web-app/src/services/threads/default.ts

- projects enhancement
- fix performance issue, thread should not overfetch items during load
- Closes #
- Closes #

cherry pick : projects + performance enhancement

---

.github/workflows/template-tauri-build-windows-x64.yml

This pull request makes a minor update to the Windows x64 build workflow by removing an unnecessary step that uploaded the MSI installer file to the S3 bucket.
* Workflow update:
* [`.github/workflows/template-tauri-build-windows-x64.yml`](diffhunk://#diff-c71636a16c635e7d32fdd0e3bebc3d7d5a2e90d1871995f8dc03f8d2a5bf63a8L276-L277): Removed the command that uploads the MSI file (`${{ steps.metadata.outputs.MSI_FILE_NAME }}`) to S3, streamlining the deployment process.

ci: remove upload msi artifact

---

extensions/llamacpp-extension/src/index.ts
web-app/src/containers/ChatInput.tsx
web-app/src/services/models/default.ts

Frontend Changes 
Added chat_template_kwargs: { enable_thinking: false } when calling engine.getTokensCount()
Updated type definition to include optional chat_template_kwargs parameter
This ensures token counting always works regardless of model defaults
- Closes #
- Closes #

fix: prompt token

---

web-app/src/containers/LeftPanel.tsx

This pull request introduces a minor UI improvement to the `Left#6684 ` component in the web app. The main change is the addition of a "Recents" label to enhance the clarity of the recent threads section when no search results are found.
UI enhancements:
* Added a "Recents" label above the recent threads list when the search returns no results, improving the user experience and clarity in the `LeftPanel` component (`web-app/src/containers/LeftPanel.tsx`).
- Closes #6691 
- Closes #

fix: title recent when no result found

---

web-app/src/containers/dialogs/AddEditMCPServer.tsx
web-app/src/containers/dialogs/EditJsonMCPserver.tsx

This pull request makes minor improvements to the styling of text areas in the `AddEditMCPServer` and `EditJsonMCPserver` dialog components. The main change is standardizing the monospace font usage by relying on the `font-mono` Tailwind CSS utility class instead of setting the font family inline.
Styling improvements:
* Replaced the inline `fontFamily: 'ui-monospace'` style with the Tailwind CSS `!font-mono` class for the text area in `AddEditMCPServer` (`AddEditMCPServer.tsx`) and added `!font-mono` to the class list.
* Replaced the inline `fontFamily: 'ui-monospace'` style with the Tailwind CSS `font-mono` class for the text area in `EditJsonMCPserver` (`EditJsonMCPserver.tsx`) and added `font-mono` to the class list.
- Closes #6686 
- Closes #

fix: font mono default from mcp json ediitor

---

src-tauri/tauri.conf.json

This pull request contains minor configuration changes to the `src-tauri/tauri.conf.json` file. The most notable update is the removal of the `zoomHotkeysEnabled` property from the Windows window configuration.
Configuration updates:
* Removed the `zoomHotkeysEnabled` property from the Windows window configuration, which may affect zoom hotkey functionality on Windows builds.
* Reformatted the `capabilities` array in the `security` section for improved readability, without changing its contents.
- Closes #6466 
- Closes #

chore: turn off zoomHotkeysEnabled
