- app-backend/worker/worker.ts
> fix: remove parsing json error and trim llm answer

- web-client/app/layout.tsx
Cleaning up legacy SEO metadata for #49 . However, need @0xSage 's confirmation.
fixes #49
> chore: update legacy web app seo metadata

- web-client/app/_components/GenerateImageList/index.tsx
- web-client/app/_components/NewChatBlankState/index.tsx
> chore: remove the grid on blank chat screen

- .github/workflows/ci-production.yml
- .github/workflows/ci-staging.yml
- .github/workflows/deploy-jan-docs.yml
- .github/workflows/quality-gate.yml
- web-client/Dockerfile
This PR aims:
- Add CICD for jan-cloud staging and production
- Update Dockerfile production for web-client
- Update deploy jan docs to trigger folder ./docs/** only
> Add CI for Jan-cloud

- .gitignore
- run.sh
- Install Homebrew
- Install Xcode Command Line Tools
- Install Git
- Install Docker
- Install Docker Compose
- Git clone & pull submodules
- Download Llama Model
- Launch Docker
- Docker compose up
- Wait for service is healthy
- python
- virtualenv
- llama.cpp
darwin:
https://github.com/janhq/jan/assets/133622055/3b45d7c9-4e00-4aa2-be4e-4a448c59fcd3
linux:
resolves #30 resolves #48 resolves #47
> #30 - bash script for jan installation

- run.sh
- remove incomplete llama.cpp setup
- suppress apt install warning
> chore: update bash script

- KC.md
- README.md
> chore: adding keycloak theme configuration

- run.sh
- `set -e` will stop the script silently
Fixes #82
> Fix incorrect bash script condition check

- README.md
> docs: add gif placeholder

- .github/workflows/deploy-jan-docs.yml
Add jan docs trigger by ci file change
> Add jan docs trigger by ci file change

- README.md
Closes #180 
Updates docs to use CUBLAS for Nvidia cards
> Change Readme to reflect new direction

- .github/workflows/deploy-jan-docs.yml
Chore: docusaurus ci move to yarn cache
> Chore: docusaurus ci move to yarn cache

- .github/workflows/deploy-jan-docs.yml
Remove hardcode docusaurus domain from CI
> Remove hardcode docusaurus domain from CI

- electron/core/plugins/inference-plugin/module.js
- electron/main.ts
- electron/package.json
- electron/utils/menu.ts
- electron/utils/versionDiff.ts
fixes #239 
this PR also refactored `main.ts`: 
```typescript
app
.whenReady()
.then(migratePlugins)
.then(setupPlugins)
.then(setupMenu)
.then(handleIPCs)
.then(handleAppUpdates)
.then(createMainWindow)
.then(() => {
app.on("activate", () => {
if (!BrowserWindow.getAllWindows().length) {
createMainWindow();
}
});
});
```
> [#239] Menu bar actions - check for update manually

- electron/core/plugins/data-plugin/module.ts
- electron/core/plugins/inference-plugin/module.js
- electron/main.ts
- electron/utils/disposable.ts
- Fixes #237 - Dispose required modules from main process
- Fixes promise with no response (invokePluginFunc)
- Unblock #234, required module cache can be deleted
> [#237] Dispose plugins from main process

- .github/workflows/linter-and-test.yml
- electron/package.json
This PR aims at fixing issue #272
> add electron artifactName

- electron/core/plugins/inference-plugin/package-lock.json
- electron/core/plugins/model-management-plugin/package-lock.json
- electron/core/plugins/monitoring-plugin/package-lock.json
- electron/main.ts
- electron/preload.ts
- web/app/_components/Preferences.tsx
- yarn.lock
chore: add reinstall plugins CTA
> Fix: package-lock.json

- web/app/_components/ConfirmDeleteConversationModal/index.tsx
- web/app/_components/LoginButton/index.tsx
- web/app/_components/ModelSelector/index.tsx
- web/app/_components/PrimaryButton/index.tsx
- web/app/_components/SendButton/index.tsx
- web/app/_components/SimpleTextMessage/index.tsx
- web/app/_hooks/useDeleteConversation.ts
> fix #283: small ui fixes

- docs/src/components/Elements/dropdown.js
Fix Docusaurus server side render error
> Fix Docusaurus server side render error

- .github/workflows/jan-docs-test.yml
Add docusaurus test build pipeline
> Add docusaurus test build pipeline

- .github/release-drafter.yml
Add release note template using Release Drafter Github app
> Add release note template

- .github/release-drafter.yml
Add Documentation category to release note template
> Add Documentation category to release note template

- web/app/_components/BasicPromptAccessories/index.tsx
- web/app/_components/BasicPromptInput/index.tsx
- web/app/_components/InputToolbar/index.tsx
- web/app/_components/SendButton/index.tsx
- web/app/_components/SimpleTextMessage/index.tsx
Fixes: #324 
- [won't do] users can emoji
> style: better chatbox ui

- .github/workflows/publish-plugins.yml
Fix error check change in plugins folder
> Fix error check change in plugins folder

- .github/workflows/publish-plugin-core.yml
- plugins/data-plugin/package-lock.json
- plugins/data-plugin/package.json
- plugins/inference-plugin/package-lock.json
- plugins/inference-plugin/package.json
- plugins/model-management-plugin/package-lock.json
- plugins/model-management-plugin/package.json
- plugins/monitoring-plugin/package-lock.json
- plugins/monitoring-plugin/package.json
- plugins/openai-plugin/package.json
> Correct version of plugins

- docs/src/components/Announcement/index.js
- docs/src/components/Footer/index.js
- docs/src/pages/index.js
> Add simple copywriting changes

- plugins/model-management-plugin/index.ts
These registrations are no longer relevant
> chore: remove deprecated extension functions

- core/events.ts
- plugins/model-management-plugin/package.json
New events for downloading progress
> chore: update core events module

- .github/workflows/jan-plugins.yml
- plugins/data-plugin/package.json
Fix data-plugin install failed on mac silicon from npm
> Fix data-plugin install failed on mac silicon from npm

- electron/main.ts
In development mode, any plugin update action (install, update, uninstall) will require an app relaunch, which would kill current electron & react development processes, developer has to kill the app window and run `yarn dev` again. 
1. Clear required module cache (by plugins)
2. Trigger dispose() from plugins so they can clear spawned resources
3. Reload frontend
> chore: install or update a plugin should not interrupt dev process

- .github/workflows/jan-plugins.yml
- plugins/inference-plugin/README.md
> Add readme inference plugin

- .github/workflows/jan-electron-build.yml
> fix error codesign

- .github/workflows/jan-electron-build.yml
Change codesign plugin folder in ci
> Change codesign plugin folder in ci

- .github/scripts/auto-sign.sh
Update auto-sign plugin by search file permission 664
> Update auto-sign plugin by search file permission 664

- web/screens/Settings/CorePlugins/PluginsCatalog.tsx
- web/screens/Settings/CorePlugins/PreferencePlugins/index.tsx
> fix: bring back install plugin manually function

- plugins/inference-plugin/module.ts
- plugins/inference-plugin/nitro/nitro_start_linux.sh
- plugins/inference-plugin/nitro/nitro_start_windows.bat
Change to load nitron on windows and linux from bash/shell script
> Change to load nitron on windows and linux from bash/shell script

- plugins/data-plugin/package.json
Use electron-rebuild to build leveldown@5.6.0 for darwin arm64
> Use electron-rebuild to build leveldown@5.6.0 for darwin arm64

- plugins/inference-plugin/index.ts
- plugins/inference-plugin/module.ts
- web/app/_components/ConversationalList/index.tsx
- web/app/_components/CreateBotContainer/index.tsx
- web/app/_components/HistoryItem/index.tsx
- web/app/_components/LeftRibbonNav/index.tsx
- web/app/_components/ModelTable/index.tsx
- web/containers/BottomBar/index.tsx
- web/containers/Providers/index.tsx
- web/containers/Sidebar/Left.tsx
- web/helpers/EventListenerWrapper.tsx
- web/hooks/useCreateBot.ts
- web/hooks/useDeleteBot.ts
- web/hooks/useGetAppVersion.ts
- web/hooks/useGetBots.ts
- web/hooks/useGetDownloadedModels.ts
- web/hooks/useGetSystemResources.ts
- web/hooks/useUpdateBot.ts
- web/next.config.js
- web/screens/ExploreModels/ExploreModelList/index.tsx
- web/screens/Settings/CorePlugins/PluginsCatalog.tsx
- web/screens/Settings/CorePlugins/PreferencePlugins/index.tsx
- web/services/pluginService.ts
- web/types/index.d.ts
- Correct version display
- Send a message without any model running yield a next error (bottom left banner)
- Don't kill nitro process when switching between models
- App crashes when core plugin is disabled
> fix: correct app version display

- electron/tests/my-models.e2e.spec.ts
- electron/tsconfig.json
- web/screens/MyModels/index.tsx
- electron app is failed to build
- unstable test case
> fix: failed to build electron app

- web/app/_components/HistoryItem/index.tsx
- web/app/_components/HistoryList/index.tsx
- web/app/_components/InputToolbar/index.tsx
- web/app/_components/SwitchingModelConfirmationModal/index.tsx
- web/containers/Providers/index.tsx
- web/helpers/EventHandler.tsx
- web/helpers/ModalWrapper.tsx
- web/helpers/atoms/Modal.atom.ts
- web/hooks/useChatMessages.ts
- web/hooks/useCreateConversation.ts
- web/hooks/useGetInputState.ts
- web/hooks/useGetModelById.ts
- web/hooks/useGetUserConversations.ts
- web/hooks/useStartStopModel.ts
- web/models/ChatMessage.ts
> fix: allow switching models when switch between conversations

- web/screens/Settings/CorePlugins/PluginsCatalog.tsx
> bug: fix logic plugin update plugin and show installed version

- plugins/retrieval-plugin/README.md
> chore: update README.md

- .github/workflows/jan-plugins.yml
Add build deps for data-plugin in CI
> Add build deps for data-plugin in CI

- plugins/data-plugin/README.md
- plugins/data-plugin/package.json
add rebuild for mac x64, fix bug data plugin on mac intel
> add rebuild for mac x64

- plugins/data-plugin/README.md
- plugins/data-plugin/package.json
Add rebuild leveldown for arm on mac intel
> Add rebuild leveldown for arm on mac intel

- electron/core/plugin-manager/execution/facade.js
- plugins/data-plugin/package.json
- plugins/inference-plugin/package.json
- plugins/model-management-plugin/package.json
- plugins/monitoring-plugin/package.json
> #255: Read plugins manifest from CDN

- plugins/data-plugin/README.md
- plugins/model-management-plugin/README.md
- plugins/monitoring-plugin/README.md
To trigger plugin manifest CI, unblock #255
> chore: update plugin readme

- electron/main.ts
- electron/preload.ts
- electron/tests/navigation.e2e.spec.ts
- web/app/_components/LeftHeaderAction/index.tsx
- web/containers/Providers/index.tsx
- web/containers/Sidebar/Left.tsx
- web/helpers/FeatureToggleWrapper.tsx
- web/screens/Settings/Advanced/index.tsx
- web/screens/Settings/CorePlugins/PluginsCatalog.tsx
- web/screens/Settings/index.tsx
- Bug fix, enhancements are blocked by a few of epics
- Need somehow to disable on-going features on stable release
- Since we do OSS, feature toggle can only be activated by enabling experimental features in settings? (no firebase / remote toggle support, work offline & locally)
- We will mark it as stable feature after tested and will only available from the next release (remove out of experimental feature list)
fixes #522
> feat: Experimental Feature Toggle

- docs/src/pages/index.js
Update website tagline from "Run Large Language Models locally on Mac, Windows or Linux." to "Jan is a powerful Personal AI built to run locally on your machine, with a rich app and plugin ecosystem."
> Update website tag line

- plugins/inference-plugin/package.json
Add install nitro mac intel inference plugin build locally
> Add install nitro mac intel inference plugin build locally

- docs/src/pages/index.js
> Update Homepage and README with 1-line pitch

- web/helpers/atoms/Conversation.atom.ts
- web/screens/Chat/index.tsx
- As discussed, there is a state issue where app could not create a new conversation and send message immediately the first time user attempt to send message without creating a new convo.
> chore: fixed an issue where app does not yield message result

- web/hooks/useDeleteConversation.ts
Issue: https://github.com/janhq/jan/issues/567
Result:
> bug: Toast messages shows [object object]

- .github/workflows/jan-electron-build.yml
- Failed to package app for productions, need to build core and uikit before installing dependencies
> fix: failed to package app since core and uikit are not being built

- web/screens/Chat/index.tsx
> bug: enable delete conversation after deleted model

- docs/docusaurus.config.js
- docs/src/css/custom_toc.css
- docs/src/styles/base.scss
- docs/src/styles/tweaks.scss
- docs/src/styles/typography.scss
> fix: line height and update typography component

- plugins/inference-plugin/package.json
Restore cpx nitro step in yarn script
> Restore cpx nitro step in yarn script

- docs/src/styles/tweaks.scss
@urmauur For your consideration, It really helps with readability
> Reduce line heights for list items

- docs/README.md
Add Instruction to publish docs
> Add Instruction to publish docs

- docs/docs/handbook/handbook.md
Pls approve the Onboarding Checklist
> Updating Onboarding Kit

- docs/docs/specs/messages.md
- docs/docs/specs/models.md
- docs/docs/specs/threads.md
- docs/sidebars.js
Will need @hieu-jan  's help to migrate the API endpoints over to /api-reference
> docs: threads and messages

- .github/workflows/jan-docs.yml
Revert docs CICD trigger on push to main instead of tag-based
> Revert docs CICD trigger on push to main instead of tag-based

- .github/workflows/jan-docs.yml
- docs/README.md
Fix error docs pipeline run failed
> Fix error docs pipeline run failed

- .github/workflows/jan-electron-build.yml
- Makefile
> Add windows code sign to CI

- web/screens/Chat/index.tsx
Fix #643 
Can't reproduce issue on my local, added `position: relative` and `z-index: 10` for just make sure button on top layer
> bug: fix clickable small download button on chat screen

- web/screens/Chat/ChatItem/index.tsx
- web/screens/Chat/MessageToolbar/index.tsx
- web/screens/Chat/SimpleTextMessage/index.tsx
issue #385 ,  PR from #717  
Update toolbar need hover and showing on the right side
Update toolbar will always show on the bottom for last message
> improvement: styling message action toolbar

- core/src/core.ts
- core/src/index.ts
- core/src/plugins/model.ts
- electron/handlers/download.ts
- plugins/model-plugin/src/index.ts
- web/containers/Layout/BottomBar/DownloadingState/index.tsx
- web/containers/ModalCancelDownload/index.tsx
> fix: cancel download does not work

- .github/workflows/jan-electron-build-nightly.yml
> Remove .zip in artifact name

- package.json
- `/models` directory is not copied into app package with production build script
> fix: CI script - reorder copy models action

- .github/workflows/jan-electron-build-nightly.yml
- README.md
Add document for nightly build and update message for manual build
> Add document for nightly build and update message for manual build

- electron/handlers/update.ts
- extensions/assistant-extension/src/index.ts
- web/hooks/useSendChatMessage.ts
- web/screens/Chat/MessageToolbar/index.tsx
Fixes: #833 
Fixes: #792
Fixes: #851
> fix: empty assistant instruction by default

- package.json
Production workflow does not populate models into app package
> fix: production CI workflow does not populate models

- web/containers/Providers/EventListener.tsx
- web/helpers/atoms/Model.atom.ts
- web/hooks/useDownloadModel.ts
- web/hooks/useDownloadState.ts
- web/hooks/useSendChatMessage.ts
> fix: can not download multiple models at once

- web/screens/ExploreModels/ExploreModelItemHeader/index.tsx
- web/screens/ExploreModels/ExploreModelList/index.tsx
- web/screens/ExploreModels/index.tsx
- Featured
- 7b Models
- Recommended
- Others
- 13b
- Recommended
- Others
- 33b
- 70b
- Tiny
> chore: update model ranking

- web/containers/CardSidebar/index.tsx
- web/screens/ExploreModels/ExploreModelItem/index.tsx
fixing #847 and bug UI broken card right panel
> bug: fix tag description showing a title and fix card right panel

- web/screens/Chat/SimpleTextMessage/index.tsx
fixes #893 
- Ask a question that has a code response
- See the code formatting
> bug: fix syntax formatting

- web/containers/CardSidebar/index.tsx
> [bug] Fix floating border outside card right panel

- docs/docusaurus.config.js
- docs/openapi/jan.yaml
- docs/openapi/specs/assistants.yaml
- docs/openapi/specs/chat.yaml
- docs/openapi/specs/messages.yaml
- docs/openapi/specs/models.yaml
- docs/openapi/specs/threads.yaml
PR Title: docs: standardize yaml files
PR Description: 
This pull request standardize .yaml files.
> docs: standardize yaml files

- .github/workflows/jan-electron-build-nightly.yml
- .github/workflows/update-release-url.yml
- README.md
Fix update release url pipeline:
- manual trigger will update url if trigger on main branch
- Add checkout step to update URL job
- Set text align center for table
> Fix update release url pipeline

- extensions/inference-openai-extension/src/index.ts
- extensions/inference-triton-trtllm-extension/src/index.ts
- web/hooks/useCreateNewThread.ts
> fix: 963 can not run openai models on windows

- docs/src/containers/DownloadApp/index.js
> fix: enable download app linux

- electron/handlers/app.ts
> fix: review finder and view as json

- web/containers/DropdownListSidebar/index.tsx
Test scenario: 
- Chat with any local model
- Create new thread
- Chat with remote model `chatgpt 3.5`
- Go back to previous thread
- See the right panel > model section
> fix: wrong selected model right panel

- core/src/types/model/modelEntity.ts
- web/containers/DropdownListSidebar/index.tsx
- web/screens/Chat/ChatBody/index.tsx
According to #995, we should guide new users to download a local model. The local models should be prioritized on top of the model list.
This is just a patch for a hotfix, please help update accordingly with a better UX @imtuyethan @urmauur
> fix: #995 - Fix onboarding state and model sorting

- extensions/conversational-extension/src/index.ts
cc @namchuai another case found related to #882 
fixes #882
> fix: delete first message then regenerate again will break the thread

- .github/workflows/jan-electron-build.yml
- web/next.config.js
fix bug #1013, enable posthog for release app version only
> fix bug #1013, enable posthog for release app version only

- web/utils/posthog.ts
Update posthog capture url list
> Update posthog capture url list

- .github/workflows/jan-electron-build.yml
Separate posthog project for jan app and docs
> Separate posthog project for jan app and docs

- extensions/conversational-extension/src/index.ts
A line break is not inserted properly
fixes #1057
> fix: thread is broken after deleted first generated message

- docs/docs/handbook/product.md
> docs: Update product.md

- web/containers/DropdownListSidebar/index.tsx
- web/hooks/useActiveModel.ts
- web/hooks/useGetDownloadedModels.ts
- web/hooks/useRecommendedModel.ts
> fix(thread): #1043 default model to prefer active model

- models/gpt-3.5-turbo-16k-0613/model.json
- models/gpt-3.5-turbo/model.json
- models/gpt-4/model.json
> Update model version

- web/containers/Checkbox/index.tsx
- web/containers/Slider/index.tsx
- web/screens/Chat/ModelSetting/index.tsx
- web/screens/Chat/ModelSetting/settingComponentBuilder.tsx
> feat(ModelSetting): #1065 update state of model setting between threads

- .github/workflows/jan-electron-build-nightly.yml
- .github/workflows/jan-electron-build.yml
Correct jq command cause ci nightly build run failed
> Correct jq command cause ci nightly build run failed

- web/screens/ExploreModels/index.tsx
fixes #1100 
https://github.com/janhq/jan/assets/10354610/78d110c2-6304-4f6d-869a-934c39eecad1
> fix: search recommended model

- web/helpers/atoms/ChatMessage.atom.ts
> fix(Thread): #1064 message being added to wrong thread if switching thread

- web/containers/DropdownListSidebar/index.tsx
> fix: added tooltip for user cannot change model after starting thread

- web/screens/Settings/Models/Row.tsx
Fixed an issue where app displays all models as active models
> fix: ui issue - all models are activated

- web/containers/Layout/TopBar/CommandListDownloadedModel/index.tsx
> fix: remove remote model from shortcut models dialog

- web/screens/Chat/ThreadList/index.tsx
> fix: added dialog confirmation clean thread

- docs/docs/handbook/product.md
- docs/src/pages/index.js
Hot fix error road map url on main page and documentation
> fix: error road map url

- docs/docs/guides/03-chatting/01-start-thread.md
Just a braindump from my notes. Take it with a grain of salt
> docs: Update 01-start-thread.md

- web/hooks/useCreateNewThread.ts
Fixes #1168 
https://github.com/janhq/jan/assets/10397206/5441da2d-6fff-4d6a-8bc4-1cfd581bc928
> fix(Thread): #1168 fix newly created thread cannot select model after restart

- docs/docs/guides/02-installation/01-mac.md
- docs/docs/guides/02-installation/02-windows.md
- docs/docs/guides/02-installation/03-linux.md
- docs/docs/guides/07-troubleshooting/01-stuck-on-broken-build.mdx
Standardize commands for entire installation guide, and troubleshooting docs. 
All commands are tested in the following operating system:
> docs: improve troubleshoot documentation

- web/screens/ExploreModels/index.tsx
> feat: temporary link how to import model

- extensions/inference-nitro-extension/src/module.ts
add sleep 500ms if platform is windows before starting nitro process
> add sleep 500ms if platform is windows before starting nitro process

- web/containers/Checkbox/index.tsx
- web/containers/ConfigInput/index.tsx
- web/containers/DropdownListSidebar/index.tsx
- web/containers/ModelConfigInput/index.tsx
- web/containers/Slider/index.tsx
- web/helpers/atoms/Thread.atom.ts
- web/hooks/useCreateNewThread.ts
- web/hooks/useRecommendedModel.ts
- web/hooks/useSendChatMessage.ts
- web/hooks/useThreads.ts
- web/hooks/useUpdateModelParameters.ts
- web/screens/Chat/EngineSetting/index.tsx
- web/screens/Chat/ModelSetting/index.tsx
- web/screens/Chat/ModelSetting/predefinedComponent.ts
- web/screens/Chat/ModelSetting/settingComponentBuilder.tsx
- web/screens/Chat/Sidebar/index.tsx
- web/utils/componentSettings.ts
- web/utils/model_param.ts
> feat: add engine settings

- core/src/api/index.ts
- core/src/core.ts
- electron/handlers/app.ts
- web/containers/CardSidebar/index.tsx
- web/next.config.js
- web/screens/Chat/Sidebar/index.tsx
- web/screens/Settings/CoreExtensions/ExtensionsCatalog/index.tsx
- web/types/index.d.ts
> fix: #1183 Reveal in finder does not work on windows

- web/screens/Chat/Sidebar/index.tsx
This feature is not fully implemented.
Blocking issues: #1250
> fix: engine settings GUI - feature toggle

- web/containers/Providers/index.tsx
- web/screens/Settings/Advanced/index.tsx
This settings is applicable for Windows & Linux only
> fix: mac users should not see GPU settings

- web/screens/Chat/index.tsx
App send 2 messages at once, with an additional final word due to the special character sent from the 3rd input extension/input sources. Especially Vietnamese input source
fixes #1174
> fix: input message duplicated due with some input sources

- extensions/inference-nitro-extension/package.json
> fix ci test run failed

- web/containers/Layout/TopBar/CommandSearch/index.tsx
- web/screens/Settings/Advanced/index.tsx
- web/screens/Settings/index.tsx
fixes #1054 
- Open app -> Setting -> Advanced -> Keyboard Shortcuts
> feat: added keyboard shortcut list in setting page

- web/screens/Chat/index.tsx
fixes #1276 
**this allow the user to scroll if text box overflows.**
> Enable scrolling in the message chat box

- .gitignore
- README.md
- core/src/api/index.ts
- electron/handlers/app.ts
- electron/main.ts
- electron/package.json
- package.json
- server/index.ts
- web/screens/Settings/Advanced/index.tsx
- Fix CSP issue where could not access server or /docs
- Add server settings to enable disable api server
- Refactor run script
> fix: swagger CSP issue

- web/containers/DropdownListSidebar/index.tsx
- web/screens/ExploreModels/ExploreModelItemHeader/index.tsx
- web/screens/ExploreModels/ModelVersionItem/index.tsx
- web/screens/Settings/Models/Row.tsx
- web/screens/SystemMonitor/index.tsx
- web/utils/converter.ts
Switch from Gigabyte to Gibibyte -  System monitor
> Switch from Gigabyte to Gibibyte - System monitor

- core/src/node/module.ts
- electron/main.ts
- Fixed an issue where the app did not clean resources properly after exit.
- Fixed an issue where the app quit unexpectedly after being force quit.
fixes #1264
> fix: clean-resource-on-exit

- .github/workflows/jan-electron-build-nightly.yml
- .github/workflows/jan-electron-build.yml
- Makefile
- README.md
Refactor CI by create shared jobs output
> Refactor CI by create shared jobs output

- docs/docs/handbook/onboarding.md
Updated "no naked top" to "no nudity"
> docs: Update onboarding.md

- extensions/monitoring-extension/package.json
- extensions/monitoring-extension/src/module.ts
- web/hooks/useGetSystemResources.ts
Fix memory on mac included cached and swap
> Fix memory on mac included cached and swap

- .github/pull_request_template.md
Please automerge for me once LGTMd
> chore: github PR template

- core/src/node/extension/manager.ts
- core/src/node/extension/store.ts
- extensions/inference-nitro-extension/src/module.ts
> correct type utf-8

- docs/docs/guides/05-using-server/01-server.md
- Bare minimal server docs, needs enhancement.
- Please automerge for me.
-
> docs: Update 01-server.md

- uikit/src/tooltip/index.tsx
- web/containers/CardSidebar/index.tsx
- web/containers/Checkbox/index.tsx
- web/containers/Layout/Ribbon/index.tsx
- web/containers/Layout/TopBar/CommandListDownloadedModel/index.tsx
- web/containers/Layout/TopBar/index.tsx
- web/containers/Loader/ModelReload.tsx
- web/containers/ModelConfigInput/index.tsx
- web/containers/Providers/EventHandler.tsx
- web/containers/Slider/index.tsx
- web/helpers/atoms/Thread.atom.ts
- web/hooks/useActiveModel.ts
- web/hooks/useSendChatMessage.ts
- web/hooks/useUpdateModelParameters.ts
- web/screens/Chat/ChatBody/index.tsx
- web/screens/Chat/EngineSetting/index.tsx
- web/screens/Chat/ModelSetting/index.tsx
- web/screens/Chat/ModelSetting/predefinedComponent.ts
- web/screens/Chat/ModelSetting/settingComponentBuilder.tsx
- web/screens/Chat/Sidebar/index.tsx
- web/screens/Chat/index.tsx
- web/screens/Settings/Models/Row.tsx
- web/screens/SystemMonitor/index.tsx
- web/utils/model_param.ts
https://github.com/janhq/jan/assets/10354610/415cd8dc-4818-4d93-9be2-b20b62aa4d24
fixes #1250  #1313
> feat: implementation new UI thread settings

- extensions/model-extension/src/index.ts
- web/screens/Chat/SimpleTextMessage/index.tsx
- Open link in message with external browser
- fixes #1321
> fix(Message): open link with external browser

- extensions/inference-nitro-extension/src/helpers/sse.ts
- extensions/inference-openai-extension/src/helpers/sse.ts
Error occurred: Unexpected token 'd', "data: {"ch"... is not valid
JSON
fixes #1331
> fix: Error occurred: Unexpected token "d", "data: ..." is not a valid JSON

- web/screens/ExploreModels/ExploreModelList/index.tsx
- web/screens/ExploreModels/index.tsx
> fix(JanHub): #1158 sort model list

- web/containers/Providers/EventListener.tsx
- web/hooks/useDownloadState.ts
Its currently only show a generic message such as Download Cancelled or nothing showing up.
fixes #1193
Note: I hacked my hosts configuration so the message is a bit unclear
> fix: show a proper error message on download failure

- web/screens/Chat/ModelSetting/predefinedComponent.ts
- web/screens/Chat/Sidebar/index.tsx
- Update copy tooltip `stream` setting params
- Hide section setting when model doesn't have a setting params
> fix: copy stream tooltip and hide section when no params setting

- web/hooks/useDownloadState.ts
Wrong condition for displaying error message so no toast displayed in Prod
> fix: wrong condition for displaying error message

- extensions/model-extension/src/index.ts
- Models migration stopped working, after updated from nightly build to new PR with model update. The changes are not applied
While testing #1342
> fix: model migration stopped working

- extensions/inference-nitro-extension/src/module.ts
- models/config/default-model.json
- Remove unsupported default model setting params
> fix(Model): remove unsupported default model setting params

- extensions/model-extension/package.json
- models/openchat-3.5-7b/model.json
> Update model hub

- docs/docs/guides/02-installation/04-from-source.md
- docs/docs/guides/04-using-models/02-import-manually.mdx
- docs/docs/guides/04-using-models/03-integrate-with-remote-server.mdx
- docs/docs/guides/07-troubleshooting/01-stuck-on-broken-build.mdx
- docs/docusaurus.config.js
> docs: improve docs syntax 

- docs/docs/guides/07-troubleshooting/02-failed-to-fetch.mdx
- add troubleshooting doc for failed to fetch
- [Y ] Added relevant comments, esp in complex areas
- [Y] Updated docs (for bug fixes / features)
- [Y] Created issues for follow-up changes or refactoring needed
> docs: Troubleshoot Failed To Fetch

- docs/docs/guides/07-troubleshooting/02-failed-to-fetch.mdx
- docs/docs/guides/07-troubleshooting/03-gpu-not-used.mdx
- docs for folks who need cuda
- #1385
> docs: gpu not detected

- USAGE.md
- docs/docs/guides/07-troubleshooting/03-gpu-not-used.mdx
> Update USAGE docs for linux

- USAGE.md
- docs/docs/guides/07-troubleshooting/03-gpu-not-used.mdx
This pull request improves the current docs by re-writing some parts of content based on original content to make it clearly and concise. Make structure consistency with our other docs.
> docs: improve gpu not used guide

- core/src/node/api/routes/v1.ts
- Fix an issue with wrong path for thread
- fixes #1409
> fix(API): #1409 fix wrong prefix for threads api

- docs/docs/guides/02-installation/06-hardware.md
- Removed typo from 06-hardware.md
-
> docs: Typo in 06-hardware.md

- web/containers/GPUDriverPromptModal/index.tsx
- Update warning url from github md file to jan.ai docs site
- No
> Update warning url from github md file to jan.ai docs site

- docs/docs/developer/01-overview/README.md
- docs/docs/docs/README.md
- docs/docs/guides/00-overview.md
- docs/docusaurus.config.js
- Rename docs page to "framework"
- Add overview for each docs page, intended audience
-
> docs: explain each docs page intent

- web/containers/Layout/TopBar/CommandListDownloadedModel/index.tsx
- web/containers/Layout/TopBar/CommandSearch/index.tsx
- web/containers/Providers/KeyListener.tsx
- web/containers/Providers/index.tsx
- web/screens/Chat/index.tsx
- web/screens/ExploreModels/ModelVersionItem/index.tsx
- Consolidate the hot key listener into one place.
- Allow user to toggle left side bar by `Command / Ctrl + b`. I think we can follow Visual studio code for this.
- fixes #1404
> feat(UI): #1404 make left side bar collapsible by hot key

- web/containers/Layout/BottomBar/SystemItem/index.tsx
- web/containers/Layout/BottomBar/index.tsx
- web/containers/Layout/TopBar/index.tsx
- web/containers/Providers/KeyListener.tsx
- web/containers/Providers/index.tsx
- web/containers/Shortcut/index.tsx
> feat(UI): update UI footer

- docs/docs/developer/01-overview/README.md
- docs/docs/guides/02-installation/01-mac.md
- docs/docs/guides/02-installation/02-windows.md
- docs/docs/guides/02-installation/04-from-source.md
- docs/docs/guides/02-installation/README.mdx
- docs/docs/guides/07-troubleshooting/02-failed-to-fetch.mdx
- docs/docs/handbook/onboarding.md
- docs/docs/handbook/product.md
- docs/docs/support/support.md
- Run typo checks for current documentation
- Typo
> docs: fix typo in docs

- web/containers/Layout/TopBar/index.tsx
- web/screens/Settings/Advanced/index.tsx
> fix: add icon collapsible left panel and update keyboard shortcut page

- docs/docs/about/about.md
- **Please automerge for me if LGTM**
- Fixes #1232
> docs: revenue philosophy

- .github/workflows/jan-electron-build-nightly.yml
- .github/workflows/update-release-url.yml
- README.md
> Correct AppImage path

- docs/docs/guides/04-using-models/01-install-from-hub.mdx
> docs: add-missing-path

- docs/docs/guides/04-using-models/04-customize-engine-settings.mdx
- Add customize-engine-setting documentation
- #1329
> docs: adding customize engine settings

- docs/docs/about/about.md
> docs: Update about.md

- docs/docs/guides/04-using-models/02-import-manually.mdx
> docs: Update 02-import-manually.mdx

- core/src/types/message/messageEntity.ts
- extensions/inference-nitro-extension/src/index.ts
- web/containers/Providers/EventHandler.tsx
- web/screens/Chat/ChatBody/index.tsx
- web/screens/Chat/ErrorMessage/index.tsx
- web/screens/Chat/SimpleTextMessage/index.tsx
> chore: error message update

- .github/workflows/update-release-url.yml
- README.md
- docs/docs/guides/02-installation/03-linux.md
- docs/src/containers/DownloadApp/index.js
- docs/src/containers/Elements/dropdown.js
- electron/package.json
Chore update docs jan - add AppImage instruction to docusaurus
> Chore update docs jan - add AppImage instruction to docusaurus

- core/src/node/api/common/builder.ts
- Fix model format for storing message correctly.
- fixes #1434
> fix(Messages): #1434 create message via api does not display on app correctly

- docs/docs/about/about.md
- docs/docs/guides/07-integrations/01-integrate-continue.mdx
- Hot-fix #1468 
- Minor improve the docs text in integration guide
- #1468
> docs: minor fix

- extensions/inference-nitro-extension/src/index.ts
- extensions/inference-nitro-extension/src/module.ts
- web/containers/Providers/EventHandler.tsx
- Periodically getting state of Nitro's process.
- 1067
> fix(InferenceExtension): #1067 sync the nitro process state

- docs/docusaurus.config.js
- docs/package.json
- docs/yarn.lock
> chore: enable agolia

- core/rollup.config.ts
- core/src/api/index.ts
- core/src/core.ts
- core/src/fs.ts
- core/src/node/api/common/builder.ts
- core/src/node/api/routes/download.ts
- core/src/node/api/routes/extension.ts
- core/src/node/api/routes/fs.ts
- core/src/node/api/routes/v1.ts
- core/src/node/download.ts
- core/src/node/extension/extension.ts
- core/src/node/extension/manager.ts
- core/src/node/log.ts
- electron/handlers/app.ts
- electron/handlers/fileManager.ts
- electron/main.ts
- electron/utils/extension.ts
- extensions/inference-nitro-extension/package.json
- extensions/inference-nitro-extension/src/@types/global.d.ts
- extensions/inference-nitro-extension/src/helpers/nvidia.ts
- extensions/inference-nitro-extension/src/index.ts
- extensions/inference-nitro-extension/src/module.ts
- extensions/inference-nitro-extension/webpack.config.js
- extensions/model-extension/src/index.ts
- server/index.ts
- web/screens/Settings/Advanced/index.tsx
- Introduce ~/jan/logs which include app, api and nitro logs.
- Resolve dependencies circular issues in @janhq/core module
- Optional import from node module, avoid crashing from extension module. E.g. import log function
- #1430 
- How logs are wiped? clean up periodically?
- Opt-out option on GUI?
> refactor: add app and nitro log - resolve dependencies issue

- web/screens/ExploreModels/ExploreModelItemHeader/index.tsx
Added hub recommendation label
fixes #1384 
https://github.com/janhq/jan/assets/10354610/0c327f00-5df4-45c9-a47d-3ba52b982887
> feat: hub recommendation labels

- README.md
Revert URL release in readme to version 0.4.3
> Revert URL release in readme to version 0.4.3

- extensions/model-extension/package.json
- models/capybara-34b/model.json
- models/codeninja-1.0-7b/model.json
- models/deepseek-coder-1.3b/model.json
- models/deepseek-coder-34b/model.json
- models/dolphin-2.7-mixtral-8x7b/model.json
- models/llama2-chat-70b-q4/model.json
- models/llama2-chat-7b-q4/model.json
- models/mistral-ins-7b-q4/model.json
- models/mixtral-8x7b-instruct/model.json
- models/noromaid-7b/model.json
- models/openchat-3.5-7b/model.json
- models/openhermes-neural-7b/model.json
- models/phi-2-3b/model.json
- models/phind-34b/model.json
- models/solar-10.7b-slerp/model.json
- models/starling-7b/model.json
- models/stealth-v1.2-7b/model.json
- models/tinyllama-1.1b/model.json
- models/trinity-v1.2-7b/model.json
- models/tulu-2-70b/model.json
- models/wizardcoder-13b/model.json
- models/yarn-mistral-7b/model.json
- models/yi-34b/model.json
- web/containers/CardSidebar/index.tsx
- web/hooks/useUpdateModelParameters.ts
- Add stop word for the prompt template correction.
- Enable stop settings and correct request body to send stop words array
- Fix "Show in Finder" title according to platform specific
> fix: stop word update

- docs/docusaurus.config.js
- This pull request fix the Algolia configuration. 
- Made some changes on Algolia platform for re-indexing and indices to make sure search functions work correctly
-
> docs: fix algolia configuration

- docs/src/css/custom.css
- Change active color
- Seach bar not displaying well in dark mode
Before:
After:
> chore: fix darkmode docs

- docs/docusaurus.config.js
- docs/src/containers/Banner/index.js
- docs/src/containers/Footer/index.js
- please automerge for me
- #1508
> docs: fix x handles

- web/containers/DropdownListSidebar/index.tsx
- web/utils/componentSettings.ts
Recent update to fix the default value actually blocked the slider, the proper fix is to set default value when thread is created instead
#1546
> fix: could not change model params settings

- web/containers/DropdownListSidebar/index.tsx
showing label compatibility on dropdown list model in thread right panel
#1533
> feat: add compatibility tag to model selection in right panel

- extensions/conversational-extension/src/index.ts
- Fix an exception when trying to delete not exists thread directory
- #1336
> fix(Thread): #1336 not allow creating too many unfinished thread

- core/src/node/api/common/builder.ts
- extensions/conversational-extension/src/index.ts
- web/containers/Layout/TopBar/index.tsx
- web/hooks/useCreateNewThread.ts
- web/hooks/useGetAssistants.ts
- Store the thread file when user change thread settings.
- #1212
> fix(Thread): #1212 thread.json not created when user change thread settings

- core/src/node/api/common/builder.ts
- docs/openapi/jan.yaml
- docs/openapi/specs/models.yaml
- docs/openapi/specs/threads.yaml
- Update swagger page to latest supported APIs.
- Update some default params so user can try it out immediately.
- Fix some issue with some APIs: DELETE model / DELETE thread
- #1511
> fix(API): #1511 update swagger page

- extensions/inference-nitro-extension/src/index.ts
- extensions/inference-nitro-extension/src/module.ts
- web/hooks/useActiveModel.ts
Fixed an issue where model settings are not applied when loading model (legacy issue).
#1569
> fix: #1569 - Does not apply thread settings when loading model

- .github/pull_request_template.md
- need specific syntax for github to auto close issues from merged PRs
- pls auto merge for me. 
-
> chore: issues should auto close with PRs through template

- .github/ISSUE_TEMPLATE/bug_report.md
> chore: teach how to attach logs

- web/containers/SliderRightPanel/index.tsx
Validate max and min value using onBlur instead onChange
- Closes #1573  
https://github.com/janhq/jan/assets/10354610/a10978cb-1d6e-43e5-9e42-a605ebc3ff40
> fix: enable user set value manually model setting from input

- docs/docs/guides/08-troubleshooting/02-somethings-amiss.mdx
- docs/docs/guides/08-troubleshooting/03-gpu-not-used.mdx
- docs/docs/guides/08-troubleshooting/04-how-to-get-error-logs.mdx
- Add How to Get Error Logs Guide
- Closes #
- Closes #
> docs: add 04-how-to-get-error-logs.mdx

- web/screens/Settings/Advanced/index.tsx
Fix duplicated command shortcut instruction
- #1548
> fix: #1548 - duplicate command shortcut instruction

- electron/package.json
- Upgrade node-fetch to fix vulnerable issue
> chore(Dependencies): upgrade node-fetch to fix vulnerable issue

- web/containers/ShortcutModal/index.tsx
- web/screens/Settings/Advanced/index.tsx
- Clean up the ShortcutModal, moving it out to another component rather than put it in Advanced setting screen.
> chore(ShortcutModal): clean up shortcut modal

- docs/src/containers/Footer/index.js
- Correct footer
- Closes #
- Closes #
> fix: correct footer

- docs/docs/guides/08-troubleshooting/05-permission-denied.mdx
- Add troubleshooting/permission-denied
- Closes #
- Closes #
> docs: add troubleshooting permission denied

- electron/main.ts
- electron/utils/menu.ts
- Fixed an issue where app missing option to check for update in Windows and Linux.
- Fixed an issue where app shows no update available but actually does.
- Correct user guide url
- Closes #1623 
- Closes #1622
> fix: enable check for update on all supported platforms

- web/containers/DropdownListSidebar/index.tsx
> fix: wrong selected model ref

- web/containers/Layout/TopBar/index.tsx
- Randomly auto select text when you double click icon for collapse panel
- Closes #1461 
https://github.com/janhq/jan/assets/10354610/de529678-0033-4d08-8ad3-87771eee794b
> fix: auto select text when collapse panel

- web/screens/Settings/Appearance/index.tsx
- web/screens/Settings/index.tsx
Restructuring the information architecture of it
- Closes #1616
> feat: relayout left panel setting page

- docs/docs/guides/02-installation/06-hardware.md
- docs/docs/guides/02-installation/07-antivirus-compatibility-testing.md
- Add Antivirus Compatibility Testing Docs based on current testing status
- Closes #
- Closes #
> docs: add antivirus compatibility testing

- .github/workflows/clean-cloudflare-page-preview-url-and-r2.yml
- .github/workflows/clean-cloudflare-page-preview-url.yml
- .github/workflows/jan-docs.yml
- .github/workflows/jan-electron-build-nightly.yml
Feature add schedule clean cloudflare page and r2
> Feature add schedule clean cloudflare page and r2

- docs/docs/template/QA_script.md
- Add QA Script `docs/docs/template/QA_script.md`
- For each release, we will pull this QA_script into hackmd and start QA progress on hackmd. (Tested this pull feature)
- Closes #763 
- Closes #
> docs: add QA Script

- extensions/inference-nitro-extension/src/node/index.ts
fix bug #1650 hogging resources
> fix bug #1650 hogging resources

- .github/workflows/clean-cloudflare-page-preview-url-and-r2.yml
- .github/workflows/codeQL-analysis.yml
- .github/workflows/jan-docs.yml
- .github/workflows/jan-electron-build-nightly.yml
- .github/workflows/jan-electron-build-pre-release.yml
- .github/workflows/jan-electron-build.yml
- .github/workflows/jan-electron-linter-and-test.yml
- .github/workflows/template-build-linux-x64.yml
- .github/workflows/template-build-macos.yml
- .github/workflows/template-build-windows-x64.yml
- .github/workflows/template-get-update-version.yml
- .github/workflows/template-noti-discord-and-update-url-readme.yml
- electron/package.json
Cherrypick cicd to main branch to apply new gitflow
> Cherrypick cicd to main branch to apply new gitflow

- docs/docs/guides/08-troubleshooting/02-somethings-amiss.mdx
- Add additional reasons to somethings amiss
- Closes #
- Closes #
> docs: update 02-somethings-amiss

- web/containers/Loader/ModelStart.tsx
#1606 
https://github.com/janhq/jan/assets/10354610/ec74a5f5-6003-4bfc-be58-f642bdca67e1
> fix: stoping model show starting model

- web/containers/DropdownListSidebar/index.tsx
- web/containers/OpenAiKeyInput/index.tsx
- web/screens/LocalServer/index.tsx
- disable api key field while server is running
- remove secondary title right panel
- #1251
- #1697
> fix: disable api key field while server is running

- web/containers/DropdownListSidebar/index.tsx
- web/containers/OpenAiKeyInput/index.tsx
> fix: switching loader from remote to local model from thread right panel

- server/package.json
- web/screens/LocalServer/Logs.tsx
Fixed an issue where Jan server (localhost:1337) is showing a blank page
- Closes #1674
> fix: Jan server is showing blank page

- docs/openapi/jan.yaml
- server/index.ts
- Update the port and host used for swagger
- Closes #1720
> fix(API): #1720 host/port provided in the local API server does not fully applied

- extensions/model-extension/src/index.ts
- models/config/default-model.json
- Fix issue size of model binary file does not shown.
- Fix default try to use GPU, if not, fallback to CPU.
- #1662
- #1647
> fix(Model): #1662 imported model does not use gpu

- .github/workflows/jan-electron-build-nightly.yml
- .github/workflows/jan-electron-build-pre-release.yml
- README.md
Correct download url readme
- Closes #1718
> Correct download url readme

- docs/docs/guides/08-troubleshooting/06-unexpected-token.mdx
- docs: add troubleshoot unexpected token 
- Closes #1708
> docs: add troubleshoot unexpected token

- .github/workflows/template-build-linux-x64.yml
- .github/workflows/template-build-macos.yml
- .github/workflows/template-build-windows-x64.yml
Override Cloudflare R2 public with generic provider
- Closes #1725
> Fix autoupdater nightly build error

- web/screens/LocalServer/index.tsx
Starting model when user start server
- #1697
Issue @Van-QA Number 10
> fix: active model when start server

- .github/workflows/jan-electron-build-nightly.yml
Fix error nightly build schedule run failed
> Fix error nightly build schedule run failed

- web/containers/Layout/Ribbon/index.tsx
- web/screens/LocalServer/index.tsx
- Validation range input port
#1697
> fix: input port have range validation

- uikit/src/button/index.tsx
- uikit/src/button/styles.scss
- uikit/src/input/styles.scss
- web/containers/Layout/index.tsx
- web/containers/ShortcutModal/index.tsx
- web/hooks/useVaultDirectory.ts
- web/screens/Settings/Advanced/DataFolder/ModalChangeDirectory.tsx
- web/screens/Settings/Advanced/DataFolder/ModalErrorSetDestGlobal.tsx
- web/screens/Settings/Advanced/DataFolder/ModalSameDirectory.tsx
- web/screens/Settings/Advanced/DataFolder/index.tsx
- web/screens/Settings/Advanced/index.tsx
- web/screens/Settings/CoreExtensions/index.tsx
- web/screens/Settings/index.tsx
> feat: update UI allow user change folder

- README.md
> Test protect rule

- .github/workflows/jan-electron-build-nightly.yml
Correct bash script syntax in ci
> Correct bash script syntax in ci

- web/screens/LocalServer/Logs.tsx
- web/screens/SystemMonitor/index.tsx
- Fix log not shown on windows
- Move CPU before RAM in System Monitor
> fix(Log): server log is not display in windows

- web/screens/LocalServer/index.tsx
- No ticket cc @Van-QA @louis-jan
> regression fix: input port not accept alphabets

- web/screens/Settings/Models/Row.tsx
Fixed and issue where start model action is not responding (model settings page)
- Closes #
> fix: can not start model when server is not enabled from model settings page

- web/screens/Settings/Models/Row.tsx
Fixed an issue where delete model button is not responding.
- Closes #1770
> fix: could not delete model

- .github/workflows/jan-docs.yml
Docs publish to github page trigger on push to docs branch
> Docs publish to github page trigger on push to docs branch

- core/src/types/config/appConfigEvent.ts
- core/src/types/config/index.ts
- extensions/inference-openai-extension/src/index.ts
- web/hooks/useEngineSettings.ts
Fixed an issue where changing API Key still allow user to chat using the previous key.
- Closes #1780
> fix: api settings are not applied on changes

- core/src/node/log.ts
- web/hooks/useVaultDirectory.ts
- fix app log not printing out
> fix: app log not being printed

- .devcontainer/devcontainer.json
Adds node:20 devcontainer for codespaces and other options that supports devcontainer setups.
> adds devcontainer

- .github/workflows/jan-electron-build-nightly.yml
CI nightly update trigger to 3AM UTC +7 Tuesday, Wednesday, and Thursday
> CI nightly update trigger to 3AM UTC +7 Tuesday, Wednesday, and Thursday

- docs/docs/guides/04-using-models/03-integrate-with-remote-server.mdx
- Improve the guide by adding model list
- Closes #1748 
- Closes #
> docs: add OpenAI model list

- .gitignore
- extensions/assistant-extension/src/index.ts
- extensions/monitoring-extension/src/index.ts
- web/containers/Layout/index.tsx
- web/containers/Providers/EventHandler.tsx
- web/containers/Providers/EventListener.tsx
- web/hooks/useGetConfiguredModels.ts
- web/screens/Chat/MessageToolbar/index.tsx
- Clean up some code and add exhaustive dependenies
> chore: clean up code and remove some lint suppression

- uikit/src/input/styles.scss
- uikit/src/select/styles.scss
- web/screens/LocalServer/index.tsx
Fix low contrast text input in darkmode
- #1697
@Van-QA Number 15 and 16
> regression fix: input disabled darkmode

- extensions/inference-openai-extension/src/index.ts
> fix: stop openai inference raises something amiss

- web/containers/DropdownListSidebar/index.tsx
- web/containers/OpenAiKeyInput/index.tsx
- web/hooks/useEngineSettings.ts
- web/hooks/useRecommendedModel.ts
- web/screens/Chat/Sidebar/index.tsx
- web/screens/LocalServer/index.tsx
- Fix issue that user can't use model in Model hub to create new thread
https://github.com/janhq/jan/assets/10397206/1d2a33c2-53c5-470d-9240-0bdec6fbf1f7
> fix: user can't use a model in model hub

- web/containers/DropdownListSidebar/index.tsx
- web/screens/LocalServer/index.tsx
The first-time user install app, there is no thread created yet, user visits API settings page will not see model selection.
- Closes https://github.com/janhq/jan/issues/1697#issuecomment-1911459168 No14
> fix: model selection does not show in API settings page

- web/containers/Layout/index.tsx
- web/screens/Settings/Advanced/DataFolder/ModalChangeDirectory.tsx
- web/screens/Settings/Advanced/DataFolder/ModalErrorSetDestGlobal.tsx
- web/screens/Settings/Advanced/DataFolder/ModalSameDirectory.tsx
- web/screens/Settings/Advanced/DataFolder/index.tsx
- Fix user cannot change jan data folder.
- https://github.com/janhq/jan/issues/1804
https://github.com/janhq/jan/assets/10397206/59f368b4-6cd8-407b-916a-377ae932b40b
> fix: cannot change jan data folder

- web/hooks/usePath.ts
- web/screens/Settings/Advanced/DataFolder/index.tsx
- Fix when user can't open model folder at local api server.
https://github.com/janhq/jan/assets/10397206/436c66fc-a59d-46b3-b9ac-31798bb33edd
- #1806
> fix: user can't view model setting in local api server

- .github/workflows/update-release-url.yml
- README.md
Update release url on README to default branch instead of main branch
- Closes #
- Closes #
> Update release url on README to default branch instead of main branch

- extensions/inference-openai-extension/src/index.ts
- web/containers/Layout/TopBar/index.tsx
Its to unblock #1830
- Closes #
- Closes #
> chore: resolve main conflict

- web/screens/LocalServer/index.tsx
highlight menu dropdown server options
#1697
> fix: highlight menu dropdown server options

- extensions/assistant-extension/package.json
Add code sign step for darwin assistant extension
- Closes #
- Closes #
> Add code sign step for darwin assistant extension

- web/screens/Settings/Advanced/index.tsx
Toggle off experimental feature for Jan Data Folder
- Closes #
- Closes #
> chore: Jan Data Folder setting is no longer an experimental feature

- web/screens/Chat/ChatInput/index.tsx
- Fix issue chat box take all the focus.
- #1854
> fix: all input text box are disabled

- extensions/assistant-extension/src/node/tools/retrieval/index.ts
- extensions/conversational-extension/src/index.ts
- web/containers/Providers/EventHandler.tsx
- web/screens/Chat/ChatBody/index.tsx
- web/screens/Chat/MessageToolbar/index.tsx
Fixed an issue where app always ask for api key when retrieval tool is toggled on.
- Closes #
- Closes #
> fix: retrieval always ask for api key

- web/screens/Chat/AssistantSetting/index.tsx
fix auto collapse panel and set retrieval with correct value 
#1848
> fix: auto collapse retrieval setting while update config

- web/screens/Settings/Advanced/DataFolder/index.tsx
- web/screens/Settings/Advanced/index.tsx
Remove open app directory from setting and move into folder icon
> feat: move open app directory into icon folder

- web/screens/Settings/Advanced/DataFolder/ModalConfirmDestNotEmpty.tsx
- web/screens/Settings/Advanced/DataFolder/index.tsx
> fix: add dialog confirm when move folder and next dest isn't empty

- web/containers/Providers/EventHandler.tsx
- web/containers/Providers/index.tsx
- web/containers/Toast/index.tsx
- web/hooks/useActiveModel.ts
- web/hooks/useDeleteModel.ts
- web/hooks/useDeleteThread.ts
- web/hooks/useDownloadState.ts
- web/hooks/useSendChatMessage.ts
- web/screens/Chat/index.tsx
- web/screens/Settings/Advanced/index.tsx
adding snackbar function similar with toaster
#1639
> feat: add snackbar component and update style side banner

- web/screens/Chat/ChatInput/index.tsx
- web/screens/Chat/Sidebar/index.tsx
- web/screens/Chat/index.tsx
- Flag Retrieval as experimental feature
Turn off experimental features will:
- Hide Retrieval Setting section
- Hide file upload button
- Block file drag and drop 
- Closes #
> chore: mark RAG as experimental feature

- extensions/inference-nitro-extension/src/node/index.ts
> feat: Add default value for ngl

- web/containers/Providers/EventHandler.tsx
- web/hooks/useCreateNewThread.ts
- web/hooks/useSendChatMessage.ts
- web/screens/Chat/ThreadList/index.tsx
- web/screens/Settings/Advanced/FactoryReset/ModalConfirmReset.tsx
- Fixed an issue where app does not show generate response after the first time sending message
- Fixed an issue where app create new thread after restarting the app even the thread list is not empty
- Closes #
- Closes #
> fix: show generate response on message send

- docs/docs/guides/08-troubleshooting/07-undefined-issue.mdx
- docs: add troubleshoot undefined issue
- Closes #
- Closes #
> docs: add troubleshoot undefined issue

- extensions/model-extension/src/index.ts
Root cause: multiple model binaries support update added new N/A fields, which must be overwritten.
Here is the generated model.json with the fix
- #1897
> fix: broken manual import model with NA fields

- web/containers/Providers/index.tsx
Regarding the white window issue, if you are using the nightly build, the most likely cause is the migration of extensions with each update (required for the new document upload feature - RAG).
We will include a loading indicator as well as additional checks to reduce migration time
NOTE: Typo fixed: `Preparing Update...`
- #1884
> fix: migration loading indicator

- .github/workflows/template-build-macos.yml
- extensions/assistant-extension/sign.sh
Switch from macos-latest github hosted runner to self hosted runner
- Closes #
- Closes #
> Switch from macos-latest github hosted runner to self hosted runner

- .github/workflows/clean-cloudflare-page-preview-url-and-r2.yml
Cloudflare R2 clean every 10 days
- Closes #
- Closes #
> Cloudflare R2 clean every 10 days

- docs/docs/about/01-README.md
- Update https://jan.ai/about/#analytics based on Umami analytics
- Closes #
- Closes #
> docs: update analytics content

- web/utils/umami.tsx
- So many issues with umami integration script, let's simply make API request to /api/send (according to their docs)
- Closes #
> fix: umami analytics send app loaded event

- docs/docs/template/QA_script.md
Adding new checklist items to cover:
> Move Jan Data App: https://github.com/janhq/jan/issues/1010
> Factory Settings: https://github.com/janhq/jan/issues/1620
> docs: adding new feature for v0.4.6 to release checklist

- web/screens/ExploreModels/ExploreModelItemHeader/index.tsx
- #1908 
https://github.com/janhq/jan/assets/10354610/22996f00-b866-491b-af57-e8c326883c75
> fix: download model will close panel item hub

- web/screens/Chat/SimpleTextMessage/index.tsx
problem we use `dangerouslySetInnerHTML`
-  #1815 
- #1849 
- #1939
> fix: markdown render for chat completion role user

- docs/blog/authors.yml
> chore: Add Author - Hiro

- docs/blog/authors.yml
- add me as one of Jan's author.
> chore: add author james

- web/containers/Providers/EventHandler.tsx
- web/helpers/atoms/ChatMessage.atom.ts
- web/hooks/useCreateNewThread.ts
unblock user when get something a miss to create new thread, solution we need check last message status
- #1887 
https://github.com/janhq/jan/assets/10354610/8947d412-9600-4445-a19b-c1d17d56759b
> fix: update conditional check last status message

- Dockerfile.gpu
- README.md
- docker-compose.yml
Change env Dockerfile.gpu and update README
- Closes #
- Closes #
> Change env Dockerfile.gpu and update README

- web/public/umami_script.js
- web/utils/umami.tsx
- Integrate Umami based on our first approach #1809 
- Store the script.js locally in public folder
- Closes #
- Closes #
> feat: integrate umami script locally

- docs/blog/authors.yml
> docs: add author.yml

- web/containers/Providers/EventHandler.tsx
- web/screens/LocalServer/index.tsx
Show information that the model is not started
- #1911
> fix: model failed to load but the server started successfully

- core/src/types/message/index.ts
- core/src/types/message/messageEntity.ts
- core/src/types/message/messageRequestType.ts
- extensions/inference-nitro-extension/src/index.ts
- extensions/inference-openai-extension/src/index.ts
- web/containers/Providers/EventHandler.tsx
- web/hooks/useSendChatMessage.ts
Fixed Issue: https://github.com/janhq/jan/issues/979
Alternative solution of https://github.com/janhq/jan/pull/1803
@louis-jan @hiro-v @urmauur 
_Still trying to figure out the race conditions, and a way to update the title in real-time_
> Alternative solution for `Thread titles should auto-summarize Topic`

- electron/package.json
Fix macos auto update failed on nightly build
- Closes #
- Closes #
> Fix macos auto update failed on nightly build

- electron/handlers/update.ts
- extensions/inference-openai-extension/src/helpers/sse.ts
- web/app/error.tsx
Currently, App just fails when there is any client error occurred. The app terminates with no clear reasons. 
ref:  [React Error Boundaries](https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary)
https://nextjs.org/docs/pages/building-your-application/configuring/error-handling
- #1967
> fix: app fails gracefully with clear error messages

- web/containers/Providers/EventHandler.tsx
1. Decouple thread message and title update logic
2. Fixed an issue where thread title could be undefined
3. Thread summary should be a non streaming request
4. Summary the entire thread messages instead of the first prompt
> fix: decouple thread summary update

- docs/docs/guides/08-troubleshooting/03-gpu-not-used.mdx
- Improve the documentation 03-gpu-not-used 
- Added RTX issues
- Closes #1946 
- Closes #1819
> docs: update 03-gpu-not-used with RTX issues

- web/containers/Providers/Jotai.tsx
- web/helpers/atoms/ChatMessage.atom.ts
- web/hooks/useSendChatMessage.ts
- web/screens/Chat/EditChatInput/index.tsx
- web/screens/Chat/MessageToolbar/index.tsx
- web/screens/Chat/SimpleTextMessage/index.tsx
- #1744 
https://github.com/janhq/jan/assets/10354610/6129f7bf-7999-4958-9640-d836b3e21621
> feat: add edit messages users

- web/containers/ServerLogs/index.tsx
- web/hooks/useCreateNewThread.ts
- web/hooks/useLogs.tsx
- web/services/restService.ts
Issue:
https://github.com/janhq/jan/assets/133622055/3be557a1-b607-4bd0-8c63-1e0282d7971e
Addressed: 
Using polling interval instead of state update loop
- Closes #
- Closes #
> fix: resolve state update loop infinitive rerendering

- Dockerfile
- Dockerfile.gpu
- server/package.json
server install core using link instead of file
- Closes #
- Closes #
> server install core using link instead of file

- web/containers/CardSidebar/index.tsx
- web/screens/Chat/Sidebar/index.tsx
> fix: content setting right panel default to collapse

- core/src/node/api/processors/extension.ts
- electron/utils/dev.ts
- web/containers/ServerLogs/index.tsx
- web/hooks/useFactoryReset.ts
- Factory reset does not remove jan data folder.
- #1907
> fix: factory reset not remove jan data folder

- web/containers/Providers/EventHandler.tsx
- Add thread context to give a better summarization.
- Add rules:
- Thread title should less than 10 words
- No new line character is present
- Remove non-alphanumeric characters
OpenChat
Tiny Llama
- #2035
> fix: app should generate thread title with length restriction

- web/containers/ServerLogs/index.tsx
- web/screens/Settings/Advanced/index.tsx
- Disable the dropdown if there's no GPU available.
- Small UI fixes.
- #1851
> fix: ui for disabled state of gpu acceleration

- extensions/model-extension/src/index.ts
- web/screens/Settings/Advanced/index.tsx
- Disable GPU dropdown box if there's no compatible GPU
> fix: disable gpu drop down box if there's no GPU ready

- web/screens/Chat/index.tsx
Update message waiting to send copy
- #1312
> fix: update copy of message queue

- core/src/node/helper/resource.ts
- server/index.ts
- web/screens/LocalServer/index.tsx
> fix: local server start error should not change to started state

- web/screens/Settings/Advanced/index.tsx
- When GPU settings are toggled, the model should stop running as well
-Fixed #1906
> fix: should stop running the model when GPU settings are changed

- web/hooks/useDownloadState.ts
- Fix issue shown infinity while downloading model.
> fix: infinity showed when haven't get total size

- electron/handlers/update.ts
- electron/package.json
- electron/utils/menu.ts
- models/mistral-ins-7b-q4/model.json
- models/openhermes-neural-7b/model.json
- models/trinity-v1.2-7b/model.json
- Correct check for update information
- Correct app display name
- Correct model cover urls
- #1622
> fix: check for updates should show no update are available on the latest build

- core/src/node/api/restful/helper/builder.ts
- server/package.json
- Fixed an issue where server crashed on missing module (docker - production)
- Closes #
- Closes #
> fix: server crashes on missing module

- web/hooks/useSendChatMessage.ts
- Something's amiss thread blocks thread creation
- https://github.com/janhq/jan/issues/1887#issuecomment-1931205720
> fix: failed to send message blocks thread creation

- web/screens/Chat/ChatInput/index.tsx
> fix: make text input scrollable

- extensions/model-extension/package.json
- models/dolphin-phi-2/model.json
- models/llamacorn-1.1b/model.json
- models/stable-zephyr-3b/model.json
- Fixed an issue where model.json files contains wrong field name
- Closes #
- Closes #
> fix: broken model.json update

- core/src/node/api/processors/app.ts
- server/index.ts
- web/screens/LocalServer/index.tsx
- Not start server if the specified port is occupied.
- #1903
> fix: check if port is occupied before start local server

- web/containers/DropdownListSidebar/index.tsx
- Minor fix caret down when dropdown list sidebar for remote model
-  #1893
https://github.com/janhq/jan/issues/1893#issuecomment-1951196613
> fix: remove caret down icon when tab selected into remote model

- web/containers/Layout/BottomBar/index.tsx
- web/screens/Chat/Sidebar/index.tsx
- Expand Tools section by default
- Closes #
- Closes #
> fix: tools section should be expanded by default

- electron/main.ts
- Printing app version into log.
> chore: add app version into log

- web/containers/Layout/Ribbon/index.tsx
- web/screens/Chat/EditChatInput/index.tsx
- web/screens/Chat/MessageToolbar/index.tsx
- web/screens/Chat/ThreadList/index.tsx
https://github.com/janhq/jan/assets/10354610/591dd5ca-b41e-457b-8133-68fd0529b2a4
[- Closes #](https://github.com/janhq/jan/issues/1744#issuecomment-1955851436)
> fix: flow edit message

- extensions/inference-nitro-extension/src/node/execute.ts
Regression: Linux vulkan binary path
- Closes #
- Closes #
> Regression: Linux vulkan binary path

- web/containers/ModalTroubleShoot/index.tsx
- web/screens/Chat/SimpleTextMessage/index.tsx
> fix: chore UI

- extensions/inference-nitro-extension/src/node/accelerator.ts
- Fixed an issue where vulkan is enabled by default but actually not
- Closes #
> fix: correct vulkan settings

- README.md
- docs/docs/about/2035.mdx
- docs/docs/about/about.md
- docs/docs/about/roadmap.md
- docs/sidebars.js
- docs/src/containers/Footer/index.js
> docs: hide incomplete pages

- web/containers/Layout/BottomBar/SystemMonitor/index.tsx
- web/containers/Layout/BottomBar/index.tsx
- https://github.com/janhq/jan/issues/2039#issuecomment-1960896368
cc @Van-QA 
-  #2039
> fix: system monitor ui

- docs/docs/how-we-work/engineering/acknowledgements.md
- docs/sidebars.js
- Add third-pary-libraries to acknowledgements page
- llama cpp
- langchain
- Closes #2109
- Closes #
> docs: add upstream acknowledgements

- docs/docs/guides/02-installation/05-docker.md
- docs: update Run Jan in Docker Mode
- Closes #2118
- Closes #
> docs: update run Jan in Docker mode

- web/screens/ExploreModels/HuggingFaceConvertingErrorModal/index.tsx
- web/screens/ExploreModels/index.tsx
- Make convert gguf as experimental feature
> chore: make convert gguf as experimental feature

- extensions/huggingface-extension/package.json
- extensions/monitoring-extension/package.json
Huggingface extension add codesign step for building on darwin
- Closes #
- Closes #
> Huggingface extension add codesign step for building on darwin

- web/containers/Layout/Ribbon/index.tsx
[convo](https://github.com/janhq/jan/issues/2039#issuecomment-1963447595)
cc @Van-QA 
#2039
> fix: system monitor expand overlap tooltip ribbon

- README.md
- Update profile name from `gpu` to `gpu-fs`
- Closes #
- Closes #
> fix: wrong profile parameter in docker command

- web/containers/Layout/BottomBar/SystemMonitor/index.tsx
- web/utils/converter.ts
fix style gpu list on system monitor
https://github.com/janhq/jan/issues/2039#issuecomment-1965920238
- #2039
> fix: style list of gpus on system monitor

- web/screens/ExploreModels/index.tsx
- https://discord.com/channels/@me/1192032350880661594/1212010179240132690
- Closes #
- Closes #
> fix: change button import model on hub page

- docs/docs/community/community.mdx
- docs/src/containers/Footer/index.js
- Add Jan newsletter
- Closes #2153
- Closes #
> docs: add Jan newsletter

- docs/docs/guides/02-installation/05-docker.md
- Follow fix #2159, update Docker guide
- Closes #
- Closes #
> docs: update docker command

- docs/docs/guides/07-integrations/01-integrate-continue.mdx
Please automerge this PR for me once LGTM
> docs: Update 01-integrate-continue.mdx

- docs/docs/template/QA_script.md
Adding new checklist items to cover:
> Import model
> System monitor
> docs: adding new feature for v0.4.7 to release checklist

- docs/docs/guides/02-installation/08-antivirus-compatibility-testing.md
- Update language around antivirus checks as it is a part of CI
@hiento09 and @Van-QA to verify this is the case. 
**Please automerge for me if LGTM.**
- Closes #
- Closes #
> docs: Update 08-antivirus-compatibility-testing.md

- web/hooks/useGetHFRepoData.ts
- web/screens/ExploreModels/HuggingFaceRepoDataLoadedModal/index.tsx
- web/screens/ExploreModels/HuggingFaceSearchErrorModal/index.tsx
Even the input box specified that users should input following the format 'username/model-name,' but there are still cases where users input weird text such as random strings or full HuggingFace URLs.
- #2167
> fix: import from HuggingFace with random string is causing app crash

- electron/package.json
Macos Notarize migrage to new Team ID
- Closes #
- Closes #
> Macos Notarize migrage to new Team ID

- README.md
> docs: add command run API server without frontend

- .github/workflows/clean-cloudflare-page-preview-url-and-r2.yml
add prefix latest for task clean r2 bucket
- Closes #
- Closes #
> Chore: add prefix latest for task clean r2 bucket

- web/screens/Chat/ChatInput/index.tsx
- web/screens/Chat/index.tsx
- Add accepted format image file for drag and drop
- #2235
> fix: drag and drop support image format to support vision model 

- web/hooks/useLogs.tsx
- web/hooks/usePath.ts
- Remove user's path from log
- #2036
> fix: replaced user path from app log

- core/src/types/message/messageEntity.ts
- extensions/inference-openai-extension/src/helpers/sse.ts
- extensions/inference-openai-extension/src/index.ts
- web/screens/Chat/ChatBody/index.tsx
- web/screens/Chat/ErrorMessage/index.tsx
- web/utils/errorMessage.ts
- Not allow error message being sent along with conversation.
- #1932
> fix: error message being sent along with conversation when inference

- extensions/model-extension/package.json
- web/containers/DropdownListSidebar/index.tsx
- web/hooks/useUpdateModelParameters.ts
- web/screens/Chat/ChatInput/index.tsx
- web/screens/Chat/index.tsx
- web/utils/modelParam.ts
- Fixed the conditions to enable image upload button and drag image to upload action
- Bump model extension version so model.json will be migrated
Vision Model is enabled
Vision Model is disabled
RAG & Vision are disabled
Tooltips
> fix: image upload button and drag event are not enabled

- extensions/inference-openai-extension/src/helpers/sse.ts
- extensions/inference-openai-extension/src/index.ts
- extensions/inference-triton-trtllm-extension/src/index.ts
- web/helpers/atoms/ChatMessage.atom.ts
- web/hooks/useSendChatMessage.ts
- web/screens/Chat/ErrorMessage/index.tsx
- web/screens/Chat/MessageToolbar/index.tsx
- web/screens/Settings/Advanced/DataFolder/ModalErrorSetDestGlobal.tsx
- web/utils/errorMessage.ts
- Inconsistent error messages
- Wrong messages context
- Show according error message instead of showing only wrong API key.
- No longer error messages attached to the completion request
- Closes #
- Closes #
> fix: should not attach error messages to the completion request

- models/gemma-2b/model.json
- models/gemma-7b/model.json
- models/noromaid-7b/model.json
- models/qwen-7b/model.json
Adding Qwen 7B and Gemma 7B since our app supports these 2
> Chore: Update new models to model hub

- web/screens/ExploreModels/index.tsx
- Temporary remove convert model feature.
> chore: temporary remove convert model

- .github/workflows/template-build-macos-arm64.yml
- .github/workflows/template-build-macos-x64.yml
Add modify notary team in CI
- Closes #
- Closes #
> Add modify notary team in CI

- docs/docusaurus.config.js
> feat: changeEditUrl

- web/styles/base/global.scss
> fix: reducing height title-bar drag window for enable clickable quick ask

- electron/package.json
- electron/utils/selectedText.ts
> fix: replace robotjs by nutjs

- core/src/node/helper/config.ts
- core/src/types/config/appConfigEntity.ts
- web/containers/OnBoarding/AllSet/index.tsx
- web/containers/OnBoarding/Hotkey/index.tsx
- web/containers/OnBoarding/Welcome/index.tsx
- web/containers/Providers/DataLoader.tsx
- web/containers/Providers/OnBoardingListener.tsx
- web/containers/Providers/index.tsx
- web/helpers/atoms/AppConfig.atom.ts
- web/hooks/useAppConfig.ts
- web/hooks/useFactoryReset.ts
- web/hooks/useLogs.tsx
- web/hooks/usePath.ts
- web/screens/Settings/Advanced/DataFolder/index.tsx
- web/screens/Settings/EditModelInfoModal/index.tsx
- web/screens/Settings/ImportingModelModal/index.tsx
- Store onboarding state under app config
> chore: store onboarding state under app config

- core/src/node/helper/config.ts
- core/src/types/config/appConfigEntity.ts
- electron/main.ts
- electron/managers/window.ts
- web/containers/OnBoarding/Hotkey/index.tsx
- web/hooks/useFactoryReset.ts
- web/utils/keyboard.ts
- Register hot key dynamically at onboarding screen.
> feat: register hotkey quick ask dynamically

- electron/main.ts
- electron/package.json
- electron/utils/selectedText.ts
- electron/utils/tray.ts
- Fix the CI issue and refactor the code.
- Closes #
- Closes #
> fix: replace robotjs by nutjs (#2295)

- core/src/api/index.ts
- electron/handlers/native.ts
- electron/managers/window.ts
- web/containers/OnBoarding/AllSet/index.tsx
- web/containers/OnBoarding/Hotkey/index.tsx
- web/containers/OnBoarding/Welcome/index.tsx
- web/containers/Providers/QuickAskListener.tsx
- Sync onboarding state across windows
> chore: sync on boarding state across windows

- docs/docusaurus.config.js
- docs/src/css/custom.css
- Make redirect link from `/guides/install` into `/install`
- Fix the sidebar style for the dark mode version
- Closes #
> docs: Fix install slug and fix navbar style in darkmode

- web/hooks/useSendChatMessage.ts
- Message sent from quick ask does not sent to latest selected model.
> fix: message from quick ask not get the selected model

- electron/main.ts
- electron/managers/window.ts
- Wrong diff apply
- Open second instance of Jan App should focus on the first one
- Resize does not work on Windows 11
- Closes #
- Closes #
> fix: quick ask not show

- electron/managers/tray.ts
- Fixed an issue where app's tray block the update
- Closes #
- Closes #
> fix: jan app tray blocks app update

- web/app/search/SelectedText.tsx
- web/app/search/UserInput.tsx
- web/app/search/page.tsx
> feat: quick ask support dark mode

- .github/workflows/template-build-linux-x64.yml
- .github/workflows/template-build-macos-arm64.yml
- .github/workflows/template-build-macos-x64.yml
- .github/workflows/template-build-windows-x64.yml
Add brevo api secret for CI
- Closes #
- Closes #
> Add brevo api secret for CI

- docs/docs/about/about.md
- docs: update slogan based on @eckartal request
- 
- Closes #
- Closes #
> docs: update slogan

- core/src/node/helper/config.ts
- core/src/types/config/appConfigEntity.ts
- electron/main.ts
- electron/managers/tray.ts
- electron/managers/window.ts
- web/containers/Providers/DataLoader.tsx
- web/helpers/atoms/AppConfig.atom.ts
- web/hooks/useFactoryReset.ts
- web/screens/Settings/Advanced/index.tsx
Gate quick question regarding Feature Toggle.
- #2305
> fix: gate quick ask with feature toggle

- web/screens/Settings/Advanced/index.tsx
> fix: put quick ask feature toggle under experimental feature

- web/screens/ExploreModels/ExploreModelItemHeader/index.tsx
> fix: ts error when declar var in case

- web/screens/Settings/CoreExtensions/TensorRtExtensionItem.tsx
> fix: badge or progress tensorRtExtensionItem

- extensions/tensorrt-llm-extension/models.json
- extensions/tensorrt-llm-extension/src/index.ts
- web/screens/Chat/ChatInput/index.tsx
- Disable text retrieval and stream settings from TensorRTLLM model.json
-
- Closes #
- Closes #
> fix: disable rag & stream settings from tensorrt llm model.json

- extensions/monitoring-extension/src/node/index.ts
Fixed an issue where app does not recognize GPU first time launch
- Closes #
- Closes #
> fix: app does not recognize GPU first launch

- extensions/tensorrt-llm-extension/models.json
- extensions/tensorrt-llm-extension/package.json
- extensions/tensorrt-llm-extension/src/index.ts
- web/screens/Chat/ErrorMessage/index.tsx
- web/screens/Settings/CoreExtensions/TensorRtExtensionItem.tsx
- Fix incompatible GPU error message on Windows, in case there is no GPU found, it says only available on Windows / MacOS
- Closes #
- Closes #
> fix: incompatible GPU error message

- extensions/tensorrt-llm-extension/src/index.ts
> fix: wrong engine handling

- web/hooks/useCreateNewThread.ts
- Use model will create new thread with corresponding model.
- #2352
> fix: use model from model hub not load correct model in thread screen

- docs/docusaurus.config.js
- From: "/guides/using-models/"
To: "/guides/models-setup/"
- From: "/guides/using-extensions/"
To: "/guides/extensions/"
- Closes #
- Closes #
> docs: fix broken link by redirecting to the right paths

- extensions/tensorrt-llm-extension/package.json
- Remove Linux support for TensorRT
> chore: temporary remove linux from tensorrt support

- docs/docusaurus.config.js
- docs/src/styles/components/typography.scss
- docs/src/styles/tweaks/markdown.scss
> fix: line height typography blog and docs

- web/containers/Providers/QuickAskListener.tsx
- Only listen quick ask for desktop.
- #2394
> fix: unable to start web with quick ask

- extensions/tensorrt-llm-extension/package.json
- extensions/tensorrt-llm-extension/rollup.config.ts
- extensions/tensorrt-llm-extension/src/@types/global.d.ts
- extensions/tensorrt-llm-extension/src/index.ts
- extensions/tensorrt-llm-extension/src/node/index.ts
- update path for tensorrt engine
> chore: update path for tensorrt engine

- docs/docs/guides/common-error/broken-build.mdx
- pls auto merge for me thank you
- Closes #
- Closes #
> docs: Update broken-build.mdx

- web/screens/Settings/Advanced/index.tsx
- Turn off quick ask as soon as users disable the experimental feature.
- #2378
> fix: turn off experimental settings should also turn off quick ask

- web/hooks/useSendChatMessage.ts
- Fixed an issue where the app was glitching, generating ~1s before starting the model.
- https://github.com/janhq/jan/issues/2358#issuecomment-2002881409
> fix: app glitches 1s generating response before starting model

- .github/workflows/jan-electron-linter-and-test.yml
- web/hooks/useSettings.ts
- web/screens/Settings/Advanced/index.tsx
- Disabling experimental features does not affect Vulkan settings.
- Closes #
- Closes #
> fix: disable experimental feature should also disable vulkan

- core/src/node/helper/config.ts
- core/src/node/helper/resource.ts
- Fallback when WMIC is not installed on user's windows.
- #2201
> fix: fallback when WMIC is not installed on user's windows

- core/package.json
- core/src/api/index.ts
- core/src/extension.ts
- core/src/fs.ts
- core/src/node/api/processors/fsExt.ts
- extensions/tensorrt-llm-extension/models.json
- extensions/tensorrt-llm-extension/package.json
- extensions/tensorrt-llm-extension/rollup.config.ts
- extensions/tensorrt-llm-extension/src/index.ts
- web/containers/Providers/index.tsx
- web/screens/Settings/CoreExtensions/TensorRtExtensionItem.tsx
- web/screens/Settings/CoreExtensions/UpdateExtensionModal.tsx
It allows users to update engines.
1. Users can see whether there is an update from the extensions page.
2. Users should be warned that updating this extension may result in the loss of any custom models or data associated with the current version. We recommend backing up important data before proceeding with the update.
3. Clicking "update" will result in relevant model deletions, since the models are outdated. Old engines will be replaced.
- Closes #
> feat: TensorRT-LLM engine update support

- extensions/model-extension/src/index.ts
- extensions/monitoring-extension/src/node/index.ts
- extensions/tensorrt-llm-extension/src/index.ts
- extensions/tensorrt-llm-extension/src/node/index.ts
- web/screens/Settings/CoreExtensions/TensorRtExtensionItem.tsx
Tensorrt llm disable turing support
- Closes #
- Closes #
> Tensorrt llm disable turing support

- extensions/tensorrt-llm-extension/models.json
- extensions/tensorrt-llm-extension/src/node/index.ts
Quick add prompt template support 
- Closes #
- Closes #
> chore: add prompt template tensorrtllm

- extensions/tensorrt-llm-extension/models.json
- Fixed TensorRT Mistral 7B model.json
- Closes #
- Closes #
> fix: correct tensorrt mistral model.json

- docs/src/pages/index.js
- Update number of pull requests and contributors on website
- Closes #
- Closes #
> docs: update new website stats

- web/screens/Chat/SimpleTextMessage/index.tsx
https://github.com/janhq/jan/assets/10354610/3d531ee1-7af6-4780-9d1e-d74a1cb20b2b
#2064
> fix: remove decodeURI for avoid URI malformed

- .github/workflows/jan-electron-linter-and-test.yml
Disable antivirus check on PR
- Closes #
- Closes #
> Disable antivirus check on PR

- core/src/node/api/restful/common.ts
- Remove unnecessary slash.
- #2435
> fix: post to /v1/threads not found

- web/screens/Settings/Advanced/DataFolder/index.tsx
- Adding the missing state.
- #2326
> fix: move jan to not empty destination folder not functioning

- extensions/tensorrt-llm-extension/src/node/index.ts
- Should not crash but show corresponding error message
- Closes #
- Closes #
> fix: app raises port not available error

- Dockerfile
- Dockerfile.gpu
- charts/server/values.yaml
- docs/openapi/jan.json
- docs/openapi/jan.yaml
- docs/openapi/specs/assistants.yaml
- docs/openapi/specs/chat.yaml
- docs/openapi/specs/messages.yaml
- docs/openapi/specs/models.yaml
- docs/openapi/specs/threads.yaml
- Since we have removed documents from the monorepo repository, we should keep Swagger API docs in the desktop project until we support auto-generating Swagger specs. It's also to address the broken build step.
> fix: docker build fails

- extensions/assistant-extension/src/node/index.ts
- extensions/assistant-extension/src/node/retrieval.ts
- extensions/assistant-extension/src/tools/retrieval.ts
- extensions/model-extension/package.json
- models/groq-llama2-70b/model.json
- models/groq-mixtral-8x7b-instruct/model.json
- web/utils/messageRequestBuilder.ts
> fix: uploading a document mid-thread does not work

- extensions/assistant-extension/src/index.ts
- extensions/conversational-extension/src/index.ts
Replacing the hacky file check with a directory check would address this issue
- #2055 
- #2055
> fix: error invoking remote method readDirSync

- extensions/assistant-extension/src/node/retrieval.ts
- Fix an error that can't find nitro.json
> fix: rag is not working for nitro

- .github/workflows/auto-assign-milestone.yml
Add CI auto assign current milestone for merged PR
- Closes #2491 
- Closes #
> Add CI auto assign current milestone for merged PR

- web/hooks/useActiveModel.ts
- web/hooks/useSendChatMessage.ts
- After refactoring (#2470), most common cases' issues have been resolved. However, there is still a case where the user can spam, causing the button to get stuck.
- #2440
> fix: load model fails - generating button is not updated

- web/hooks/useDeleteThread.ts
- Remove corresponding files and memory when user clean thread.
- #2232
> fix: remove files and memory when user clean thread

- web/screens/ExploreModels/ExploreModelItemHeader/index.tsx
> fix: should not show broken image

- core/src/browser/extensions/engines/OAIEngine.ts
- core/src/types/message/messageEntity.ts
- web/containers/AutoLink/index.tsx
- web/screens/Chat/ErrorMessage/index.tsx
- Display default error message.
- #2512
> fix: display default error message

- README.md
- web/app/layout.tsx
- web/app/page.tsx
- web/app/search/SelectedText.tsx
- web/app/search/layout.tsx
- web/containers/Layout/TopBar/index.tsx
- web/containers/Layout/index.tsx
- web/containers/MainViewContainer/index.tsx
- web/containers/Providers/ClipboardListener.tsx
- web/containers/Providers/QuickAskListener.tsx
- web/containers/Providers/index.tsx
- web/package.json
- web/services/extensionService.ts
- web/styles/base/global.scss
- Using different layout to prevent duplicate installing extension.
- Fix an issue that can't drag Jan app in macos when drag on below half of top bar.
- Debounce sending quick ask to main app.
> fix: quick ask improvement

- extensions/model-extension/package.json
- models/tinyllama-1.1b/model.json
> Chore: Add tinyllama back to model hub

- extensions/inference-groq-extension/resources/settings.json
- web/screens/Settings/SettingMenu/index.tsx
- Some wording on extension setting screen.
- https://github.com/janhq/jan/issues/776#issuecomment-2031166778
> chore: some wordings in extension settings

- web/hooks/useSettings.ts
- Fixed an issue where disabling Vulkan causes users to be stuck in GPU-accelerated mode
- #2513
> fix: disabling Vulkan causes users to be stuck in GPU-accelerated mode

- web/screens/Chat/ErrorMessage/index.tsx
> fix: broken auto link

- core/src/browser/extensions/engines/helpers/sse.ts
Fixed an issue where Groq intermittently stops during long responses.
- #2561
> fix: groq frequently stops during long responses

- extensions/inference-groq-extension/resources/settings.json
- extensions/inference-openai-extension/resources/settings.json
- Update place holder value.
- #757
> chore: update place holder for api key of groq and openai

- web/containers/ModalTroubleShoot/AppLogs.tsx
- web/containers/ModalTroubleShoot/DeviceSpecs.tsx
- web/containers/ServerLogs/index.tsx
- Copied logs would be well formatted, instead of being in a single line.
- Closes #
- Closes #
> fix: copied logs line break

- .github/workflows/jan-electron-linter-and-test.yml
Change condition for trigger PR from forked repo
- Closes #
- Closes #
> Change condition for trigger PR from forked repo

- core/src/node/api/restful/helper/builder.ts
- electron/managers/window.ts
- web/hooks/useCreateNewThread.ts
- web/screens/Chat/ChatInput/index.tsx
- web/screens/Chat/EditChatInput/index.tsx
- [APP]::Error: TypeError: Object has been destroyed
- Closes #
- Closes #
> fix: object is destroyed block app exit

- web/screens/Chat/ErrorMessage/index.tsx
- web/screens/Chat/LoadModelError/index.tsx
-  Settings redirect is not leading users to the correct sub-page for settings
- #2572
> fix: redirect to extension setting

- .github/workflows/jan-electron-linter-and-test.yml
- Makefile
- electron/package.json
Feature playwright integrate report portal
- Closes #1937
- Closes #
> Feature playwright integrate report portal

- web/containers/DropdownListSidebar/index.tsx
> fix: model selector lack of warning message when no models downloaded

- core/src/types/miscellaneous/selectFiles.ts
- electron/handlers/native.ts
- web/screens/Settings/ChooseWhatToImportModal/index.tsx
- Filter GGUF files when import model.
- #2374
> chore: filter gguf files when importing model on windows

- server/index.ts
> fix: api server - server url prefix is not updated

- extensions/inference-nitro-extension/src/node/index.ts
- extensions/inference-triton-trtllm-extension/resources/settings.json
- web/hooks/useActiveModel.ts
- web/hooks/useSendChatMessage.ts
- web/screens/Chat/Sidebar/index.tsx
- Upon unloading a model while the loading process is ongoing, an unknown error is encountered.
- #2527
> fix: unload model while loading cause unknown error

- web/screens/Chat/ChatInput/index.tsx
- Add checking `isComposing` when handling the keyboard event in submitting a message. 
- Closes #2585
> handle enter key in cjk input method

- .github/workflows/jan-electron-linter-and-test.yml
Change report portal description to git commit hash
- Closes #
- Closes #
> Change report portal description to git commit hash

- .github/workflows/jan-electron-linter-and-test.yml
Enable ci linter workflow_dispatch event
- Closes #
- Closes #
> Enable ci linter workflow_dispatch event

- core/src/browser/extensions/engines/OAIEngine.ts
- extensions/inference-groq-extension/resources/settings.json
- extensions/inference-groq-extension/src/index.ts
- extensions/inference-mistral-extension/resources/settings.json
- extensions/inference-mistral-extension/src/index.ts
- extensions/inference-openai-extension/resources/settings.json
- extensions/inference-openai-extension/src/index.ts
- extensions/inference-triton-trtllm-extension/resources/settings.json
- extensions/inference-triton-trtllm-extension/src/index.ts
- Add default setting as fallback when user removed the endpoint from extension setting.
- #2659
> fix: add fallback as default endpoint for inference engine

- extensions/assistant-extension/package.json
- extensions/conversational-extension/package.json
- extensions/huggingface-extension/package.json
- extensions/inference-groq-extension/package.json
- extensions/inference-mistral-extension/package.json
- extensions/inference-nitro-extension/package.json
- extensions/inference-openai-extension/package.json
- extensions/inference-triton-trtllm-extension/package.json
- extensions/model-extension/package.json
- extensions/monitoring-extension/package.json
- extensions/monitoring-extension/src/node/index.ts
- extensions/tensorrt-llm-extension/package.json
- web/hooks/useActiveModel.ts
- web/hooks/useFactoryReset.ts
- Fixed an issue where the user would get stuck on the 'RESETTING DATA' screen while starting a model
- Read System Information before settings file is created would raise this error
- [#2555](https://github.com/janhq/jan/issues/2555)
> fix: race condition issue - reading settings.json file

- web/containers/Checkbox/index.tsx
- web/containers/ModelConfigInput/index.tsx
- web/containers/SliderRightPanel/index.tsx
- web/screens/Chat/EngineSetting/index.tsx
- web/screens/Chat/ModelSetting/SettingComponent.tsx
- web/screens/Chat/ModelSetting/index.tsx
- web/screens/Chat/Sidebar/index.tsx
- web/screens/LocalServer/index.tsx
- Handle the model setting changes.
> fix: not able to update model setting in local api

- .github/workflows/jan-electron-linter-and-test.yml
- .github/workflows/template-noti-discord-and-update-url-readme.yml
I test add clean jan folder and revert download url notification on discord
- Closes #
- Closes #
> I test add clean jan folder and revert download url notification on discord

- electron/managers/mainWindowConfig.ts
> fix: allow smaller min width

- web/screens/Chat/ModelSetting/index.tsx
- Fixed an error where users could not change thread settings
- Closes #
- Closes #
> fix: broken thread settings - component disabled

- web/containers/Providers/KeyListener.tsx
- web/containers/ShortcutModal/index.tsx
- web/screens/Settings/Advanced/index.tsx
- web/screens/Settings/Appearance/index.tsx
> fix: add new shortcut to create new thread

- core/src/types/setting/settingComponent.ts
- extensions/monitoring-extension/resources/settings.json
- uikit/src/input/index.tsx
- uikit/src/input/styles.scss
- web/containers/SliderRightPanel/index.tsx
- web/screens/Settings/SettingDetail/SettingDetailItem/SettingDetailTextInputItem/index.tsx
- update text alignment input component
- #2667
> enhancement: update input component dynamic text alignment

- extensions/inference-nitro-extension/package.json
- extensions/inference-nitro-extension/resources/models/command-r-34b/model.json
- extensions/inference-nitro-extension/resources/models/wizardcoder-13b/model.json
- web/containers/DropdownListSidebar/index.tsx
- web/containers/Layout/TopBar/index.tsx
- web/containers/ModelLabel/index.tsx
- web/screens/ExploreModels/ExploreModelItemHeader/index.tsx
- Add tags upcoming for CommandR
- Change wizard 13B to Q4 for consistancy
> Chore: Change CommandR to unavailable

- core/src/types/api/index.ts
- extensions/monitoring-extension/src/node/logger.ts
- Log directory is removed, which make log writing not possible.
- #2730
> fix: log is not generated after clear log from setting

- server/helpers/logger.ts
> fix: the log server does not write to the log file

- extensions/inference-nitro-extension/resources/models/phind-34b/model.json
- User can't download phin34 model
- #2568
> fix: cannot download phin34 model

- web/hooks/useUpdateModelParameters.ts
- web/utils/componentSettings.ts
> fix: broken stop word input - support multiple stop words

- web/screens/Settings/Advanced/index.tsx
- Wrong condition to enable GPU Acceleration
- Closes #
- Closes #
> fix: wrong condition for GPU acceleration

- extensions/inference-nitro-extension/package.json
- extensions/inference-nitro-extension/resources/models/phi3-3.8b/model.json
> Chore: Add phi-3

- extensions/inference-nitro-extension/package.json
- extensions/inference-nitro-extension/resources/models/command-r-34b/model.json
- extensions/inference-nitro-extension/resources/models/hermes-pro-7b/model.json
- extensions/inference-nitro-extension/resources/models/openhermes-neural-7b/model.json
- extensions/inference-nitro-extension/resources/models/stealth-v1.2-7b/model.json
- extensions/inference-nitro-extension/resources/models/trinity-v1.2-7b/model.json
- Llama3
- Command R
- Mistral 7b
- Closes #
> Feat: Change featured models

- core/src/browser/extensions/engines/OAIEngine.ts
- core/src/browser/extensions/engines/helpers/sse.ts
- core/src/types/api/index.ts
- extensions/inference-cohere-extension/README.md
- extensions/inference-cohere-extension/package.json
- extensions/inference-cohere-extension/resources/models.json
- extensions/inference-cohere-extension/resources/settings.json
- extensions/inference-cohere-extension/src/index.ts
- extensions/inference-cohere-extension/tsconfig.json
- extensions/inference-cohere-extension/webpack.config.js
- Add transformMessage to core
- Add transformResponse to core
- Add Cohere support
- Closes #
- Closes #
> feat: cohere remote API extension

- web/containers/Providers/EventHandler.tsx
Thanks to @jameshas for pointing out the fix
- #2809
> fix: infinite talking in auto thread titles generators

- extensions/inference-nitro-extension/resources/models/command-r-34b/model.json
- extensions/inference-nitro-extension/resources/models/hermes-pro-7b/model.json
- extensions/inference-nitro-extension/resources/models/openhermes-neural-7b/model.json
- extensions/inference-nitro-extension/resources/models/stealth-v1.2-7b/model.json
- extensions/inference-nitro-extension/resources/models/trinity-v1.2-7b/model.json
- Fix model version
- Closes #
Do I need to update version package? cc @louis-jan
> Feat: Bump version

- .github/workflows/template-build-macos-x64.yml
Fix macos ci
- Closes #
- Closes #
> Fix macos ci

- web/containers/ListContainer/index.tsx
- Remove scroll animation of chat screen
https://github.com/janhq/jan/assets/10397206/c400c4ab-b388-478a-8535-3a68f89478ec
> fix: remove scroll animation chat screen

- electron/package.json
- electron/utils/selectedText.ts
> chore: remove nutjs

- web/screens/Chat/EditChatInput/index.tsx
- Update class name syntaxes.
- Closes no issues
> fix: fix ESlint issue in EditChatInput

- web/screens/Chat/ModelSetting/SettingComponent.tsx
- web/screens/Chat/ModelSetting/predefinedComponent.ts
https://github.com/janhq/jan/pull/2870#issuecomment-2095470016
- Closes #
- Closes #
> fix: validate context length

- extensions/inference-cohere-extension/resources/settings.json
- extensions/inference-openrouter-extension/README.md
- extensions/inference-openrouter-extension/package.json
- extensions/inference-openrouter-extension/resources/models.json
- extensions/inference-openrouter-extension/resources/settings.json
- extensions/inference-openrouter-extension/src/index.ts
- extensions/inference-openrouter-extension/tsconfig.json
- extensions/inference-openrouter-extension/webpack.config.js
- Add OpenRouter extension
- Currently, only use chatgpt 3.5 for open router
- Closes #
- Closes #
> Add OpenRouter

- core/src/types/api/index.ts
- electron/handlers/native.ts
- electron/main.ts
- electron/managers/window.ts
- electron/package.json
- electron/utils/dev.ts
- web/containers/Layout/index.tsx
- web/containers/LoadingModal/index.tsx
- web/containers/Providers/DeepLinkListener.tsx
- web/containers/Providers/index.tsx
- Add deeplink support
https://github.com/janhq/jan/assets/10397206/d7339e3b-aa9e-4183-9e7a-822f58bed9b0
> feat: add deeplink support

- electron/managers/window.ts
- web/containers/LoadingModal/index.tsx
- web/containers/Providers/DeepLinkListener.tsx
- Fix deep link for linux user
Deeplink: `jan://models/huggingface/TheBloke/Magicoder-S-DS-6.7B-GGUF`
> fix: deeplink when app not open on linux

- extensions/inference-openai-extension/package.json
- extensions/inference-openai-extension/resources/models.json
Update gpt4o API to Jan
- Closes # https://github.com/janhq/jan/issues/2897
> Chore: Add gpt4o API

- electron/package.json
- electron/utils/selectedText.ts
Change to @kirillvakalov/nut-tree__nut-js
- Closes #
- Closes #
> Change to @kirillvakalov/nut-tree__nut-js

- core/src/browser/extensions/engines/helpers/sse.ts
- extensions/inference-cohere-extension/src/index.ts
- Fixed an issue where the Cohere extension does not work properly.
- #2684
> fix: cohere stream param does not work

- .github/workflows/template-build-macos-arm64.yml
- .github/workflows/template-build-macos-x64.yml
Change mac arm64 build use github runner
- Closes #
- Closes #
> Change mac arm64 build use github runner

- .github/workflows/template-build-macos-arm64.yml
- .github/workflows/template-build-macos-x64.yml
Revert "Change mac arm64 build use github runner"
> Revert "Change mac arm64 build use github runner"

- .github/workflows/template-build-macos-arm64.yml
- .github/workflows/template-build-macos-x64.yml
> Revert "Revert "Change mac arm64 build use github runner""

- extensions/inference-nitro-extension/package.json
- extensions/inference-nitro-extension/resources/models/phi3-3.8b/model.json
- Add Phi3 back after gguf support it correctly
- Closes # https://github.com/janhq/jan/issues/2800
- Closes #
> Chore: Add phi3

- extensions/inference-nitro-extension/package.json
- extensions/inference-nitro-extension/resources/models/phi3-3.8b/model.json
- extensions/inference-nitro-extension/rollup.config.ts
- After adding model.json Phi-3 doesn't show
- Closes #
> Fix: Phi-3 doesn't display

- .github/workflows/jan-openai-api-test.yml
- docs/tests/conftest.py
- docs/tests/endpoints_mapping.json
-
https://github.com/janhq/jan/issues/2656
> Feat/oai endpoints mapper using JSON

- .github/workflows/jan-electron-build.yml
Replace deprecated steps github action
- Closes #
- Closes #
> Replace deprecated steps github action

- web/package.json
> Update package.json to use next@14.2.3

- web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
- web/screens/Thread/ThreadLeftPanel/ModalEditTitleThread/index.tsx
- web/screens/Thread/ThreadLeftPanel/index.tsx
- Edit title thread
https://github.com/janhq/jan/assets/10354610/c5d97ced-d0bf-499e-8a64-6bebdea50785
- Closes #
- Closes #
> feat: edit title thread

- extensions/inference-nitro-extension/package.json
- extensions/inference-nitro-extension/resources/models/codestral-22b/model.json
- extensions/inference-nitro-extension/resources/models/mistral-ins-7b-q4/model.json
- extensions/inference-nitro-extension/resources/models/phi3-medium/model.json
- extensions/inference-nitro-extension/rollup.config.ts
- extensions/model-extension/resources/default-model.json
- typo adjustment
- model update (Mistral v2 -> Mistral v3)
- model add (Codestral 22B)
- Closes #
- Closes #
> Chore: Model Hub update

- web/screens/Settings/Appearance/index.tsx
- web/screens/Thread/ThreadRightPanel/index.tsx
- Max value of max_tokens should equal to current value of context length.
> fix: max value of max_tokens should follow context_length's value

- web/containers/ModelDropdown/index.tsx
> fix: clickable remote model

- extensions/model-extension/resources/settings.json
- extensions/model-extension/rollup.config.ts
- extensions/model-extension/src/index.ts
- Allowing user to enter their access token to download restricted models.
> feat: allow user to register their access token

- electron/utils/migration.ts
- Introduce theme versioning; if theme versions are the same, they should be kept, and customized themes should be retained.
- Closes #
- Closes #
> fix: theme migration overwrite existing theme

- web/styles/components/message.scss
- 
https://discord.com/channels/1107178041848909847/1213048058955300934/1246122324353351770
> fix: missing markdown list and blockquotes

- web/app/search/SelectedText.tsx
- web/app/search/layout.tsx
Fixed quick ask color schema
#2977 
https://github.com/janhq/jan/assets/10354610/1eef4fcc-f11c-4c6d-a19c-c8c2d6e62850
> fix: quickask missing color schema

- extensions/model-extension/package.json
- Increase version of model extension.
> chore: upgrade version model extension for hf auth token

- extensions/inference-nvidia-extension/README.md
- extensions/inference-nvidia-extension/package.json
- extensions/inference-nvidia-extension/resources/models.json
- extensions/inference-nvidia-extension/resources/settings.json
- extensions/inference-nvidia-extension/src/index.ts
- extensions/inference-nvidia-extension/tsconfig.json
- extensions/inference-nvidia-extension/webpack.config.js
- Adding support for nVidia NIM. More information can be found [here](https://www.nvidia.com/en-us/ai/).
https://github.com/janhq/jan/assets/10397206/beb14603-25de-45d1-b0f7-c4cbb5c6e17e
- #2854
> Added NVIDIA API to new jan after jan rework

- web/hooks/useLoadTheme.ts
Fix crash loading jan in browser on docker
undefined, electron is not available
- Closes #
- Closes #
> fix: loading jan browser

- web/containers/Loader/ProgressCircle.tsx
- web/containers/ModelDropdown/index.tsx
- web/containers/ModelLabel/NotEnoughMemoryLabel.tsx
- web/containers/ModelLabel/SlowOnYourDeviceLabel.tsx
> feat: update icon alert warning and copies tooltip model dropdown

- web/containers/Providers/KeyListener.tsx
- web/screens/Settings/Hotkeys/index.tsx
> feat: enable hotkey collapse right panel

- web/containers/ModelDropdown/index.tsx
> chore: update some copy

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
> chore: update template check box

- .github/workflows/jan-server-build-nightly.yml
- .github/workflows/nightly-integrate-cortex-cpp.yml
Add nightly update cortex cpp to Jan app
- Closes #
- Closes #
> Add nightly update cortex cpp to Jan app

- .github/workflows/nightly-integrate-cortex-cpp.yml
Change reviewer for nightly PR update cortex cpp
- Closes #
- Closes #
> Change reviewer for nightly PR update cortex cpp

- web/package.json
https://discord.com/channels/1107178041848909847/1242419382341341227/1242419382341341227
> chore: bump version marked-katex-extension

- web/screens/Thread/ThreadCenterPanel/SimpleTextMessage/index.tsx
Handle long words without space
#3042
> fix: handle long words without space to avoid right panel disappears

- web/screens/Settings/MyModels/MyModelList/index.tsx
https://github.com/janhq/jan/assets/10354610/c1082f12-1c13-44c4-9a45-a1e0a3d78815
https://discord.com/channels/1107178041848909847/1148527080527646751/1252360254012788817
- Closes #
> fix: position dropdown on my model

- web/containers/ModelDropdown/index.tsx
search model based on the configured model
https://github.com/janhq/jan/assets/10354610/e56557fc-3620-46c7-8956-7dc6691216ea
- download some models the try searching, you will fine the configured model 
- if downloaded model doesn't have icon download
- Try click download icon, and icon will change to loader
- #3043
> fix: model dropdown search by configured model

- core/src/types/api/index.ts
- extensions/inference-anthropic-extension/package.json
- extensions/inference-anthropic-extension/src/index.ts
- Fix anthropic streaming error.
- #[744](https://github.com/janhq/cortex/issues/744)
> Fix anthropic streaming error

- web/hooks/useActiveModel.ts
- disable flash_attn if vulkan is enabled
> fix: disable flash_attn if vulkan is enabled

- extensions/inference-nitro-extension/resources/models/aya-23-35b/model.json
- extensions/inference-nitro-extension/resources/models/aya-23-8b/model.json
- extensions/inference-nitro-extension/resources/models/codeninja-1.0-7b/model.json
- extensions/inference-nitro-extension/resources/models/codestral-22b/model.json
- extensions/inference-nitro-extension/resources/models/command-r-34b/model.json
- extensions/inference-nitro-extension/resources/models/deepseek-coder-1.3b/model.json
- extensions/inference-nitro-extension/resources/models/deepseek-coder-34b/model.json
- extensions/inference-nitro-extension/resources/models/gemma-2b/model.json
- extensions/inference-nitro-extension/resources/models/gemma-7b/model.json
- extensions/inference-nitro-extension/resources/models/llama2-chat-70b/model.json
- extensions/inference-nitro-extension/resources/models/llama2-chat-7b/model.json
- extensions/inference-nitro-extension/resources/models/llama3-8b-instruct/model.json
- extensions/inference-nitro-extension/resources/models/llama3-hermes-8b/model.json
- extensions/inference-nitro-extension/resources/models/llamacorn-1.1b/model.json
- extensions/inference-nitro-extension/resources/models/mistral-ins-7b-q4/model.json
- extensions/inference-nitro-extension/resources/models/noromaid-7b/model.json
- extensions/inference-nitro-extension/resources/models/openchat-3.5-7b/model.json
- extensions/inference-nitro-extension/resources/models/phi3-3.8b/model.json
- extensions/inference-nitro-extension/resources/models/phi3-medium/model.json
- extensions/inference-nitro-extension/resources/models/phind-34b/model.json
- extensions/inference-nitro-extension/resources/models/qwen-7b/model.json
- extensions/inference-nitro-extension/resources/models/qwen2-7b/model.json
- extensions/inference-nitro-extension/resources/models/stable-zephyr-3b/model.json
- extensions/inference-nitro-extension/resources/models/stealth-v1.2-7b/model.json
- extensions/inference-nitro-extension/resources/models/tinyllama-1.1b/model.json
- extensions/inference-nitro-extension/resources/models/trinity-v1.2-7b/model.json
- extensions/inference-nitro-extension/resources/models/vistral-7b/model.json
- extensions/inference-nitro-extension/resources/models/wizardcoder-13b/model.json
- extensions/inference-nitro-extension/resources/models/yi-34b/model.json
- +1 to every ngl parameter
- Closes #
> Chore: ngl adjust for correct usage

- extensions/inference-nitro-extension/package.json
- extensions/inference-nitro-extension/resources/models/aya-23-35b/model.json
- extensions/inference-nitro-extension/resources/models/aya-23-8b/model.json
- extensions/inference-nitro-extension/resources/models/codeninja-1.0-7b/model.json
- extensions/inference-nitro-extension/resources/models/codestral-22b/model.json
- extensions/inference-nitro-extension/resources/models/command-r-34b/model.json
- extensions/inference-nitro-extension/resources/models/deepseek-coder-1.3b/model.json
- extensions/inference-nitro-extension/resources/models/deepseek-coder-34b/model.json
- extensions/inference-nitro-extension/resources/models/gemma-2b/model.json
- extensions/inference-nitro-extension/resources/models/gemma-7b/model.json
- extensions/inference-nitro-extension/resources/models/llama2-chat-70b/model.json
- extensions/inference-nitro-extension/resources/models/llama2-chat-7b/model.json
- extensions/inference-nitro-extension/resources/models/llama3-8b-instruct/model.json
- extensions/inference-nitro-extension/resources/models/llama3-hermes-8b/model.json
- extensions/inference-nitro-extension/resources/models/llamacorn-1.1b/model.json
- extensions/inference-nitro-extension/resources/models/mistral-ins-7b-q4/model.json
- extensions/inference-nitro-extension/resources/models/noromaid-7b/model.json
- extensions/inference-nitro-extension/resources/models/openchat-3.5-7b/model.json
- extensions/inference-nitro-extension/resources/models/phi3-3.8b/model.json
- extensions/inference-nitro-extension/resources/models/phi3-medium/model.json
- extensions/inference-nitro-extension/resources/models/phind-34b/model.json
- extensions/inference-nitro-extension/resources/models/qwen-7b/model.json
- extensions/inference-nitro-extension/resources/models/qwen2-7b/model.json
- extensions/inference-nitro-extension/resources/models/stable-zephyr-3b/model.json
- extensions/inference-nitro-extension/resources/models/stealth-v1.2-7b/model.json
- extensions/inference-nitro-extension/resources/models/tinyllama-1.1b/model.json
- extensions/inference-nitro-extension/resources/models/trinity-v1.2-7b/model.json
- extensions/inference-nitro-extension/resources/models/vistral-7b/model.json
- extensions/inference-nitro-extension/resources/models/wizardcoder-13b/model.json
- extensions/inference-nitro-extension/resources/models/yi-34b/model.json
- Model version bump
- Closes #
> Chore: Model bump version

- extensions/inference-nitro-extension/package.json
- extensions/inference-nitro-extension/resources/models/aya-23-35b/model.json
- extensions/inference-nitro-extension/resources/models/aya-23-8b/model.json
- extensions/inference-nitro-extension/resources/models/codeninja-1.0-7b/model.json
- extensions/inference-nitro-extension/resources/models/codestral-22b/model.json
- extensions/inference-nitro-extension/resources/models/command-r-34b/model.json
- extensions/inference-nitro-extension/resources/models/deepseek-coder-1.3b/model.json
- extensions/inference-nitro-extension/resources/models/deepseek-coder-34b/model.json
- extensions/inference-nitro-extension/resources/models/gemma-2b/model.json
- extensions/inference-nitro-extension/resources/models/gemma-7b/model.json
- extensions/inference-nitro-extension/resources/models/llama2-chat-70b/model.json
- extensions/inference-nitro-extension/resources/models/llama2-chat-7b/model.json
- extensions/inference-nitro-extension/resources/models/llama3-8b-instruct/model.json
- extensions/inference-nitro-extension/resources/models/llama3-hermes-8b/model.json
- extensions/inference-nitro-extension/resources/models/llamacorn-1.1b/model.json
- extensions/inference-nitro-extension/resources/models/mistral-ins-7b-q4/model.json
- extensions/inference-nitro-extension/resources/models/noromaid-7b/model.json
- extensions/inference-nitro-extension/resources/models/openchat-3.5-7b/model.json
- extensions/inference-nitro-extension/resources/models/phi3-3.8b/model.json
- extensions/inference-nitro-extension/resources/models/phi3-medium/model.json
- extensions/inference-nitro-extension/resources/models/phind-34b/model.json
- extensions/inference-nitro-extension/resources/models/qwen-7b/model.json
- extensions/inference-nitro-extension/resources/models/qwen2-7b/model.json
- extensions/inference-nitro-extension/resources/models/stable-zephyr-3b/model.json
- extensions/inference-nitro-extension/resources/models/stealth-v1.2-7b/model.json
- extensions/inference-nitro-extension/resources/models/tinyllama-1.1b/model.json
- extensions/inference-nitro-extension/resources/models/trinity-v1.2-7b/model.json
- extensions/inference-nitro-extension/resources/models/vistral-7b/model.json
- extensions/inference-nitro-extension/resources/models/wizardcoder-13b/model.json
- extensions/inference-nitro-extension/resources/models/yi-34b/model.json
> chore: bump version (#3082)

- core/src/node/helper/download.ts
> chore: update download.ts

- web/screens/Thread/ThreadLeftPanel/ModalCleanThread/index.tsx
- web/screens/Thread/ThreadLeftPanel/ModalDeleteThread/index.tsx
- web/screens/Thread/ThreadLeftPanel/ModalEditTitleThread/index.tsx
- web/screens/Thread/ThreadLeftPanel/index.tsx
> feat: enable right click to show setting on thread items

- extensions/inference-nitro-extension/package.json
- extensions/inference-nitro-extension/resources/models/gemma-2b/model.json
- Add stop token for Gemma 2b
- Closes #https://github.com/janhq/jan/issues/3105
> Chore: Add stop token for Gemma 2b

- extensions/inference-nitro-extension/package.json
> fix: set specific version for terminate

- extensions/inference-anthropic-extension/package.json
- extensions/inference-anthropic-extension/resources/models.json
> feat: add claude 3.5 sonnet

- web/helpers/atoms/Setting.atom.ts
- web/screens/Settings/Appearance/index.tsx
- web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
- web/screens/Thread/ThreadCenterPanel/EditChatInput/index.tsx
> feat: add options config spell check for chat input

- web/screens/Settings/Appearance/index.tsx
- web/screens/Settings/CoreExtensions/index.tsx
- web/screens/Settings/SettingLeftPanel/index.tsx
- web/screens/Settings/index.tsx
- Fixed the minute grammar mistakes
- Closes #3109
> fixed grammar nits

- web/containers/ModalTroubleShoot/index.tsx
> fix: toggle button for expand log section on modal troubleshoot

- core/src/types/message/messageEntity.ts
- web/containers/ErrorMessage/index.tsx
Before
After
- Closes #
- Closes #
> fix: handle error message when apikey is not setup

- web/screens/Thread/ThreadLeftPanel/ModalEditTitleThread/index.tsx
Testing
- U‌‌pda‌te thread name
- Clean threa‌d
- E‌dit the thread name again 
- #3116
- Closes #
> fix: title thread not updated on input edit title

- web/screens/Settings/SettingDetail/index.tsx
- web/screens/Settings/index.tsx
> fix: missing keyboard sand shortcuts screen

- web/containers/Layout/BottomPanel/SystemMonitor/index.tsx
> feat: add shortcut app logs on system monitor

- web/hooks/useSendMessage.ts
- web/screens/HubScreen2/components/BuiltInModelGroup.tsx
- web/screens/HubScreen2/components/HeaderModal.tsx
- web/screens/HubScreen2/components/HuggingFaceModelGroup.tsx
- web/screens/HubScreen2/components/RemoteModelGroup.tsx
- web/screens/HubScreen2/components/SetUpRemoteModelModal.tsx
- web/screens/Settings/MyModels/ModelItem/index.tsx
- web/screens/Thread/ThreadLeftPanel/ThreadItem/index.tsx
- web/screens/Thread/ThreadLeftPanel/TypingAnimated/index.tsx
- web/screens/Thread/ThreadLeftPanel/index.tsx
- web/styles/base/global.scss
1. Fixed 3 dots thread list and take back right click on the list to show the menu
2. On device tab showing 6 items instead 4 items
3. Reduce color of typography modal detail
4. Fix dropdown position on my models 
- Closes #
- Closes #
> chore: minor UI hub

- core/src/types/api/index.ts
- electron/handlers/native.ts
- web/containers/Providers/ModalMigrations.tsx
- web/helpers/atoms/AppConfig.atom.ts
- web/hooks/useMigratingData.ts
> fix: logic show modal migration

- web/containers/Providers/ModalMigrations.tsx
- web/helpers/atoms/AppConfig.atom.ts
> chore: set state thread and models migration using getOnInit

- extensions/monitoring-extension/resources/settings.json
- web/screens/Settings/Advanced/DataFolder/index.tsx
- web/screens/Settings/Advanced/FactoryReset/index.tsx
- web/screens/Settings/Advanced/index.tsx
- web/screens/Settings/Appearance/index.tsx
- web/screens/Settings/Hotkeys/index.tsx
- small copy fixes
- pls automerge for me
- Closes #
- Closes #
> fix: jan app copy nits

- web/containers/Layout/BottomPanel/SystemMonitor/TableActiveModel/index.tsx
> chore: system monitor show engine model

- web/screens/HubScreen2/components/HfListModel.tsx
- web/screens/HubScreen2/components/ListModel.tsx
- web/screens/HubScreen2/components/ModelInformation.tsx
- Added loader each tab on model detail popup
- Closes #
- Closes #
> chore: added loader detail model

- web/containers/Loader/ModelStart.tsx
- web/containers/Providers/ModelEventListener.tsx
- web/helpers/atoms/Thread.atom.ts
- web/screens/Thread/ThreadCenterPanel/index.tsx
> chore: model start loader

- web/screens/Settings/CoreExtensions/index.tsx
Fix typo Extention -> Extension
-
> Fix typo Extention -> Extension

- web/containers/Layout/TopPanel/index.tsx
- web/screens/HubScreen2/components/BuiltInModelCard.tsx
- web/screens/HubScreen2/components/Filter.tsx
> chore: minor UI feedback

- Makefile
- electron/download.bat
- web/helpers/atoms/SetupRemoteModel.atom.ts
- web/screens/HubScreen2/components/SetUpApiKeyModal.tsx
- web/screens/Thread/ThreadCenterPanel/ChatBody/EmptyModel/OnDeviceListStarter.tsx
- web/screens/Thread/ThreadCenterPanel/ChatBody/EmptyModel/index.tsx
- web/screens/Thread/index.tsx
> feat: new starter screen

- web/screens/Thread/ThreadRightPanel/ModelSettingContainer/index.tsx
- web/utils/componentSettings.ts
> fix: max token issue

- web/containers/WaitingCortexModal/index.tsx
- web/helpers/atoms/App.atom.ts
- web/hooks/useCortex.ts
- web/package.json
- Fixed an issue where cortex process overlay should be on top
- Closes #
- Closes #
> fix: wait for cortex process overlay should be on top

- electron/download.bat
- electron/handlers/native.ts
- electron/main.ts
- cleaning dangling processes before starting jan.
> fix: clean up port before start jan

- web/hooks/useSendMessage.ts
- Add back normalize messages function.
> fix: normalize messages for some providers

- web/containers/Providers/ModalMigrations.tsx
Minor grammar in Modal Migration:
`Migration in Progressed` -> `Migration in Progress`
> chore: minor copy for grammar

- web/screens/Thread/ThreadCenterPanel/SimpleTextMessage/index.tsx
Furthermore, Jan will not share cortex data, so the issue will not persist afterward (e.g., empty message).
- Closes #
> chore: check the legacy incompatible message type

- core/src/types/model/modelEntity.ts
- Add nvidia to remote engine.
> fix: add nvidia engine

- web/screens/HubScreen2/components/DownloadLocalModelModal.tsx
- web/screens/HubScreen2/components/HeaderModal.tsx
- web/screens/HubScreen2/components/ListModel.tsx
- web/screens/HubScreen2/components/SetUpRemoteModelModal.tsx
- web/screens/Settings/ImportingModelModal/ImportingModelItem.tsx
- web/screens/Settings/ImportingModelModal/index.tsx
- Add more selection for cortex popup.
https://github.com/user-attachments/assets/c6a65e05-b0c4-4e09-a5ba-fda2f9fda1bd
- Closes #
- Closes #
> feat: add more options for cortex popup

- web/screens/HubScreen2/components/ModelSearchBar.tsx
> chore: temporary hidden button import model

- joi/src/core/Button/styles.scss
> chore: remove focus button

- electron/main.ts
- While the app is running, if users attempt to open any new Jan app instance which would break both instances. E.g. Deep Linking case
- #3246
> fix: should not let second instance terminate cortex

- web/screens/Settings/ImportingModelModal/index.tsx
This is a follow-up PR to improve Jan UX when importing a model that has already been imported, which was previously fixed in Cortex.
- #3249
> chore: toast message on model import fail with reason

- web/containers/WaitingCortexModal/index.tsx
- This is to make the app loading prompt better with improved messages & instructions
- #3246
> fix: clearer app loading prompt

- electron/handlers/native.ts
- electron/main.ts
- electron/utils/path.ts
- web/containers/Providers/ModalMigrations.tsx
- web/screens/Settings/Advanced/components/DataMigration.tsx
- Move the setup to the top to prevent using a wrong `userData` path.
> fix: migration wrong directory

- core/src/types/model/modelEntity.ts
> feat: add nvidia engine

- joi/src/core/Tooltip/styles.scss
Render tooltip on top of modal component
- Closes #
- Closes #
> chore: update z-index tooltip

- web/containers/Layout/BottomPanel/SystemMonitor/index.tsx
- web/helpers/atoms/SystemBar.atom.ts
> fix: system bar always show RAM usage 0%

- web/screens/HubScreen2/components/ListModel.tsx
- Fix onnx can't be selected on downloading model
> fix: onnx can't be selected in download model modal

- web/screens/HubScreen2/components/ModelSearchBar.tsx
- web/utils/huggingface.ts
- Add support for lower case quantization. Can be tested with https://huggingface.co/BafS/gemma-2-2b-it-Q4_K_M-GGUF/tree/main
> fix: add lower case quantization support

- web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
> fix: icon setting can close and open right panel

- web/utils/huggingface.ts
- Merge GPU arch and OS for tensorrt models.
> fix: merge gpu arch and os tensorrt models

- web/containers/Layout/BottomPanel/DownloadingStatus/index.tsx
- web/screens/Settings/Advanced/components/DataMigration.tsx
- Text pushed the button to the right.
> fix: migration item in setting detail omit buttons

- web/containers/WaitingCortexModal/index.tsx
- web/helpers/atoms/AppConfig.atom.ts
- Fixed an issue where Jan app is broken due to incorrect host 
- #3306
> fix: broken app due to incorrect api path

- electron/utils/path.ts
- web/helpers/atoms/AppConfig.atom.ts
- This is to force disable quick ask until it's added back
- Closes #
- Closes #
> chore: disable quick ask

- electron/main.ts
- electron/package.json
- electron/utils/setup.ts
- web/hooks/useThreads.ts
- This fixes the version fetching which broke the build.
- This PR also added jan.log under jan data folder to log all electron node logs
- Closes #
> fix: broken jan build - add log trace (jan.log)

- .github/workflows/template-build-linux-x64.yml
- .github/workflows/template-build-macos-arm64.yml
- .github/workflows/template-build-macos-x64.yml
- .github/workflows/template-build-windows-x64.yml
- Increase retry upload to R2 to 5 times
- Closes #
- Closes #
> Increase retry upload to R2 to 5 times

- web/screens/Thread/ThreadCenterPanel/ChatBody/EmptyModel/OnDeviceListStarter.tsx
Before
After
- Closes #
- Closes #
> chore(ui): fix alignment loader starter screen

- web/containers/Providers/DownloadEventListener.tsx
- web/containers/Providers/ModalMigrations.tsx
- web/containers/Providers/ModelEventListener.tsx
- web/hooks/useModels.ts
- web/screens/HubScreen2/components/HubModelCard.tsx
- web/screens/HubScreen2/components/RemoteModelCard.tsx
- web/screens/Settings/MyModels/ModelItem/index.tsx
- web/screens/Thread/index.tsx
- fix blank state that Alan met when using Jan.
> fix: blank state when delete jan data folder content

- web/containers/ModelDropdown/ModelSection.tsx
Using button variant outline for configure icon and reduce color title of model 
- Closes #
- Closes #
> chore: button outline for configure cloud model

- web/containers/Layout/TopPanel/index.tsx
- web/hooks/useGetModelsByEngine.ts
- web/screens/Settings/MyModels/ModelGroup/index.tsx
- web/screens/Settings/MyModels/ModelItem/index.tsx
- web/screens/Settings/MyModels/index.tsx
- web/utils/model-engine.ts
Allow user configure cloud model via my model
- #3134 
- #3315
> feat: allow user configure remote model from my model

- electron/main.ts
- electron/utils/clean.ts
- electron/utils/cortex.ts
- electron/utils/process.ts
- web/containers/Layout/BottomPanel/SystemMonitor/index.tsx
- Fixed an issue where app does not relaunch on update
- Fixed an issue where app does not show GPU information when it's not utilized
- Closes #
- Closes #
> fix: failed to relaunch app to update

- web/screens/HubScreen2/components/DetailModelGroup.tsx
- web/screens/HubScreen2/components/HubScreenFilter/index.tsx
- web/screens/HubScreen2/components/HuggingFaceModelCard.tsx
- web/screens/Settings/Advanced/components/DataMigration.tsx
- web/screens/Settings/Appearance/index.tsx
- web/screens/Settings/EngineSetting/index.tsx
- web/screens/Settings/Hotkeys/index.tsx
- web/screens/Settings/MyModels/ModelItem/index.tsx
- web/screens/Settings/MyModels/index.tsx
- web/screens/Thread/ThreadRightPanel/AssistantSettingContainer/components/CopyOverInstruction.tsx
- web/screens/Thread/ThreadRightPanel/AssistantSettingContainer/index.tsx
All changes request from https://www.figma.com/design/nWgBmwxaZ2CVrJT6CIoiGO/QA-Jan-x-Cortex?node-id=75-10095&t=PjXFhUpu3ARypCqc-0
- #3333 
- Closes #
> chore: minor ui improvement

- web/app/layout.tsx
- web/screens/Thread/ThreadCenterPanel/SimpleTextMessage/index.tsx
This PR is to address LaTex render issue on Jan
- #2865
> fix: LaTex formula render issue

- web/containers/CenterPanelContainer/index.tsx
- web/containers/Layout/TopPanel/index.tsx
- web/screens/Thread/ThreadLeftPanel/index.tsx
- Rework of move create new thread into top panel
- #3312 
- Closes #
> chore: move create new thread to top panel

- web/containers/Layout/BottomPanel/SystemMonitor/TableActiveModel/index.tsx
- web/containers/Layout/BottomPanel/SystemMonitor/index.tsx
- web/screens/Settings/Appearance/index.tsx
- web/screens/Settings/Hotkeys/index.tsx
- https://www.figma.com/design/nWgBmwxaZ2CVrJT6CIoiGO/QA-Jan-x-Cortex?node-id=95-4407
- #3368 
- Closes #
> feat: small ui improvement

- web/screens/Thread/ThreadCenterPanel/SimpleTextMessage/index.tsx
Rework improve readability message using max width 700px
Large window 
Small window
- #3184 
- Closes #
> chore: improve readability with set max width container message

- web/screens/Thread/ThreadRightPanel/index.tsx
> feat: add model assistant tab

- joi/src/core/Modal/index.tsx
Before
After
- Closes #
- Closes #
> chore: clean up console modal component

- web/containers/CopyInstruction/index.tsx
- web/hooks/useCreateNewThread.ts
- web/screens/Thread/ThreadRightPanel/index.tsx
- toggle copy instruction for new thread
toggle on
toggle off
- #3377 
- Closes #
> feat: enable copy instruction

- web/screens/Thread/ThreadRightPanel/index.tsx
- Based on discuss with @imtuyethan confirmed we remove model selection on assistant tab
- #3313 
- Closes #
> chore: remove model selection in assistant tab model

- web/containers/ModelDropdown/index.tsx
disable remote model when user did not setup apiKey, and change cursor not allowed when model disabled
- #
- Closes #
> fix: disable remote model when user did not setup apiKey

- web/package.json
CI stopped working because of a dependency rollback.
> chore: fix CI - remove headless ui

- web/containers/Layout/BottomPanel/SystemMonitor/TableActiveModel/index.tsx
- web/containers/Layout/BottomPanel/SystemMonitor/index.tsx
> fix: avoid show remote model on system monitor

- web/containers/ModelDropdown/index.tsx
- web/screens/Thread/ThreadCenterPanel/index.tsx
[link conv](https://discord.com/channels/1107178041848909847/1275007592690749480/1275011963407044608)
- Remove queued Message indicator
- Increased color model list when available
- Closes #
- Closes #
> chore: small ui improvement

- web/containers/BlankState/index.tsx
- web/screens/Hub/index.tsx
- web/screens/Settings/MyModels/index.tsx
Add blank state component for no result found when user search on hub and my model
- #3410 
- Closes #
> feat: add blank state component for hub and my model search

- core/src/types/model/modelEntity.ts
- electron/package.json
- extensions/inference-cortex-extension/helpers/huggingface.js
- extensions/inference-cortex-extension/package.json
- extensions/inference-cortex-extension/rollup.config.ts
- extensions/inference-cortex-extension/src/index.ts
- extensions/inference-cortex-extension/src/node/index.ts
- extensions/model-extension/package.json
- extensions/model-extension/src/helpers/params.ts
- extensions/model-extension/src/index.ts
- extensions/tensorrt-llm-extension/src/node/index.ts
- joi/package.json
- package.json
- web/containers/ModelDropdown/index.tsx
- web/containers/ModelLabel/index.tsx
- web/package.json
- web/screens/Hub/ModelList/ModelHeader/index.tsx
- web/screens/Hub/ModelList/ModelItem/index.tsx
- web/screens/Hub/ModelList/index.tsx
- web/utils/componentSettings.ts
- Pre-populate cortexso models from Cortex extension
- Model settings & inference params can be flattened (strict settings {} and parameters {} before)
- Model can be under json or yaml format
|Pre-populate Cortexhub with recommended models|
|:--:|
|<img width="1480" alt="Screenshot 2024-08-20 at 18 34 42" src="https://github.com/user-attachments/assets/92356d0b-5b11-4c11-95b8-4566169be883">|
|Remote models do not have recommended tags|
|<img width="1480" alt="Screenshot 2024-08-20 at 18 34 51" src="https://github.com/user-attachments/assets/462e9fef-46d9-490f-a995-82f4161f9b8d">|
|Tensorrt-llm models with supported platform only - platform label is trimmed out|
|![image](https://github.com/user-attachments/assets/b30fcecb-19b3-405a-8a42-99666a2804d7)|
- The model name is easily …
> feat: cortex extension pulls hf model list

- web/screens/Hub/ModelList/ModelItem/index.tsx
- web/screens/Settings/CoreExtensions/ExtensionItem.tsx
- web/screens/Settings/CoreExtensions/index.tsx
- web/screens/Settings/SettingDetail/SettingDetailItem/SettingDetailTextInputItem/index.tsx
- web/screens/Settings/SettingDetail/SettingDetailItem/SettingDetailToggleItem/index.tsx
- web/utils/marked.ts
- We duplicated a marked helper around components; let's reduce the duplication. 
- This is to render markdown properly in the Model card as well.
| Model description |
|:-:|
| Extensions Setting|
|<img width="1273" alt="Screenshot 2024-08-21 at 13 39 16" src="https://github.com/user-attachments/assets/1b63ea77-102d-464d-84b9-d97c6d728867">|
|Extension Settings|
|<img width="1273" alt="Screenshot 2024-08-21 at 13 39 22" src="https://github.com/user-attachments/assets/27b8c469-e7db-4d1e-a53a-32314ba64184">|
- Closes #
- Closes #
> refactor: marked helper - model description as markdown

- joi/src/core/ScrollArea/styles.scss
- web/containers/ModelDropdown/index.tsx
Issue 
After 
- #3331 
- Closes #
> fix: decreased scrollbar width

- web/containers/ModelDropdown/index.tsx
- web/hooks/useCreateNewThread.ts
- web/hooks/useUpdateModelParameters.ts
- web/screens/Thread/ThreadCenterPanel/index.tsx
- Nits: Address linter warning issues
- Closes #
- Closes #
> chore: fix linter issues

- web/utils/datetime.ts
Before
After
- #3333 
- Closes #
> fix: date format for chat item

- core/src/browser/extension.ts
- extensions/inference-anthropic-extension/resources/settings.json
- extensions/inference-cohere-extension/resources/settings.json
- extensions/inference-groq-extension/resources/settings.json
- extensions/inference-martian-extension/resources/settings.json
- extensions/inference-mistral-extension/resources/settings.json
- extensions/inference-nvidia-extension/resources/settings.json
- extensions/inference-openai-extension/resources/settings.json
- extensions/inference-openrouter-extension/resources/settings.json
- extensions/inference-triton-trtllm-extension/resources/settings.json
Update placeholder and add input action setting api key extension
https://discord.com/channels/1107178041848909847/1275647742906994699/1275652463273312378
NB this PR need @louis-jan migration since we have changes on `setting.json` each extension
- Closes #
- Closes #
> fix: setting extension placeholder and input action apikey

- extensions/model-extension/src/index.ts
- To reproduce: 
import following model 
https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v0.3-GGUF
- Closes #
- Closes #
> fix: unable to import model due to missing metadata

- extensions/inference-openrouter-extension/resources/settings.json
- This PR is to add back a missing OpenRouter setting 
=
- Closes #
- Closes #
> chore: add back OpenRouter request endpoint setting

- electron/utils/migration.ts
- web/hooks/useUpdateModelParameters.ts
- Fixed an issue where extensions are not being migrated when updating app
- #3387
> fix: enable extensions migration

- web/screens/Settings/HuggingFaceRepoDetailModal/ModelDownloadList/index.tsx
- web/screens/Settings/HuggingFaceRepoDetailModal/ModelDownloadRow/index.tsx
- web/screens/Settings/HuggingFaceRepoDetailModal/index.tsx
https://discord.com/channels/1107178041848909847/1275647742906994699/1276464972649599017
- #3181 
- Closes #
> fix: responsive modal import model

- joi/src/core/Modal/styles.scss
- https://discord.com/channels/1107178041848909847/1275647742906994699/1276445172883783703
- Closes #
- Closes #
> fix: modal title should not truncated

- .husky/pre-commit
- package.json
- Add husky pre-commit to run lint check before committing
- Closes #
- Closes #
> chore: add husky pre-commit

- extensions/inference-nitro-extension/package.json
- extensions/inference-nitro-extension/resources/models/gemma-1.1-2b/model.json
- extensions/inference-nitro-extension/resources/models/gemma-1.1-7b/model.json
- extensions/inference-nitro-extension/resources/models/gemma-2-27b/model.json
- extensions/inference-nitro-extension/resources/models/gemma-2-2b/model.json
- extensions/inference-nitro-extension/resources/models/gemma-2-9b/model.json
- extensions/inference-nitro-extension/resources/models/llama3-8b-instruct/model.json
- extensions/inference-nitro-extension/resources/models/llama3.1-70b-instruct/model.json
- extensions/inference-nitro-extension/resources/models/llama3.1-8b-instruct/model.json
- extensions/inference-nitro-extension/rollup.config.ts
This PR is to add llama3.1 models
- https://huggingface.co/bartowski/Meta-Llama-3.1-8B-Instruct-GGUF - Q4_K_M
- https://huggingface.co/bartowski/Meta-Llama-3.1-70B-Instruct-GGUF - Q4_K_M
|Llama3.1 8B GGUF|
|:-:|
|<img width="1289" alt="Screenshot 2024-08-27 at 12 20 10" src="https://github.com/user-attachments/assets/46510c23-3ea8-4f70-bcf2-b917e5f044c2">|
- Closes #
> chore: add llama 3.1 8B gguf model

- core/src/node/api/restful/helper/builder.ts
- web/hooks/useImportModel.ts
- add engine in payload for nitro chat completion api
- Closes #
- Closes #
> fix: add engine in payload for nitro chat completion api

- extensions/inference-nitro-extension/resources/models/gemma-1.1-2b/model.json
- extensions/inference-nitro-extension/resources/models/gemma-1.1-7b/model.json
> chore: Update model.json with correct filename

- web/containers/Layout/BottomPanel/SystemMonitor/index.tsx
- web/screens/Settings/HuggingFaceRepoDetailModal/ModelDownloadList/index.tsx
- web/screens/Settings/HuggingFaceRepoDetailModal/ModelDownloadRow/index.tsx
- web/screens/Settings/HuggingFaceRepoDetailModal/ModelSegmentInfo/index.tsx
- web/utils/modelEngine.ts
> fix: responsive modal import gguf

- web/.eslintrc.js
- web/containers/Layout/BottomPanel/SystemMonitor/index.tsx
- web/jest.config.js
- web/package.json
- web/testRunner.js
- web/tsconfig.json
- web/utils/memory.test.ts
- web/utils/memory.ts
- Fixed an issue where app shows incorrect utilized GPU memory
| GPU usage |
|:-:|
|![image](https://github.com/user-attachments/assets/61e2a8b9-c79c-4fc6-b3e3-6c8603898ec6)|
- Closes #
- Closes #
> fix: gpu memory utilization

- electron/managers/mainWindowConfig.ts
- #3093 
- #3084 
- #3237 
- #3324 for this we stay default to transparent
> fix: electron window

- core/src/types/api/index.ts
- electron/managers/window.ts
- electron/utils/menu.ts
- web/containers/Layout/index.tsx
- Add setting option to dropdown menu
- Closes #3203 
- Closes #
> feat: add setting options to dropdown menu

- joi/src/core/Tabs/index.tsx
- joi/src/core/Tabs/styles.scss
- web/containers/ModelDropdown/index.tsx
- web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
- web/screens/Thread/ThreadRightPanel/index.tsx
The "Tools" tab should be hidden or disabled when using remote models that do not support tool functionality excluding OpenAI
- Closes #3472 
- Closes #
> fix: disabled UI RAG and tools

- web/screens/Thread/ThreadRightPanel/index.tsx
- Change Inference, Model, Engine Parameters into Inference, Model, Engine Settings
- Closes #3025 
- Closes #
> chore: copy edit for model setting

- .gitignore
- joi/jest.config.js
- joi/package.json
- joi/src/core/Accordion/Accordion.test.tsx
- joi/src/core/Badge/Badge.test.tsx
- joi/src/core/Badge/index.tsx
- joi/src/core/Button/Button.test.tsx
- joi/src/core/Button/index.tsx
- joi/src/hooks/useClickOutside/useClickOutside.test.tsx
- joi/src/hooks/useClipboard/useClipboard.test.ts
- joi/src/hooks/useMediaQuery/useMediaQuery.test.ts
- joi/src/hooks/useOs/useOs.test.ts
- joi/src/hooks/usePageLeave/usePageLeave.test.ts
- joi/src/hooks/useTextSelection/useTextSelection.test.ts
- joi/tsconfig.json
- WIP unit test component 
- #3507 
- Closes #
> chore: setup jest for unit test hooks and component from joi

- web/containers/ModelDropdown/index.tsx
- Enable user search based configured model 
- When user not have downloaded model , showing featured model, and still can search configured model.
- When user already have downloaded model, user still can search configured model and can download it from icon download on the list.
- #3043 
- Closes #
> feat: enable search model dropdown by configured model

- .github/workflows/jan-electron-linter-and-test.yml
- web/helpers/atoms/HuggingFace.atom.ts
- web/screens/Thread/ThreadCenterPanel/ChatBody/EmptyModel/index.tsx
- web/utils/predefinedComponent.ts
- Fixed test issues where some wrong imports were made from components.
The PRs have failed to run tests since many components import `core` from `@janhq/core/.` where it should be `@janhq/core`
- Closes #
- Closes #
> test: fix import from components

- web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
There 2 case tooltip content, if model not support and if retrieval turn off
https://discord.com/channels/1107178041848909847/1281512188762128467/1281518987179462656
- Closes #
- Closes #
> chore: update copy when retrieval turn off

- web/containers/Layout/RibbonPanel/index.tsx
- web/jest.config.js
- web/screens/Thread/ThreadCenterPanel/ChatBody/OnDeviceStarterScreen/index.test.tsx
- web/screens/Thread/ThreadCenterPanel/ChatBody/OnDeviceStarterScreen/index.tsx
- web/screens/Thread/index.tsx
- web/tsconfig.json
Resolved 
- Closes #3642 
- Closes #3641
> fix: issue responsive and missing size on starter screen

- web/hooks/useOnboarding.ts
- web/hooks/useStarterScreen.ts
- web/screens/Thread/index.tsx
- We will move starter screen to 0.5.5 just temporary disabled condition on thread index for render starter screen
- Closes #
- Closes #
> chore: temporary disabled starter screen

- web/helpers/atoms/Setting.atom.ts
- web/screens/Settings/Advanced/index.tsx
- web/screens/Settings/Appearance/index.tsx
- web/screens/Settings/MyModels/MyModelList/index.tsx
- web/screens/Settings/SettingDetail/SettingDetailItem/SettingDetailTextInputItem/index.tsx
1. Alignment on my model
2. Adjust width on select GPU 
3. Updated copy for spellcheck description and make it turn off by default
4. Overlap value on API key input field
Changes code
No functional changes were made, only `classNames` were adjusted to fix UI element issues and update styles for different breakpoints
- Closes #3674 
- Closes #
> fix: enhance various minor UI elements

- web/containers/Providers/EventHandler.tsx
https://github.com/user-attachments/assets/e0ce3899-8983-494e-ad82-32a470770d55
- #3121 
- Closes #
> fix:  thread title for remote model from first prompt

- web/screens/LocalServer/LocalServerLeftPanel/index.tsx
- https://discord.com/channels/1107178041848909847/1286259086064746518/1286611575817637939
- Closes #
- Closes #
> fix: remove title local API server page

- joi/src/hooks/useClickOutside/index.tsx
- joi/src/hooks/useClickOutside/useClickOutside.test.tsx
- joi/src/hooks/useMediaQuery/index.ts
- joi/src/hooks/useMediaQuery/useMediaQuery.test.ts
- joi/src/hooks/useOs/index.tsx
- joi/src/hooks/useOs/useOs.test.ts
- joi/src/index.test.ts
Before
After
Update some hooks and test to get 100 coverage
1. useCLickOutside
The tests verify that the useClickOutside hook works correctly for different scenarios:
-  triggers the handler when clicking outside the target element.
- does not trigger the handler for clicks inside the target element or any of the elements in the nodes array.
- It correctly handles special elements marked with data-ignore-outside-clicks.
2. useMediqQuery
- These tests ensure the useMediaQuery hook and getInitialValue function work as expected in different scenarios: with and without window, with matchMedia, in older browsers, and when media queries change.
- The tests mock global objects like window.matchMedia to simulate different environments and ensure the functions behave correctly across various …
> test: update test coverage UI component Joi

- extensions/conversational-extension/jest.config.js
- extensions/conversational-extension/package.json
- extensions/conversational-extension/src/Conversational.test.ts
- extensions/conversational-extension/src/index.ts
- extensions/conversational-extension/src/jsonUtil.ts
- extensions/conversational-extension/tsconfig.json
- extensions/model-extension/src/helpers/path.test.ts
- extensions/model-extension/src/helpers/path.ts
- jest.config.js
- web/containers/ErrorMessage/index.test.tsx
- web/containers/ListContainer/index.test.tsx
- web/containers/ListContainer/index.tsx
- web/containers/Loader/GenerateResponse.test.tsx
- web/containers/Loader/ModelReload.test.tsx
- web/containers/Loader/ProgressCircle.test.tsx
- web/containers/Loader/ProgressCircle.tsx
- web/containers/ModalTroubleShoot/AppLogs.test.tsx
- web/screens/Thread/ThreadCenterPanel/AssistantSetting/index.test.tsx
When the thread.json file is corrupted or contains invalid JSON, it causes the entire thread list to become inaccessible (empty list). This issue is critical as it disrupts the user experience by preventing access to all threads.
Please refer to the discussion for more context:
https://discord.com/channels/1107178041848909847/1285798898161418260
The application should handle the corrupted thread.json gracefully. It should either:
Skip the corrupted entries and continue to load the rest of the threads.
The application fails to load any threads, displaying an error or crashing due to the corrupted thread.json.
Implement error handling for JSON parsing in the thread loading functionality. Ensure that:
The application can detect and skip over corrupted JSON entries.
- #3693
1. **Index File …
> fix: #3693 broken thread.json should not break the entire threads

- joi/src/core/Tabs/Tabs.test.tsx
- joi/src/core/Tabs/index.tsx
- joi/src/core/Tabs/styles.scss
- web/containers/ModelDropdown/index.test.tsx
- web/containers/ModelDropdown/index.tsx
- Enhance UI Tab component on model selection 
- Closes #3475 
- Closes #
> enhance: tabs component in model selection

- .github/workflows/auto-trigger-jan-docs.yaml
- ci: auto trigger jan docs ci for new release
- Related ticket: https://github.com/janhq/docs/issues/147
> ci: auto trigger jan docs ci for new release

- web/containers/Loader/ModelStart.tsx
- web/containers/ModelDropdown/index.tsx
- it's from https://github.com/janhq/jan/pull/3756
- Closes #
- Closes #
> fix: overlap text on model selector and loader

- README.md
- docs/theme.config.tsx
- Since we moved the docs to this repo, we should also update the base edit URL link in Nextra
- Closes #3787 
- Closes #
> fix: update base url edit page docs

- .github/workflows/jan-docs.yml
- ci: Update jan-docs.yml
- Closes #
- Closes #
> ci: Update jan-docs.yml

- electron/utils/setup.ts
Certainly! The provided Git diff shows several changes made to the `electron/utils/setup.ts` file. Here's a breakdown of each change:
```diff
-if (bounds) {
-  return bounds as Electron.Rectangle
-} else {
+if (!bounds) {
```
This change reverses the condition inside the if statement. Instead of checking if `bounds` is not undefined, it now checks if `bounds` is undefined and handles that case first.
```diff
+// If no bounds are saved, use the defaults
+if (!bounds) {
+  storage.set('windowBounds', defaultBounds)
+  return defaultBounds
+}
+
+// Validate that the bounds are on a valid display
+const displays = screen.getAllDisplays()
+const isValid = displays.some((display) => {
+  const { x, y, width, height } = display.bounds
+  return (
+    bounds.x >= x &&
+    bounds.x < x + width …
```
> fix: reset window state after disconnected from multi monitor

- joi/src/core/Modal/styles.scss
- Simple PR enable scroll content from modal/dialog component 
- Closes #3804 
- Closes #
> fix: enable scroll modal component

- extensions/model-extension/package.json
- extensions/model-extension/src/index.ts
The Git diff you provided shows the following changes made to two files in a project:
1. In `extensions/model-extension/package.json`, the version number has been updated from "1.0.33" to "1.0.34".
2. In `extensions/model-extension/src/index.ts`, the updated code uses the length of an array to compare against the number of sources provided for the model. This ensures that only files that are actually associated with a source will be considered as a match.
- Closes #3858 
- Closes #
> fix: inconsistent state of downloading multimodal

- .github/scripts/rename-app-beta.sh
- .github/scripts/rename-uninstaller-beta.sh
- .github/scripts/rename-workspace-beta.sh
- .github/workflows/jan-electron-build-beta.yml
- .github/workflows/jan-electron-linter-and-test.yml
- .github/workflows/template-build-linux-x64.yml
- .github/workflows/template-build-macos-arm64.yml
- .github/workflows/template-build-macos-x64.yml
- .github/workflows/template-build-windows-x64.yml
- Feat Jan beta version
- Related issue #2985 
- Closes #
Now we can install 2 isolated app beta and stable in a same machine 
Difference app opening (process) and data
Difference model hub
> Feat Jan beta version

- .github/workflows/jan-electron-linter-and-test.yml
- electron/package.json
> Revert "ci: migrate to github hosted runner"

- .github/workflows/jan-docs.yml
- ci: fix docusaurus
- Closes #
- Closes #
> ci: fix docusaurus

- web/screens/Settings/Advanced/index.tsx
> fix: hidden box dropdown hardware if no list

- web/screens/Settings/Advanced/index.tsx
> fix: placeholder no hardware detect

- .github/workflows/jan-docs-new-release.yaml
- fix: docs trigger on release deploy to production
- Closes #
- Closes #
> fix: docs trigger on release deploy to production

- README.md
- chore: Readme add beta download url
- Closes #
- Closes #
> chore: Readme add beta download url

- extensions/inference-openai-extension/package.json
- extensions/inference-openai-extension/resources/models.json
- Deprecated GPT 4 with Vision
- Closes #3864 
- Closes #
> fix: deprecated gpt with vision

- core/tsconfig.json
- extensions/assistant-extension/tsconfig.json
- extensions/inference-nitro-extension/tsconfig.json
- extensions/tensorrt-llm-extension/tsconfig.json
> fix: types issue (#internalTypeOnlyBrand) in the @types/node package

- .github/workflows/jan-electron-build-beta.yml
- chore: beta version add discord notification
- Closes #
- Closes #
> chore: beta version add discord notification

- web/containers/Layout/BottomPanel/SystemMonitor/TableActiveModel/index.tsx
Decreased redundant labels
Before
After
- Closes #3882 
- Closes #
> ui: minor update list model running system monitor

- web/screens/Settings/HuggingFaceRepoDetailModal/ModelDownloadRow/index.tsx
- web/screens/Settings/MyModels/MyModelList/index.tsx
Enhance the `className` to improve text alignment.
- Closes #3883 
- Closes #
> fix: text align my model list and import model

- web/screens/LocalServer/LocalServerRightPanel/index.tsx
> feat: show model id on local api serve page

- web/screens/Thread/ThreadCenterPanel/SimpleTextMessage/index.tsx
Fix the chat input issue where messages render outside the box when being edited. 
- Closes #
- Closes #
> fix: edit chat input 

- web/package.json
Fix slate react version 
- Closes #
- Closes #
> fix: slate react version

- web/containers/ErrorMessage/index.test.tsx
- web/containers/ErrorMessage/index.tsx
Before
After
- Closes #3881 
- Closes #
> ui: remove generation interrupted message

- electron/utils/migration.ts
Don’t check if a theme already exists, just delete the theme folder if it’s present. This one is temporary since theme will move to extension and extension already have mechanism for migration
https://github.com/user-attachments/assets/951a2c84-e395-43b9-a5f3-243ffd75a94f
- Closes #3933 
- Closes #
> fix: update themes migrations

- extensions/inference-cortex-extension/src/index.ts
This addresses the issue where the app creates a dangling cortex-server process after relaunch. Killing it helps respawn a cortex.cpp session. Otherwise, cortex.cpp will reuse the previously loaded data cache even after everything is deleted.
1. **Introduction of `clean()` method**:
- A new method, `clean()`, is added to the `JanInferenceCortexExtension` class.
- This method sends a DELETE request to the `${CORTEX_API_URL}/processmanager/destroy` endpoint with a timeout of 2000 milliseconds.
- It includes error handling with a catch block that silently fails (does nothing).
2. **Integration of `clean()` method**:
- `clean()` is called in multiple places within the class:
- Right after fetching `systemInfo` and before executing the main node command.
- On the window's `beforeunload` event …
> chore: clean dangling process on exit and relaunch

- web/screens/LocalServer/LocalServerRightPanel/index.tsx
> fix: remove tooltip and update text color model ID API server page

- web/screens/Settings/HuggingFaceRepoDetailModal/ModelDownloadRow/index.tsx
> fix: text alignment on import model dialog

- .github/workflows/template-build-linux-x64.yml
- .github/workflows/template-build-macos-arm64.yml
- .github/workflows/template-build-macos-x64.yml
- .github/workflows/template-build-windows-x64.yml
- chore: revert change app name
- Closes #
- Closes #
> chore: revert change app name

- web/screens/LocalServer/LocalServerRightPanel/index.tsx
> fix: make input clickable for copying instead of just the copy icon

- web/containers/Layout/BottomPanel/SystemMonitor/index.tsx
https://github.com/janhq/jan/issues/3812#issuecomment-2459188308
https://github.com/user-attachments/assets/ecadd4f2-1ac4-47aa-aec1-35cf1d8889cc
- Closes #3812
- Closes #
> fix: remove click outside system monitor panel

- web/styles/components/code-block.scss
- https://github.com/janhq/jan/issues/3911#issuecomment-2460359849
avoid `codeblock` responsive push right panel 
- Closes #
- Closes #
> fix: codeblock responsive push right panel

- web/screens/LocalServer/LocalServerRightPanel/index.tsx
- web/screens/Thread/ThreadCenterPanel/ChatInput/RichTextEditor.tsx
- web/styles/components/code-block.scss
- web/styles/main.scss
> fix: handle edge cases syntax highlight

- web/containers/ErrorMessage/index.tsx
- web/screens/Thread/ThreadCenterPanel/LoadModelError/index.tsx
- Fix copy error message
- Closes #
- Closes #
> fix: update copy error message

- web/containers/Layout/BottomPanel/SystemMonitor/TableActiveModel/index.tsx
> fix: alignment stop model btn system monitor

- extensions/inference-cortex-extension/package.json
- extensions/inference-cortex-extension/resources/models/qwen2.5-coder-14b-instruct/model.json
- extensions/inference-cortex-extension/resources/models/qwen2.5-coder-32b-instruct/model.json
- extensions/inference-cortex-extension/rollup.config.ts
- extensions/inference-cortex-extension/src/@types/global.d.ts
- extensions/inference-cortex-extension/src/index.ts
- extensions/model-extension/src/cortex.ts
- web/screens/Settings/Advanced/index.tsx
This PR adds two new model.json files: Qwen2.5-Coder-14B and 32B. These files are to be listed on the Jan Model Hub. Moved the download event subscription from the model extension to the cortex to ensure consistency after reloading.
The changes in the diff primarily focus on updating the `inference-cortex-extension`, adding new model configurations, integrating websocket events, and cleaning up unused code. Here's a summary:
1. **Package Version Update:**  
- Updated the version in `package.json` from `1.0.20` to `1.0.21`.
2. **Model Configurations Added:**  
- Two new model JSON configuration files were added for `Qwen2.5-Coder-14B-Instruct` and `Qwen2.5-Coder-32B-Instruct` in the `resources/models` directory.
3. **Build Configuration (`rollup.config.ts`):**  
- Imported the new model …
> chore: add qwen2.5-coder 14B and 32B models

- extensions/inference-cortex-extension/src/index.ts
The cortex.cpp server could crash for various reasons. There’s a watchdog that restarts it, but the client should also reestablish the connection using the websocket endpoint /events.
This ensures download progress updates. 
Reproduce: 
1. Open Jan
2. Kill cortex.cpp process using Task Manager
3. Download a model
4. It stucks as 0%
1. **Class Properties:**
- Added a new class property `shouldReconnect` initialized to `true`. This indicates whether the WebSocket should attempt to reconnect after being closed.
2. **`onUnload` Method:**
- Added a `console.log` statement to indicate cleaning up services.
- Set the `shouldReconnect` property to `false` to prevent reconnection attempts when the object is being unloaded.
5. **WebSocket Handling:**
- Improved formatting by removing an empty space …
> hotfix: resubscribe download events on connection issue

- .github/workflows/jan-electron-build-nightly.yml
- .github/workflows/template-build-linux-x64.yml
- .github/workflows/template-build-macos-arm64.yml
- .github/workflows/template-build-macos-x64.yml
- .github/workflows/template-build-windows-x64.yml
- .github/workflows/template-noti-discord-and-update-url-readme.yml
> Revert "chore: enable notification nightly"

- .github/workflows/template-noti-discord-and-update-url-readme.yml
- chore: correct discord message notification
- Closes #
- Closes #
> chore: correct discord message notification

- extensions/inference-cortex-extension/src/index.ts
This PR fixes the issue where loading a model causes a timeout due to the client’s default configuration.
- #4056
> fix: disable timeout on model load

- extensions/inference-cortex-extension/download.sh
This folder structure update aims to ensure that cortex.cpp functions correctly when attempting to create a folder in a read-only location. It needs an empty folder for the current logic check. There will be a fix from cortex.cpp on that.
- #4062 
- #4063
> fix: temporary create a deps folder to have cortex.cpp work

- web/package.json
This is to bring this project up to a new version for the 0.5.9 release cut. The current code base is not synchronized with the released version, so this series of pull requests aims to address this issue.
#3445
> chore: version bump 0.5.9

- web/hooks/useStarterScreen.ts
- Closes # https://github.com/janhq/jan/issues/4055#issuecomment-2490335332
- Closes #4028
> fix: auto select model when finished download from starter screen

- web/screens/Settings/Advanced/index.tsx
- Closes # https://github.com/janhq/jan/issues/4055#issuecomment-2490576104
- Closes #
> fix: responsive vulkan support

- web/screens/Settings/Advanced/index.tsx
-
- Closes # https://github.com/janhq/jan/issues/4055#issuecomment-2490576104
- Closes #
> fix: vulkan responsive

- extensions/inference-anthropic-extension/package.json
- extensions/inference-anthropic-extension/resources/models.json
-  just update max-token limit 
- Closes #3973 
- Closes #
> enhancement: increased max-token limit claude-3.5

- web/screens/Thread/ThreadLeftPanel/index.tsx
https://github.com/user-attachments/assets/1a04459f-c585-4d39-9cbc-4d66368946dd
- Closes #4114 
- Closes #
> fix: default local model from starter screen

- web/package.json
- web/screens/Thread/ThreadCenterPanel/SimpleTextMessage/index.tsx
Reverts janhq/jan#4134 since this changes broke Latex support
> Revert "fix: memory leak lowlight dependencies"

- web/containers/TagInput/index.tsx
> fix: handle case stop word too long

- web/containers/ListContainer/index.tsx
https://github.com/user-attachments/assets/16d431ff-d3c5-4d3c-a305-07f2d21608c2
- Closes #
- Closes #
> fix: scroll bottom when switch thread

- web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx
- Fixed an issue where css inherited from Joi would increase the z-index
> fix: scrollbar issue css

- web/package.json
- This PR is to update web package.json app version from 0.5.10 to 0.5.11
- Closes #
- Closes #
> chore: bump web version 0.5.11

- README.md
- chore: update download url for macos universal
- Closes #
- Closes #
> chore: update download url for macos universal

- .github/workflows/jan-electron-build-beta.yml
- chore: fix beta ci
- Closes #
- Closes #
> chore: fix beta ci

- .github/ISSUE_TEMPLATE/roadmap.md
- Roadmap issue didnt appear due to headers
> chore: roadmap template fix

- .github/workflows/jan-electron-build-nightly.yml
- feat: add auto build when PR is approved
- Related issue: #4237
- Closes #
> feat: add auto build when PR is approved

- web/containers/CenterPanelContainer/index.tsx
- web/containers/Layout/index.tsx
- web/containers/LeftPanelContainer/index.tsx
- web/containers/MainViewContainer/index.tsx
- web/containers/RightPanelContainer/index.tsx
- web/screens/Thread/ThreadCenterPanel/ChatInput/RichTextEditor.tsx
- web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
- **Imports and State Management:**
- Added `useMediaQuery` import from `@janhq/joi`.
- Removed an unused `useMemo` import from `Layout`.
- Updated atom usage by importing new atoms for view and panel states.
1. **CenterPanelContainer/index.tsx:**
- Added logic to dynamically adjust the panel's `maxWidth` based on screen width and view state.
- Introduced new state variables using `useAtomValue` to manage panel visibility and view state.
- Adjusted CSS styles using `twMerge` for conditionally applying styles.
2. **Layout/index.tsx:**
- Removed an unused `useMemo` import to clean up the code.
3. **LeftPanelContainer/index.tsx:**
- Exported `LEFT_PANEL_WIDTH` for external access, enabling it to be used elsewhere in the application.
4. **MainViewContainer/index.tsx:**
- Modified the width of …
> fix: performance issue when pasting long content into the chat input box

- .github/workflows/publish-npm-joi.yml
- joi/package.json
- feat: add cicd for janhq/joi
- Closes #
- Closes #
> feat: add cicd for janhq/joi

- web/screens/LocalServer/LocalServerLeftPanel/index.tsx
Removal of <Tooltip> Component:
The <Tooltip> component wrapper has been removed entirely along with its properties, such as trigger and content
- Closes #4180 
- Closes #
> enhancement: remove tooltip local api server when server start

- web/containers/ErrorMessage/index.test.tsx
- web/containers/ErrorMessage/index.tsx
- web/containers/Providers/ModelHandler.tsx
- web/helpers/atoms/ChatMessage.atom.ts
- web/hooks/useActiveModel.ts
- web/hooks/useCreateNewThread.ts
- web/hooks/usePath.ts
- web/hooks/useSendChatMessage.ts
- web/screens/Thread/ThreadCenterPanel/ChatItem/index.tsx
- web/screens/Thread/ThreadCenterPanel/EditChatInput/index.tsx
- web/screens/Thread/ThreadCenterPanel/MessageToolbar/index.tsx
- web/screens/Thread/ThreadCenterPanel/TextMessage/DocMessage.tsx
- web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx
- web/utils/file.ts
- web/utils/messageRequestBuilder.ts
- web/utils/threadMessageBuilder.ts
This PR addresses an issue where the app didn't display the file name and size of message attachments since we were fetching messages from cortex.cpp. Now, we're fetching these details from the backend, and the client will save this information in the message metadata for quick retrieval without making numerous requests to the server.
- Closes #
- Closes #
The provided Git diff summary details the changes made to several files within a web application, specifically focusing on enhancing file handling and metadata management. Here's a breakdown of the main modifications:
- **Purpose**: To display file size along with the file ID.
- **Details**:
- Added props `id` and `metadata`.
- Used the `toGibibytes` function to convert the file size from bytes to GiB (gibibytes) if metadata is …
> fix: attach file information into message metadata for a quick retrieval

- web/screens/LocalServer/LocalServerLeftPanel/index.tsx
> fix: overlap bottom system monitor

- web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx
https://github.com/user-attachments/assets/fda219f8-0ae6-48f8-abe4-19964a8b1fc5
- Closes #4332 
- Closes #
> fix: regenerate scroll bottom

- extensions/inference-cortex-extension/download.bat
- extensions/inference-cortex-extension/download.sh
- extensions/inference-cortex-extension/rollup.config.ts
This PR aims to resolve the conflict arising from the hotfix change regarding the engine version update.
This pull request updates the version of the Cortex engine used in the `inference-cortex-extension` to a stable release. The most important changes include modifying the version in several configuration and script files.
Version updates:
* [`extensions/inference-cortex-extension/download.bat`](diffhunk://#diff-8a7d1c23da498167c2b1a94a2d4ce076f6f2549607a116a66528fe8e44c678a6L5-R5): Changed `ENGINE_VERSION` from `0.1.42-hotfix` to `0.1.42`.
* [`extensions/inference-cortex-extension/download.sh`](diffhunk://#diff-f67e38c5644b8fd2bea4d9a5ef8ac582f57884716ff91932b02809aa3fe36bedL5-R5): Changed `ENGINE_VERSION` from `0.1.42-hotfix` to `0.1.42`.
* …
> chore: resolve hotfix from main into dev

- .github/workflows/publish-npm-core.yml
- .github/workflows/publish-npm-joi.yml
- fix: ci npm publish
- Closes #
- Closes #
> fix: ci npm publish

- web/hooks/useSendChatMessage.ts
This pull request aims to resolve the issue of including the latest assistant response in the resend of recent chat messages, which disrupts the context. There are two main problems with this:
1. Some remote providers do not accept two consecutive assistant messages.
2. The models would be misled by the incorrect context of the user prompt.
- Closes #4423
- Closes #4339
This pull request includes changes to the `useSendChatMessage` function in the `web/hooks/useSendChatMessage.ts` file to enhance the message sending process. The most important changes include adding new conversation data to the `sendChatMessage` call and refactoring the message request building logic.
Enhancements to message sending:
* [`web/hooks/useSendChatMessage.ts`](diffhunk://#diff-4bcabf86358832bf98408dfb9dc4ef66ba0 …
> fix: empty response on some generation attempts

- docs/src/pages/index.mdx
This pull request includes a minor change to the `docs/src/pages/index.mdx` file. The change corrects a typo in the description.
* Corrected typo in the description from "privact" to "private" in `docs/src/pages/index.mdx`.
- Closes #
- Closes #
> fix: typo meta description

- docs/src/pages/docs/_meta.json
- docs/src/pages/docs/privacy-policy.mdx
- docs/src/pages/docs/privacy.mdx
- Add a comprehensive privacy policy page
- Hide privacy policy from navigation
- Update privacy page content
- Configure _meta.json for proper page visibility
- Closes #
- Closes #
> chore: privacy policy final

- web/containers/Layout/TopPanel/index.tsx
- web/screens/Settings/Engines/RemoteEngineSettings.tsx
This pull request includes changes to the `TopPanel` component and `RemoteEngineSettings` component to enhance the user interface and improve user experience. The most important changes are summarized below:
Enhancements to `TopPanel` component:
* Added `PanelLeftOpenIcon` to the import statement in `web/containers/Layout/TopPanel/index.tsx` to support the new icon usage.
* Modified the button in `TopPanel` to conditionally render `PanelLeftOpenIcon` when the `mainViewState` is not `MainViewState.Thread`, improving the visual feedback for users.
Improvements to `RemoteEngineSettings` component:
* Added bottom padding to the div in `web/screens/Settings/Engines/RemoteEngineSettings.tsx` to enhance the layout and spacing of the settings section.
- Closes #4495 
- Closes #
> enhancement: added space scroll remote engine setting

- extensions/yarn.lock
- web/containers/Providers/ModelHandler.tsx
- web/package.json
- web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx
- web/screens/Thread/ThreadCenterPanel/ChatItem/index.tsx
- web/screens/Thread/ThreadCenterPanel/TextMessage/ThinkingBlock.tsx
- web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx
- web/tailwind.config.js
- yarn.lock
This pull request introduces a new component for displaying "thinking" states in text messages and updates the Tailwind CSS configuration. The most important changes include adding the `ThinkingBlock` component, updating the `TextMessage` component to use the new `ThinkingBlock`, and enhancing the Tailwind CSS configuration.
* [`web/screens/Thread/ThreadCenterPanel/TextMessage/ThinkingBlock.tsx`](diffhunk://#diff-ab6a818fc54ea9f5203a346ab74e247517f9e3bdece1c4f52c109fe68c48e14eR1-R45): Added a new `ThinkingBlock` component to display a loading spinner and toggleable text block for "thinking" states.
* [`web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx`](diffhunk://#diff-efce7749ad34c34cc3f189aea671b9975208995580033b9de787c3c96c878cccR19): Imported the new `ThinkingBlock` …
> chore: reasoning block

- web/screens/Settings/Engines/ModalDeleteCustomEngine.tsx
- web/screens/Settings/Engines/RemoteEngineItem.tsx
- web/screens/Settings/Engines/RemoteEngineSettings.tsx
This pull request introduces a new modal component to handle the deletion of custom engines, along with several related changes to integrate this functionality into the existing settings screens. The key changes include the addition of the `ModalDeleteCustomEngine` component, updates to the `RemoteEngineItem` and `RemoteEngineSettings` components to use this new modal, and the addition of a utility function to retrieve engine logos.
Integration of the new modal component:
* Added `ModalDeleteCustomEngine` component to handle the deletion of custom engines, with state management for modal visibility and a confirmation dialog. (`web/screens/Settings/Engines/ModalDeleteCustomEngine.tsx`)
Updates to existing components:
* Integrated `ModalDeleteCustomEngine` into `RemoteEngineItem` to provide …
> chore: delete custom engine

- web/screens/Hub/index.tsx
This pull request includes a small change to the `web/screens/Hub/index.tsx` file. The change updates the `HubScreen` component to improve the visual appearance and consistency of the UI elements.
* Updated the background color of the `div` element to use `hsla(var(--app-bg))` instead of `bg-white`.
* Added a `className` to the `ImagePlusIcon` to set the text color to `hsla(var(--text-secondary))`.
- Closes #
- Closes #
> enhancement: toggle change cover hub banner style

- extensions/yarn.lock
- web/containers/ModelLabel/ModelLabel.test.tsx
- web/containers/ModelLabel/index.tsx
- yarn.lock
This pull request includes a change to the `ModelLabel` component in the `web/containers/ModelLabel/index.tsx` file. The most important change involves modifying the calculation of `minimumRamModel` to ensure it is correctly converted to bytes.
* [`web/containers/ModelLabel/index.tsx`](diffhunk://#diff-bfb0a9dfbc5c4313f7542042221037f3f5ddca8a52b56683ecffa1c42460e0e7L41-R46): Updated the `minimumRamModel` calculation to convert the size from megabytes to bytes.
- Closes #4583 
- Closes #
> chore: calculate model label

- docs/src/pages/docs/configure-extensions.mdx
- docs/src/pages/docs/install-engines.mdx
- electron/package.json
- extensions/inference-cortex-extension/resources/default_settings.json
- web/screens/Settings/Advanced/FactoryReset/ModalConfirmReset.tsx
- web/screens/Settings/Advanced/FactoryReset/index.tsx
- web/screens/Settings/Advanced/index.tsx
- web/screens/Settings/CoreExtensions/index.tsx
- web/screens/Settings/Engines/ModalAddRemoteEngine.tsx
- web/screens/Settings/Engines/RemoteEngineSettings.tsx
> chore: Updated copies in-app

- web/styles/components/code-block.scss
This pull request includes minor style adjustments to the `code-block` component in the `web/styles/components/code-block.scss` file. The changes primarily focus on improving the visual appearance of code blocks.
Style adjustments:
* Removed an unnecessary blank line within the `pre` block to maintain cleaner code formatting.
* Added a background color to the `pre` element within the `.code-block` class to enhance the visual distinction of code blocks.
- Closes #4219 
- Closes #
> chore: update style codeblock

- extensions/yarn.lock
- web/containers/ModelDropdown/index.tsx
This pull request includes changes to the `ModelDropdown` component in `web/containers/ModelDropdown/index.tsx` to improve the handling of model items based on their download status and configuration.
Key changes:
* Added conditional rendering for `isDownloaded` models to ensure that only downloaded models are displayed in the dropdown. [[1]](diffhunk://#diff-897fe0e9366de0fa6ec9428b1423439aaab3dee774cea4b7efd6401a42fb00fbR552-R553) [[2]](diffhunk://#diff-897fe0e9366de0fa6ec9428b1423439aaab3dee774cea4b7efd6401a42fb00fbR626-R627)
* Improved the readability of the `onClick` handler by reformatting the conditional check for `isConfigured` and `engine.type`.
- Closes # https://github.com/janhq/jan/issues/4456#issuecomment-2646811963
- Closes #
> fix: remove from list dropdown when deleted remote model

- web/screens/Settings/Advanced/index.tsx
This pull request involves significant changes to the `Advanced` component in the `web/screens/Settings/Advanced/index.tsx` file, primarily focusing on the removal of GPU and Vulkan support settings. These changes simplify the component by eliminating unused states and corresponding UI elements.
Key changes include:
* Removed state management for `vulkanEnabled`, `gpuEnabled`, `gpuList`, and `gpusInUse`, along with their associated hooks and state updates. [[1]](diffhunk://#diff-8d119b4ddbfcbb13597702a44730e486bc4c02dc630069686effa3333ab90411L61-L67) [[2]](diffhunk://#diff-8d119b4ddbfcbb13597702a44730e486bc4c02dc630069686effa3333ab90411L80-L85) [[3]](diffhunk://#diff-8d119b4ddbfcbb13597702a44730e486bc4c02dc630069686effa3333ab90411L113-L130) …
> fix: remove toggle enable GPU from setting

- extensions/yarn.lock
- web/containers/ErrorMessage/index.tsx
- web/utils/modelEngine.ts
This pull request includes changes to improve the handling of engine names and logos in the `web` application. The most important changes include updating the logic for setting the selected settings screen and modifying the logo returned for the Google Gemini engine.
Changes to engine handling:
* [`web/containers/ErrorMessage/index.tsx`](diffhunk://#diff-711ca7c6c49338a63c87e2e9eee4cae1cc0ec950daf8269051e23ca64ca0f244L70-R70): Updated the logic to set the selected settings screen to use the `activeAssistant` model's engine if available, otherwise default to an empty string.
Changes to logo handling:
* [`web/utils/modelEngine.ts`](diffhunk://#diff-309cd47b5075dcd8ead194871d0804128567943093ba99c5138ce1c173cf1918L33-R33): Modified the logo returned for the 'google_gemini' case to use the …
> fix: error setting remote engine

- extensions/yarn.lock
- web/screens/Settings/Hardware/index.tsx
This pull request includes several changes to the `Hardware` component in the `web/screens/Settings/Hardware/index.tsx` file. The changes focus on improving the GPU management functionality, including handling GPU activation, reordering GPUs, and updating the UI to reflect these changes.
Key changes include:
* Added state management for GPU activation using `isActivatingGpu` to handle the loading state when toggling GPU activation. [[1]](diffhunk://#diff-3121a4c10de81ebf1d30e16b0b45015089e9777193653a11ef4b9fd4ccaf123cR61-R72) [[2]](diffhunk://#diff-3121a4c10de81ebf1d30e16b0b45015089e9777193653a11ef4b9fd4ccaf123cR327-R330)
* Updated the `handleSwitchChange` function to call the API for updating active GPUs and to use the `mutate` function for refreshing hardware data.
* Introduced …
> fix: gpu hardware state

- core/src/types/api/index.ts
- electron/handlers/native.ts
- electron/handlers/update.ts
- extensions/yarn.lock
- web/containers/Layout/index.tsx
- web/containers/ModalAppUpdaterChangelog/index.tsx
- web/containers/ModalAppUpdaterNotAvailable/index.tsx
- web/containers/Providers/AppUpdateListener.tsx
- web/helpers/atoms/App.atom.ts
- web/hooks/useGetLatestRelease.ts
- web/styles/components/marked.scss
This pull request introduces a new feature for handling app updates, including downloading updates and notifying users when updates are available or not available. The changes span across multiple files to integrate this new functionality.
* Added new routes and events for app updates in `core/src/types/api/index.ts` (`NativeRoute.appUpdateDownload`, `AppEvent.onAppUpdateNotAvailable`, `AppEvent.onAppUpdateAvailable`). [[1]](diffhunk://#diff-543426fd3b39253ddc7713a91eb8c1f46d7afb727cd65c2668dd987f3913de7eR34-R35) [[2]](diffhunk://#diff-543426fd3b39253ddc7713a91eb8c1f46d7afb727cd65c2668dd987f3913de7eR55-R56)
* Integrated `electron-updater` to handle app updates in `electron/handlers/native.ts` and `electron/handlers/update.ts`. This includes handling IPC messages for downloading updates …
> feat: app updater with changelog

- web/containers/SliderRightPanel/index.tsx
- web/screens/Settings/SettingDetail/SettingDetailItem/SettingDetailTextInputItem/index.tsx
This pull request includes several changes to the `web` directory, specifically enhancing input handling and UI adjustments in the `SliderRightPanel` and `SettingDetailTextInputItem` components. The most important changes include modifying the width of an input field, adding a `value` prop to the `InputExtraActions` component, and conditionally rendering the `CopyIcon` based on the `value` prop.
UI Adjustments:
* [`web/containers/SliderRightPanel/index.tsx`](diffhunk://#diff-9775d009332933969544fe2d0fbd175e312327e5f3b63bd9ec2ef89b56492f65L76-R76): Modified the width of the input field from `60px` to `68px`  to improve the layout.
Enhancements to input handling:
* [`web/screens/Settings/SettingDetail/SettingDetailItem/SettingDetailTextInputItem/index.tsx`](diffhunk://#diff-7fe05fe4ba4617679 …
> chore: update ui width text field slider, and conditional button copy based value length

- server/cortex.json
This PR updates the server playground schema to align with the latest Cortex.cpp API specifications. The changes ensure compatibility with new API structures, parameter updates, and any recent modifications in request/response formats.
Changes:
- Updated schema definitions to reflect the latest Cortex.cpp API updates.
- Adjusted request/response handling to match the new specifications.
- Refactored validation rules to align with updated parameter constraints.
- Fixed any inconsistencies between the schema and the API responses.
> chore: Sync Server Playground Schema with Latest Cortex.cpp API Specs

- joi/src/core/Slider/Slider.test.tsx
- joi/src/core/Slider/index.tsx
- web/screens/Hub/ModelFilter/ContextLength/index.tsx
- web/screens/Hub/ModelFilter/ModelSize/index.tsx
- web/screens/Hub/ModelList/index.tsx
- web/screens/Hub/index.tsx
- web/screens/Settings/MyModels/index.tsx
This pull request includes significant enhancements to the filtering functionality and UI improvements in the `Hub` screen. The most important changes include the addition of new filter components, modifications to the filtering logic, and UI adjustments to accommodate these new features.
* **Context Length Filter**: Added a new `ContextLengthFilter` component that allows users to filter models based on context length. (`web/screens/Hub/ModelFilter/ContextLength/index.tsx`)
* **Model Size Filter**: Added a new `ModelSizeFilter` component that allows users to filter models based on their size. (`web/screens/Hub/ModelFilter/ModelSize/index.tsx`)
* **Filtering Logic**: Implemented filtering logic in `HubScreen` to filter models based on compatibility, context length, and model size. …
> feat: Jan Model Hub filter options and responsiveness

- .husky/pre-commit
- web/containers/ModelDropdown/index.tsx
- web/screens/Settings/SettingLeftPanel/index.tsx
- web/screens/Thread/ThreadCenterPanel/ChatBody/OnDeviceStarterScreen/index.test.tsx
- web/screens/Thread/ThreadCenterPanel/ChatBody/OnDeviceStarterScreen/index.tsx
- web/utils/model.ts
This pull request includes significant updates to the model handling logic in the `ModelDropdown` and `OnDeviceStarterScreen` components, as well as some improvements to the settings panel. The main changes involve refactoring how models are filtered and displayed, and updating the manual recommendation model list.
- Closes #4724
* [`web/containers/ModelDropdown/index.tsx`](diffhunk://#diff-897fe0e9366de0fa6ec9428b1423439aaab3dee774cea4b7efd6401a42fb00fbR59-R60): Refactored to use `useGetModelSources` for fetching model sources and updated the logic for filtering and displaying featured models. [[1]](diffhunk://#diff-897fe0e9366de0fa6ec9428b1423439aaab3dee774cea4b7efd6401a42fb00fbR59-R60) [[2]](diffhunk://#diff-897fe0e9366de0fa6ec9428b1423439aaab3dee774cea4b7efd6401a42fb00fbR89) …
> chore: enhance onboarding screen's models

- web/containers/Providers/ModelHandler.tsx
- web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx
- web/utils/datetime.test.ts
- web/utils/datetime.ts
This pull request includes several changes to the `ModelHandler` and `MessageContainer` components to enhance the handling and display of the active model. Additionally, there are improvements to the `displayDate` utility function. The most important changes are listed below:
Enhancements to `ModelHandler`:
* Added the `model` property to the metadata in the `ModelHandler` component to keep track of the active model. (`web/containers/Providers/ModelHandler.tsx`, [[1]](diffhunk://#diff-c52744b512485151ef69f9c9e8b58535cc47dc550c4caf152cb52ec103ea898dR236) [[2]](diffhunk://#diff-c52744b512485151ef69f9c9e8b58535cc47dc550c4caf152cb52ec103ea898dR289)
Updates to `MessageContainer`:
* Imported `selectedModelAtom` to use the selected model in the `MessageContainer` component. …
> enhancement: improve chat thread

- extensions/yarn.lock
- web/screens/Settings/Engines/RemoteEngineSettings.tsx
- web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx
- web/screens/Thread/ThreadCenterPanel/TextMessage/MarkdownTextMessage.tsx
- web/styles/base/global.scss
- yarn.lock
This pull request includes changes to improve the user experience in the `ChatBody` component and minor text formatting adjustments. The most important changes include adding a new import for `ScrollArea`, introducing a new atom for showing the scrollbar, and replacing a `div` with `ScrollArea` to control scrollbar visibility.
Improvements to `ChatBody` component:
* [`web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx`](diffhunk://#diff-3f5d1c0b7af75f2f221b9504d3f50f0cb42b683d7eb7b565caf7ced16b2c765fR4): Added import for `ScrollArea` from `@janhq/joi`.
* [`web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx`](diffhunk://#diff-3f5d1c0b7af75f2f221b9504d3f50f0cb42b683d7eb7b565caf7ced16b2c765fR18): Added import for `showScrollBarAtom` from `@/helpers/atoms/Setting.atom`.
* …
> fix: chat body scrollbar

- extensions/model-extension/resources/default.json
- extensions/model-extension/src/index.ts
- web/containers/ModelDropdown/index.tsx
- web/hooks/useModelSource.ts
- web/screens/Hub/ModelPage/index.tsx
- web/screens/Thread/ThreadCenterPanel/ChatBody/OnboardingScreen/index.test.tsx
- web/screens/Thread/ThreadCenterPanel/ChatBody/OnboardingScreen/index.tsx
- web/utils/model.ts
- web/utils/modelSource.ts
This pull request includes changes to improve the handling of featured models and streamline the codebase. The most important changes include adding a new hook to fetch featured models, updating components to use this new hook, and removing hardcoded model recommendations.
Improvements to model handling:
* [`web/hooks/useModelSource.ts`](diffhunk://#diff-5e0c973c39a3d16e59f104aab16adb5d1d5cc6c16ae514199d619efc6a281129R39-R54): Added a new `useGetFeaturedSources` hook to fetch featured models based on tags.
Updates to components:
* [`web/containers/ModelDropdown/index.tsx`](diffhunk://#diff-897fe0e9366de0fa6ec9428b1423439aaab3dee774cea4b7efd6401a42fb00fbL38-L45): Updated the `ModelDropdown` component to use the new `useGetFeaturedSources` hook instead of filtering sources manually. …
> chore: remove hard coded recommendation models and use cortexso featured tags

- joi/src/core/Select/index.tsx
- web/helpers/atoms/App.atom.ts
- web/screens/Settings/Engines/LocalEngineSettings.tsx
This pull request introduces a new feature to recommend engine variants and updates the `Select` component to display recommended items. The changes span across multiple files, including `index.tsx`, `App.atom.ts`, and `LocalEngineSettings.tsx`.
* [`joi/src/core/Select/index.tsx`](diffhunk://#diff-b0abbab7f956d242f3fb0661d91d04167bef8130b803631b55b9b88a853f2bc1L10-R10): Added an optional `recommend` property to the `options` type and updated the component to display a "Recommended" label next to recommended items. [[1]](diffhunk://#diff-b0abbab7f956d242f3fb0661d91d04167bef8130b803631b55b9b88a853f2bc1L10-R10) [[2]](diffhunk://#diff-b0abbab7f956d242f3fb0661d91d04167bef8130b803631b55b9b88a853f2bc1R65-R74)
* [`web/helpers/atoms/App.atom.ts`](diffhunk://#diff-1d0026312115a8f15cb85d46967de396a06 …
> enhancement: recommended label engine variant

- joi/src/core/Select/index.tsx
- web/screens/Settings/Appearance/index.tsx
This pull request includes changes to the `Select` component in `joi/src/core/Select/index.tsx` and its usage in `web/screens/Settings/Appearance/index.tsx`. The updates primarily add new props to the `Select` component to enhance its positioning and alignment capabilities.
Enhancements to `Select` component:
* [`joi/src/core/Select/index.tsx`](diffhunk://#diff-b0abbab7f956d242f3fb0661d91d04167bef8130b803631b55b9b88a853f2bc1R14-R20): Added new props `side`, `position`, and `sideOffset` to the `Props` type definition. These props allow specifying the side of the content, the position alignment, and the offset of the content, respectively.
* [`joi/src/core/Select/index.tsx`](diffhunk://#diff-b0abbab7f956d242f3fb0661d91d04167bef8130b803631b55b9b88a853f2bc1R32-R35): Updated the `Select` …
> fix: cannot click dropdown appearance

- server/cortex.json
- server/index.ts
This pull request includes several changes to the `server/cortex.json` and `server/index.ts` files to enhance the server configuration and proxy setup. The most important changes include adding server URLs to various endpoints in the `cortex.json` file and registering multiple proxies in the `index.ts` file.
- Closes #4489 
Enhancements to server configuration:
* [`server/cortex.json`](diffhunk://#diff-c4d6fe70c5695c3864cbd758d142aabacd9fdbbf8b25024726949689543a9675R599-R603): Added server URLs to the `/healthz`, `/processManager/destroy`, `/system`, `/system/events/download`, `/system/events/model`, and `/system/events/resources` endpoints. [[1]](diffhunk://#diff-c4d6fe70c5695c3864cbd758d142aabacd9fdbbf8b25024726949689543a9675R599-R603) …
> fix: some endpoints are invisible

- web/containers/ModalTroubleShoot/index.tsx
- fix jan-help discord channel
> fix: correct jan discord channel

- web/app/search/layout.tsx
- web/screens/Settings/MyModels/MyModelList/index.tsx
This pull request includes changes to the `RootLayout` component in `web/app/search/layout.tsx` and a minor adjustment in the `MyModelList` component in `web/screens/Settings/MyModels/MyModelList/index.tsx`. The main focus is on wrapping the layout with a `ThemeWrapper` and adjusting the layout of the `MyModelList`.
Changes to `RootLayout`:
* [`web/app/search/layout.tsx`](diffhunk://#diff-e3e6bfcab6aea9a6a11b1560a67b5d763bedef343aeeda9d0ef990c2097acfb5R19): Imported `ThemeWrapper` to provide theme context to the component tree.
* [`web/app/search/layout.tsx`](diffhunk://#diff-e3e6bfcab6aea9a6a11b1560a67b5d763bedef343aeeda9d0ef990c2097acfb5L48-R52): Wrapped the `RootLayout` component's return elements with `ThemeWrapper` to ensure proper theming.
Changes to `MyModelList`:
* …
> fix: quickask ui color and alignment on mymodel list

- extensions/yarn.lock
- web/package.json
- web/screens/Hub/ModelPage/index.tsx
- web/screens/Hub/index.tsx
- web/screens/Thread/ThreadCenterPanel/TextMessage/MarkdownTextMessage.tsx
- web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx
- web/styles/components/code-block.scss
- web/styles/components/marked.scss
- yarn.lock
This pull request includes several updates to the `web` package, focusing on dependency updates, UI improvements, and style adjustments. The most important changes include adding the `rehype-raw` plugin, improving the table layout in `ModelPage`, and making various style adjustments to enhance the appearance and functionality of code blocks and tables.
Dependency updates:
* [`web/package.json`](diffhunk://#diff-b861012a5dd72b8a9f3281b7cf09f5a779c98569d040b1bbc1db50f1b15e7cceR52): Added `rehype-raw` dependency to the project.
UI improvements:
* [`web/screens/Hub/ModelPage/index.tsx`](diffhunk://#diff-02e81029a62de211929358113c60a101efd0bd0f7ce9b2237fa4cfabecba0a21L141-R142): Improved the table layout by making it horizontally scrollable and using the `table-auto` class for better table …
> fix: Hub UI issue render readme

- web/screens/Thread/ThreadCenterPanel/TextMessage/MarkdownUtils.tsx
- web/styles/components/marked.scss
This pull request includes changes to improve the rendering of markdown tables and adjust the styles for marked components. The most important changes include adding a custom component for rendering tables in markdown and updating the styles for marked components.
Improvements to markdown rendering:
* [`web/screens/Thread/ThreadCenterPanel/TextMessage/MarkdownUtils.tsx`](diffhunk://#diff-5aeffa1f37d6a07d7c13880bbf949af39e58962c8b394045ec540998a9b56274R14-R20): Added a custom `table` component to improve the rendering of tables in markdown by wrapping them in a div with overflow handling and border styling.
Adjustments to styles:
* [`web/styles/components/marked.scss`](diffhunk://#diff-1b1f53e7a74b33e06c05954c28edd796aaa6576156a27e4e154d70e4c2bf2651L67): Removed the `display: flow;` …
> fix: table markdown

- web/screens/Hub/ModelPage/index.tsx
- web/screens/Settings/Appearance/index.tsx
- web/styles/components/marked.scss
This pull request includes changes to improve the user interface and style of the application. The most important changes focus on enhancing the layout and appearance of components on the ModelPage and within the marked lists.
User Interface Improvements:
* [`web/screens/Hub/ModelPage/index.tsx`](diffhunk://#diff-02e81029a62de211929358113c60a101efd0bd0f7ce9b2237fa4cfabecba0a21L54-R54): Added `z-10` to the class of the sticky header div to ensure it appears above other content when scrolling.
Styling Enhancements:
* [`web/styles/components/marked.scss`](diffhunk://#diff-1b1f53e7a74b33e06c05954c28edd796aaa6576156a27e4e154d70e4c2bf2651R103-R105): Modified the `li` element to include a `p` tag with `display: inline` to ensure paragraphs within list items are displayed inline, improving the …
> fix: minor ui issue

- core/src/types/api/index.ts
- electron/handlers/native.ts
- electron/main.ts
- extensions/assistant-extension/rolldown.config.mjs
- extensions/assistant-extension/src/@types/global.d.ts
- extensions/assistant-extension/src/node/retrieval.ts
- extensions/conversational-extension/rolldown.config.mjs
- extensions/conversational-extension/src/@types/global.d.ts
- extensions/conversational-extension/src/index.ts
- extensions/engine-management-extension/rolldown.config.mjs
- extensions/engine-management-extension/src/@types/global.d.ts
- extensions/engine-management-extension/src/index.ts
- extensions/hardware-management-extension/rolldown.config.mjs
- extensions/hardware-management-extension/src/@types/global.d.ts
- extensions/hardware-management-extension/src/index.ts
- extensions/inference-cortex-extension/rolldown.config.mjs
- extensions/inference-cortex-extension/src/@types/global.d.ts
- extensions/inference-cortex-extension/src/index.ts
- extensions/inference-cortex-extension/src/node/index.ts
- extensions/model-extension/rolldown.config.mjs
- extensions/model-extension/src/@types/global.d.ts
- extensions/model-extension/src/index.ts
- server/global.d.ts
- server/index.ts
- server/rolldown.config.mjs
- web/hooks/useGetLatestRelease.ts
This update enables Jan to generate an app API key for each run, which will be whitelisted by the corresponding cortex.cpp server. To ensure that the application does not require access to a persistent environment variable or file system that is restricted for browser access,
Flow:
1. Main node is up
2. Generate a new api key and persist into it's process environment variable (so that other functions run on this node will have access to)
3. Pass it thru the browser window context so that browser process can access
4. This api key will then be used to spawn a cortex-server (whitelisted)
5. Now both main and browser processes will have access to the api key and use it to communicate with cortex.cpp server.
```mermaid
graph TD
A[Main Node is Up] --> B[Generate New API Key]
B --> C[Persist …
```
> feat: rotate api token for each run

- electron/package.json
- web/containers/ModelDropdown/index.tsx
- web/hooks/useHardwareManagement.ts
- Fix the two warnings that is displayed in the main chat page.
> fix/main-chat-page: warnings from React

- docs/src/pages/integrations/_meta.json
- docs/src/pages/integrations/index.mdx
This PR is to remove outdated Workflow Automation from Jan's doc
> chore: remove workflow automation

- src-tauri/src/core/cmd.rs
- src-tauri/src/lib.rs
- web/package.json
- web/screens/Settings/MCP/configuration.tsx
- web/screens/Settings/MCP/index.tsx
- web/screens/Settings/MCP/search.tsx
- web/screens/Settings/SettingDetail/index.tsx
- web/screens/Settings/index.tsx
- web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx
- web/services/tauriService.ts
This pull request includes several changes to add MCP server configuration and management functionality to the application. The most important changes include the addition of new commands for handling MCP configurations, updates to the user interface to support these configurations, and modifications to the package dependencies.
* [`src-tauri/src/core/cmd.rs`](diffhunk://#diff-ada8b0b4d64e53c5f2faf5f2de4c0e1fadc30594e3446b5c414a1ccb1b6999b7R10-R12): Added new constants and two new Tauri commands, `get_mcp_configs` and `save_mcp_configs`, to handle MCP configuration files. (`[[1]](diffhunk://#diff-ada8b0b4d64e53c5f2faf5f2de4c0e1fadc30594e3446b5c414a1ccb1b6999b7R10-R12)`, `[[2]](diffhunk://#diff-ada8b0b4d64e53c5f2faf5f2de4c0e1fadc30594e3446b5c414a1ccb1b6999b7R358-R383)`)
* …
> feat: MCP settings UI 

- README.md
- Updated the llama.cpp project URL in readme
> chore: update llama.cpp repo url in readme

- docs/bun.lock
- docs/src/pages/docs/index.mdx
- docs/src/pages/docs/quickstart.mdx
This PR only deals with documentation, and it represents the first of many in an effort to make the Jan docs a best-in-class documentation site.
Files changes
- Overview
- Quickstart
> Enhanced the wording on the overview and the quickstart pages.

- package.json
- src-tauri/.gitignore
- src-tauri/binaries/download.bat
- src-tauri/tauri.conf.json
This pull request introduces several changes to improve cross-platform compatibility, enhance the build process, and add support for Windows-specific binaries. The key updates include adding the `cross-env` package, modifying configuration files to use `cross-env`, and introducing a new batch script for managing Windows binaries.
* Added the `cross-env` package to `package.json` to ensure environment variables are set correctly across different operating systems. (`[package.jsonR48](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R48)`)
* Updated `src-tauri/tauri.conf.json` to use `cross-env` for the `beforeDevCommand` and `beforeBuildCommand` properties, ensuring compatibility in development and build processes. …
> chore: add windows download script

- package.json
- web-app/package.json
- web-app/src/containers/HeaderPage.tsx
- The previous package.json was referring to a non existent dev:web-app command so I modified it slightly
> fix: chore FE package

- .github/workflows/jan-electron-build-beta.yml
- .github/workflows/jan-electron-build-nightly.yml
- .github/workflows/jan-electron-build.yml
- .github/workflows/template-electron-build-linux-x64.yml
- .github/workflows/template-electron-build-macos.yml
- .github/workflows/template-electron-build-windows-x64.yml
- .github/workflows/template-tauri-build-linux-x64-preview.yml
- .github/workflows/template-tauri-build-macos-preview.yml
- .github/workflows/template-tauri-build-windows-x64-preview.yml
This pull request updates the workflow configuration for nightly builds to include both Tauri and Electron builds across macOS, Windows, and Linux platforms. It also introduces a new reusable workflow for building Electron apps on Linux. The changes improve modularity, support for multiple build types, and alignment with the nightly build process.
* Added support for triggering the workflow on pull requests targeting the `chore/tauri-cicd` branch, enabling better CI/CD integration for Tauri builds. (`.github/workflows/jan-electron-build-nightly.yml`)
* Renamed and updated job definitions to distinguish between Tauri and Electron builds for macOS, Windows, and Linux platforms, with Tauri builds using preview templates. (`.github/workflows/jan-electron-build-nightly.yml`) …
> feat: tauri cicd preview

- Makefile
- scripts/download-bin.js
- Update download script to only download when files do not exist locally
- Add download command to `dev-tauri` make target
- Closes #
- Closes #
> [feat] Download bun+uv on `make dev-tauri`

- web-app/src/containers/DropdownModelProvider.tsx
- web-app/src/containers/HeaderPage.tsx
- web-app/src/containers/LeftPanel.tsx
- web-app/src/routes/__root.tsx
- web-app/src/routes/hub.tsx
This pull request introduces several changes to improve the z-index layering of UI components across various parts of the application. These updates aim to ensure proper stacking order and avoid visual overlapping issues. Below is a summary of the most important changes grouped by theme.
* [`DropdownModelProvider.tsx`](diffhunk://#diff-c2c9bb4171fbcfe7f094df2d1c84e275b36e6193bb6138e5dd30779eaf990facL57-R57): Added `relative z-20` to the button in the dropdown menu to ensure it appears above other elements.
* [`HeaderPage.tsx`](diffhunk://#diff-6142e9d00525ff508db8ebee2ddba27512057338ca4658ce5b63ad738d4dbd47L27-R30): Updated the `IconLayoutSidebar` component to include `relative z-20` for proper layering.
* [`LeftPanel.tsx`](diffhunk://#diff-8fe9510686bc63c447d596c9015da8053ef7172d644ed42f7 …
> chore: increase hight of drag area window

- web-app/src/containers/LeftPanel.tsx
- web-app/src/routes/settings/providers/$providerName.tsx
- web-app/src/routes/threads/$threadId.tsx
This pull request introduces updates to improve the user experience in the `LeftPanel` and `ProviderDetail` components, refactors menu handling, and enhances empty state messaging across the application. Additionally, it removes unnecessary debugging logs.
* [`web-app/src/containers/LeftPanel.tsx`](diffhunk://#diff-8fe9510686bc63c447d596c9015da8053ef7172d644ed42f7daa12a2a794a706R262-R296): Added empty state messages for when no threads are available or when a search yields no results. These messages include icons (`IconMessageFilled` and `IconSearch`) and descriptive text to guide users.
* [`web-app/src/routes/settings/providers/$providerName.tsx`](diffhunk://#diff-bf67bc43ea4ed453c69e14c27bd2fe2006545cb6cedc1fbad166857e073303b5L259-R274): Added a message for when no models are available …
> chore: update empty state thread list, search, and no model

- web-app/src/containers/DownloadManegement.tsx
- web-app/src/routes/hub.tsx
- web-app/src/routes/index.tsx
This pull request introduces enhancements to the download management and model handling functionality in the web application, including improved user feedback, progress tracking, and dynamic UI updates. Key changes involve adding toast notifications, refining progress display, and integrating download states into the Hub and Index routes.
* Added toast notifications for download completion and cancellation to improve user feedback. (`web-app/src/containers/DownloadManegement.tsx`, [[1]](diffhunk://#diff-3f20b1fc2c81e2b1ad736c8382f24d27627a894a8f7ddd6483a5df7acf3d494dR81-R84) [[2]](diffhunk://#diff-3f20b1fc2c81e2b1ad736c8382f24d27627a894a8f7ddd6483a5df7acf3d494dL145-R187)
* Updated download progress display to use rounded percentages for clarity. …
> chore: cleanup download management

- web-app/package.json
- web-app/src/components/ui/dropdown-menu.tsx
- web-app/src/components/ui/textarea.tsx
- web-app/src/constants/localStorage.ts
- web-app/src/constants/routes.ts
- web-app/src/containers/ChatInput.tsx
- web-app/src/containers/DropdownAssistant.tsx
- web-app/src/containers/DropdownModelProvider.tsx
- web-app/src/containers/HeaderPage.tsx
- web-app/src/containers/LeftPanel.tsx
- web-app/src/containers/dialogs/AddEditAssistant.tsx
- web-app/src/hooks/useAssistant.ts
- web-app/src/routeTree.gen.ts
- web-app/src/routes/assistant.tsx
- web-app/src/routes/index.tsx
- web-app/src/routes/threads/$threadId.tsx
This pull request introduces a new "Assistant" feature to the web application, along with several UI and functionality improvements. The changes include adding a dropdown for managing assistants, updating routes and constants, and refining the UI components for better usability.
* [`web-app/src/hooks/useAssistant.ts`](diffhunk://#diff-31ef10114cb17030e296e4b582d6c4d5f6c1873078a75c4af856450a32f540cdR1-R51): Added a new `useAssistant` hook to manage assistant data, including adding, updating, and deleting assistants. A default assistant is pre-configured.
* [`web-app/src/containers/DropdownAssistant.tsx`](diffhunk://#diff-e9ccbe160523f61bf72f5ab0b7596479eb20b8303ead55a263f87a32d3c1f4c4R1-R67): Created a dropdown menu for selecting and managing assistants, with functionality to add or edit …
> chore: initial assistant feature

- extensions/conversational-extension/package.json
- extensions/hardware-management-extension/package.json
- extensions/model-extension/package.json
- src-tauri/src/core/mcp.rs
- web-app/src/hooks/useMCPServers.ts
- web-app/src/hooks/useProxyConfig.ts
- web-app/src/routes/settings/extensions.tsx
- web-app/src/routes/settings/https-proxy.tsx
- web-app/src/routes/settings/mcp-servers.tsx
- web-app/src/services/models.ts
- web-app/src/types/modelProviders.d.ts
This pull request introduces several updates, focusing on improving proxy configuration, enhancing MCP server management, and refining extension handling in the web application. Additionally, minor description changes were made in package metadata files. Below is a summary of the most important changes grouped by theme:
* Added a new `useProxyConfig` hook using `zustand` to manage proxy-related state, including settings for SSL verification and proxy credentials (`web-app/src/hooks/useProxyConfig.ts`).
* Integrated the `useProxyConfig` hook into the HTTPS Proxy settings page, enabling dynamic updates to proxy configurations and syncing them with the backend via the `configurePullOptions` function (`web-app/src/routes/settings/https-proxy.tsx`). …
> chore: allow users to enable/disable MCP servers

- web-app/src/components/ui/textarea.tsx
- web-app/src/containers/DropdownAssistant.tsx
- web-app/src/containers/dialogs/AddEditAssistant.tsx
- web-app/src/hooks/useAssistant.ts
- web-app/src/routes/assistant.tsx
This pull request introduces significant updates to the assistant management UI and functionality, including improvements to dropdown menus, parameter handling, and assistant deletion. The changes enhance user experience, add support for more complex parameter types, and improve the overall maintainability of the codebase.
* Added a dropdown menu for selecting and editing assistants, with improved UI for displaying the selected assistant's name and settings icon (`web-app/src/containers/DropdownAssistant.tsx`). [[1]](diffhunk://#diff-e9ccbe160523f61bf72f5ab0b7596479eb20b8303ead55a263f87a32d3c1f4c4L11-R91) [[2]](diffhunk://#diff-e9ccbe160523f61bf72f5ab0b7596479eb20b8303ead55a263f87a32d3c1f4c4L60-R116)
* Introduced a `selectedAssistantId` state to manage the currently selected assistant and …
> chore: add function delete and params type assistant

- web-app/src/routes/settings/appearance.tsx
This pull request updates the `Appareances` function in `web-app/src/routes/settings/appearance.tsx` to add new customization options and improve clarity in the user interface. The most important changes include adding a new setting for window background color, renaming and reorganizing the "Code Block" section, and refining the success message for resetting code block styles.
* Added a new `CardItem` for "Window Background" to allow users to choose the app window color.
* Renamed the "Chat Message" section to "Code Block" and reorganized the related `CardItem` for better clarity.
* Updated the toast success message when resetting code block styles to use the term "Code Block" instead of "Code Block Style" for consistency.
https://discord.com/channels/1107178041848909847/137389031048819513 …
> chore: regroup codeblock setting appearance

- web-app/src/routes/local-api-server/logs.tsx
This pull request enhances the `LogsViewer` component in `web-app/src/routes/local-api-server/logs.tsx` by adding functionality to automatically scroll to the bottom of the logs container when new logs are loaded or appended. The changes improve user experience by ensuring the latest logs are always visible.
* **Automatic Scrolling to Bottom:**
- Introduced a `useRef` hook to create a reference (`logsContainerRef`) for the logs container DOM element.
- Added a `scrollToBottom` function to handle scrolling logic, ensuring the logs container scrolls to the latest log entry.
- Integrated `scrollToBottom` into the initial log loading process and log update logic, using `setTimeout` to ensure the DOM updates are applied before scrolling.
* **DOM Refactoring:**
- Updated the logs container's …
> chore: scroll to bottom when have new log message

- web-app/src/containers/ChatInput.tsx
- web-app/src/containers/ThreadContent.tsx
- web-app/src/hooks/useAppState.ts
- web-app/src/hooks/useChat.ts
- web-app/src/types/threads.d.ts
This pull request introduces function handler of token speed tracking for chat interactions and an edit message functionality within threads. 
https://github.com/user-attachments/assets/5a2361a3-3c0c-4e75-b4ec-110a193f6633
* Added `tokenSpeed` to the `AppState` type and implemented `updateTokenSpeed` and `resetTokenSpeed` methods to calculate and reset token speed during streaming responses. (`web-app/src/hooks/useAppState.ts`, [[1]](diffhunk://#diff-071de59046b101d5fae68c69f345a198bb86cc8804dc51e281a302aae03a8f52R11-R18) [[2]](diffhunk://#diff-071de59046b101d5fae68c69f345a198bb86cc8804dc51e281a302aae03a8f52R27) [[3]](diffhunk://#diff-071de59046b101d5fae68c69f345a198bb86cc8804dc51e281a302aae03a8f52R46-R78)
* Integrated token speed updates into the `useChat` hook to reset and update token …
> chore: token speed and edit message

- extensions/inference-cortex-extension/resources/default_settings.json
- extensions/inference-cortex-extension/src/index.ts
- web-app/src/containers/ProvidersMenu.tsx
- web-app/src/containers/dialogs/DeleteProvider.tsx
- web-app/src/hooks/useChat.ts
- web-app/src/hooks/useModelProvider.ts
- web-app/src/lib/utils.ts
- web-app/src/mock/data.ts
- web-app/src/routes/settings/providers/$providerName.tsx
- web-app/src/services/providers.ts
This pull request introduces functionality to manage providers in the application, including adding and deleting providers, and updates related UI components and utilities. The most significant changes involve adding dialogs for creating and deleting providers, updating the provider state management, and refining the provider logo utility.
https://github.com/user-attachments/assets/b20d71ca-15b6-4fa7-81b2-de20adca67b6
* **Add Provider Dialog**: Introduced a dialog in `ProvidersMenu` to add new providers. Users can specify a provider name, which is then added to the state and navigates to the provider's settings page. (`web-app/src/containers/ProvidersMenu.tsx`, [[1]](diffhunk://#diff-db573253ae646febf83887d8c24ddba65b1e0e66f01f40ab1898f1747a279cf0L5-R46) …
> feat: add custom OpenAI provider

- web-app/src/containers/LeftPanel.tsx
- web-app/src/containers/ThreadList.tsx
Typo change 
| From | To |
|---|---|
| ![image](https://github.com/user-attachments/assets/b97ba493-d3b9-4c36-b8d0-e7231cf223f5) |   <img width="538" alt="image" src="https://github.com/user-attachments/assets/493e7aeb-dc17-42ef-9d25-73e749cb0b68" />| 
| <img width="378" alt="image" src="https://github.com/user-attachments/assets/97377059-ce2b-43ff-852f-00ec91cc2894" /> |  <img width="368" alt="image" src="https://github.com/user-attachments/assets/8352dc6f-c523-4fe2-9067-704a1c276bcf" /> | 
|  <img width="546" alt="image" src="https://github.com/user-attachments/assets/a7731954-62f9-4efd-bd9d-67c1f94dcb9c" /> |  <img width="541" alt="image" src="https://github.com/user-attachments/assets/65c7222d-edd9-47d5-a3dc-956fb613b493" />|
| <img width="379" alt="image" …
> fix: type rename thread

- web-app/package.json
- web-app/src/hooks/useHardware.ts
- web-app/src/routes/settings/general.tsx
- web-app/src/routes/settings/hardware.tsx
- web-app/src/services/hardware.ts
- web-app/src/types/global.d.ts
- web-app/vite.config.ts
This pull request introduces several updates to improve hardware management, enhance the application's versioning, and optimize data formatting and retrieval. The most significant changes include integrating a hardware management extension, replacing mock hardware data with real-time data fetching, and dynamically displaying the app version. Additionally, the data formatting for memory and VRAM has been refined.
- Allow users to activate GPUs on the new UI
- Show app version and system information
> Later go down to new hardware API
* Introduced `getHardwareInfo` and `setActiveGpus` functions in `web-app/src/services/hardware.ts` to fetch real hardware data and manage GPU activation using the `HardwareManagementExtension`.
* Replaced mock hardware data with real-time data fetching in …
> chore: handle hardware settings

- .gitignore
- .vscode/extensions.json
- .vscode/settings.json
- web/containers/ModelDropdown/index.tsx
- Make the model selector popup wider for longer model names on wider screens/windows
- [na] Added relevant comments, esp in complex areas
- [na] Updated docs (for bug fixes / features)
- [na] Created issues for follow-up changes or refactoring needed
> make the model selector popup responsive and wider for bigger screens

- web-app/src/containers/ChatInput.tsx
This pull request introduces improvements to the `ChatInput` component in `web-app/src/containers/ChatInput.tsx`, focusing on user feedback, error handling, and code maintainability. The key changes include adding a user notification when no model is selected, refactoring message submission logic, and enhancing UI responsiveness.
* Added a state variable `message` to display a warning when users attempt to send a message without selecting a model. The warning includes a dismissible UI element with an `IconX` button. [[1]](diffhunk://#diff-e6927577dd0c5d682ae3ac9367b9a6b7df9f76df4cf35c5a05779e539749f417R60-R69) [[2]](diffhunk://#diff-e6927577dd0c5d682ae3ac9367b9a6b7df9f76df4cf35c5a05779e539749f417R296-R309)
* Introduced a new `handleSendMesage` function to encapsulate the message-sending …
> chore: add inline message chat input

- core/src/browser/extensions/hardwareManagement.ts
- extensions/hardware-management-extension/src/index.ts
- package.json
- src-tauri/src/core/cmd.rs
- src-tauri/src/lib.rs
- web-app/src/containers/LanguageSwitcher.tsx
- web-app/src/containers/ModelSetting.tsx
- web-app/src/containers/dynamicControllerSetting/DropdownControl.tsx
- web-app/src/containers/dynamicControllerSetting/index.tsx
- web-app/src/hooks/useGeneralSetting.ts
- web-app/src/hooks/useHardware.ts
- web-app/src/lib/completion.ts
- web-app/src/lib/service.ts
- web-app/src/routes/settings/general.tsx
- web-app/src/services/app.ts
- web-app/src/services/hardware.ts
- web-app/src/services/mcp.ts
- web-app/src/services/providers.ts
- web-app/src/types/app.d.ts
- web-app/src/types/global.d.ts
- web-app/src/types/modelProviders.d.ts
This PR is to correct linter run step to run on latest web-app project instead of legacy web folder. This also fixed a couple of typo in the code base.
This also add relocate Jan Data Folder function back.
- Closes #
- Closes #
> chore: add relocate jan data folder function to new FE

- web-app/src/routes/settings/providers/$providerName.tsx
- web-app/src/services/providers.ts
This pull request introduces functionality for refreshing models from a provider's API and integrates it into the `ProviderDetail` component. It includes updates to the services layer, UI enhancements, and error handling mechanisms.
* [`web-app/src/services/providers.ts`](diffhunk://#diff-0000268145d26670fb69e7dd6741d904ce607b3406f963188b5f5f0f38ce0ff3R104-R157): Added a new function `fetchModelsFromProvider` to fetch model IDs from a provider's API endpoint. It handles multiple response formats and includes error handling for missing configurations or failed requests.
* [`web-app/src/routes/settings/providers/$providerName.tsx`](diffhunk://#diff-bf67bc43ea4ed453c69e14c27bd2fe2006545cb6cedc1fbad166857e073303b5R79): Added state `refreshingModels` to track the refresh operation, and …
> feat: add refresh button list model remote provider

- web-app/src/containers/DropdownModelProvider.tsx
- because macos auto capitalize, make fzf case insensitive
> Fix: fuzzy search model case sensitive 

- web-app/src/lib/version.ts
This PR fixes typo in build version check, where production gate is not checked properly.
- Closes #
- Closes #
> 🐛fix: typo in build type check

- yarn.lock
The yarn.lock file hasn't been updated for a while, so it needs to be updated for Dependabot to work properly.
- Closes #
- Closes #
> 🔧 config: update yarn.lock file

- web-app/package.json
- web-app/src/components/ui/resizable.tsx
- web-app/src/containers/LeftPanel.tsx
- web-app/src/hooks/useLeftPanel.ts
- web-app/src/routes/__root.tsx
https://github.com/user-attachments/assets/f5080858-347e-4942-b75d-ace50953d7bb
- Closes #5446 
- Closes #
> ✨enhancement: enable resizable left panel

- web-app/src/containers/LeftPanel.tsx
This pull request makes a small but impactful change to the `LeftPanel` component in the `web-app` project. The change updates the styling for small screens to improve the visual hierarchy and consistency.
Styling update for small screens:
* [`web-app/src/containers/LeftPanel.tsx`](diffhunk://#diff-8fe9510686bc63c447d596c9015da8053ef7172d644ed42f7daa12a2a794a706L200-R200): Changed the background color class from `bg-main-view` to `bg-app` and increased the `z-index` from `z-40` to `z-50` for better layering and alignment with the app's design system.
min
- Closes #5980 
- Closes #
> fix: missing text color responsive left panel

- docs/src/components/FooterMenu/index.tsx
- docs/src/components/Navbar.tsx
This pull request updates the navigation and footer menus to improve company branding and social media visibility. The main changes include adding new social media links to the navbar and updating the footer menu to better reflect current company information.
**Navigation improvements:**
* Added LinkedIn icon and link (`FaLinkedinIn`) to the navbar social section for easier access to the company's LinkedIn page. [[1]](diffhunk://#diff-c684642fec44014717f5be65d4fadad713a1f118418ec64d96c3440750643013L7-R7) [[2]](diffhunk://#diff-c684642fec44014717f5be65d4fadad713a1f118418ec64d96c3440750643013R116-R152) [[3]](diffhunk://#diff-c684642fec44014717f5be65d4fadad713a1f118418ec64d96c3440750643013R272-R279)
**Footer menu update:**
* Replaced the "Vision" link with "Open Superintelligence" in the …
> enhancement: social media navbar and update menu footer

- docs/plopfile.js
- docs/src/components/Blog/index.tsx
- docs/src/pages/post/_meta.json
- docs/src/pages/post/ai-for-law.mdx
- docs/src/pages/post/is-chatgpt-down-use-jan.mdx
> Emre to improve SEO

- web-app/src/components/ui/dropdown-menu.tsx
- web-app/src/containers/dialogs/AddEditAssistant.tsx
This pull request makes minor improvements to the UI components by adjusting styling and dialog interaction behavior.
*Dropdown menu styling:*
* In `dropdown-menu.tsx`, the z-index of the dropdown menu content was changed from `z-[51]` to `z-[90]` to ensure proper stacking order in the interface.
*Dialog interaction behavior:*
* In `AddEditAssistant.tsx`, the custom `onInteractOutside` handler was removed from the `DialogContent` component, allowing default behavior when interacting outside the dialog.
- Closes #6682 
- Closes #
> fix: dropdown type assistant

- web-app/index.html
- web-app/src/lib/analytics.ts
- web-app/src/providers/GoogleAnalyticsProvider.tsx
- web-app/src/routes/index.tsx
- web-app/vite.config.ts
- web-app/vite.config.web.ts
> fix: web gg tag

- src-tauri/src/core/app/commands.rs
- src-tauri/src/core/downloads/commands.rs
- src-tauri/src/core/downloads/helpers.rs
- src-tauri/src/core/extensions/commands.rs
- src-tauri/src/core/filesystem/tests.rs
- src-tauri/src/core/mcp/commands.rs
- src-tauri/src/core/mcp/helpers.rs
- src-tauri/src/core/mcp/tests.rs
- src-tauri/src/core/server/proxy.rs
- src-tauri/src/core/setup.rs
- src-tauri/src/core/system/commands.rs
- src-tauri/src/core/threads/commands.rs
- src-tauri/src/core/threads/helpers.rs
- src-tauri/src/core/threads/tests.rs
- src-tauri/src/lib.rs
- **Modern String Formatting**: Updated string formatting to use modern interpolation syntax (`{variable}` instead of `format!()` macros) for better readability and performance
- **Enhanced Logging**: Improved logging statements with more descriptive messages and consistent formatting
- **Process Synchronization**: Added proper process waiting in `open_app_directory` and `open_file_explorer` functions in `/src-tauri/src/core/system/commands.rs`
- Replaced `.status()` calls with proper `.spawn()` and `.wait()` for better process lifecycle management
- Ensures spawned processes complete before function returns
- Closes #N/A
> resolve rust analyzer warnings

- src-tauri/tauri.linux.conf.json
- src-tauri/tauri.macos.conf.json
- Fix issue of missing extension on make dev on UNIX
> fix: extensions missing on Unix dev

- docs/src/pages/changelog/2025-10-02-jan-projects.mdx
- docs/src/pages/changelog/2025-10-03-jan-stability-improvements.mdx
> changelog: release 0.7.1

- web-app/src/containers/LeftPanel.tsx
- Add conditional check to hide `projects` on mobile
- Closes #
- Closes #
> feat: Hide projects for mobile version

- web-app/src/containers/ThreadList.tsx
This pull request includes minor UI improvements and code formatting updates to the `ThreadList` component in `web-app/src/containers/ThreadList.tsx`. The changes focus on enhancing dropdown menu usability and improving code readability.
**UI enhancements:**
* Set a minimum width for dropdown menus by changing the class from `w-44` to `min-w-44` in `DropdownMenuContent`, ensuring consistent sizing for the menu.
* Improved the appearance and usability of the project selection dropdown by adding `max-h-60 min-w-44 overflow-y-auto` to `DropdownMenuSubContent`, which constrains its height and enables scrolling for long lists.
**Code formatting:**
* Reformatted the `ThreadList` function parameters and the `SortableItem` component props for better readability and maintainability. …
> chore: make dropdown sub menu assign projects scrollable
